/*
   Animal Shelter Manager
   Copyright(c)2000-2009, R. Rawson-Tetley

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2 of
   the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the
   Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston
   MA 02111-1307, USA.

   Contact me by electronic mail: bobintetley@users.sourceforge.net
*/
package net.sourceforge.sheltermanager.asm.db;

import java.util.*;


/**
 *
 * This class handles PetFinder specific
 * data issues.
 *
 * @author  Robin Rawson-Tetley
 */
public abstract class DBPetFinder {
    public static Vector getBreeds() {
        Vector pfBreeds = new Vector();
        pfBreeds.add("Affenpinscher");
        pfBreeds.add("Afghan Hound");
        pfBreeds.add("Airedale Terrier");
        pfBreeds.add("Akbash");
        pfBreeds.add("Akita");
        pfBreeds.add("Alaskan Malamute");
        pfBreeds.add("American Bulldog");
        pfBreeds.add("American Eskimo Dog");
        pfBreeds.add("American Staffordshire Terrier");
        pfBreeds.add("American Water Spaniel");
        pfBreeds.add("Anatolian Shepherd");
        pfBreeds.add("Appenzell Mountain Dog");
        pfBreeds.add("Australian Cattle Dog/Blue Heeler");
        pfBreeds.add("Australian Kelpie");
        pfBreeds.add("Australian Shepherd");
        pfBreeds.add("Australian Terrier");
        pfBreeds.add("Basenji");
        pfBreeds.add("Basset Hound");
        pfBreeds.add("Beagle");
        pfBreeds.add("Bearded Collie");
        pfBreeds.add("Beauceron");
        pfBreeds.add("Bedlington Terrier");
        pfBreeds.add("Belgian Shepherd Dog Sheepdog");
        pfBreeds.add("Belgian Shepherd Laekenois");
        pfBreeds.add("Belgian Shepherd Malinois");
        pfBreeds.add("Belgian Shepherd Tervuren ");
        pfBreeds.add("Bernese Mountain Dog");
        pfBreeds.add("Bichon Frise");
        pfBreeds.add("Black and Tan Coonhound");
        pfBreeds.add("Black Labrador Retriever");
        pfBreeds.add("Black Mouth Cur");
        pfBreeds.add("Bloodhound");
        pfBreeds.add("Bluetick Coonhound");
        pfBreeds.add("Border Collie");
        pfBreeds.add("Border Terrier");
        pfBreeds.add("Borzoi");
        pfBreeds.add("Boston Terrier");
        pfBreeds.add("Bouvier des Flanders");
        pfBreeds.add("Boykin Spaniel");
        pfBreeds.add("Boxer");
        pfBreeds.add("Briard");
        pfBreeds.add("Brittany Spaniel");
        pfBreeds.add("Brussels Griffon");
        pfBreeds.add("Bull Terrier");
        pfBreeds.add("Bullmastiff");
        pfBreeds.add("Cairn Terrier");
        pfBreeds.add("Canaan Dog");
        pfBreeds.add("Cane Corso Mastiff");
        pfBreeds.add("Carolina Dog");
        pfBreeds.add("Catahoula Leopard Dog");
        pfBreeds.add("Cattle Dog");
        pfBreeds.add("Cavalier King Charles Spaniel");
        pfBreeds.add("Chesapeake Bay Retriever");
        pfBreeds.add("Chihuahua");
        pfBreeds.add("Chinese Crested Dog");
        pfBreeds.add("Chinese Foo Dog");
        pfBreeds.add("Chocolate Labrador Retriever");
        pfBreeds.add("Chow Chow");
        pfBreeds.add("Clumber Spaniel");
        pfBreeds.add("Cockapoo");
        pfBreeds.add("Cocker Spaniel");
        pfBreeds.add("Collie");
        pfBreeds.add("Coonhound");
        pfBreeds.add("Corgi");
        pfBreeds.add("Coton de Tulear");
        pfBreeds.add("Dachshund");
        pfBreeds.add("Dalmatian");
        pfBreeds.add("Dandi Dinmont Terrier");
        pfBreeds.add("Doberman Pinscher");
        pfBreeds.add("Dogo Argentino");
        pfBreeds.add("Dogue de Bordeaux");
        pfBreeds.add("Dutch Shepherd");
        pfBreeds.add("English Bulldog");
        pfBreeds.add("English Cocker Spaniel");
        pfBreeds.add("English Coonhound");
        pfBreeds.add("English Pointer");
        pfBreeds.add("English Setter");
        pfBreeds.add("English Shepherd");
        pfBreeds.add("English Springer Spaniel");
        pfBreeds.add("English Toy Spaniel");
        pfBreeds.add("Entlebucher");
        pfBreeds.add("Eskimo Dog");
        pfBreeds.add("Field Spaniel");
        pfBreeds.add("Fila Brasileiro");
        pfBreeds.add("Finnish Lapphund");
        pfBreeds.add("Finnish Spitz");
        pfBreeds.add("Flat-coated Retriever");
        pfBreeds.add("Fox Terrier");
        pfBreeds.add("Foxhound");
        pfBreeds.add("French Bulldog");
        pfBreeds.add("German Pinscher");
        pfBreeds.add("German Shepherd Dog");
        pfBreeds.add("German Shorthaired Pointer");
        pfBreeds.add("German Wirehaired Pointer");
        pfBreeds.add("Glen of Imaal Terrier");
        pfBreeds.add("Golden Retriever");
        pfBreeds.add("Gordon Setter");
        pfBreeds.add("Great Dane");
        pfBreeds.add("Great Pyrenees");
        pfBreeds.add("Greater Swiss Mountain Dog");
        pfBreeds.add("Greyhound");
        pfBreeds.add("Havanese");
        pfBreeds.add("Hound");
        pfBreeds.add("Hovawart");
        pfBreeds.add("Husky");
        pfBreeds.add("Ibizan Hound");
        pfBreeds.add("Illyrian Sheepdog");
        pfBreeds.add("Irish Setter");
        pfBreeds.add("Irish Terrier");
        pfBreeds.add("Irish Water Spaniel");
        pfBreeds.add("Irish Wolfhound");
        pfBreeds.add("Italian Greyhound");
        pfBreeds.add("Italian Spinone");
        pfBreeds.add("Jack Russell Terrier");
        pfBreeds.add("Japanese Chin");
        pfBreeds.add("Jindo");
        pfBreeds.add("Kai Dog");
        pfBreeds.add("Karelian Bear Dog");
        pfBreeds.add("Keeshond");
        pfBreeds.add("Kerry Blue Terrier");
        pfBreeds.add("Kishu");
        pfBreeds.add("Komondor");
        pfBreeds.add("Kuvasz");
        pfBreeds.add("Kyi Leo");
        pfBreeds.add("Labrador Retriever");
        pfBreeds.add("Lakeland Terrier");
        pfBreeds.add("Lancashire Heeler");
        pfBreeds.add("Lhasa Apso");
        pfBreeds.add("Leonberger");
        pfBreeds.add("L�wchen");
        pfBreeds.add("Maltese");
        pfBreeds.add("Manchester Terrier");
        pfBreeds.add("Maremma Sheepdog");
        pfBreeds.add("Mastiff");
        pfBreeds.add("McNab");
        pfBreeds.add("Miniature Pinscher");
        pfBreeds.add("Mountain Cur");
        pfBreeds.add("Mountain Dog");
        pfBreeds.add("Munsterlander");
        pfBreeds.add("Neapolitan Mastiff");
        pfBreeds.add("New Guinea Singing Dog");
        pfBreeds.add("Newfoundland Dog");
        pfBreeds.add("Norfolk Terrier");
        pfBreeds.add("Norwich Terrier");
        pfBreeds.add("Norwegian Buhund");
        pfBreeds.add("Norwegian Elkhound");
        pfBreeds.add("Norwegian Lundehund");
        pfBreeds.add("Nova Scotia Duck-Tolling Retriever");
        pfBreeds.add("Old English Sheepdog");
        pfBreeds.add("Otterhound");
        pfBreeds.add("Papillon");
        pfBreeds.add("Patterdale Terrier (Fell Terrier)");
        pfBreeds.add("Pekingese");
        pfBreeds.add("Peruvian Inca Orchid");
        pfBreeds.add("Petit Basset Griffon Vendeen");
        pfBreeds.add("Pharaoh Hound");
        pfBreeds.add("Pit Bull Terrier");
        pfBreeds.add("Plott Hound");
        pfBreeds.add("Podengo Portugueso");
        pfBreeds.add("Pointer");
        pfBreeds.add("Polish Lowland Sheepdog");
        pfBreeds.add("Pomeranian");
        pfBreeds.add("Poodle");
        pfBreeds.add("Portuguese Water Dog");
        pfBreeds.add("Presa Canario");
        pfBreeds.add("Pug");
        pfBreeds.add("Puli");
        pfBreeds.add("Pumi");
        pfBreeds.add("Rat Terrier");
        pfBreeds.add("Redbone Coonhound");
        pfBreeds.add("Retriever");
        pfBreeds.add("Rhodesian Ridgeback");
        pfBreeds.add("Rottweiler");
        pfBreeds.add("Saluki");
        pfBreeds.add("Saint Bernard St. Bernard");
        pfBreeds.add("Samoyed");
        pfBreeds.add("Schipperke");
        pfBreeds.add("Schnauzer");
        pfBreeds.add("Scottish Deerhound");
        pfBreeds.add("Scottish Terrier Scottie");
        pfBreeds.add("Sealyham Terrier");
        pfBreeds.add("Setter");
        pfBreeds.add("Shar Pei");
        pfBreeds.add("Sheep Dog");
        pfBreeds.add("Shepherd");
        pfBreeds.add("Shetland Sheepdog Sheltie");
        pfBreeds.add("Shiba Inu");
        pfBreeds.add("Shih Tzu");
        pfBreeds.add("Siberian Husky");
        pfBreeds.add("Silky Terrier");
        pfBreeds.add("Skye Terrier");
        pfBreeds.add("Sloughi");
        pfBreeds.add("Smooth Fox Terrier");
        pfBreeds.add("Spaniel");
        pfBreeds.add("Spitz");
        pfBreeds.add("Staffordshire Bull Terrier");
        pfBreeds.add("South Russian Ovcharka");
        pfBreeds.add("Swedish Vallhund");
        pfBreeds.add("Terrier");
        pfBreeds.add("Thai Ridgeback");
        pfBreeds.add("Tibetan Mastiff");
        pfBreeds.add("Tibetan Spaniel");
        pfBreeds.add("Tibetan Terrier");
        pfBreeds.add("Tosa Inu");
        pfBreeds.add("Toy Fox Terrier");
        pfBreeds.add("Treeing Walker Coonhound");
        pfBreeds.add("Vizsla");
        pfBreeds.add("Weimaraner");
        pfBreeds.add("Welsh Corgi");
        pfBreeds.add("Welsh Terrier");
        pfBreeds.add("Welsh Springer Spaniel");
        pfBreeds.add("West Highland White Terrier Westie");
        pfBreeds.add("Wheaten Terrier");
        pfBreeds.add("Whippet");
        pfBreeds.add("White German Shepherd");
        pfBreeds.add("Wire-haired Pointing Griffon");
        pfBreeds.add("Wirehaired Terrier");
        pfBreeds.add("Yellow Labrador Retriever");
        pfBreeds.add("Yorkshire Terrier Yorkie");
        pfBreeds.add("Xoloitzcuintle/Mexican Hairless");
        pfBreeds.add("Abyssinian");
        pfBreeds.add("American Curl");
        pfBreeds.add("American Shorthair");
        pfBreeds.add("American Wirehair");
        pfBreeds.add("Applehead Siamese");
        pfBreeds.add("Balinese");
        pfBreeds.add("Bengal");
        pfBreeds.add("Birman");
        pfBreeds.add("Bobtail");
        pfBreeds.add("Bombay");
        pfBreeds.add("British Shorthair");
        pfBreeds.add("Burmese");
        pfBreeds.add("Burmilla");
        pfBreeds.add("Calico");
        pfBreeds.add("Canadian Hairless");
        pfBreeds.add("Chartreux");
        pfBreeds.add("Chinchilla");
        pfBreeds.add("Cornish Rex");
        pfBreeds.add("Cymric");
        pfBreeds.add("Devon Rex");
        pfBreeds.add("Dilute Calico");
        pfBreeds.add("Dilute Tortoiseshell");
        pfBreeds.add("Domestic Long Hair");
        pfBreeds.add("Domestic Long Hair-black");
        pfBreeds.add("Domestic Long Hair - buff");
        pfBreeds.add("Domestic Long Hair-gray");
        pfBreeds.add("Domestic Long Hair - orange");
        pfBreeds.add("Domestic Long Hair - orange and white");
        pfBreeds.add("Domestic Long Hair - gray and white");
        pfBreeds.add("Domestic Long Hair-white");
        pfBreeds.add("Domestic Long Hair-black and white");
        pfBreeds.add("Domestic Medium Hair");
        pfBreeds.add("Domestic Medium Hair-black");
        pfBreeds.add("Domestic Medium Hair - buff");
        pfBreeds.add("Domestic Medium Hair-gray");
        pfBreeds.add("Domestic Medium Hair - gray and white");
        pfBreeds.add("Domestic Medium Hair-white");
        pfBreeds.add("Domestic Medium Hair-orange");
        pfBreeds.add("Domestic Medium Hair - orange and white");
        pfBreeds.add("Domestic Medium Hair-black and white");
        pfBreeds.add("Domestic Short Hair");
        pfBreeds.add("Domestic Short Hair-black");
        pfBreeds.add("Domestic Short Hair - buff");
        pfBreeds.add("Domestic Short Hair-black and white");
        pfBreeds.add("Domestic Short Hair-gray");
        pfBreeds.add("Domestic Short Hair - gray and white");
        pfBreeds.add("Domestic Short Hair-mitted");
        pfBreeds.add("Domestic Short Hair-orange");
        pfBreeds.add("Domestic Short Hair - orange and white");
        pfBreeds.add("Domestic Short Hair-white");
        pfBreeds.add("Egyptian Mau");
        pfBreeds.add("Exotic Shorthair");
        pfBreeds.add("Extra-Toes Cat (Hemingway Polydactyl)");
        pfBreeds.add("Havana");
        pfBreeds.add("Himalayan");
        pfBreeds.add("Japanese Bobtail");
        pfBreeds.add("Javanese");
        pfBreeds.add("Korat");
        pfBreeds.add("Maine Coon");
        pfBreeds.add("Manx");
        pfBreeds.add("Munchkin");
        pfBreeds.add("Norwegian Forest Cat");
        pfBreeds.add("Ocicat");
        pfBreeds.add("Oriental Long Hair");
        pfBreeds.add("Oriental Short Hair");
        pfBreeds.add("Oriental Tabby");
        pfBreeds.add("Persian");
        pfBreeds.add("Pixie-Bob");
        pfBreeds.add("Ragamuffin");
        pfBreeds.add("Ragdoll");
        pfBreeds.add("Russian Blue");
        pfBreeds.add("Scottish Fold");
        pfBreeds.add("Selkirk Rex");
        pfBreeds.add("Siamese");
        pfBreeds.add("Siberian");
        pfBreeds.add("Singapura");
        pfBreeds.add("Snowshoe");
        pfBreeds.add("Somali");
        pfBreeds.add("Sphynx (hairless cat)");
        pfBreeds.add("Tabby");
        pfBreeds.add("Tabby - Orange");
        pfBreeds.add("Tabby - Grey");
        pfBreeds.add("Tabby - Brown");
        pfBreeds.add("Tabby - white");
        pfBreeds.add("Tabby - buff");
        pfBreeds.add("Tabby - black");
        pfBreeds.add("Tiger");
        pfBreeds.add("Tonkinese");
        pfBreeds.add("Torbie");
        pfBreeds.add("Tortoiseshell");
        pfBreeds.add("Turkish Angora");
        pfBreeds.add("Turkish Van");
        pfBreeds.add("Tuxedo");
        pfBreeds.add("American");
        pfBreeds.add("American Fuzzy Lop");
        pfBreeds.add("American Sable");
        pfBreeds.add("Angora Rabbit");
        pfBreeds.add("Belgian Hare");
        pfBreeds.add("Beveren");
        pfBreeds.add("Britannia Petite");
        pfBreeds.add("Bunny Rabbit");
        pfBreeds.add("Californian");
        pfBreeds.add("Champagne D'Argent");
        pfBreeds.add("Checkered Giant");
        pfBreeds.add("Chinchilla");
        pfBreeds.add("Cinnamon");
        pfBreeds.add("Cr�me D'Argent");
        pfBreeds.add("Dutch");
        pfBreeds.add("Dwarf");
        pfBreeds.add("Dwarf Eared");
        pfBreeds.add("English Lop");
        pfBreeds.add("English Spot");
        pfBreeds.add("Flemish Giant");
        pfBreeds.add("Florida White");
        pfBreeds.add("French-Lop");
        pfBreeds.add("Harlequin");
        pfBreeds.add("Havana");
        pfBreeds.add("Himalayan");
        pfBreeds.add("Holland Lop");
        pfBreeds.add("Hotot");
        pfBreeds.add("Jersey Wooly");
        pfBreeds.add("Lilac");
        pfBreeds.add("Lop Eared");
        pfBreeds.add("Mini-Lop");
        pfBreeds.add("Mini Rex");
        pfBreeds.add("Netherland Dwarf");
        pfBreeds.add("New Zealand");
        pfBreeds.add("Palomino");
        pfBreeds.add("Polish");
        pfBreeds.add("Rex");
        pfBreeds.add("Rhinelander");
        pfBreeds.add("Satin");
        pfBreeds.add("Silver");
        pfBreeds.add("Silver Fox");
        pfBreeds.add("Silver Marten");
        pfBreeds.add("Tan");
        pfBreeds.add("Appaloosa");
        pfBreeds.add("Arabian");
        pfBreeds.add("Clydesdale");
        pfBreeds.add("Donkey/Mule");
        pfBreeds.add("Draft");
        pfBreeds.add("Gaited ");
        pfBreeds.add("Grade");
        pfBreeds.add("Missouri Foxtrotter");
        pfBreeds.add("Morgan");
        pfBreeds.add("Mustang");
        pfBreeds.add("Paint/Pinto");
        pfBreeds.add("Palomino");
        pfBreeds.add("Paso Fino");
        pfBreeds.add("Percheron");
        pfBreeds.add("Peruvian Paso");
        pfBreeds.add("Pony");
        pfBreeds.add("Quarterhorse");
        pfBreeds.add("Saddlebred");
        pfBreeds.add("Standardbre");
        pfBreeds.add("Thoroughbred");
        pfBreeds.add("Tennessee Walker");
        pfBreeds.add("Warmblood");
        pfBreeds.add("Chinchilla");
        pfBreeds.add("Ferret");
        pfBreeds.add("Gerbil");
        pfBreeds.add("Guinea Pig");
        pfBreeds.add("Hamster");
        pfBreeds.add("Hedgehog");
        pfBreeds.add("Mouse");
        pfBreeds.add("Prairie Dog");
        pfBreeds.add("Rat");
        pfBreeds.add("Skunk");
        pfBreeds.add("Sugar Glider");
        pfBreeds.add("Pot Bellied");
        pfBreeds.add("Vietnamese Pot Bellied");
        pfBreeds.add("Gecko");
        pfBreeds.add("Iguana");
        pfBreeds.add("Lizard");
        pfBreeds.add("Snake");
        pfBreeds.add("Turtle");
        pfBreeds.add("Fish");
        pfBreeds.add("African Grey");
        pfBreeds.add("Amazon");
        pfBreeds.add("Brotogeris");
        pfBreeds.add("Budgie/Budgerigar");
        pfBreeds.add("Caique");
        pfBreeds.add("Canary");
        pfBreeds.add("Chicken");
        pfBreeds.add("Cockatiel");
        pfBreeds.add("Cockatoo");
        pfBreeds.add("Conure");
        pfBreeds.add("Dove");
        pfBreeds.add("Duck");
        pfBreeds.add("Eclectus");
        pfBreeds.add("Emu");
        pfBreeds.add("Finch");
        pfBreeds.add("Goose");
        pfBreeds.add("Guinea fowl");
        pfBreeds.add("Kakariki");
        pfBreeds.add("Lory/Lorikeet");
        pfBreeds.add("Lovebird");
        pfBreeds.add("Macaw");
        pfBreeds.add("Mynah");
        pfBreeds.add("Ostrich");
        pfBreeds.add("Parakeet (Other)");
        pfBreeds.add("Parrot (Other)");
        pfBreeds.add("Parrotlet");
        pfBreeds.add("Peacock/Pea fowl");
        pfBreeds.add("Pheasant");
        pfBreeds.add("Pigeon");
        pfBreeds.add("Pionus");
        pfBreeds.add("Poicephalus/Senegal");
        pfBreeds.add("Quaker Parakeet");
        pfBreeds.add("Rhea");
        pfBreeds.add("Ringneck/Psittacula");
        pfBreeds.add("Rosella");
        pfBreeds.add("Softbill (Other)");
        pfBreeds.add("Swan");
        pfBreeds.add("Toucan");
        pfBreeds.add("Turkey");
        pfBreeds.add("Cow");
        pfBreeds.add("Goat");
        pfBreeds.add("Sheep");
        pfBreeds.add("Llama");
        pfBreeds.add("Pig (Farm)");

        return pfBreeds;
    }
}
