#!/bin/sh

# We need to remove the following things from the code (artifacts
# of old netbeans crap
#
# // initComponents
# // event_.*
# // Variables declaration - do not modify//variables
# // End of variables declaration//variables
#    /**
#    * This method is called from within the constructor to initialize the form.
#    * WARNING: Do NOT modify this code. The content of this method is always
#    * regenerated by the Form Editor.
#    */

cd `dirname $0`
cd ../src
for i in `find . -name '*.java'`; do

	echo $i

	cat $i | sed 's/\/\/\ initComponents//g' > $i.tmp
	mv $i.tmp $i

	cat $i | sed 's/\/\/\ event_.*//g' > $i.tmp
	mv $i.tmp $i

	cat $i | sed 's/\/\/\ Variables\ declaration \- do not modify\/\/variables//g' > $i.tmp
	mv $i.tmp $i

	cat $i | sed 's/\/\/\ End of variables declaration\/\/variables//g' > $i.tmp
	mv $i.tmp $i

	cat $i | sed 's/\* This method is called from within the constructor to initialize the form\.//g' > $i.tmp
	mv $i.tmp $i

	cat $i | sed 's/\* WARNING\: Do NOT modify this code\. The content of this method is always//g' > $i.tmp
	mv $i.tmp $i

	cat $i | sed 's/\* regenerated by the Form Editor\.//g' > $i.tmp
	mv $i.tmp $i

done
