#!/usr/bin/python

"""
Reads an ASM SQL patch file and turns it into a java property file. This
assumes the file has already been re-encoded in java/latin1 format

args:

    filename - the original db filename (so we can extract lang)
    output_directory - where to put the property file
    input_file - the sql file

"""

import os, sys

filename = sys.argv[1];
outputdir = sys.argv[2];
inputfile = sys.argv[3];

infile = open(inputfile, "r")
lines = infile.readlines()
infile.close()

# Languages we recognise and prop suffix - if we don't recognise, assume
# english and our template - each new language should be added here
codes = (  ( "lt", "_lt_LT" ), ( "es", "_es_ES" ), ( "nl", "_nl_NL" ), ( "fr", "_fr_FR" ) )
code = ""

for c in codes:
    if filename.find(c[0]) != -1:
        code = c[1]
        break

# Open the output file
outfilename = "database" + code + ".properties"
outfile = open(outputdir + "/database" + code + ".properties", "w")
outfile.write("# " + outfilename + "\n")
outfile.write("# Generated by scripts/database_to_java.sh\n")
outfile.write("##########################################################\n\n")

# Loop through the list of lines in the file. We use the
# DELETE FROM lines to determine the current key prefix and we extract
# the ID from the first of the values list to complete the key.
# Depending on what table we're dealing with determines how many values

currentTable = ""

for l in lines:

    if l.startswith("DELETE"):
        # Get the new table
        currentTable = l.split(" ")[2].replace(";", "").strip()

    if l.startswith("INSERT"):
        # Get the values
        valuestring = l[l.find("(")+1:l.rfind(")")]
        values = valuestring.split(",")

        # ID
        id = values[0]

        # key prefix
        keyprefix = currentTable.strip() + "_" + id

        # Depending on the table determines what we extract
        if currentTable == "customreport":
            v = values[1].strip()
            if v.startswith("'"): v = v[1:]
            if v.endswith("'"): v = v[0:len(v)-1]
            cat = values[11].strip().replace("'", "")
            sqlcode = values[2].strip().replace("'", "")
            nextline = keyprefix + "_" + sqlcode + "=" + v
            outfile.write(nextline + "\n\n")
            outfile.write(keyprefix + "_category=" + cat + "\n\n")
        elif currentTable == "breed":
            v = values[1].strip()
            if v.startswith("'"): v = v[1:]
            if v.endswith("'"): v = v[0:len(v)-1]
            try:
                speciesid = values[4].strip()
            except:
                print "FAILED: " + valuestring
                speciesid = "1"
            nextline = keyprefix + "_" + speciesid + "=" + v
            outfile.write(nextline + "\n\n")
        elif currentTable == "users":
            # Ignore any users table - that should be kept in English
            # to match documentation
            pass
        else:
            # Must be a single value translation
            v = values[1].strip()
            if v.startswith("'"): v = v[1:]
            if v.endswith("'"): v = v[0:len(v)-1]
            nextline = keyprefix + "=" + v
            outfile.write(nextline + "\n\n")

outfile.close()
