DELETE FROM accounts;
INSERT INTO accounts VALUES (1, 'Income::Donation', 'Einkommende Spenden (misc)', 5, 1, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (2, 'Income::Adoption', 'Adoption fee donations', 5, 2, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (3, 'Income::WaitingList', 'Spenden Warteliste', 5, 3, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (4, 'Income::EntryDonation', 'Donations for animals entering the shelter', 5, 4, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (5, 'Income::Sponsorship', 'Sponsorship donations', 5, 5, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (6, 'Income::Shop', 'Income from an on-site shop', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (7, 'Income::Interest', 'Bank account interest', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (8, 'Income::OpeningBalances', 'Opening balances', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (9, 'Bank::Current', 'Bank current account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (10, 'Bank::Deposit', 'Bank deposit account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (11, 'Bank::Savings', 'Bank savings account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (12, 'Asset::Premises', 'Premises', 8, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (13, 'Expenses::Phone', 'Telefonrechnungen', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (14, 'Expenses::Electricity', 'Stromrechnungen', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (15, 'Expenses::Water', 'Wasserrechnungen', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (16, 'Expenses::Gas', 'Gasrechnungen', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (17, 'Expenses::Postage', 'Postage costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (18, 'Expenses::Stationary', 'Stationary costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (19, 'Expenses::Food', 'Tier-Futter Kosten', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Hund)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Streunender Hund)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Ungewollte Katze)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Streunende Katze)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Sonstiges)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Kein Tier aus einem Tierheim)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Schwarz', NULL);
INSERT INTO basecolour VALUES (2, 'Weiß', NULL);
INSERT INTO basecolour VALUES (3, 'Schwarz und Weiß', NULL);
INSERT INTO basecolour VALUES (4, 'Rothaarig', NULL);
INSERT INTO basecolour VALUES (5, 'Weiß und Schwarz', NULL);
INSERT INTO basecolour VALUES (6, 'Tortie', NULL);
INSERT INTO basecolour VALUES (7, 'Getigert', NULL);
INSERT INTO basecolour VALUES (8, 'Hellbraun', NULL);
INSERT INTO basecolour VALUES (9, 'Schwarz und Hellbraun', NULL);
INSERT INTO basecolour VALUES (10, 'Hellbraun und Schwarz', NULL);
INSERT INTO basecolour VALUES (11, 'Braun', NULL);
INSERT INTO basecolour VALUES (12, 'Braun und Schwarz', NULL);
INSERT INTO basecolour VALUES (13, 'Schwarz und Braun', NULL);
INSERT INTO basecolour VALUES (14, 'Gescheckt', NULL);
INSERT INTO basecolour VALUES (15, 'Gescheckt und Schwarz', NULL);
INSERT INTO basecolour VALUES (16, 'Gescheckt und Weiß', NULL);
INSERT INTO basecolour VALUES (17, 'Schwarz und Gescheckt', NULL);
INSERT INTO basecolour VALUES (18, 'Weiß und Gescheckt', NULL);
INSERT INTO basecolour VALUES (19, 'Dreifarbig', NULL);
INSERT INTO basecolour VALUES (20, 'Rotbraun', NULL);
INSERT INTO basecolour VALUES (21, 'Rotbraun und Weiß', NULL);
INSERT INTO basecolour VALUES (22, 'Weiß und Rotbraun', NULL);
INSERT INTO basecolour VALUES (23, 'Cremefarben', NULL);
INSERT INTO basecolour VALUES (24, 'Hellbraun und Weiß', NULL);
INSERT INTO basecolour VALUES (26, 'Weiß und Hellbraun', NULL);
INSERT INTO basecolour VALUES (27, 'Tortie and White', NULL);
INSERT INTO basecolour VALUES (28, 'Gefleckt und Weiß', NULL);
INSERT INTO basecolour VALUES (29, 'Rothaaring und Weiß', NULL);
INSERT INTO basecolour VALUES (30, 'Grau', NULL);
INSERT INTO basecolour VALUES (31, 'Grau und Weiß', NULL);
INSERT INTO basecolour VALUES (32, 'Weiß und Grau', NULL);
INSERT INTO basecolour VALUES (33, 'Weiß und Braun gemischt (Torti)', NULL);
INSERT INTO basecolour VALUES (35, 'Braun und Weiß', NULL);
INSERT INTO basecolour VALUES (36, 'Blau', NULL);
INSERT INTO basecolour VALUES (37, 'Weiß und Gescheckt', NULL);
INSERT INTO basecolour VALUES (38, 'Gelb und Grau', NULL);
INSERT INTO basecolour VALUES (39, 'Verschiedene', NULL);
INSERT INTO basecolour VALUES (40, 'Weiß und Braun', NULL);
INSERT INTO basecolour VALUES (41, 'Grün', NULL);
INSERT INTO basecolour VALUES (42, 'Amber', NULL);
INSERT INTO basecolour VALUES (43, 'Black Tortie', NULL);
INSERT INTO basecolour VALUES (44, 'Blue Tortie', NULL);
INSERT INTO basecolour VALUES (45, 'Chocolate', NULL);
INSERT INTO basecolour VALUES (46, 'Chocolate Tortie', NULL);
INSERT INTO basecolour VALUES (47, 'Cinnamon', NULL);
INSERT INTO basecolour VALUES (48, 'Cinnamon Tortoiseshell', NULL);
INSERT INTO basecolour VALUES (49, 'Fawn', NULL);
INSERT INTO basecolour VALUES (50, 'Fawn Tortoiseshell', NULL);
INSERT INTO basecolour VALUES (51, 'Golden', NULL);
INSERT INTO basecolour VALUES (52, 'Light Amber', NULL);
INSERT INTO basecolour VALUES (53, 'Lilac', NULL);
INSERT INTO basecolour VALUES (54, 'Lilac Tortie', NULL);
INSERT INTO basecolour VALUES (55, 'Ruddy', NULL);
INSERT INTO basecolour VALUES (56, 'Seal', NULL);
INSERT INTO basecolour VALUES (57, 'Silber', NULL);
INSERT INTO basecolour VALUES (58, 'Sorrel', NULL);
INSERT INTO basecolour VALUES (59, 'Sorrel Tortoiseshell', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Afghanischer Windhund', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Alaskan Malamute', '', '', 1);
INSERT INTO breed VALUES (7, 'Amerikanische Bulldogge', '', '', 1);
INSERT INTO breed VALUES (8, 'Amerikanischer Eskimohund', '', '', 1);
INSERT INTO breed VALUES (9, 'Amerikanischer Staffordshire-Terrier', '', '', 1);
INSERT INTO breed VALUES (10, 'Amerikanischer Wasserspaniel', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolischer Hirtenhund', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzeller Sennenhund', '', '', 1);
INSERT INTO breed VALUES (13, 'Australischer Treibhund/Blue Heeler', '', '', 1);
INSERT INTO breed VALUES (14, 'Australischer Kelpie', '', '', 1);
INSERT INTO breed VALUES (15, 'Australischer Schäferhund', '', '', 1);
INSERT INTO breed VALUES (16, 'Australischer Terrier', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgischer Schäferhund', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgischer Schäferhund Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgischer Schäferhund Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgischer Schäferhund Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Berner Sennenhund', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon Frise', '', '', 1);
INSERT INTO breed VALUES (29, 'Schwarz-Roter Waschbärenhund (Black and Tan Coonhound)', '', '', 1);
INSERT INTO breed VALUES (30, 'Schwarz Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Bluthund', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Russischer Jagd Windhund', '', '', 1);
INSERT INTO breed VALUES (37, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (38, 'Flandrischer Treibhund', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Bretonischer Spaniel', '', '', 1);
INSERT INTO breed VALUES (43, 'Brüsseler Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Kanaan Hund', '', '', 1);
INSERT INTO breed VALUES (48, 'Italienischer Corso-Hund', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina Dog', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Treibhund', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bay Retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chinesische Schopfhund (Chinesischer Nackthund)', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinesischer Glückshund', '', '', 1);
INSERT INTO breed VALUES (57, 'Chocolate Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Waschbärhund', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Dachshund', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatiner', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandie Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Dobermann (Doberman Pinscher)', '', '', 1);
INSERT INTO breed VALUES (70, 'Argentinische Dogge', '', '', 1);
INSERT INTO breed VALUES (71, 'Bordeauxdogge', '', '', 1);
INSERT INTO breed VALUES (72, 'Holländischer Schäferhund', '', '', 1);
INSERT INTO breed VALUES (73, 'Englische Bulldoge', '', '', 1);
INSERT INTO breed VALUES (74, 'Englischer Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (75, 'Englischer Waschbärenhund', '', '', 1);
INSERT INTO breed VALUES (76, 'Englisch Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'English Setter', '', '', 1);
INSERT INTO breed VALUES (78, 'Englischer Schäferhund (Shepherd)', '', '', 1);
INSERT INTO breed VALUES (79, 'English-Springer-Spaniel', '', '', 1);
INSERT INTO breed VALUES (80, 'King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher Sennenhund', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimohund', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Brasilianische Dogge', '', '', 1);
INSERT INTO breed VALUES (85, 'Finnischer Lapphund', '', '', 1);
INSERT INTO breed VALUES (86, 'Finnen-Spitz', '', '', 1);
INSERT INTO breed VALUES (87, 'Glatthaarig Retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Französiche Bulldogge', '', '', 1);
INSERT INTO breed VALUES (91, 'Deutscher Pinscher', '', '', 1);
INSERT INTO breed VALUES (92, 'Deutscher Schäferhund', '', '', 1);
INSERT INTO breed VALUES (93, 'Deutsch Kurzhaar', '', '', 1);
INSERT INTO breed VALUES (94, 'Deutsch Drahthaar', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Deutsche Dogge', '', '', 1);
INSERT INTO breed VALUES (99, 'Pyrenäen-Berghund', '', '', 1);
INSERT INTO breed VALUES (100, 'Grosser Schweizer Sennenhund', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Havaneser', '', '', 1);
INSERT INTO breed VALUES (103, 'Laufhunde', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibiza-Podenco', '', '', 1);
INSERT INTO breed VALUES (107, 'Jugoslawischer Hirtenhund-Sarplaninac', '', '', 1);
INSERT INTO breed VALUES (108, 'Irischer Setter', '', '', 1);
INSERT INTO breed VALUES (109, 'Irish Terrier', '', '', 1);
INSERT INTO breed VALUES (110, 'Irischer Wasserspaniel', '', '', 1);
INSERT INTO breed VALUES (111, 'Irischer Wolfshund', '', '', 1);
INSERT INTO breed VALUES (112, 'Italienisches Windspiel', '', '', 1);
INSERT INTO breed VALUES (113, 'Italienischer Rauhhaariger Vorstehhund', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Japan-Chin', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelischer Bärenhund', '', '', 1);
INSERT INTO breed VALUES (119, 'Wolfsspitz/Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue Terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Löwchen', '', '', 1);
INSERT INTO breed VALUES (131, 'Malteser', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremme-Abruzzen-Schäferhund', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Zwergpinscher', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Berghund', '', '', 1);
INSERT INTO breed VALUES (139, 'Münsterländer', '', '', 1);
INSERT INTO breed VALUES (140, 'Mastino Napoletano', '', '', 1);
INSERT INTO breed VALUES (141, 'Neuguinea-Dingo', '', '', 1);
INSERT INTO breed VALUES (142, 'Neufundländer', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich Terrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Norwegischer Buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Norwegischer Elchhund', '', '', 1);
INSERT INTO breed VALUES (147, 'Norwegischer Lundehund', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Altenglischer Schäferhund/Bobtail', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhund', '', '', 1);
INSERT INTO breed VALUES (151, 'Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier (Fell Terrier)', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekingese', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruanischer Nackthund', '', '', 1);
INSERT INTO breed VALUES (155, 'Kleiner Basset Griffon Vendéen', '', '', 1);
INSERT INTO breed VALUES (156, 'Pharaonenhund', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Portugiesischer Podengo', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polnischer Niederungshütehund', '', '', 1);
INSERT INTO breed VALUES (162, 'Zwergspitz/Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Pudel', '', '', 1);
INSERT INTO breed VALUES (164, 'Portugiesischer Wasserhund', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Mops', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesian Ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'St.Bernhardshund', '', '', 1);
INSERT INTO breed VALUES (176, 'Samojede', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Deerhound', '', '', 1);
INSERT INTO breed VALUES (180, 'Schottischer Hirschhund', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Hütehund', '', '', 1);
INSERT INTO breed VALUES (185, 'Schäferhund', '', '', 1);
INSERT INTO breed VALUES (186, 'Shetland Sheepdog Sheltie', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Siberian Husky', '', '', 1);
INSERT INTO breed VALUES (190, 'Silky Terrier', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Arabischer Windhund', '', '', 1);
INSERT INTO breed VALUES (193, 'Glatthaar-Foxterrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'Südrussischer Ovtcharka', '', '', 1);
INSERT INTO breed VALUES (198, 'Schwedischer Vallhund', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Tibetmastiff', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibet-Spaniel', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibet-Terrier', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimaraner', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'Weisser Deutscher Schäferhund', '', '', 1);
INSERT INTO breed VALUES (216, 'Französischer Rauhhaariger Vorstehhund', '', '', 1);
INSERT INTO breed VALUES (217, 'Drahthaarig Terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'Gelb Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier', '', '', 1);
INSERT INTO breed VALUES (220, 'Mexikanischer Nackthund', '', '', 1);
INSERT INTO breed VALUES (221, 'Abessinier', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'Amerikanisch Kurzhaar', '', '', 2);
INSERT INTO breed VALUES (224, 'Amerikanisch Drahthaar', '', '', 2);
INSERT INTO breed VALUES (225, 'Apfelkopf Siam', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinesen', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengalkatze', '', '', 2);
INSERT INTO breed VALUES (228, 'Birma', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombaykatze', '', '', 2);
INSERT INTO breed VALUES (231, 'Britisch Kurzhaar', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmesen', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Dreifarbige', '', '', 2);
INSERT INTO breed VALUES (235, 'Kanadische haarlose Katze', '', '', 2);
INSERT INTO breed VALUES (236, 'Kartäuser', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (243, 'Langhaarige Hauskatze', '', '', 2);
INSERT INTO breed VALUES (252, 'Mittelhaarige Hauskatze', '', '', 2);
INSERT INTO breed VALUES (261, 'Kurzhaarige Hauskatze', '', '', 2);
INSERT INTO breed VALUES (271, 'Ägyptische Mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Exotisch Kurzhaar', '', '', 2);
INSERT INTO breed VALUES (273, 'Vielzehigkeit (Hemingway-Katze)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havanna', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Japanese Bobtail', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Norwegische Waldkatze', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Orientalisches Langhaar', '', '', 2);
INSERT INTO breed VALUES (285, 'Orientalisches Kurzhaar', '', '', 2);
INSERT INTO breed VALUES (286, 'Orientalisches Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'Perser', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Russisch Blau', '', '', 2);
INSERT INTO breed VALUES (292, 'Scottish Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siam', '', '', 2);
INSERT INTO breed VALUES (295, 'Sibirische Katze', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somali', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphinx (haarlose Katze)', '', '', 2);
INSERT INTO breed VALUES (307, 'Tiger', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkanese', '', '', 2);
INSERT INTO breed VALUES (311, 'Türkische Angora', '', '', 2);
INSERT INTO breed VALUES (312, 'Türkisch Van', '', '', 2);
INSERT INTO breed VALUES (314, 'Amerikanisch', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angora Kaninchen', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Karnickel', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgen', '', '', 7);
INSERT INTO breed VALUES (328, 'Niederländisch', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havanna', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'Neuseeland', '', '', 7);
INSERT INTO breed VALUES (348, 'Gescheckt', '', '', 7);
INSERT INTO breed VALUES (349, 'Polnisch', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silber', '', '', 7);
INSERT INTO breed VALUES (354, 'Silber Fuchs', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Hellbraun', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabisch', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Esel / Maultier', '', '', 26);
INSERT INTO breed VALUES (361, 'Vorlage', '', '', 24);
INSERT INTO breed VALUES (362, 'Gangpferd', '', '', 24);
INSERT INTO breed VALUES (363, 'Stufe', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Gescheckt', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Reitpferd', '', '', 24);
INSERT INTO breed VALUES (375, 'Halbblut', '', '', 24);
INSERT INTO breed VALUES (376, 'Vollblut', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblut', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Frettchen', '', '', 3);
INSERT INTO breed VALUES (381, 'Rennmaus', '', '', 18);
INSERT INTO breed VALUES (382, 'Hausmeerschweinchen', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Stacheligel', '', '', 6);
INSERT INTO breed VALUES (385, 'Maus', '', '', 4);
INSERT INTO breed VALUES (386, 'Prärie Hund', '', '', 5);
INSERT INTO breed VALUES (387, 'Ratte', '', '', 5);
INSERT INTO breed VALUES (388, 'Stinktier', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (391, 'Vietnamese Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (392, 'Geckos', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Echse', '', '', 13);
INSERT INTO breed VALUES (395, 'Schlange', '', '', 13);
INSERT INTO breed VALUES (396, 'Schildkröte', '', '', 13);
INSERT INTO breed VALUES (397, 'Fisch', '', '', 21);
INSERT INTO breed VALUES (398, 'Graupapagei', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Wellensittich', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Kanarienvogel', '', '', 3);
INSERT INTO breed VALUES (404, 'Huhn', '', '', 3);
INSERT INTO breed VALUES (405, 'Cockatiel', '', '', 3);
INSERT INTO breed VALUES (406, 'Nymphensittich', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Taube', '', '', 3);
INSERT INTO breed VALUES (409, 'Ente', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Fink', '', '', 3);
INSERT INTO breed VALUES (413, 'Gans', '', '', 3);
INSERT INTO breed VALUES (414, 'Guinea fowl', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lory/Lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Strauss', '', '', 3);
INSERT INTO breed VALUES (421, 'Sittich', '', '', 3);
INSERT INTO breed VALUES (422, 'Papagei', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Pfau', '', '', 3);
INSERT INTO breed VALUES (425, 'Fasan', '', '', 3);
INSERT INTO breed VALUES (426, 'Taube', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringeltaube', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Swan', '', '', 3);
INSERT INTO breed VALUES (435, 'Toucan', '', '', 3);
INSERT INTO breed VALUES (436, 'Türkei', '', '', 3);
INSERT INTO breed VALUES (437, 'Kuh', '', '', 16);
INSERT INTO breed VALUES (438, 'Ziege', '', '', 16);
INSERT INTO breed VALUES (439, 'Schaf', '', '', 16);
INSERT INTO breed VALUES (440, 'Lama', '', '', 16);
INSERT INTO breed VALUES (441, 'Schwein', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%Name';
INSERT INTO configuration VALUES ('Organisation', 'Organisation');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Baby');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Jungtier');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Ausgewachsen');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Senior');
DELETE FROM costtype;
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Tiere ohne Microchip', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Überprüfung');
INSERT INTO customreport VALUES (37, 'Tiere ohne Foto', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Überprüfung');
INSERT INTO customreport VALUES (38, 'Tiere ohne Impfung', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Überprüfung');
INSERT INTO customreport VALUES (39, 'Tiere ohne Sterilisation über 6 Monate', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Überprüfung');
INSERT INTO customreport VALUES (40, 'Katzen nicht Kombi getestet', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Überprüfung');
INSERT INTO customreport VALUES (41, 'Monatliche Tier Statistiken', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistik');
INSERT INTO customreport VALUES (42, 'langzeitbewohner', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistik');
INSERT INTO customreport VALUES (43, 'Heim Inventar', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Bestandsaufnahme');
INSERT INTO customreport VALUES (44, 'Detaillierte Bestandsaufnahme', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Bestandsaufnahme');
INSERT INTO customreport VALUES (45, 'Tiere die nicht Teil eines Wurfes sind', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Würfe');
INSERT INTO customreport VALUES (46, 'Eingang/Ausgang', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Bewegungen');
INSERT INTO customreport VALUES (47, 'Eingang/Ausgang Ergebnisse', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Bewegungen');
INSERT INTO customreport VALUES (48, 'In Bericht überführen', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Bewegungen');
INSERT INTO customreport VALUES (49, 'Anzahl der Adoptierungen pro Händler', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Händler');
INSERT INTO customreport VALUES (50, 'Durchschnittliche Aufenthaltszeit bei Händlern bis zur Adoption', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Händler');
INSERT INTO customreport VALUES (51, 'Händler Inventory', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Händler');
INSERT INTO customreport VALUES (52, 'Bericht über wiedergekehrte Tiere', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Rückgabe');
INSERT INTO customreport VALUES (53, 'Zurückgebrachte Tiere in den letzten 6 Monaten', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Rückgabe');
INSERT INTO customreport VALUES (54, 'Zurückgebrachte Tiere nach mehr als 6 Monaten', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Rückgabe');
INSERT INTO customreport VALUES (55, 'Häufigster Name', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiken');
INSERT INTO customreport VALUES (56, 'Gründe für das Ableben von Tieren', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiken');
INSERT INTO customreport VALUES (57, 'Häufigste Eingangsbereiche', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiken');
INSERT INTO customreport VALUES (58, 'Häufigste Adoptionsbereiche', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiken');
INSERT INTO customreport VALUES (59, 'Durchschnittliche Wartezeit', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiken');
INSERT INTO customreport VALUES (60, 'Monatliche Abgaben', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphische Finazielle Auswertung');
INSERT INTO customreport VALUES (61, 'Monatliche Abgaben nach Rassen', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphische Finazielle Auswertung');
INSERT INTO customreport VALUES (62, 'Monatliche Adoptionen nach Rassen', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphische Bewegungs Auswertung');
INSERT INTO customreport VALUES (63, 'Monatliche Adoption nach Ort', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphische Bewegungs Auswertung');
INSERT INTO customreport VALUES (64, 'Abgabe Gründe', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphische Bewegungs Auswertung');
INSERT INTO customreport VALUES (65, 'Rückgabegründe', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphische Bewegungs Auswertung');
INSERT INTO customreport VALUES (66, 'Besitzer Kriterien Vergleich', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Bestandsaufnahme');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Tot eingeliefert', '');
INSERT INTO deathreason VALUES (2, 'Gestorben', '');
INSERT INTO deathreason VALUES (3, 'Gesund', '');
INSERT INTO deathreason VALUES (4, 'Krank/Verlezt', '');
INSERT INTO deathreason VALUES (5, 'Angeordnet', '');
INSERT INTO deathreason VALUES (6, 'Tötung', '');
INSERT INTO deathreason VALUES (7, 'Wild', '');
INSERT INTO deathreason VALUES (8, 'Bissig', '');
DELETE FROM diet;
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Spende', '');
INSERT INTO donationtype VALUES (2, 'Vermittlungsgebühr', '');
INSERT INTO donationtype VALUES (3, 'Wartelistengebühr', '');
INSERT INTO donationtype VALUES (4, 'Eingangsgebühr', '');
INSERT INTO donationtype VALUES (5, 'Patenschaftsgebühr', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Scheidung/Trennung', '');
INSERT INTO entryreason VALUES (2, 'Allergien', '');
INSERT INTO entryreason VALUES (3, 'Bissig', '');
INSERT INTO entryreason VALUES (4, 'Erziehungsproblem', '');
INSERT INTO entryreason VALUES (5, 'Unterbringung', '');
INSERT INTO entryreason VALUES (6, 'Gestorben', '');
INSERT INTO entryreason VALUES (7, 'Fundtier', '');
INSERT INTO entryreason VALUES (8, 'Krank/Verlezt', '');
INSERT INTO entryreason VALUES (9, 'Finanzielle Probleme', '');
INSERT INTO entryreason VALUES (10, 'Quälerei', '');
INSERT INTO entryreason VALUES (11, 'Ausgesetzt', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Keine Angabe', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Weibchen');
INSERT INTO lksex VALUES (1, 'Männchen');
INSERT INTO lksex VALUES (2, 'Unbekannt');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Sehr groß');
INSERT INTO lksize VALUES (1, 'Groß');
INSERT INTO lksize VALUES (2, 'Mittel');
INSERT INTO lksize VALUES (3, 'Klein');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Kurz');
INSERT INTO lkcoattype VALUES (1, 'Lang');
INSERT INTO lkcoattype VALUES (2, 'Rau');
INSERT INTO lkcoattype VALUES (3, 'Kraus');
INSERT INTO lkcoattype VALUES (4, 'Verschnürt');
INSERT INTO lkcoattype VALUES (5, 'Haarlos');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Keiner');
INSERT INTO lksmovementtype VALUES (1, 'Adoption');
INSERT INTO lksmovementtype VALUES (2, 'Pflege');
INSERT INTO lksmovementtype VALUES (3, 'Transfer');
INSERT INTO lksmovementtype VALUES (4, 'Entlaufen');
INSERT INTO lksmovementtype VALUES (5, 'Zurück Beansprucht');
INSERT INTO lksmovementtype VALUES (6, 'Entwendet');
INSERT INTO lksmovementtype VALUES (7, 'Freigelassen');
INSERT INTO lksmovementtype VALUES (8, 'Händler');
INSERT INTO lksmovementtype VALUES (9, 'Reservierung');
INSERT INTO lksmovementtype VALUES (10, 'Stornierte Reservierung');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Tier');
INSERT INTO lksmedialink VALUES (1, 'Entlaufen');
INSERT INTO lksmedialink VALUES (2, 'Fundtier');
INSERT INTO lksmedialink VALUES (3, 'Eigentümer');
INSERT INTO lksmedialink VALUES (4, 'Bewegung');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Keiner');
INSERT INTO lksdiarylink VALUES (1, 'Tier');
INSERT INTO lksdiarylink VALUES (2, 'Eigentümer');
INSERT INTO lksdiarylink VALUES (3, 'Entlaufen');
INSERT INTO lksdiarylink VALUES (4, 'Fundtier');
INSERT INTO lksdiarylink VALUES (5, 'Warteliste');
INSERT INTO lksdiarylink VALUES (6, 'Bewegung');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'Einmalig');
INSERT INTO lksdonationfreq VALUES (1, 'wöchentlich');
INSERT INTO lksdonationfreq VALUES (2, 'monatlich');
INSERT INTO lksdonationfreq VALUES (3, 'vierteljährlich');
INSERT INTO lksdonationfreq VALUES (4, 'halbjährlich');
INSERT INTO lksdonationfreq VALUES (5, 'jährlich');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Tier');
INSERT INTO lksfieldlink VALUES (1, 'Eigentümer');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Ja/Nein');
INSERT INTO lksfieldtype VALUES (1, 'Text');
INSERT INTO lksfieldtype VALUES (2, 'Anmerkungen');
INSERT INTO lksfieldtype VALUES (3, 'Nummer');
INSERT INTO lksfieldtype VALUES (4, 'Datum');
INSERT INTO lksfieldtype VALUES (5, 'Geld');
INSERT INTO lksfieldtype VALUES (6, 'Suche');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Tier');
INSERT INTO lksloglink VALUES (1, 'Eigentümer');
INSERT INTO lksloglink VALUES (2, 'Entlaufen');
INSERT INTO lksloglink VALUES (3, 'Fundtier');
INSERT INTO lksloglink VALUES (4, 'Warteliste');
INSERT INTO lksloglink VALUES (5, 'Bewegung');
DELETE FROM lksyesno;
DELETE FROM lksynun;
DELETE FROM lksposneg;
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Dringend');
INSERT INTO lkurgency VALUES (2, 'Hoch');
INSERT INTO lkurgency VALUES (3, 'Mittel');
INSERT INTO lkurgency VALUES (4, 'Niedrig');
INSERT INTO lkurgency VALUES (5, 'Sehr gering');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Biss', '');
INSERT INTO logtype VALUES (2, 'Beschwerde', '');
INSERT INTO logtype VALUES (3, 'Historie', '');
INSERT INTO logtype VALUES (4, 'Gewicht', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Hund', '', '');
INSERT INTO species VALUES (2, 'Katze', '', '');
INSERT INTO species VALUES (3, 'Vogel', '', '');
INSERT INTO species VALUES (4, 'Maus', '', '');
INSERT INTO species VALUES (5, 'Ratte', '', '');
INSERT INTO species VALUES (6, 'Stacheligel', '', '');
INSERT INTO species VALUES (7, 'Kaninchen', '', '');
INSERT INTO species VALUES (8, 'Taube', '', '');
INSERT INTO species VALUES (9, 'Frettchen', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Schlange', '', '');
INSERT INTO species VALUES (12, 'Tortoise', '', '');
INSERT INTO species VALUES (13, 'Terrapin', '', '');
INSERT INTO species VALUES (14, 'Huhn', '', '');
INSERT INTO species VALUES (15, 'Eule', '', '');
INSERT INTO species VALUES (16, 'Ziege', '', '');
INSERT INTO species VALUES (17, 'Gans', '', '');
INSERT INTO species VALUES (18, 'Rennmaus', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'Hausmeerschweinchen', '', '');
INSERT INTO species VALUES (21, 'Goldfisch', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Kamel', '', '');
INSERT INTO species VALUES (24, 'Pferd', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Esel', '', '');
INSERT INTO species VALUES (27, 'Lama', '', '');
INSERT INTO species VALUES (28, 'Schwein', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Sterilisiert', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Vorrübergehende Impfung', '');
INSERT INTO vaccinationtype VALUES (2, 'Erstimpfung', '');
INSERT INTO vaccinationtype VALUES (3, 'Zweitimpfung', '');
INSERT INTO vaccinationtype VALUES (4, 'Verstärker', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukaemie', '');
INSERT INTO vaccinationtype VALUES (6, 'Zwingerhusten', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirus', '');
