DELETE FROM animaltype;
INSERT INTO animaltype VALUES (10, 'G (Gyvūnas iš gatvės)', NULL);
INSERT INTO animaltype VALUES (11, 'N (Gyvūnas iš namų)', NULL);
INSERT INTO animaltype VALUES (12, 'P (Gyvūnas iš prieglaudos)', NULL);
INSERT INTO animaltype VALUES (13, 'X (Nežinoma)', NULL);
INSERT INTO animaltype VALUES (40, 'E (Ne prieglaudos apskaitai)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Juoda', NULL);
INSERT INTO basecolour VALUES (2, 'Balta', NULL);
INSERT INTO basecolour VALUES (3, 'Juoda su balta', NULL);
INSERT INTO basecolour VALUES (4, 'Ryža', NULL);
INSERT INTO basecolour VALUES (5, 'Balta su juoda', NULL);
INSERT INTO basecolour VALUES (6, 'Tamsi trispalvė (katėms)', NULL);
INSERT INTO basecolour VALUES (7, 'Raina (katėms)', NULL);
INSERT INTO basecolour VALUES (8, 'Rusva', NULL);
INSERT INTO basecolour VALUES (9, 'Juoda su rusva', NULL);
INSERT INTO basecolour VALUES (10, 'Rusva su juoda', NULL);
INSERT INTO basecolour VALUES (11, 'Ruda', NULL);
INSERT INTO basecolour VALUES (12, 'Ruda su juoda', NULL);
INSERT INTO basecolour VALUES (13, 'Juoda su ruda', NULL);
INSERT INTO basecolour VALUES (14, 'Tigrinė (šunims)', NULL);
INSERT INTO basecolour VALUES (15, 'Tigrinė su juoda', NULL);
INSERT INTO basecolour VALUES (16, 'Tigrinė su balta', NULL);
INSERT INTO basecolour VALUES (17, 'Juoda su tigrine', NULL);
INSERT INTO basecolour VALUES (18, 'Balta su tigrine', NULL);
INSERT INTO basecolour VALUES (19, 'Trispalvė (šviesi)', NULL);
INSERT INTO basecolour VALUES (20, 'Bordinė', NULL);
INSERT INTO basecolour VALUES (21, 'Bordinė su balta', NULL);
INSERT INTO basecolour VALUES (22, 'Balta su bordine', NULL);
INSERT INTO basecolour VALUES (23, 'Kreminė', NULL);
INSERT INTO basecolour VALUES (24, 'Rusva su balta', NULL);
INSERT INTO basecolour VALUES (26, 'Balta su rusva', NULL);
INSERT INTO basecolour VALUES (27, 'Tamsiai trispalvė su balta', NULL);
INSERT INTO basecolour VALUES (28, 'Raina su balta', NULL);
INSERT INTO basecolour VALUES (29, 'Ryža su balta', NULL);
INSERT INTO basecolour VALUES (30, 'Pilka', NULL);
INSERT INTO basecolour VALUES (31, 'Pilka su balta', NULL);
INSERT INTO basecolour VALUES (32, 'Balta su pilka', NULL);
INSERT INTO basecolour VALUES (33, 'Balta su tamsia trispalve', NULL);
INSERT INTO basecolour VALUES (35, 'Ruda su balta', NULL);
INSERT INTO basecolour VALUES (36, 'Melsva', NULL);
INSERT INTO basecolour VALUES (37, 'Balta su raina', NULL);
INSERT INTO basecolour VALUES (38, 'Geltona su pilka', NULL);
INSERT INTO basecolour VALUES (39, 'Įvairi', NULL);
INSERT INTO basecolour VALUES (40, 'Balta su ruda', NULL);
INSERT INTO basecolour VALUES (41, 'Žalia', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Afenpinčeris', '', '', 1);
INSERT INTO breed VALUES (2, 'Afganų kurtas', '', '', 1);
INSERT INTO breed VALUES (3, 'Airių terjeras', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbašas', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Aliaskos malamutas', '', '', 1);
INSERT INTO breed VALUES (7, 'Amerikiečių buldogas', '', '', 1);
INSERT INTO breed VALUES (8, 'Amerikiečių eskimų šuo', '', '', 1);
INSERT INTO breed VALUES (9, 'Amerikiečių Stafordšyro terjeras', '', '', 1);
INSERT INTO breed VALUES (10, 'Amerikiečių vandens spanielis', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolijos aviganis', '', '', 1);
INSERT INTO breed VALUES (12, 'Apenceleris', '', '', 1);
INSERT INTO breed VALUES (13, 'Australų piemenų šuo/Žydrasis hileris', '', '', 1);
INSERT INTO breed VALUES (14, 'Australų kelpis', '', '', 1);
INSERT INTO breed VALUES (15, 'Australų aviganis', '', '', 1);
INSERT INTO breed VALUES (16, 'Australų terjeras', '', '', 1);
INSERT INTO breed VALUES (17, 'Basendžis', '', '', 1);
INSERT INTO breed VALUES (18, 'Basetas', '', '', 1);
INSERT INTO breed VALUES (19, 'Biglis', '', '', 1);
INSERT INTO breed VALUES (20, 'Barzdotasis kolis', '', '', 1);
INSERT INTO breed VALUES (21, 'Boseronas', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlingtono terjeras', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgų aviganis', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgų aviganis lakenua', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgų aviganis malinua', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgų aviganis terviurenas', '', '', 1);
INSERT INTO breed VALUES (27, 'Berno kalnų šuo/Berno zenenhundas', '', '', 1);
INSERT INTO breed VALUES (28, 'Bišon frizas', '', '', 1);
INSERT INTO breed VALUES (29, 'Anglų kokerspanielis', '', '', 1);
INSERT INTO breed VALUES (30, 'Amerikiečių kokerspanielis', '', '', 1);
INSERT INTO breed VALUES (31, 'Neveislinis', '', '', 1);
INSERT INTO breed VALUES (32, 'Bladhaundas', '', '', 1);
INSERT INTO breed VALUES (34, 'Borderkolis', '', '', 1);
INSERT INTO breed VALUES (35, 'Borderterjeras', '', '', 1);
INSERT INTO breed VALUES (36, 'Rusų kurtas', '', '', 1);
INSERT INTO breed VALUES (37, 'Bostono terjeras', '', '', 1);
INSERT INTO breed VALUES (38, 'Flamandų buvje', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin spanielis', '', '', 1);
INSERT INTO breed VALUES (40, 'Bokseris', '', '', 1);
INSERT INTO breed VALUES (41, 'Briaras', '', '', 1);
INSERT INTO breed VALUES (42, 'Bretanės spanielis', '', '', 1);
INSERT INTO breed VALUES (43, 'Briuselio grifonas', '', '', 1);
INSERT INTO breed VALUES (44, 'Bulterjeras', '', '', 1);
INSERT INTO breed VALUES (45, 'Bulmastifas', '', '', 1);
INSERT INTO breed VALUES (46, 'Kernterjeras', '', '', 1);
INSERT INTO breed VALUES (47, 'Kanų šuo', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso', '', '', 1);
INSERT INTO breed VALUES (49, 'Karolinos šuo', '', '', 1);
INSERT INTO breed VALUES (52, 'Kavalieriaus karaliaus Karolio spanielis', '', '', 1);
INSERT INTO breed VALUES (53, 'Česapiko įlankos retriveris', '', '', 1);
INSERT INTO breed VALUES (54, 'Čihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Kiniečių kuoduotasis šuo', '', '', 1);
INSERT INTO breed VALUES (56, 'Kiniečių plikasis šuo', '', '', 1);
INSERT INTO breed VALUES (58, 'Čiau čiau', '', '', 1);
INSERT INTO breed VALUES (59, 'Klamberio spanielis', '', '', 1);
INSERT INTO breed VALUES (60, 'Vidurinės Azijos aviganis', '', '', 1);
INSERT INTO breed VALUES (61, 'Kaukazo aviganis', '', '', 1);
INSERT INTO breed VALUES (62, 'Kolis', '', '', 1);
INSERT INTO breed VALUES (64, 'Korgis', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Taksas', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatinas', '', '', 1);
INSERT INTO breed VALUES (68, 'Dendžio Dinmonto terjeras', '', '', 1);
INSERT INTO breed VALUES (69, 'Dobermanas', '', '', 1);
INSERT INTO breed VALUES (70, 'Argentinos dogas', '', '', 1);
INSERT INTO breed VALUES (71, 'Bordo dogas', '', '', 1);
INSERT INTO breed VALUES (72, 'Danų aviganis', '', '', 1);
INSERT INTO breed VALUES (73, 'Anglų buldogas', '', '', 1);
INSERT INTO breed VALUES (76, 'Anglų pointeris', '', '', 1);
INSERT INTO breed VALUES (77, 'Anglų seteris', '', '', 1);
INSERT INTO breed VALUES (78, 'Anglų aviganis', '', '', 1);
INSERT INTO breed VALUES (79, 'Anglų springerspanielis', '', '', 1);
INSERT INTO breed VALUES (80, 'Anglų toi spanielis', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucheris', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimų šuo', '', '', 1);
INSERT INTO breed VALUES (83, 'Fildspanielis', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila Brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Suomių laphundas', '', '', 1);
INSERT INTO breed VALUES (86, 'Suomių špicas', '', '', 1);
INSERT INTO breed VALUES (87, 'Lygiaplaukis retriveris', '', '', 1);
INSERT INTO breed VALUES (88, 'Foksterjeras', '', '', 1);
INSERT INTO breed VALUES (89, 'Fokshaundas', '', '', 1);
INSERT INTO breed VALUES (90, 'Prancūzų buldogas', '', '', 1);
INSERT INTO breed VALUES (91, 'Pinčeris', '', '', 1);
INSERT INTO breed VALUES (92, 'Vokiečių aviganis', '', '', 1);
INSERT INTO breed VALUES (93, 'Vokiečių trumpaplaukis pointeris', '', '', 1);
INSERT INTO breed VALUES (94, 'Vokiečių šiurkščiaplaukis pointeris', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal terjeras', '', '', 1);
INSERT INTO breed VALUES (96, 'Auksaspalvis retriveris', '', '', 1);
INSERT INTO breed VALUES (97, 'Škotų seteris/Gordono seteris', '', '', 1);
INSERT INTO breed VALUES (98, 'Dogas', '', '', 1);
INSERT INTO breed VALUES (99, 'Pirėnų kalnų šuo', '', '', 1);
INSERT INTO breed VALUES (100, 'Didysis šveicarų kalnų šuo', '', '', 1);
INSERT INTO breed VALUES (101, 'Greihaundas', '', '', 1);
INSERT INTO breed VALUES (102, 'Havanos bišonas', '', '', 1);
INSERT INTO breed VALUES (103, 'Skalikas', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovavartas', '', '', 1);
INSERT INTO breed VALUES (105, 'Haskis', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibizos kurtas', '', '', 1);
INSERT INTO breed VALUES (108, 'Airių seteris', '', '', 1);
INSERT INTO breed VALUES (109, 'Airių terjeras', '', '', 1);
INSERT INTO breed VALUES (110, 'Airių vandens spanielis', '', '', 1);
INSERT INTO breed VALUES (111, 'Airių volfhaundas', '', '', 1);
INSERT INTO breed VALUES (112, 'Italų greihaundas', '', '', 1);
INSERT INTO breed VALUES (113, 'Italų spinonė', '', '', 1);
INSERT INTO breed VALUES (114, 'Džeko Raselo terjeras', '', '', 1);
INSERT INTO breed VALUES (115, 'Japonų činas', '', '', 1);
INSERT INTO breed VALUES (116, 'Juodasis terjeras', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelų laika', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshondas', '', '', 1);
INSERT INTO breed VALUES (120, 'Keribliuterjeras', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondoras', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasas', '', '', 1);
INSERT INTO breed VALUES (125, 'Labradoro retriveris', '', '', 1);
INSERT INTO breed VALUES (126, 'Leiklendo terjeras', '', '', 1);
INSERT INTO breed VALUES (127, 'Lietuvių skalikas', '', '', 1);
INSERT INTO breed VALUES (128, 'Lasos apsas', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonbergeris', '', '', 1);
INSERT INTO breed VALUES (130, 'Šuo liūtukas', '', '', 1);
INSERT INTO breed VALUES (131, 'Maltos bolonė', '', '', 1);
INSERT INTO breed VALUES (132, 'Mančesterio terjeras', '', '', 1);
INSERT INTO breed VALUES (133, 'Marema', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastifas', '', '', 1);
INSERT INTO breed VALUES (136, 'Miniatiūrinis pinčeris', '', '', 1);
INSERT INTO breed VALUES (137, 'Mitelšnauceris', '', '', 1);
INSERT INTO breed VALUES (139, 'Miunsterlenderis', '', '', 1);
INSERT INTO breed VALUES (140, 'Neapolio mastinas', '', '', 1);
INSERT INTO breed VALUES (142, 'Niufaundlendas', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolko terjeras', '', '', 1);
INSERT INTO breed VALUES (144, 'Norvičo terjeras', '', '', 1);
INSERT INTO breed VALUES (145, 'Norvegų buhundas', '', '', 1);
INSERT INTO breed VALUES (146, 'Norvegų elkhundas', '', '', 1);
INSERT INTO breed VALUES (147, 'Norvegų lundehundas', '', '', 1);
INSERT INTO breed VALUES (148, 'Naujosios Škotijos retriveris', '', '', 1);
INSERT INTO breed VALUES (149, 'Bobteilas', '', '', 1);
INSERT INTO breed VALUES (150, 'Oterhaundas', '', '', 1);
INSERT INTO breed VALUES (151, 'Papiljonas', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekinas', '', '', 1);
INSERT INTO breed VALUES (154, 'Peru plikasis šuo', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit Basset Griffon Vendeen', '', '', 1);
INSERT INTO breed VALUES (156, 'Faraonų šuo', '', '', 1);
INSERT INTO breed VALUES (157, 'Pitbulterjeras', '', '', 1);
INSERT INTO breed VALUES (159, 'Portugalų Podengo', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointeris', '', '', 1);
INSERT INTO breed VALUES (161, 'Lenkų žemumų aviganis', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomeranės aviganis', '', '', 1);
INSERT INTO breed VALUES (163, 'Pudelis', '', '', 1);
INSERT INTO breed VALUES (164, 'Portugalų vandens šuo', '', '', 1);
INSERT INTO breed VALUES (166, 'Mopsas', '', '', 1);
INSERT INTO breed VALUES (167, 'Pulis', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumis', '', '', 1);
INSERT INTO breed VALUES (169, 'Ryzenšnauceris', '', '', 1);
INSERT INTO breed VALUES (172, 'Rodezijos ridžbekas', '', '', 1);
INSERT INTO breed VALUES (173, 'Rotveileris', '', '', 1);
INSERT INTO breed VALUES (174, 'Saliukis', '', '', 1);
INSERT INTO breed VALUES (175, 'Senbernaras', '', '', 1);
INSERT INTO breed VALUES (176, 'Samojedų laika', '', '', 1);
INSERT INTO breed VALUES (177, 'Šiperkė', '', '', 1);
INSERT INTO breed VALUES (178, 'Šnauceris', '', '', 1);
INSERT INTO breed VALUES (179, 'Dirhaundas', '', '', 1);
INSERT INTO breed VALUES (181, 'Silihemo terjeras', '', '', 1);
INSERT INTO breed VALUES (182, 'Seteris', '', '', 1);
INSERT INTO breed VALUES (183, 'Šarpėjus', '', '', 1);
INSERT INTO breed VALUES (186, 'Šeltis', '', '', 1);
INSERT INTO breed VALUES (187, 'Šiba inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Ši-cu', '', '', 1);
INSERT INTO breed VALUES (190, 'Šilkinis terjeras', '', '', 1);
INSERT INTO breed VALUES (191, 'Skajaus terjeras', '', '', 1);
INSERT INTO breed VALUES (192, 'Slugis', '', '', 1);
INSERT INTO breed VALUES (193, 'Trumpaplaukis foksterjeras', '', '', 1);
INSERT INTO breed VALUES (194, 'Spanielis', '', '', 1);
INSERT INTO breed VALUES (195, 'Špicas', '', '', 1);
INSERT INTO breed VALUES (196, 'Stafordšyro bulterjeras', '', '', 1);
INSERT INTO breed VALUES (197, 'Pietų Rusijos aviganis', '', '', 1);
INSERT INTO breed VALUES (198, 'Švedų valhundas', '', '', 1);
INSERT INTO breed VALUES (199, 'Terjeras', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai ridžbekas', '', '', 1);
INSERT INTO breed VALUES (201, 'Tibeto mastifas', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibeto spanielis', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibeto terjeras', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (207, 'Vižlas', '', '', 1);
INSERT INTO breed VALUES (208, 'Veimaraneris', '', '', 1);
INSERT INTO breed VALUES (209, 'Valų korgis', '', '', 1);
INSERT INTO breed VALUES (210, 'Valų terjeras', '', '', 1);
INSERT INTO breed VALUES (212, 'Vakarų Škotijos baltasis terjeras', '', '', 1);
INSERT INTO breed VALUES (213, 'Kviečiaplaukis terjeras', '', '', 1);
INSERT INTO breed VALUES (214, 'Vipetas', '', '', 1);
INSERT INTO breed VALUES (215, 'Baltasis šveicarų aviganis', '', '', 1);
INSERT INTO breed VALUES (217, 'Šiurkščiaplaukis terjeras', '', '', 1);
INSERT INTO breed VALUES (219, 'Jorkšyro terjeras', '', '', 1);
INSERT INTO breed VALUES (220, 'Meksikiečių plikasis šuo', '', '', 1);
INSERT INTO breed VALUES (221, 'Abisinijos katė', '', '', 2);
INSERT INTO breed VALUES (222, 'Amerikiečių riestaausė katė', '', '', 2);
INSERT INTO breed VALUES (223, 'Amerikiečių trumpaplaukė katė', '', '', 2);
INSERT INTO breed VALUES (226, 'Balio katė', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengalijos katė', '', '', 2);
INSERT INTO breed VALUES (228, 'Birmos katė', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombėjaus katė', '', '', 2);
INSERT INTO breed VALUES (231, 'Britų trumpaplaukė katė', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmos katė', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilos katė', '', '', 2);
INSERT INTO breed VALUES (236, 'Kartezianinė katė', '', '', 2);
INSERT INTO breed VALUES (237, 'Šinšila', '', '', 2);
INSERT INTO breed VALUES (238, 'Kornvalio reksas', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devonreksas', '', '', 2);
INSERT INTO breed VALUES (271, 'Egipto Mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Egzotų katė', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalajų katė', '', '', 2);
INSERT INTO breed VALUES (276, 'Japonų bobteilas', '', '', 2);
INSERT INTO breed VALUES (278, 'Koratas', '', '', 2);
INSERT INTO breed VALUES (279, 'Meino meškėnas', '', '', 2);
INSERT INTO breed VALUES (280, 'Manksų katė', '', '', 2);
INSERT INTO breed VALUES (282, 'Norvegų miškinė katė', '', '', 2);
INSERT INTO breed VALUES (283, 'Oksikat', '', '', 2);
INSERT INTO breed VALUES (284, 'Rytų katė (orientalas)', '', '', 2);
INSERT INTO breed VALUES (287, 'Persų katė', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Rusų melsvoji katė', '', '', 2);
INSERT INTO breed VALUES (292, 'Škotų nulėpausė', '', '', 2);
INSERT INTO breed VALUES (294, 'Siamo katė', '', '', 2);
INSERT INTO breed VALUES (295, 'Sibiro katė', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Sniego letenėlė', '', '', 2);
INSERT INTO breed VALUES (298, 'Somalio katė', '', '', 2);
INSERT INTO breed VALUES (299, 'Sfinksas', '', '', 2);
INSERT INTO breed VALUES (311, 'Turkų angora', '', '', 2);
INSERT INTO breed VALUES (312, 'Turkų van katė', '', '', 2);
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Gyvūnai be mikroschemų', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditas');
INSERT INTO customreport VALUES (37, 'Gyvūnai be vaizdinės medžiagos', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditas');
INSERT INTO customreport VALUES (38, 'Nevakcinuoti gyvūnai', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditas');
INSERT INTO customreport VALUES (39, 'Nekastruoti/Nesterilizuoti 6 mėn. ir vyresni gyvūnai', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditas');
INSERT INTO customreport VALUES (40, 'Katės be FLV/FIV testo', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditas');
INSERT INTO customreport VALUES (41, 'Gyvūnų skaičiai per mėnesį', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Skaičiai');
INSERT INTO customreport VALUES (42, 'Prieglaudos senbuviai', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Skaičiai');
INSERT INTO customreport VALUES (43, 'Prieglaudos gyvūnų suvestinė', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Prieglauda');
INSERT INTO customreport VALUES (44, 'Prieglaudos gyvūnai detaliai', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Prieglauda');
INSERT INTO customreport VALUES (45, 'Jaunikliai nepriklausantys vadai', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Vados');
INSERT INTO customreport VALUES (46, 'Į prieglaudą/Iš prieglaudos detaliai', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Veiksmai');
INSERT INTO customreport VALUES (47, 'Į prieglaudą/Iš prieglaudos suvestinė', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Veiksmai');
INSERT INTO customreport VALUES (48, 'Gyvūnai iš kitų prieglaudų', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Veiksmai');
INSERT INTO customreport VALUES (49, 'Atidavimų apimtis pagal tarpininkus', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Tarpininkai');
INSERT INTO customreport VALUES (50, 'Vidutinis laikas pas tarpininką iki atidavimo', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Tarpininkai');
INSERT INTO customreport VALUES (51, 'Gyvūnai pas tarpininkus', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Tarpininkai');
INSERT INTO customreport VALUES (52, 'Grąžintų gyvūnų ataskaita', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grąžinimai');
INSERT INTO customreport VALUES (53, 'Gyvūnai grąžinti 6 mėn. laikotarpiu', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grąžinimai');
INSERT INTO customreport VALUES (54, 'Gyvūnai grąžinti vėliau kaip po 6 mėn.', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grąžinimai');
INSERT INTO customreport VALUES (55, 'Populiariausias vardas', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistika');
INSERT INTO customreport VALUES (56, 'Gyvūnų mirčių priežastys', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistika');
INSERT INTO customreport VALUES (57, 'Dažniausi gyvūnų radimo rajonai', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistika');
INSERT INTO customreport VALUES (58, 'Dažniausi gyvūnų atidavimo rajonai', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistika');
INSERT INTO customreport VALUES (59, 'Vidutinis laikas laukiančių vietos sąraše', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistika');
INSERT INTO customreport VALUES (60, 'Parama per mėnesį', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Finansiniai grafikai');
INSERT INTO customreport VALUES (61, 'Parama per mėnesį pagal rūšis', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Finansiniai grafikai');
INSERT INTO customreport VALUES (62, 'Atidavimai per mėnesį pagal gyvūnų rūšis', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Veiksmų grafikai');
INSERT INTO customreport VALUES (63, 'Atidavimai per mėnesį pagal vietą', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Veiksmų grafikai');
INSERT INTO customreport VALUES (64, 'Gyvūnų patekimo priežastys', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Veiksmų grafikai');
INSERT INTO customreport VALUES (65, 'Gyvūnų grąžinimo priežastys', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Veiksmų grafikai');
INSERT INTO customreport VALUES (66, 'Atitikimas norimiems įsigyti gyvūnams', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Prieglauda');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Atvyko miręs', '');
INSERT INTO deathreason VALUES (2, 'Mirė', '');
INSERT INTO deathreason VALUES (3, 'Sveikas', '');
INSERT INTO deathreason VALUES (4, 'Sergantis/Sužeistas', '');
INSERT INTO deathreason VALUES (5, 'Pagal prašymą', '');
INSERT INTO deathreason VALUES (6, 'Skerdimui', '');
INSERT INTO deathreason VALUES (7, 'Sulaukėjęs', '');
INSERT INTO deathreason VALUES (8, 'Įkando', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Skyrybos', '');
INSERT INTO entryreason VALUES (2, 'Alergija', '');
INSERT INTO entryreason VALUES (3, 'Įkando', '');
INSERT INTO entryreason VALUES (4, 'Nesusitvarko', '');
INSERT INTO entryreason VALUES (5, 'Netinkama gyvenamoji vieta', '');
INSERT INTO entryreason VALUES (6, 'Mirė šeimininkas', '');
INSERT INTO entryreason VALUES (7, 'Iš gatvės', '');
INSERT INTO entryreason VALUES (8, 'Serga/Sužeistas', '');
INSERT INTO entryreason VALUES (9, 'Finansinės problemos', '');
INSERT INTO entryreason VALUES (10, 'Žiaurus elgesys', '');
INSERT INTO entryreason VALUES (11, 'Paliktas be priežiūros', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'SOS gyvūnų namelis', '');
INSERT INTO internallocation VALUES (2, 'Žalgirio g. 60', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Patelė');
INSERT INTO lksex VALUES (1, 'Patinas');
INSERT INTO lksex VALUES (2, 'Nežinoma');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Labai didelis');
INSERT INTO lksize VALUES (1, 'Didelis');
INSERT INTO lksize VALUES (2, 'Vidutinis');
INSERT INTO lksize VALUES (3, 'Mažas');
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Joks');
INSERT INTO lksmovementtype VALUES (1, 'Atidavimas');
INSERT INTO lksmovementtype VALUES (2, 'Laikina globa namuose');
INSERT INTO lksmovementtype VALUES (3, 'Perkėlimas į kitą prieglaudą');
INSERT INTO lksmovementtype VALUES (4, 'Pabėgo');
INSERT INTO lksmovementtype VALUES (5, 'Grįžo į namus');
INSERT INTO lksmovementtype VALUES (6, 'Pavogtas');
INSERT INTO lksmovementtype VALUES (7, 'Paleistas į laisvę');
INSERT INTO lksmovementtype VALUES (8, 'Pas tarpininką');
INSERT INTO lksmovementtype VALUES (9, 'Rezervacija');
INSERT INTO lksmovementtype VALUES (10, 'Atšaukta rezervacija');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Gyvūnas');
INSERT INTO lksmedialink VALUES (1, 'Dingęs gyvūnas');
INSERT INTO lksmedialink VALUES (2, 'Rastas gyvūnas');
INSERT INTO lksmedialink VALUES (3, 'Asmuo');
INSERT INTO lksmedialink VALUES (4, 'Perkėlimas');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Joks');
INSERT INTO lksdiarylink VALUES (1, 'Gyvūnas');
INSERT INTO lksdiarylink VALUES (2, 'Asmuo');
INSERT INTO lksdiarylink VALUES (3, 'Dingęs gyvūnas');
INSERT INTO lksdiarylink VALUES (4, 'Rastas gyvūnas');
INSERT INTO lksdiarylink VALUES (5, 'Laukia vietos');
INSERT INTO lksdiarylink VALUES (6, 'Veiksmas');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Gyvūnas');
INSERT INTO lksloglink VALUES (1, 'Asmuo');
INSERT INTO lksloglink VALUES (2, 'Dingęs gyvūnas');
INSERT INTO lksloglink VALUES (3, 'Rastas gyvūnas');
INSERT INTO lksloglink VALUES (4, 'Laukia vietos');
INSERT INTO lksloglink VALUES (5, 'Veiksmas');
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Skubus');
INSERT INTO lkurgency VALUES (2, 'Aukštas');
INSERT INTO lkurgency VALUES (3, 'Vidutinis');
INSERT INTO lkurgency VALUES (4, 'Žemas');
INSERT INTO lkurgency VALUES (5, 'Žemiausias');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Įkandimai', '');
INSERT INTO logtype VALUES (2, 'Nusiskundimai', '');
INSERT INTO logtype VALUES (3, 'Istorija', '');
INSERT INTO logtype VALUES (4, 'Svoris', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Šuo', '', '');
INSERT INTO species VALUES (2, 'Katė', '', '');
INSERT INTO species VALUES (3, 'Banguotoji papūgėlė', '', '');
INSERT INTO species VALUES (4, 'Pelė', '', '');
INSERT INTO species VALUES (5, 'Žiurkė', '', '');
INSERT INTO species VALUES (6, 'Ežys', '', '');
INSERT INTO species VALUES (7, 'Triušis', '', '');
INSERT INTO species VALUES (8, 'Balandis', '', '');
INSERT INTO species VALUES (9, 'Šeškas', '', '');
INSERT INTO species VALUES (10, 'Šinšila', '', '');
INSERT INTO species VALUES (11, 'Gyvatė', '', '');
INSERT INTO species VALUES (12, 'Sausumos vėžlys', '', '');
INSERT INTO species VALUES (13, 'Vandens vėžlys', '', '');
INSERT INTO species VALUES (18, 'Smiltpelė', '', '');
INSERT INTO species VALUES (19, 'Papūga', '', '');
INSERT INTO species VALUES (20, 'Jūros kiaulytė', '', '');
INSERT INTO species VALUES (21, 'Žuvytė', '', '');
INSERT INTO species VALUES (22, 'Žiurkėnas', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Kastracija/Sterilizacija', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Laikina vakcinacija', '');
INSERT INTO vaccinationtype VALUES (2, 'Pirma vakcinacija', '');
INSERT INTO vaccinationtype VALUES (3, 'Antra vakcinacija', '');
INSERT INTO vaccinationtype VALUES (4, 'Pakartotinė vakcinacija (booster)', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukemija', '');
INSERT INTO vaccinationtype VALUES (6, 'Šunidžių kosulys', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirusas', '');
