DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Hond)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Zwerfhond)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Ongewenste kat)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Zwerfkat)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Veelsoortig)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Niet-centrumdier)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Zwart', NULL);
INSERT INTO basecolour VALUES (2, 'Wit', NULL);
INSERT INTO basecolour VALUES (3, 'Zwart en wit', NULL);
INSERT INTO basecolour VALUES (4, 'Ros', NULL);
INSERT INTO basecolour VALUES (5, 'Wit en zwart', NULL);
INSERT INTO basecolour VALUES (6, 'Schildpad', NULL);
INSERT INTO basecolour VALUES (7, 'Tabby', NULL);
INSERT INTO basecolour VALUES (8, 'Lichtbruin', NULL);
INSERT INTO basecolour VALUES (9, 'Zwart en lichtbruin', NULL);
INSERT INTO basecolour VALUES (10, 'Lichtbruin en zwart', NULL);
INSERT INTO basecolour VALUES (11, 'Bruin', NULL);
INSERT INTO basecolour VALUES (12, 'Bruin en zwart', NULL);
INSERT INTO basecolour VALUES (13, 'Zwart en bruin', NULL);
INSERT INTO basecolour VALUES (14, 'Tijgergestreept', NULL);
INSERT INTO basecolour VALUES (15, 'Tijgergestreept en zwart', NULL);
INSERT INTO basecolour VALUES (16, 'Tijgergestreept en wit', NULL);
INSERT INTO basecolour VALUES (17, 'Zwart en tijgergestreept', NULL);
INSERT INTO basecolour VALUES (18, 'Wit en tijgergestreept', NULL);
INSERT INTO basecolour VALUES (19, 'Driekleurig', NULL);
INSERT INTO basecolour VALUES (20, 'Donkerbruin', NULL);
INSERT INTO basecolour VALUES (21, 'Donkerbruin en wit', NULL);
INSERT INTO basecolour VALUES (22, 'Wit en donkerbruin', NULL);
INSERT INTO basecolour VALUES (23, 'Crèmekleurig', NULL);
INSERT INTO basecolour VALUES (24, 'Lichtbruin en wit', NULL);
INSERT INTO basecolour VALUES (26, 'Wit en lichtbruin', NULL);
INSERT INTO basecolour VALUES (27, 'Schildpad en wit', NULL);
INSERT INTO basecolour VALUES (28, 'Tabby en wit', NULL);
INSERT INTO basecolour VALUES (29, 'Ros en wit', NULL);
INSERT INTO basecolour VALUES (30, 'Grijs', NULL);
INSERT INTO basecolour VALUES (31, 'Grijs en wit', NULL);
INSERT INTO basecolour VALUES (32, 'Wit en grijs', NULL);
INSERT INTO basecolour VALUES (33, 'Wit en schildpad', NULL);
INSERT INTO basecolour VALUES (35, 'Bruin en wit', NULL);
INSERT INTO basecolour VALUES (36, 'Blauw', NULL);
INSERT INTO basecolour VALUES (37, 'Wit en tabby', NULL);
INSERT INTO basecolour VALUES (38, 'Geel en grijs', NULL);
INSERT INTO basecolour VALUES (39, 'Meerdere', NULL);
INSERT INTO basecolour VALUES (40, 'Wit en bruin', NULL);
INSERT INTO basecolour VALUES (41, 'Groen', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Afghaanse windhond', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedaleterriër', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Alaska-malamute', '', '', 1);
INSERT INTO breed VALUES (7, 'Amerikaanse buldog', '', '', 1);
INSERT INTO breed VALUES (8, 'American Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (9, 'Amerikaanse Staffordshireterriër', '', '', 1);
INSERT INTO breed VALUES (10, 'Amerikaanse waterspaniël', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolische herder', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzeller sennenhond', '', '', 1);
INSERT INTO breed VALUES (13, 'Australische veedrijvershond', '', '', 1);
INSERT INTO breed VALUES (14, 'Kelpie', '', '', 1);
INSERT INTO breed VALUES (15, 'Australische herder', '', '', 1);
INSERT INTO breed VALUES (16, 'Australische terriër', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlingtonterriër', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgische herder', '', '', 1);
INSERT INTO breed VALUES (24, 'Laekense herder', '', '', 1);
INSERT INTO breed VALUES (25, 'Mechelse herder', '', '', 1);
INSERT INTO breed VALUES (26, 'Tervuerense herder', '', '', 1);
INSERT INTO breed VALUES (27, 'Berner sennenhond', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon frisé', '', '', 1);
INSERT INTO breed VALUES (29, 'Black and Tan Coonhound', '', '', 1);
INSERT INTO breed VALUES (30, 'Zwarte labrador retriever', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Bloedhond', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Borderterriër', '', '', 1);
INSERT INTO breed VALUES (36, 'Barzoi', '', '', 1);
INSERT INTO breed VALUES (37, 'Bostonterriër', '', '', 1);
INSERT INTO breed VALUES (38, 'Vlaamse koehond', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Bretoense Spaniël', '', '', 1);
INSERT INTO breed VALUES (43, 'Brussels Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bulterriër', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairnterriër', '', '', 1);
INSERT INTO breed VALUES (47, 'Kanaänhond', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane corso', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina Dog', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Australische veedrijvershond', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles-spaniël', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bayretriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chinese gekuifde naakthond', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinese Foo Dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Chocolate Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumberspaniël', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cockerspaniël', '', '', 1);
INSERT INTO breed VALUES (62, 'Schotse herdershond', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tuléar', '', '', 1);
INSERT INTO breed VALUES (66, 'Dashond', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatiër', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandie Dinmont-terriër', '', '', 1);
INSERT INTO breed VALUES (69, 'Dobermann', '', '', 1);
INSERT INTO breed VALUES (70, 'Dogo argentino', '', '', 1);
INSERT INTO breed VALUES (71, 'Bordeauxdog', '', '', 1);
INSERT INTO breed VALUES (72, 'Hollandse herder', '', '', 1);
INSERT INTO breed VALUES (73, 'Engelse buldog', '', '', 1);
INSERT INTO breed VALUES (74, 'Engelse cockerspaniël', '', '', 1);
INSERT INTO breed VALUES (75, 'English Coonhound', '', '', 1);
INSERT INTO breed VALUES (76, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'Engelse setter', '', '', 1);
INSERT INTO breed VALUES (78, 'English Shepherd', '', '', 1);
INSERT INTO breed VALUES (79, 'Engelse springerspaniël', '', '', 1);
INSERT INTO breed VALUES (80, 'King Charles-spaniël', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher sennenhond', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (83, 'Fieldspaniël', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Finse lappenhond', '', '', 1);
INSERT INTO breed VALUES (86, 'Finse spits', '', '', 1);
INSERT INTO breed VALUES (87, 'Flatcoated retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Foxterriër', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Franse buldog', '', '', 1);
INSERT INTO breed VALUES (91, 'Duitse pincher', '', '', 1);
INSERT INTO breed VALUES (92, 'Duitse herder', '', '', 1);
INSERT INTO breed VALUES (93, 'Duitse staande korthaar', '', '', 1);
INSERT INTO breed VALUES (94, 'German Wirehaired Pointer', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaalterriër', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Duitse dog', '', '', 1);
INSERT INTO breed VALUES (99, 'Pyreneese berghond', '', '', 1);
INSERT INTO breed VALUES (100, 'Grote Zwitserse sennenhond', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Havanezer', '', '', 1);
INSERT INTO breed VALUES (103, 'Jachthond', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Podenco ibicenco', '', '', 1);
INSERT INTO breed VALUES (107, 'Šarplaninac', '', '', 1);
INSERT INTO breed VALUES (108, 'Ierse setter', '', '', 1);
INSERT INTO breed VALUES (109, 'Irish Terrier', '', '', 1);
INSERT INTO breed VALUES (110, 'Ierse waterspaniël', '', '', 1);
INSERT INTO breed VALUES (111, 'Ierse wolfshond', '', '', 1);
INSERT INTO breed VALUES (112, 'Italiaans windhondje', '', '', 1);
INSERT INTO breed VALUES (113, 'Spinone italiano', '', '', 1);
INSERT INTO breed VALUES (114, 'Jackrussellterriër', '', '', 1);
INSERT INTO breed VALUES (115, 'Japanse spaniël', '', '', 1);
INSERT INTO breed VALUES (116, 'Koreaanse jindohond', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Dog', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelische berenhond', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue-terriër', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakelandterriër', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Leeuwhondje', '', '', 1);
INSERT INTO breed VALUES (131, 'Maltezer', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchesterterriër', '', '', 1);
INSERT INTO breed VALUES (133, 'Berghond van de Maremmen en Abruzzen', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Dwergpinscher', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (140, 'Mastino napoletano', '', '', 1);
INSERT INTO breed VALUES (141, 'New Guinea Singing Dog', '', '', 1);
INSERT INTO breed VALUES (142, 'Newfoundlander', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolkterriër', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwichterriër', '', '', 1);
INSERT INTO breed VALUES (145, 'Noorse buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Noorse elandhond', '', '', 1);
INSERT INTO breed VALUES (147, 'Noorse lundehond', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia duck tolling retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Bobtail', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhound', '', '', 1);
INSERT INTO breed VALUES (151, 'Vlinderhondje', '', '', 1);
INSERT INTO breed VALUES (152, 'Fellterriër', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekingees', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruaanse naakthond', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit Basset griffon vendéen', '', '', 1);
INSERT INTO breed VALUES (156, 'Pharaohond', '', '', 1);
INSERT INTO breed VALUES (157, 'Pitbull', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Podengo português', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Poolse laaglandherder', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Poedel', '', '', 1);
INSERT INTO breed VALUES (164, 'Portugese waterhond', '', '', 1);
INSERT INTO breed VALUES (165, 'Dogo canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Mopshond', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesische pronkrug', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'Sint-Bernard', '', '', 1);
INSERT INTO breed VALUES (176, 'Samojeed', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Deerhound', '', '', 1);
INSERT INTO breed VALUES (180, 'Schotse terriër', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyhamterriër', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar-Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Berghond', '', '', 1);
INSERT INTO breed VALUES (185, 'Herdershond', '', '', 1);
INSERT INTO breed VALUES (186, 'Sheltie', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Siberische husky', '', '', 1);
INSERT INTO breed VALUES (190, 'Australische silkyterriër', '', '', 1);
INSERT INTO breed VALUES (191, 'Skyeterriër', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Smooth Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniël', '', '', 1);
INSERT INTO breed VALUES (195, 'Spits', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire-bulterriër', '', '', 1);
INSERT INTO breed VALUES (197, 'Zuid-Russische owcharka', '', '', 1);
INSERT INTO breed VALUES (198, 'Västgötaspets', '', '', 1);
INSERT INTO breed VALUES (199, 'Terriër', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai ridgebackdog', '', '', 1);
INSERT INTO breed VALUES (201, 'Tibetaanse mastiff', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibetaanse spaniël', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibetaanse terriër', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimarse staande hond', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh terriër', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland white terriër', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten terriër', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'White German Shepherd', '', '', 1);
INSERT INTO breed VALUES (216, 'Griffon Korthals', '', '', 1);
INSERT INTO breed VALUES (217, 'Wirehaired Terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'Labrador retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshireterriër', '', '', 1);
INSERT INTO breed VALUES (220, 'Mexicaanse naakthond', '', '', 1);
INSERT INTO breed VALUES (221, 'Abessijn', '', '', 2);
INSERT INTO breed VALUES (222, 'Amerikaanse kruloorkat', '', '', 2);
INSERT INTO breed VALUES (223, 'Amerikaans korthaar', '', '', 2);
INSERT INTO breed VALUES (224, 'American Wirehair', '', '', 2);
INSERT INTO breed VALUES (225, 'Siamees', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinees', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengaal', '', '', 2);
INSERT INTO breed VALUES (228, 'Birmaan', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'Brits korthaar', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmees', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Schildpadkat', '', '', 2);
INSERT INTO breed VALUES (235, 'Sphynx', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Schildpadkat', '', '', 2);
INSERT INTO breed VALUES (242, 'Schildpadkat', '', '', 2);
INSERT INTO breed VALUES (243, 'Domestic Long Hair', '', '', 2);
INSERT INTO breed VALUES (252, 'Domestic Medium Hair', '', '', 2);
INSERT INTO breed VALUES (261, 'Domestic Short Hair', '', '', 2);
INSERT INTO breed VALUES (271, 'Egyptische mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Exotic', '', '', 2);
INSERT INTO breed VALUES (273, 'Extra-Toes Cat (Hemingway Polydactyl)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Japanse stompstaartkat', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Noorse boskat', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Oosters langhaar', '', '', 2);
INSERT INTO breed VALUES (285, 'Oosters korthaar', '', '', 2);
INSERT INTO breed VALUES (286, 'Oriental Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'Pers', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Blauwe Rus', '', '', 2);
INSERT INTO breed VALUES (292, 'Schotse vouwoorkat', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siamees', '', '', 2);
INSERT INTO breed VALUES (295, 'Siberian', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somali', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphynx', '', '', 2);
INSERT INTO breed VALUES (300, 'Tabby', '', '', 2);
INSERT INTO breed VALUES (307, 'Tijger', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkanees', '', '', 2);
INSERT INTO breed VALUES (309, 'Schildpadkat', '', '', 2);
INSERT INTO breed VALUES (310, 'Schildpadkat', '', '', 2);
INSERT INTO breed VALUES (311, 'Turkse angora', '', '', 2);
INSERT INTO breed VALUES (312, 'Turkse Van', '', '', 2);
INSERT INTO breed VALUES (313, 'Tuxedo', '', '', 2);
INSERT INTO breed VALUES (314, 'American', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angorakonijn', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgische haas', '', '', 7);
INSERT INTO breed VALUES (319, 'Van Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Dutch', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Vlaamse reus', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polish', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silver', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Lichtbruin', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabier', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Donkey/Mule', '', '', 26);
INSERT INTO breed VALUES (361, 'Koudbloed', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Pintopony', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarter horse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Engelse volbloed', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee walking horse', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmbloed', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Fret', '', '', 3);
INSERT INTO breed VALUES (381, 'Gerbil', '', '', 18);
INSERT INTO breed VALUES (382, 'Huiscavia', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Egel', '', '', 6);
INSERT INTO breed VALUES (385, 'Muis', '', '', 4);
INSERT INTO breed VALUES (386, 'Prairiehond', '', '', 5);
INSERT INTO breed VALUES (387, 'Rat', '', '', 5);
INSERT INTO breed VALUES (388, 'Stinkdier', '', '', 5);
INSERT INTO breed VALUES (389, 'Suikereekhoorn', '', '', 5);
INSERT INTO breed VALUES (390, 'Hangbuikzwijn', '', '', 28);
INSERT INTO breed VALUES (391, 'Vietnamees hangbuikzwijn', '', '', 28);
INSERT INTO breed VALUES (392, 'Gekko', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Hagedis', '', '', 13);
INSERT INTO breed VALUES (395, 'Slang', '', '', 13);
INSERT INTO breed VALUES (396, 'Schildpad', '', '', 13);
INSERT INTO breed VALUES (397, 'Vis', '', '', 21);
INSERT INTO breed VALUES (398, 'Grijze roodstaart', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Grasparkiet', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Kanarie', '', '', 3);
INSERT INTO breed VALUES (404, 'Kip', '', '', 3);
INSERT INTO breed VALUES (405, 'Valkparkiet', '', '', 3);
INSERT INTO breed VALUES (406, 'Kaketoe', '', '', 3);
INSERT INTO breed VALUES (407, 'Papegaai', '', '', 3);
INSERT INTO breed VALUES (408, 'Duif', '', '', 3);
INSERT INTO breed VALUES (409, 'Eend', '', '', 3);
INSERT INTO breed VALUES (410, 'Edelpapegaai', '', '', 3);
INSERT INTO breed VALUES (411, 'Emoe', '', '', 3);
INSERT INTO breed VALUES (412, 'Vink', '', '', 3);
INSERT INTO breed VALUES (413, 'Gans', '', '', 3);
INSERT INTO breed VALUES (414, 'Parelhoen', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lori', '', '', 3);
INSERT INTO breed VALUES (417, 'Dwergpapegaai', '', '', 3);
INSERT INTO breed VALUES (418, 'Ara', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Struisvogel', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakeet (Other)', '', '', 3);
INSERT INTO breed VALUES (422, 'Parkiet (andere)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Pauw', '', '', 3);
INSERT INTO breed VALUES (425, 'Fazant', '', '', 3);
INSERT INTO breed VALUES (426, 'Duif', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus', '', '', 3);
INSERT INTO breed VALUES (429, 'Monniksparkiet', '', '', 3);
INSERT INTO breed VALUES (430, 'Nandoe', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Zwaan', '', '', 3);
INSERT INTO breed VALUES (435, 'Toekan', '', '', 3);
INSERT INTO breed VALUES (436, 'Kalkoen', '', '', 3);
INSERT INTO breed VALUES (437, 'Koe', '', '', 16);
INSERT INTO breed VALUES (438, 'Geit', '', '', 16);
INSERT INTO breed VALUES (439, 'Schaap', '', '', 16);
INSERT INTO breed VALUES (440, 'Lama', '', '', 16);
INSERT INTO breed VALUES (441, 'Pig (Farm)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%';
INSERT INTO configuration VALUES ('Organisation', 'Organisatie');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Baby');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Jongvolwassen');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Volwassen');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Ouder');
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Niet-gechipte dieren', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Controleren');
INSERT INTO customreport VALUES (37, 'Dieren zonder foto', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Controleren');
INSERT INTO customreport VALUES (38, 'Nooit-gevaccineerde dieren', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Controleren');
INSERT INTO customreport VALUES (39, 'Ongesteriliseerde/ongecastreerde dieren ouder dan 6 maanden', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Controleren');
INSERT INTO customreport VALUES (40, 'Katten zonder combi-Test', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Controleren');
INSERT INTO customreport VALUES (41, 'Maandelijkse diercijfers', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Cijfers');
INSERT INTO customreport VALUES (42, 'Langverblijvende dieren', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Cijfers');
INSERT INTO customreport VALUES (43, 'Opvangcentruminventaris', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Aanwezige dieren');
INSERT INTO customreport VALUES (44, 'Gedetailleerde opvangcentruminventaris', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Aanwezige dieren');
INSERT INTO customreport VALUES (45, 'Dieren die niet tot een nest behoren', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Nesten');
INSERT INTO customreport VALUES (46, 'In/uit', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mutaties');
INSERT INTO customreport VALUES (47, 'In/uit samenvatting', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mutaties');
INSERT INTO customreport VALUES (48, 'Transfer In Report', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mutaties');
INSERT INTO customreport VALUES (49, 'Aantal adopties per handelaar', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Handelaars');
INSERT INTO customreport VALUES (50, 'Gemiddelde tijd bij handelaar voor adoptie', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Handelaars');
INSERT INTO customreport VALUES (51, 'Handelaarsinventaris', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Handelaars');
INSERT INTO customreport VALUES (52, 'Rapportage teruggebrachte dieren', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Terugbrengingen');
INSERT INTO customreport VALUES (53, 'Dieren teruggebracht binnen de 6 maanden', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Terugbrengingen');
INSERT INTO customreport VALUES (54, 'Dieren teruggebracht na 6 maanden', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Terugbrengingen');
INSERT INTO customreport VALUES (55, 'Meest voorkomende naam', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistieken');
INSERT INTO customreport VALUES (56, 'Doodsoorzaken', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistieken');
INSERT INTO customreport VALUES (57, 'Meest voorkomende herkomstgebieden', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistieken');
INSERT INTO customreport VALUES (58, 'Meest voorkomende adoptiegebieden', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistieken');
INSERT INTO customreport VALUES (59, 'Gemiddelde tijd op wachtlijst', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistieken');
INSERT INTO customreport VALUES (60, 'Maandelijkse giften', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Financieële grafieken');
INSERT INTO customreport VALUES (61, 'Maandelijkse giften per diersoort', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Financieële grafieken');
INSERT INTO customreport VALUES (62, 'Maandelijkse adopties per diersoort', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mutatiegrafieken');
INSERT INTO customreport VALUES (63, 'Maandelijkse adopties per locatie', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mutatiegrafieken');
INSERT INTO customreport VALUES (64, 'Binnenbrengredenen', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mutatiegrafieken');
INSERT INTO customreport VALUES (65, 'Terugbrengredenen', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mutatiegrafieken');
INSERT INTO customreport VALUES (66, 'Koppeling eigenaarscriteria', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Aanwezige dieren');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Dood bij aankomst', '');
INSERT INTO deathreason VALUES (2, 'Overleden', '');
INSERT INTO deathreason VALUES (3, 'Gezond', '');
INSERT INTO deathreason VALUES (4, 'Ziek/gewond', '');
INSERT INTO deathreason VALUES (5, 'Gevraagd', '');
INSERT INTO deathreason VALUES (6, 'Keuze', '');
INSERT INTO deathreason VALUES (7, 'Wild', '');
INSERT INTO deathreason VALUES (8, 'Bijtend', '');
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Gift', '');
INSERT INTO donationtype VALUES (2, 'Adoptiegeld', '');
INSERT INTO donationtype VALUES (3, 'Wachtlijstgift', '');
INSERT INTO donationtype VALUES (4, 'Inbrenggift', '');
INSERT INTO donationtype VALUES (5, 'Sponsoring', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Scheiding', '');
INSERT INTO entryreason VALUES (2, 'Allergieën', '');
INSERT INTO entryreason VALUES (3, 'Bijtend', '');
INSERT INTO entryreason VALUES (4, 'Onbedwingbaar', '');
INSERT INTO entryreason VALUES (5, 'Ongeschikte accomodatie', '');
INSERT INTO entryreason VALUES (6, 'Overleden', '');
INSERT INTO entryreason VALUES (7, 'Verdwaald', '');
INSERT INTO entryreason VALUES (8, 'Ziek/gewond', '');
INSERT INTO entryreason VALUES (9, 'Onveroorloofbaar', '');
INSERT INTO entryreason VALUES (10, 'Misbruik', '');
INSERT INTO entryreason VALUES (11, 'Verlaten', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Geen locaties', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Vrouwelijk');
INSERT INTO lksex VALUES (1, 'Mannelijk');
INSERT INTO lksex VALUES (2, 'Onbekend');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Erg groot');
INSERT INTO lksize VALUES (1, 'Groot');
INSERT INTO lksize VALUES (2, 'Gewoon');
INSERT INTO lksize VALUES (3, 'Klein');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Kort');
INSERT INTO lkcoattype VALUES (1, 'Lang');
INSERT INTO lkcoattype VALUES (2, 'Ruw');
INSERT INTO lkcoattype VALUES (3, 'Gekruld');
INSERT INTO lkcoattype VALUES (4, 'Draderig');
INSERT INTO lkcoattype VALUES (5, 'Naakt');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Geen');
INSERT INTO lksmovementtype VALUES (1, 'Adoptie');
INSERT INTO lksmovementtype VALUES (2, 'Gastgezin');
INSERT INTO lksmovementtype VALUES (3, 'Verplaatsing');
INSERT INTO lksmovementtype VALUES (4, 'Ontsnapt');
INSERT INTO lksmovementtype VALUES (5, 'Teruggeëist');
INSERT INTO lksmovementtype VALUES (6, 'Gestolen');
INSERT INTO lksmovementtype VALUES (7, 'Losgelaten');
INSERT INTO lksmovementtype VALUES (8, 'Handelaar');
INSERT INTO lksmovementtype VALUES (9, 'Reservering');
INSERT INTO lksmovementtype VALUES (10, 'Geannuleerde reservatie');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Dier');
INSERT INTO lksmedialink VALUES (1, 'Vermist dier');
INSERT INTO lksmedialink VALUES (2, 'Gevonden dier');
INSERT INTO lksmedialink VALUES (3, 'Eigenaar');
INSERT INTO lksmedialink VALUES (4, 'Mutatie');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Geen');
INSERT INTO lksdiarylink VALUES (1, 'Dier');
INSERT INTO lksdiarylink VALUES (2, 'Eigenaar');
INSERT INTO lksdiarylink VALUES (3, 'Vermist dier');
INSERT INTO lksdiarylink VALUES (4, 'Gevonden dier');
INSERT INTO lksdiarylink VALUES (5, 'Wachtlijst');
INSERT INTO lksdiarylink VALUES (6, 'Mutatie');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'One-Off');
INSERT INTO lksdonationfreq VALUES (1, 'Wekelijks');
INSERT INTO lksdonationfreq VALUES (2, 'Maandelijks');
INSERT INTO lksdonationfreq VALUES (3, 'Driemaandelijks');
INSERT INTO lksdonationfreq VALUES (4, 'Halfjaarlijks');
INSERT INTO lksdonationfreq VALUES (5, 'Jaarlijks');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Dier');
INSERT INTO lksfieldlink VALUES (1, 'Eigenaar');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Ja/nee');
INSERT INTO lksfieldtype VALUES (1, 'Tekst');
INSERT INTO lksfieldtype VALUES (2, 'Opmerkingen');
INSERT INTO lksfieldtype VALUES (3, 'Aantal');
INSERT INTO lksfieldtype VALUES (4, 'Datum');
INSERT INTO lksfieldtype VALUES (5, 'Geld');
INSERT INTO lksfieldtype VALUES (6, 'Opzoeking');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Dier');
INSERT INTO lksloglink VALUES (1, 'Eigenaar');
INSERT INTO lksloglink VALUES (2, 'Vermist dier');
INSERT INTO lksloglink VALUES (3, 'Gevonden dier');
INSERT INTO lksloglink VALUES (4, 'Wachtlijst');
INSERT INTO lksloglink VALUES (5, 'Mutatie');
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Dringend');
INSERT INTO lkurgency VALUES (2, 'Hoog');
INSERT INTO lkurgency VALUES (3, 'Gewoon');
INSERT INTO lkurgency VALUES (4, 'Laag');
INSERT INTO lkurgency VALUES (5, 'Laagste');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Beet', '');
INSERT INTO logtype VALUES (2, 'Klacht', '');
INSERT INTO logtype VALUES (3, 'Geschiedenis', '');
INSERT INTO logtype VALUES (4, 'Gewicht', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Hond', '', '');
INSERT INTO species VALUES (2, 'Kat', '', '');
INSERT INTO species VALUES (3, 'Vogel', '', '');
INSERT INTO species VALUES (4, 'Muis', '', '');
INSERT INTO species VALUES (5, 'Rat', '', '');
INSERT INTO species VALUES (6, 'Egel', '', '');
INSERT INTO species VALUES (7, 'Konijn', '', '');
INSERT INTO species VALUES (8, 'Duif', '', '');
INSERT INTO species VALUES (9, 'Fret', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Slang', '', '');
INSERT INTO species VALUES (12, 'Schild', '', '');
INSERT INTO species VALUES (13, 'Waterschildpad', '', '');
INSERT INTO species VALUES (14, 'Kip', '', '');
INSERT INTO species VALUES (15, 'Uil', '', '');
INSERT INTO species VALUES (16, 'Geit', '', '');
INSERT INTO species VALUES (17, 'Gans', '', '');
INSERT INTO species VALUES (18, 'Gerbil', '', '');
INSERT INTO species VALUES (19, 'Valkparkiet', '', '');
INSERT INTO species VALUES (20, 'Huiscavia', '', '');
INSERT INTO species VALUES (21, 'Goudvis', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Kameel', '', '');
INSERT INTO species VALUES (24, 'Paard', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Ezel', '', '');
INSERT INTO species VALUES (27, 'Lama', '', '');
INSERT INTO species VALUES (28, 'Varken', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Gesteriliseerd/gecastreerd', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Tijdelijke vaccinatie', '');
INSERT INTO vaccinationtype VALUES (2, 'Eerste vaccinatie', '');
INSERT INTO vaccinationtype VALUES (3, 'Tweede vaccinatie', '');
INSERT INTO vaccinationtype VALUES (4, 'Boost', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukemie', '');
INSERT INTO vaccinationtype VALUES (6, 'Kennelhoest', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirose', '');
