DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Hund)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Streunender Hund)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Ungewollte Katze)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Streunende Katze)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Sonstiges)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Kein Tier aus einem Tierheim)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Schwarz', NULL);
INSERT INTO basecolour VALUES (2, 'Weiß', NULL);
INSERT INTO basecolour VALUES (3, 'Schwarz und Weiß', NULL);
INSERT INTO basecolour VALUES (4, 'Rothaarig', NULL);
INSERT INTO basecolour VALUES (5, 'Weiß und Schwarz', NULL);
INSERT INTO basecolour VALUES (6, 'Bunt', NULL);
INSERT INTO basecolour VALUES (7, 'Getigert', NULL);
INSERT INTO basecolour VALUES (8, 'Hellbraun', NULL);
INSERT INTO basecolour VALUES (9, 'Schwarz und Hellbraun', NULL);
INSERT INTO basecolour VALUES (10, 'Hellbraun und Schwarz', NULL);
INSERT INTO basecolour VALUES (11, 'Braun', NULL);
INSERT INTO basecolour VALUES (12, 'Braun und Schwarz', NULL);
INSERT INTO basecolour VALUES (13, 'Schwarz und Braun', NULL);
INSERT INTO basecolour VALUES (14, 'Gescheckt', NULL);
INSERT INTO basecolour VALUES (15, 'Gescheckt und Schwarz', NULL);
INSERT INTO basecolour VALUES (16, 'Gescheckt und Weiß', NULL);
INSERT INTO basecolour VALUES (17, 'Schwarz und Gescheckt', NULL);
INSERT INTO basecolour VALUES (18, 'Weiß und Gescheckt', NULL);
INSERT INTO basecolour VALUES (19, 'Dreifarbig', NULL);
INSERT INTO basecolour VALUES (20, 'Rotbraun', NULL);
INSERT INTO basecolour VALUES (21, 'Rotbraun und Weiß', NULL);
INSERT INTO basecolour VALUES (22, 'Weiß und Rotbraun', NULL);
INSERT INTO basecolour VALUES (23, 'Cremefarben', NULL);
INSERT INTO basecolour VALUES (24, 'Hellbraun und Weiß', NULL);
INSERT INTO basecolour VALUES (26, 'Weiß und Hellbraun', NULL);
INSERT INTO basecolour VALUES (27, 'Braungemischt und Weiß', NULL);
INSERT INTO basecolour VALUES (28, 'Gefleckt und Weiß', NULL);
INSERT INTO basecolour VALUES (29, 'Rothaaring und Weiß', NULL);
INSERT INTO basecolour VALUES (30, 'Grau', NULL);
INSERT INTO basecolour VALUES (31, 'Grau und Weiß', NULL);
INSERT INTO basecolour VALUES (32, 'Weiß und Grau', NULL);
INSERT INTO basecolour VALUES (33, 'Weiß und Braun gemischt (Torti)', NULL);
INSERT INTO basecolour VALUES (35, 'Braun und Weiß', NULL);
INSERT INTO basecolour VALUES (36, 'Blau', NULL);
INSERT INTO basecolour VALUES (37, 'Weiß und Gescheckt', NULL);
INSERT INTO basecolour VALUES (38, 'Gelb und Grau', NULL);
INSERT INTO basecolour VALUES (39, 'Verschiedene', NULL);
INSERT INTO basecolour VALUES (40, 'Weiß und Braun', NULL);
INSERT INTO basecolour VALUES (41, 'Grün', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Afghanischer Windhund', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Alaskan Malamute', '', '', 1);
INSERT INTO breed VALUES (7, 'Amerikanische Bulldogge', '', '', 1);
INSERT INTO breed VALUES (8, 'Amerikanischer Eskimohund', '', '', 1);
INSERT INTO breed VALUES (9, 'Amerikanischer Staffordshire-Terrier', '', '', 1);
INSERT INTO breed VALUES (10, 'Amerikanischer Wasserspaniel', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolischer Hirtenhund', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzeller Sennenhund', '', '', 1);
INSERT INTO breed VALUES (13, 'Australischer Treibhund/Blue Heeler', '', '', 1);
INSERT INTO breed VALUES (14, 'Australischer Kelpie', '', '', 1);
INSERT INTO breed VALUES (15, 'Australischer Schäferhund', '', '', 1);
INSERT INTO breed VALUES (16, 'Australischer Terrier', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgischer Schäferhund', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgischer Schäferhund Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgischer Schäferhund Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgischer Schäferhund Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Berner Sennenhund', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon Frise', '', '', 1);
INSERT INTO breed VALUES (29, 'Schwarz-Roter Waschbärenhund (Black and Tan Coonhound)', '', '', 1);
INSERT INTO breed VALUES (30, 'Schwarz Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Bluthund', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Russischer Jagd Windhund', '', '', 1);
INSERT INTO breed VALUES (37, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (38, 'Flandrischer Treibhund', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Bretonischer Spaniel', '', '', 1);
INSERT INTO breed VALUES (43, 'Brüsseler Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Kanaan Hund', '', '', 1);
INSERT INTO breed VALUES (48, 'Italienischer Corso-Hund', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina Dog', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Treibhund', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bay Retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chinesische Schopfhund (Chinesischer Nackthund)', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinesischer Glückshund', '', '', 1);
INSERT INTO breed VALUES (57, 'Chocolate Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Waschbärhund', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Dachshund', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatiner', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandie Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Dobermann (Doberman Pinscher)', '', '', 1);
INSERT INTO breed VALUES (70, 'Argentinische Dogge', '', '', 1);
INSERT INTO breed VALUES (71, 'Bordeauxdogge', '', '', 1);
INSERT INTO breed VALUES (72, 'Holländischer Schäferhund', '', '', 1);
INSERT INTO breed VALUES (73, 'Englische Bulldoge', '', '', 1);
INSERT INTO breed VALUES (74, 'Englischer Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (75, 'Englischer Waschbärenhund', '', '', 1);
INSERT INTO breed VALUES (76, 'Englisch Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'English Setter', '', '', 1);
INSERT INTO breed VALUES (78, 'Englischer Schäferhund (Shepherd)', '', '', 1);
INSERT INTO breed VALUES (79, 'English-Springer-Spaniel', '', '', 1);
INSERT INTO breed VALUES (80, 'King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher Sennenhund', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimohund', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Brasilianische Dogge', '', '', 1);
INSERT INTO breed VALUES (85, 'Finnischer Lapphund', '', '', 1);
INSERT INTO breed VALUES (86, 'Finnen-Spitz', '', '', 1);
INSERT INTO breed VALUES (87, 'Glatthaarig Retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Französiche Bulldogge', '', '', 1);
INSERT INTO breed VALUES (91, 'Deutscher Pinscher', '', '', 1);
INSERT INTO breed VALUES (92, 'Deutscher Schäferhund', '', '', 1);
INSERT INTO breed VALUES (93, 'Deutsch Kurzhaar', '', '', 1);
INSERT INTO breed VALUES (94, 'Deutsch Drahthaar', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Deutsche Dogge', '', '', 1);
INSERT INTO breed VALUES (99, 'Pyrenäen-Berghund', '', '', 1);
INSERT INTO breed VALUES (100, 'Grosser Schweizer Sennenhund', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Havaneser', '', '', 1);
INSERT INTO breed VALUES (103, 'Laufhunde', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibiza-Podenco', '', '', 1);
INSERT INTO breed VALUES (107, 'Jugoslawischer Hirtenhund-Sarplaninac', '', '', 1);
INSERT INTO breed VALUES (108, 'Irischer Setter', '', '', 1);
INSERT INTO breed VALUES (109, 'Irish Terrier', '', '', 1);
INSERT INTO breed VALUES (110, 'Irischer Wasserspaniel', '', '', 1);
INSERT INTO breed VALUES (111, 'Irischer Wolfshund', '', '', 1);
INSERT INTO breed VALUES (112, 'Italienisches Windspiel', '', '', 1);
INSERT INTO breed VALUES (113, 'Italienischer Rauhhaariger Vorstehhund', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Japan-Chin', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelischer Bärenhund', '', '', 1);
INSERT INTO breed VALUES (119, 'Wolfsspitz/Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue Terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Löwchen', '', '', 1);
INSERT INTO breed VALUES (131, 'Malteser', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremme-Abruzzen-Schäferhund', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Zwergpinscher', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Berghund', '', '', 1);
INSERT INTO breed VALUES (139, 'Münsterländer', '', '', 1);
INSERT INTO breed VALUES (140, 'Mastino Napoletano', '', '', 1);
INSERT INTO breed VALUES (141, 'Neuguinea-Dingo', '', '', 1);
INSERT INTO breed VALUES (142, 'Neufundländer', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich Terrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Norwegischer Buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Norwegischer Elchhund', '', '', 1);
INSERT INTO breed VALUES (147, 'Norwegischer Lundehund', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Altenglischer Schäferhund/Bobtail', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhund', '', '', 1);
INSERT INTO breed VALUES (151, 'Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier (Fell Terrier)', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekingese', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruanischer Nackthund', '', '', 1);
INSERT INTO breed VALUES (155, 'Kleiner Basset Griffon Vendéen', '', '', 1);
INSERT INTO breed VALUES (156, 'Pharaonenhund', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Portugiesischer Podengo', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polnischer Niederungshütehund', '', '', 1);
INSERT INTO breed VALUES (162, 'Zwergspitz/Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Pudel', '', '', 1);
INSERT INTO breed VALUES (164, 'Portugiesischer Wasserhund', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Mops', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesian Ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'St.Bernhardshund', '', '', 1);
INSERT INTO breed VALUES (176, 'Samojede', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Scottish Deerhound', '', '', 1);
INSERT INTO breed VALUES (180, 'Schottischer Hirschhund', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Hütehund', '', '', 1);
INSERT INTO breed VALUES (185, 'Schäferhund', '', '', 1);
INSERT INTO breed VALUES (186, 'Shetland Sheepdog Sheltie', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Siberian Husky', '', '', 1);
INSERT INTO breed VALUES (190, 'Silky Terrier', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Arabischer Windhund', '', '', 1);
INSERT INTO breed VALUES (193, 'Glatthaar-Foxterrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'Südrussischer Ovtcharka', '', '', 1);
INSERT INTO breed VALUES (198, 'Schwedischer Vallhund', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Tibetmastiff', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibet-Spaniel', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibet-Terrier', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimaraner', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'Weisser Deutscher Schäferhund', '', '', 1);
INSERT INTO breed VALUES (216, 'Wire-haired Pointing Griffon', '', '', 1);
INSERT INTO breed VALUES (217, 'Drahthaarig Terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'Gelb Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier', '', '', 1);
INSERT INTO breed VALUES (220, 'Mexikanischer Nackthund', '', '', 1);
INSERT INTO breed VALUES (221, 'Abessinier', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'Amerikanisch Kurzhaar', '', '', 2);
INSERT INTO breed VALUES (224, 'Amerikanisch Drahthaar', '', '', 2);
INSERT INTO breed VALUES (225, 'Apfelkopf Siam', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinesen', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengalkatze', '', '', 2);
INSERT INTO breed VALUES (228, 'Birma', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombaykatze', '', '', 2);
INSERT INTO breed VALUES (231, 'Britisch Kurzhaar', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmesen', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Dreifarbige', '', '', 2);
INSERT INTO breed VALUES (235, 'Kanadische haarlose Katze', '', '', 2);
INSERT INTO breed VALUES (236, 'Kartäuser', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Verdünnt dreifarbig', '', '', 2);
INSERT INTO breed VALUES (242, 'Verdünnt Schildpatt', '', '', 2);
INSERT INTO breed VALUES (243, 'Langhaarige Hauskatze', '', '', 2);
INSERT INTO breed VALUES (252, 'Mittelhaarige Hauskatze', '', '', 2);
INSERT INTO breed VALUES (261, 'Kurzhaarige Hauskatze', '', '', 2);
INSERT INTO breed VALUES (271, 'Ägyptische Mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Exotisch Kurzhaar', '', '', 2);
INSERT INTO breed VALUES (273, 'Vielzehigkeit (Hemingway-Katze)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havanna', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Japanese Bobtail', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Norwegische Waldkatze', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Orientalisches Langhaar', '', '', 2);
INSERT INTO breed VALUES (285, 'Orientalisches Kurzhaar', '', '', 2);
INSERT INTO breed VALUES (286, 'Orientalisches Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'Perser', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Russisch Blau', '', '', 2);
INSERT INTO breed VALUES (292, 'Scottish Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siam', '', '', 2);
INSERT INTO breed VALUES (295, 'Sibirische Katze', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somali', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphinx (haarlose Katze)', '', '', 2);
INSERT INTO breed VALUES (300, 'Getigert', '', '', 2);
INSERT INTO breed VALUES (307, 'Tiger', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkanese', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Schildpatt', '', '', 2);
INSERT INTO breed VALUES (311, 'Türkische Angora', '', '', 2);
INSERT INTO breed VALUES (312, 'Türkisch Van', '', '', 2);
INSERT INTO breed VALUES (313, 'Smoking', '', '', 2);
INSERT INTO breed VALUES (314, 'Amerikanisch', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angora Rabbit', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Karnickel', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Dutch', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havanna', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polish', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silber', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Hellbraun', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabian', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Donkey/Mule', '', '', 26);
INSERT INTO breed VALUES (361, 'Draft', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Frettchen', '', '', 3);
INSERT INTO breed VALUES (381, 'Rennmäuse', '', '', 18);
INSERT INTO breed VALUES (382, 'Hausmeerschweinchen', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Hedgehog', '', '', 6);
INSERT INTO breed VALUES (385, 'Mäuse', '', '', 4);
INSERT INTO breed VALUES (386, 'Prairie Dog', '', '', 5);
INSERT INTO breed VALUES (387, 'Ratte', '', '', 5);
INSERT INTO breed VALUES (388, 'Skunk', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (391, 'Vietnamese Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (392, 'Geckos', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Echse', '', '', 13);
INSERT INTO breed VALUES (395, 'Schlange', '', '', 13);
INSERT INTO breed VALUES (396, 'Schildkröte', '', '', 13);
INSERT INTO breed VALUES (397, 'Fisch', '', '', 21);
INSERT INTO breed VALUES (398, 'Graupapagei', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Wellensittich', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Kanarienvogel', '', '', 3);
INSERT INTO breed VALUES (404, 'Chicken', '', '', 3);
INSERT INTO breed VALUES (405, 'Cockatiel', '', '', 3);
INSERT INTO breed VALUES (406, 'Cockatoo', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Dove', '', '', 3);
INSERT INTO breed VALUES (409, 'Duck', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Finch', '', '', 3);
INSERT INTO breed VALUES (413, 'Goose', '', '', 3);
INSERT INTO breed VALUES (414, 'Guinea fowl', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lory/Lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Ostrich', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakeet (Other)', '', '', 3);
INSERT INTO breed VALUES (422, 'Parrot (Other)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Peacock/Pea fowl', '', '', 3);
INSERT INTO breed VALUES (425, 'Pheasant', '', '', 3);
INSERT INTO breed VALUES (426, 'Pigeon', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Swan', '', '', 3);
INSERT INTO breed VALUES (435, 'Toucan', '', '', 3);
INSERT INTO breed VALUES (436, 'Turkey', '', '', 3);
INSERT INTO breed VALUES (437, 'Kuh', '', '', 16);
INSERT INTO breed VALUES (438, 'Ziege', '', '', 16);
INSERT INTO breed VALUES (439, 'Schaf', '', '', 16);
INSERT INTO breed VALUES (440, 'Llama', '', '', 16);
INSERT INTO breed VALUES (441, 'Pig (Farm)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%';
INSERT INTO configuration VALUES ('Organisation', 'Organisation');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Baby');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Young Adult');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Adult');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Senior');
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Non-Microchipped Animals', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (37, 'Animals Without Photo Media', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (38, 'Animals Never Vaccinated', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (39, 'Non-Neutered/Spayed Animals Aged Over 6 Months', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (40, 'Cats Not Combi-Tested', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (41, 'Monthly Animal Figures', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (42, 'Long Term Animals', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (43, 'Shelter Inventory', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (44, 'Detailed Shelter Inventory', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (45, 'Animals Not Part Of A Litter', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Litters');
INSERT INTO customreport VALUES (46, 'In/Out', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (47, 'In/Out Summary', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (48, 'Transfer In Report', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (49, 'Volume Of Adoptions Per Retailer', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (50, 'Average Time At Retailer Before Adoption', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (51, 'Retailer Inventory', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (52, 'Returned Animals Report', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (53, 'Animals Returned Within 6 Months', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (54, 'Animals Returned After 6 Months', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (55, 'Most Common Name', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (56, 'Animal Death Reasons', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (57, 'Most Common Animal Entry Areas', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (58, 'Most Common Animal Adoption Areas', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (59, 'Average Time On Waiting List', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (60, 'Monthly Donations', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Financial Graphs');
INSERT INTO customreport VALUES (61, 'Monthly Donations By Species', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Financial Graphs');
INSERT INTO customreport VALUES (62, 'Monthly Adoptions By Species', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (63, 'Monthly Adoptions By Location', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (64, 'Animal Entry Reasons', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (65, 'Animal Return Reasons', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (66, 'Owner Criteria Matching', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Dead On Arrival', '');
INSERT INTO deathreason VALUES (2, 'Gestorben', '');
INSERT INTO deathreason VALUES (3, 'Healthy', '');
INSERT INTO deathreason VALUES (4, 'Sick/Injured', '');
INSERT INTO deathreason VALUES (5, 'Requested', '');
INSERT INTO deathreason VALUES (6, 'Culling', '');
INSERT INTO deathreason VALUES (7, 'Feral', '');
INSERT INTO deathreason VALUES (8, 'Biting', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Marriage/Relationship split', '');
INSERT INTO entryreason VALUES (2, 'Allergies', '');
INSERT INTO entryreason VALUES (3, 'Biting', '');
INSERT INTO entryreason VALUES (4, 'Unable to Cope', '');
INSERT INTO entryreason VALUES (5, 'Unsuitable Accomodation', '');
INSERT INTO entryreason VALUES (6, 'Gestorben', '');
INSERT INTO entryreason VALUES (7, 'Stray', '');
INSERT INTO entryreason VALUES (8, 'Sick/Injured', '');
INSERT INTO entryreason VALUES (9, 'Unable to Afford', '');
INSERT INTO entryreason VALUES (10, 'Abuse', '');
INSERT INTO entryreason VALUES (11, 'Abandoned', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'No Locations', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Weibchen');
INSERT INTO lksex VALUES (1, 'Männchen');
INSERT INTO lksex VALUES (2, 'Unkekannt');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Sehr groß');
INSERT INTO lksize VALUES (1, 'Groß');
INSERT INTO lksize VALUES (2, 'Mittel');
INSERT INTO lksize VALUES (3, 'Klein');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Kurz');
INSERT INTO lkcoattype VALUES (1, 'Lang');
INSERT INTO lkcoattype VALUES (2, 'Rau');
INSERT INTO lkcoattype VALUES (3, 'Kraus');
INSERT INTO lkcoattype VALUES (4, 'Verschnürt');
INSERT INTO lkcoattype VALUES (5, 'Haarlos');
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Keiner');
INSERT INTO lksmovementtype VALUES (1, 'Adoption');
INSERT INTO lksmovementtype VALUES (2, 'Foster');
INSERT INTO lksmovementtype VALUES (3, 'Transfer');
INSERT INTO lksmovementtype VALUES (4, 'Entlaufen');
INSERT INTO lksmovementtype VALUES (5, 'Reclaimed');
INSERT INTO lksmovementtype VALUES (6, 'Entwendet');
INSERT INTO lksmovementtype VALUES (7, 'Released To Wild');
INSERT INTO lksmovementtype VALUES (8, 'Händler');
INSERT INTO lksmovementtype VALUES (9, 'Reservierung');
INSERT INTO lksmovementtype VALUES (10, 'Cancelled Reservation');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Tier');
INSERT INTO lksmedialink VALUES (1, 'Lost Animal');
INSERT INTO lksmedialink VALUES (2, 'Found Animal');
INSERT INTO lksmedialink VALUES (3, 'Owner');
INSERT INTO lksmedialink VALUES (4, 'Movement');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Keiner');
INSERT INTO lksdiarylink VALUES (1, 'Tier');
INSERT INTO lksdiarylink VALUES (2, 'Owner');
INSERT INTO lksdiarylink VALUES (3, 'Lost Animal');
INSERT INTO lksdiarylink VALUES (4, 'Found Animal');
INSERT INTO lksdiarylink VALUES (5, 'Waiting List');
INSERT INTO lksdiarylink VALUES (6, 'Movement');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Tier');
INSERT INTO lksfieldlink VALUES (1, 'Owner');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Ja/Nein');
INSERT INTO lksfieldtype VALUES (1, 'Text');
INSERT INTO lksfieldtype VALUES (2, 'Notes');
INSERT INTO lksfieldtype VALUES (3, 'Nummer');
INSERT INTO lksfieldtype VALUES (4, 'Datum');
INSERT INTO lksfieldtype VALUES (5, 'Geld');
INSERT INTO lksfieldtype VALUES (6, 'Lookup');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Tier');
INSERT INTO lksloglink VALUES (1, 'Owner');
INSERT INTO lksloglink VALUES (2, 'Lost Animal');
INSERT INTO lksloglink VALUES (3, 'Found Animal');
INSERT INTO lksloglink VALUES (4, 'Waiting List');
INSERT INTO lksloglink VALUES (5, 'Movement');
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Urgent');
INSERT INTO lkurgency VALUES (2, 'High');
INSERT INTO lkurgency VALUES (3, 'Mittel');
INSERT INTO lkurgency VALUES (4, 'Low');
INSERT INTO lkurgency VALUES (5, 'Lowest');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Bite', '');
INSERT INTO logtype VALUES (2, 'Complaint', '');
INSERT INTO logtype VALUES (3, 'History', '');
INSERT INTO logtype VALUES (4, 'Weight', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Hund', '', '');
INSERT INTO species VALUES (2, 'Katze', '', '');
INSERT INTO species VALUES (3, 'Vogel', '', '');
INSERT INTO species VALUES (4, 'Mäuse', '', '');
INSERT INTO species VALUES (5, 'Ratte', '', '');
INSERT INTO species VALUES (6, 'Hedgehog', '', '');
INSERT INTO species VALUES (7, 'Kaninchen', '', '');
INSERT INTO species VALUES (8, 'Dove', '', '');
INSERT INTO species VALUES (9, 'Frettchen', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Schlange', '', '');
INSERT INTO species VALUES (12, 'Tortoise', '', '');
INSERT INTO species VALUES (13, 'Terrapin', '', '');
INSERT INTO species VALUES (14, 'Chicken', '', '');
INSERT INTO species VALUES (15, 'Owl', '', '');
INSERT INTO species VALUES (16, 'Ziege', '', '');
INSERT INTO species VALUES (17, 'Goose', '', '');
INSERT INTO species VALUES (18, 'Rennmäuse', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'Hausmeerschweinchen', '', '');
INSERT INTO species VALUES (21, 'Goldfish', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Camel', '', '');
INSERT INTO species VALUES (24, 'Pferd', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Donkey', '', '');
INSERT INTO species VALUES (27, 'Llama', '', '');
INSERT INTO species VALUES (28, 'Schwein', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Neuter/Spay', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Temporary Vaccination', '');
INSERT INTO vaccinationtype VALUES (2, 'First Vaccination', '');
INSERT INTO vaccinationtype VALUES (3, 'Second Vaccination', '');
INSERT INTO vaccinationtype VALUES (4, 'Booster', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukaemia', '');
INSERT INTO vaccinationtype VALUES (6, 'Kennel Cough', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirus', '');
