DELETE FROM accounts;
INSERT INTO accounts VALUES (1, 'Inkomst::Gåva', 'Inkommande gåvor (övrigt)', 5, 1, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (2, 'Inkomst::Adoption', 'Adoptionsavgiftsgåvor', 5, 2, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (3, 'Inkomst::Väntelista', 'Väntelista gåvor', 5, 3, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (4, 'Intäkt::Förstagångsdonation', 'Donationer för besökande djur i hemmet', 5, 4, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (5, 'Income::Sponsorship', 'Sponsorship donations', 5, 5, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (6, 'Intäkt::Butik', 'Income from an on-site shop', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (7, 'Income::Interest', 'Bankränta', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (8, 'Income::OpeningBalances', 'Opening balances', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (9, 'Bank::Nuvarande', 'Bank nuvarande konto', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (10, 'Bank::Uttag', 'Bankuttagsbelopp', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (11, 'Bank::Sparande', 'Bankkontosparande', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (12, 'Asset::Premises', 'Premises', 8, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (13, 'Utgifter::Telefon', 'Telefonräkningar', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (14, 'Utgifter::Elektricitet', 'Elräkningar', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (15, 'Utgifter::Vatten', 'Water Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (16, 'Expenses::Gas', 'Gas Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (17, 'Expenses::Postage', 'Postage costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (18, 'Expenses::Stationary', 'Stationary costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (19, 'Expenses::Food', 'Animal food costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'H (Hund)', NULL);
INSERT INTO animaltype VALUES (10, 'HH (Hemlös hund)', NULL);
INSERT INTO animaltype VALUES (11, 'O (Oönskad katt)', NULL);
INSERT INTO animaltype VALUES (12, 'UK (Upphittad katt)', NULL);
INSERT INTO animaltype VALUES (13, 'D (Diverse)', NULL);
INSERT INTO animaltype VALUES (40, 'E (Ej djurhemsdjur)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Svart', NULL);
INSERT INTO basecolour VALUES (2, 'Vit', NULL);
INSERT INTO basecolour VALUES (3, 'Svart och vit', NULL);
INSERT INTO basecolour VALUES (4, 'Rödgul', NULL);
INSERT INTO basecolour VALUES (5, 'Vit och svart', NULL);
INSERT INTO basecolour VALUES (6, 'Tortie', NULL);
INSERT INTO basecolour VALUES (7, 'Randig', NULL);
INSERT INTO basecolour VALUES (8, 'Mellanbrun', NULL);
INSERT INTO basecolour VALUES (9, 'Svart och mellanbrun', NULL);
INSERT INTO basecolour VALUES (10, 'Mellanbrun och svart', NULL);
INSERT INTO basecolour VALUES (11, 'Brun', NULL);
INSERT INTO basecolour VALUES (12, 'Brun och svart', NULL);
INSERT INTO basecolour VALUES (13, 'Svart och brun', NULL);
INSERT INTO basecolour VALUES (14, 'Spräcklig', NULL);
INSERT INTO basecolour VALUES (15, 'Spräcklig och svart', NULL);
INSERT INTO basecolour VALUES (16, 'Spräcklig och vit', NULL);
INSERT INTO basecolour VALUES (17, 'Svart och spräcklig', NULL);
INSERT INTO basecolour VALUES (18, 'Vit och spräcklig', NULL);
INSERT INTO basecolour VALUES (19, 'Trefärgad', NULL);
INSERT INTO basecolour VALUES (20, 'Mörkbrun', NULL);
INSERT INTO basecolour VALUES (21, 'Mörkbrun och vit', NULL);
INSERT INTO basecolour VALUES (22, 'Vit och mörkbrun', NULL);
INSERT INTO basecolour VALUES (23, 'Krämfärgad', NULL);
INSERT INTO basecolour VALUES (24, 'Mellanbrun och vit', NULL);
INSERT INTO basecolour VALUES (26, 'Vit och mellanbrun', NULL);
INSERT INTO basecolour VALUES (27, 'Tortie and White', NULL);
INSERT INTO basecolour VALUES (28, 'Randig och vit', NULL);
INSERT INTO basecolour VALUES (29, 'Brungul och vit', NULL);
INSERT INTO basecolour VALUES (30, 'Grå', NULL);
INSERT INTO basecolour VALUES (31, 'Grå och vit', NULL);
INSERT INTO basecolour VALUES (32, 'Vit och grå', NULL);
INSERT INTO basecolour VALUES (33, 'Vit och sköldpaddsfärgad', NULL);
INSERT INTO basecolour VALUES (35, 'Brun och vit', NULL);
INSERT INTO basecolour VALUES (36, 'Blå', NULL);
INSERT INTO basecolour VALUES (37, 'Vit och randig', NULL);
INSERT INTO basecolour VALUES (38, 'Gul och grå', NULL);
INSERT INTO basecolour VALUES (39, 'Blandat', NULL);
INSERT INTO basecolour VALUES (40, 'Vit och brun', NULL);
INSERT INTO basecolour VALUES (41, 'Grön', NULL);
INSERT INTO basecolour VALUES (42, 'Amber', NULL);
INSERT INTO basecolour VALUES (43, 'Black Tortie', NULL);
INSERT INTO basecolour VALUES (44, 'Blue Tortie', NULL);
INSERT INTO basecolour VALUES (45, 'Chocolate', NULL);
INSERT INTO basecolour VALUES (46, 'Chocolate Tortie', NULL);
INSERT INTO basecolour VALUES (47, 'Cinnamon', NULL);
INSERT INTO basecolour VALUES (48, 'Cinnamon Tortoiseshell', NULL);
INSERT INTO basecolour VALUES (49, 'Fawn', NULL);
INSERT INTO basecolour VALUES (50, 'Fawn Tortoiseshell', NULL);
INSERT INTO basecolour VALUES (51, 'Golden', NULL);
INSERT INTO basecolour VALUES (52, 'Light Amber', NULL);
INSERT INTO basecolour VALUES (53, 'Lilac', NULL);
INSERT INTO basecolour VALUES (54, 'Lilac Tortie', NULL);
INSERT INTO basecolour VALUES (55, 'Ruddy', NULL);
INSERT INTO basecolour VALUES (56, 'Seal', NULL);
INSERT INTO basecolour VALUES (57, 'Silver', NULL);
INSERT INTO basecolour VALUES (58, 'Sorrel', NULL);
INSERT INTO basecolour VALUES (59, 'Sorrel Tortoiseshell', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Afghanhund', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedaleterrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash (Anatolisk herdehund)', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Alaskan Malamute', '', '', 1);
INSERT INTO breed VALUES (7, 'Amerikansk bulldogg', '', '', 1);
INSERT INTO breed VALUES (8, 'American Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (9, 'Amerikansk staffordshire terrier', '', '', 1);
INSERT INTO breed VALUES (10, 'American water spaniel', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolian Shepherd', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzell Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (13, 'Australian Cattle Dog/Blue Heeler', '', '', 1);
INSERT INTO breed VALUES (14, 'Australian kelpie', '', '', 1);
INSERT INTO breed VALUES (15, 'Australian shepherd', '', '', 1);
INSERT INTO breed VALUES (16, 'Australian Terrier', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlingtonterrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgisk vallhund', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgisk vallhund/Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgisk vallhund/Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgisk vallhund/Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Bernese Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon frisé', '', '', 1);
INSERT INTO breed VALUES (29, 'Black and tan coonhound', '', '', 1);
INSERT INTO breed VALUES (30, 'Svart Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Blodhund', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Borderterrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Borzoi', '', '', 1);
INSERT INTO breed VALUES (37, 'Bostonterrier', '', '', 1);
INSERT INTO breed VALUES (38, 'Bouvier des flandres', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Brittany Spaniel', '', '', 1);
INSERT INTO breed VALUES (43, 'Brussels Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bullterrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairnterrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Canaan dog', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso Mastiff', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina Dog', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Vallhund', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake bay retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chinese crested dog', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinese Foo Dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Brun Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Dachshund', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatiner', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Dobermannpinscher', '', '', 1);
INSERT INTO breed VALUES (70, 'Dogo Argentino', '', '', 1);
INSERT INTO breed VALUES (71, 'Dogue de Bordeaux', '', '', 1);
INSERT INTO breed VALUES (72, 'Dutch Shepherd', '', '', 1);
INSERT INTO breed VALUES (73, 'Engelsk bulldog', '', '', 1);
INSERT INTO breed VALUES (74, 'Engelsk cockerspaniel', '', '', 1);
INSERT INTO breed VALUES (75, 'English Coonhound', '', '', 1);
INSERT INTO breed VALUES (76, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'Engelsk setter', '', '', 1);
INSERT INTO breed VALUES (78, 'English Shepherd', '', '', 1);
INSERT INTO breed VALUES (79, 'Engelsk springer spaniel', '', '', 1);
INSERT INTO breed VALUES (80, 'King charles spaniel', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher sennenhund', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimåhund', '', '', 1);
INSERT INTO breed VALUES (83, 'Field spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Finsk lapphund', '', '', 1);
INSERT INTO breed VALUES (86, 'Finsk spets', '', '', 1);
INSERT INTO breed VALUES (87, 'Flatcoated retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Foxterrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Fransk bulldogg', '', '', 1);
INSERT INTO breed VALUES (91, 'Pinscher', '', '', 1);
INSERT INTO breed VALUES (92, 'Schäfer', '', '', 1);
INSERT INTO breed VALUES (93, 'Korthårig vorsteh', '', '', 1);
INSERT INTO breed VALUES (94, 'Strävhårig vorsteh', '', '', 1);
INSERT INTO breed VALUES (95, 'Irish glen of imaal terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordonsetter', '', '', 1);
INSERT INTO breed VALUES (98, 'Grand danois', '', '', 1);
INSERT INTO breed VALUES (99, 'Great Pyrenees', '', '', 1);
INSERT INTO breed VALUES (100, 'Greater Swiss Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Havanese', '', '', 1);
INSERT INTO breed VALUES (103, 'Hound', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibizan Hound', '', '', 1);
INSERT INTO breed VALUES (107, 'Illyrian Sheepdog', '', '', 1);
INSERT INTO breed VALUES (108, 'Irländsk röd setter', '', '', 1);
INSERT INTO breed VALUES (109, 'Irländsk terrier', '', '', 1);
INSERT INTO breed VALUES (110, 'Irländsk vattenspaniel', '', '', 1);
INSERT INTO breed VALUES (111, 'Irländsk varghund', '', '', 1);
INSERT INTO breed VALUES (112, 'Italiensk vinthund', '', '', 1);
INSERT INTO breed VALUES (113, 'Spinone', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Japanese chin', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelsk björnhund', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry blue terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakelandterrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Löwchen', '', '', 1);
INSERT INTO breed VALUES (131, 'Malteser', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchesterterrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremmano Abruzzese', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Mini Pinscher', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (139, 'Münsterländer', '', '', 1);
INSERT INTO breed VALUES (140, 'Mastino napoletano', '', '', 1);
INSERT INTO breed VALUES (141, 'New Guinea Singing Dog', '', '', 1);
INSERT INTO breed VALUES (142, 'Newfoundland', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolkterrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwichterrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Norsk buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Norsk älghund', '', '', 1);
INSERT INTO breed VALUES (147, 'Norsk lundehund', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova scotia duck tolling retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Old English Sheepdog', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhound', '', '', 1);
INSERT INTO breed VALUES (151, 'Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Lakelandterrier', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekingese', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruvian Inca Orchid', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit basset griffon vendéen', '', '', 1);
INSERT INTO breed VALUES (156, 'Faraohund', '', '', 1);
INSERT INTO breed VALUES (157, 'Amerikansk pitbullterrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Podengo portugues', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polsk låglandsvallhund (Polski owczarek nizinny)', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Pudel', '', '', 1);
INSERT INTO breed VALUES (164, 'Portugisisk vattenhund', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Mops', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesian Ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'Saint Bernard St. Bernard', '', '', 1);
INSERT INTO breed VALUES (176, 'Samoyed', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Skotsk hjorthund', '', '', 1);
INSERT INTO breed VALUES (180, 'Skotsk terrier', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Fårhund', '', '', 1);
INSERT INTO breed VALUES (185, 'Vallhund', '', '', 1);
INSERT INTO breed VALUES (186, 'Shetland Sheepdog (Sheltie)', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Siberian Husky', '', '', 1);
INSERT INTO breed VALUES (190, 'Silkyterrier', '', '', 1);
INSERT INTO breed VALUES (191, 'Skyeterrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Släthårig foxterrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spets', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire bullterrier', '', '', 1);
INSERT INTO breed VALUES (197, 'Juzjnorusskaja ovtjarka (sydrysk ovtjarka)', '', '', 1);
INSERT INTO breed VALUES (198, 'Svensk vallhund', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Tibetansk mastiff', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibetansk spaniel', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibetansk terrier', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Ungersk vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimaraner', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welshterrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh springer spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier (Westie)', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'Vit Schäfer', '', '', 1);
INSERT INTO breed VALUES (216, 'Strävhårig Pointing Griffon', '', '', 1);
INSERT INTO breed VALUES (217, 'Strävhårig terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'Gul Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier (Yorkie)', '', '', 1);
INSERT INTO breed VALUES (220, 'Xoloitzcuintle/Mexican Hairless', '', '', 1);
INSERT INTO breed VALUES (221, 'Abyssinian', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'Amerikanskt korthå', '', '', 2);
INSERT INTO breed VALUES (224, 'American Wirehair', '', '', 2);
INSERT INTO breed VALUES (225, 'Applehead Siamese', '', '', 2);
INSERT INTO breed VALUES (226, 'Balines', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengal', '', '', 2);
INSERT INTO breed VALUES (228, 'Birma', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'Brittiskt korthår', '', '', 2);
INSERT INTO breed VALUES (232, 'Burma', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Calico', '', '', 2);
INSERT INTO breed VALUES (235, 'Sphynx', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (243, 'Huskatt långhårig', '', '', 2);
INSERT INTO breed VALUES (252, 'Huskatt halvlång päls', '', '', 2);
INSERT INTO breed VALUES (261, 'Huskatt korthårig', '', '', 2);
INSERT INTO breed VALUES (271, 'Egyptisk mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Exotiskt korthår', '', '', 2);
INSERT INTO breed VALUES (273, 'Skeppskatt', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Japanese Bobtail', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Norsk skogskatt', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Orientaliskt långhår', '', '', 2);
INSERT INTO breed VALUES (285, 'Orientaliskt korthår', '', '', 2);
INSERT INTO breed VALUES (286, 'Oriental Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'Perser', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Russian Blue', '', '', 2);
INSERT INTO breed VALUES (292, 'Scottish Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siames', '', '', 2);
INSERT INTO breed VALUES (295, 'Siberian', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somali', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphynx', '', '', 2);
INSERT INTO breed VALUES (307, 'Tiger', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkinese', '', '', 2);
INSERT INTO breed VALUES (311, 'Turkisk Angora', '', '', 2);
INSERT INTO breed VALUES (312, 'Turkisk Van', '', '', 2);
INSERT INTO breed VALUES (314, 'American', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angora kanin', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgisk hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Tysk jättescheck', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Holländsk kanin', '', '', 7);
INSERT INTO breed VALUES (329, 'Dvärg', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polsk', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silver', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Mellanbrun', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arab', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Åsna/Mula', '', '', 26);
INSERT INTO breed VALUES (361, 'Utkast', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Ponny', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardras', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Varmblod', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Iller', '', '', 3);
INSERT INTO breed VALUES (381, 'Ökenråtta', '', '', 18);
INSERT INTO breed VALUES (382, 'Marsvin', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Igelkott', '', '', 6);
INSERT INTO breed VALUES (385, 'Mus', '', '', 4);
INSERT INTO breed VALUES (386, 'Präriehund', '', '', 5);
INSERT INTO breed VALUES (387, 'Råtta', '', '', 5);
INSERT INTO breed VALUES (388, 'Skunk', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Hängbuksvin', '', '', 28);
INSERT INTO breed VALUES (391, 'Vietnamesiskt hängbuksvin', '', '', 28);
INSERT INTO breed VALUES (392, 'Gecko', '', '', 13);
INSERT INTO breed VALUES (393, 'Leguan', '', '', 13);
INSERT INTO breed VALUES (394, 'Ödla', '', '', 13);
INSERT INTO breed VALUES (395, 'Orm', '', '', 13);
INSERT INTO breed VALUES (396, 'Sköldpadda', '', '', 13);
INSERT INTO breed VALUES (397, 'Fisk', '', '', 21);
INSERT INTO breed VALUES (398, 'African Grey', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Undulat', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Kanariefågel', '', '', 3);
INSERT INTO breed VALUES (404, 'Kyckling', '', '', 3);
INSERT INTO breed VALUES (405, 'Nymfparakit/nymfkakadua', '', '', 3);
INSERT INTO breed VALUES (406, 'Kakadua', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Duva', '', '', 3);
INSERT INTO breed VALUES (409, 'Anka', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Fink', '', '', 3);
INSERT INTO breed VALUES (413, 'Gås', '', '', 3);
INSERT INTO breed VALUES (414, 'Pärlhöna', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lori/lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Dvärgpapegoja', '', '', 3);
INSERT INTO breed VALUES (418, 'Arapapegoja', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Struts', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakit (annan)', '', '', 3);
INSERT INTO breed VALUES (422, 'Papegoja (annan)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Påfågel', '', '', 3);
INSERT INTO breed VALUES (425, 'Fasan', '', '', 3);
INSERT INTO breed VALUES (426, 'Duva', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Munkparakit', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Svan', '', '', 3);
INSERT INTO breed VALUES (435, 'Tukan', '', '', 3);
INSERT INTO breed VALUES (436, 'Kalkon', '', '', 3);
INSERT INTO breed VALUES (437, 'Ko', '', '', 16);
INSERT INTO breed VALUES (438, 'Get', '', '', 16);
INSERT INTO breed VALUES (439, 'Får', '', '', 16);
INSERT INTO breed VALUES (440, 'Lama', '', '', 16);
INSERT INTO breed VALUES (441, 'Gris (farm)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%Name';
INSERT INTO configuration VALUES ('Organisation', 'Organisation');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Unge');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Ung');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Vuxen');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Senior');
DELETE FROM costtype;
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Ej microchippade djur', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Revision');
INSERT INTO customreport VALUES (37, 'Djur utan fotomedia', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Revision');
INSERT INTO customreport VALUES (38, 'Aldrig vaccinerade djur', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Revision');
INSERT INTO customreport VALUES (39, 'Ej kastrerade/steriliserade djur över 6 månader', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Revision');
INSERT INTO customreport VALUES (40, 'Ej combi-testade katter', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Revision');
INSERT INTO customreport VALUES (41, 'Djurstatistik månadsvis', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistik');
INSERT INTO customreport VALUES (42, 'Långvariga djur', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistik');
INSERT INTO customreport VALUES (43, 'Djurhemsförteckning/inventering', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventeringar/förteckningar');
INSERT INTO customreport VALUES (44, 'Detaljerad djurhemsförteckning', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventeringar/förteckningar');
INSERT INTO customreport VALUES (45, 'Djur som ej tillhör någon kull', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Kullar');
INSERT INTO customreport VALUES (46, 'In/ut', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Förflyttningar');
INSERT INTO customreport VALUES (47, 'In/ut sammanfattning', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Förflyttningar');
INSERT INTO customreport VALUES (48, 'Transfer In Report', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Förflyttningar');
INSERT INTO customreport VALUES (49, 'Volym av adoptioner per återförsäljare', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Återförsäljare');
INSERT INTO customreport VALUES (50, 'Tid i genomsnitt hos återförsäljare innan adoption', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Återförsäljare');
INSERT INTO customreport VALUES (51, 'Återförsäljarförteckning', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Återförsäljare');
INSERT INTO customreport VALUES (52, 'Återlämnade djur rapport', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Återlämningar');
INSERT INTO customreport VALUES (53, 'Djur som återlämnats inom 6 månader', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Återlämningar');
INSERT INTO customreport VALUES (54, 'Djur som återlämnats efetr 6 månader', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Återlämningar');
INSERT INTO customreport VALUES (55, 'Vanligaste namn', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistik');
INSERT INTO customreport VALUES (56, 'Djurs dödsorsaker', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistik');
INSERT INTO customreport VALUES (57, 'Vanligaste djurinlämningsområden', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistik');
INSERT INTO customreport VALUES (58, 'Vanligaste adoptionsområden', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistik');
INSERT INTO customreport VALUES (59, 'Genomsnittlig tid på väntelistan', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistik');
INSERT INTO customreport VALUES (60, 'Donationer per månad', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Ekonomiska diagram');
INSERT INTO customreport VALUES (61, 'Donationer per månad efter art', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Ekonomiska diagram');
INSERT INTO customreport VALUES (62, 'Adoptioner per månad efter art', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Förflyttningsdiagram');
INSERT INTO customreport VALUES (63, 'Adoptioner per månad efter placering', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Förflyttningsdiagram');
INSERT INTO customreport VALUES (64, 'Anledning till djurets ankomst', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Förflyttningsdiagram');
INSERT INTO customreport VALUES (65, 'Anledning till återlämning av djur', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Förflyttningsdiagram');
INSERT INTO customreport VALUES (66, 'Ägarkritieriematchning', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventeringar/förteckningar');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Död vid ankomst', '');
INSERT INTO deathreason VALUES (2, 'Dog', '');
INSERT INTO deathreason VALUES (3, 'Frisk', '');
INSERT INTO deathreason VALUES (4, 'Sjuk/Skadad', '');
INSERT INTO deathreason VALUES (5, 'Efterfrågad', '');
INSERT INTO deathreason VALUES (6, 'Utrensning', '');
INSERT INTO deathreason VALUES (7, 'Vild', '');
INSERT INTO deathreason VALUES (8, 'Bits', '');
DELETE FROM diet;
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Donation', '');
INSERT INTO donationtype VALUES (2, 'Adoption Fee', '');
INSERT INTO donationtype VALUES (3, 'Waiting List Donation', '');
INSERT INTO donationtype VALUES (4, 'Entry Donation', '');
INSERT INTO donationtype VALUES (5, 'Animal Sponsorship', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Separation', '');
INSERT INTO entryreason VALUES (2, 'Allergi', '');
INSERT INTO entryreason VALUES (3, 'Bits', '');
INSERT INTO entryreason VALUES (4, 'Oförmögen att ta hand om', '');
INSERT INTO entryreason VALUES (5, 'Olämpligt Boende', '');
INSERT INTO entryreason VALUES (6, 'Dog', '');
INSERT INTO entryreason VALUES (7, 'Hittedjur', '');
INSERT INTO entryreason VALUES (8, 'Sjuk/Skadad', '');
INSERT INTO entryreason VALUES (9, 'Hade inte råd', '');
INSERT INTO entryreason VALUES (10, 'Vanvård', '');
INSERT INTO entryreason VALUES (11, 'Övergiven', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Inga platser', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Hona');
INSERT INTO lksex VALUES (1, 'Hane');
INSERT INTO lksex VALUES (2, 'Okänd');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Mycket stor');
INSERT INTO lksize VALUES (1, 'Stor');
INSERT INTO lksize VALUES (2, 'Medel');
INSERT INTO lksize VALUES (3, 'Liten');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Kort');
INSERT INTO lkcoattype VALUES (1, 'Lång');
INSERT INTO lkcoattype VALUES (2, 'Grov');
INSERT INTO lkcoattype VALUES (3, 'Krullig');
INSERT INTO lkcoattype VALUES (4, 'Corded');
INSERT INTO lkcoattype VALUES (5, 'Hårlös');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Inget');
INSERT INTO lksmovementtype VALUES (1, 'Adoption');
INSERT INTO lksmovementtype VALUES (2, 'Jourhem');
INSERT INTO lksmovementtype VALUES (3, 'Överföring');
INSERT INTO lksmovementtype VALUES (4, 'Bortsprungen');
INSERT INTO lksmovementtype VALUES (5, 'Reclaimed');
INSERT INTO lksmovementtype VALUES (6, 'Stulet');
INSERT INTO lksmovementtype VALUES (7, 'Släppts fri');
INSERT INTO lksmovementtype VALUES (8, 'Återförsäljare');
INSERT INTO lksmovementtype VALUES (9, 'Reservation');
INSERT INTO lksmovementtype VALUES (10, 'Avbokad reservation');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Djur');
INSERT INTO lksmedialink VALUES (1, 'Försvunnet djur');
INSERT INTO lksmedialink VALUES (2, 'Upphittat djur');
INSERT INTO lksmedialink VALUES (3, 'Ägare');
INSERT INTO lksmedialink VALUES (4, 'Förflyttning');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Inget');
INSERT INTO lksdiarylink VALUES (1, 'Djur');
INSERT INTO lksdiarylink VALUES (2, 'Ägare');
INSERT INTO lksdiarylink VALUES (3, 'Försvunnet djur');
INSERT INTO lksdiarylink VALUES (4, 'Upphittat djur');
INSERT INTO lksdiarylink VALUES (5, 'Väntelista');
INSERT INTO lksdiarylink VALUES (6, 'Förflyttning');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'Engångsföreteelse');
INSERT INTO lksdonationfreq VALUES (1, 'Weekly');
INSERT INTO lksdonationfreq VALUES (2, 'Monthly');
INSERT INTO lksdonationfreq VALUES (3, 'Quarterly');
INSERT INTO lksdonationfreq VALUES (4, 'Half-Yearly');
INSERT INTO lksdonationfreq VALUES (5, 'Annually');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Djur');
INSERT INTO lksfieldlink VALUES (1, 'Ägare');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Ja/Nej');
INSERT INTO lksfieldtype VALUES (1, 'Text');
INSERT INTO lksfieldtype VALUES (2, 'Anteckningar');
INSERT INTO lksfieldtype VALUES (3, 'Nummer');
INSERT INTO lksfieldtype VALUES (4, 'Datum');
INSERT INTO lksfieldtype VALUES (5, 'Pengar');
INSERT INTO lksfieldtype VALUES (6, 'Uppslag');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Djur');
INSERT INTO lksloglink VALUES (1, 'Ägare');
INSERT INTO lksloglink VALUES (2, 'Försvunnet djur');
INSERT INTO lksloglink VALUES (3, 'Upphittat djur');
INSERT INTO lksloglink VALUES (4, 'Väntelista');
INSERT INTO lksloglink VALUES (5, 'Förflyttning');
DELETE FROM lksyesno;
DELETE FROM lksynun;
DELETE FROM lksposneg;
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Bråttom');
INSERT INTO lkurgency VALUES (2, 'Hög');
INSERT INTO lkurgency VALUES (3, 'Medel');
INSERT INTO lkurgency VALUES (4, 'Låg');
INSERT INTO lkurgency VALUES (5, 'Lägsta');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Bits', '');
INSERT INTO logtype VALUES (2, 'Klagomål', '');
INSERT INTO logtype VALUES (3, 'Historik', '');
INSERT INTO logtype VALUES (4, 'Vikt', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Hund', '', '');
INSERT INTO species VALUES (2, 'Katt', '', '');
INSERT INTO species VALUES (3, 'Fågel', '', '');
INSERT INTO species VALUES (4, 'Mus', '', '');
INSERT INTO species VALUES (5, 'Råtta', '', '');
INSERT INTO species VALUES (6, 'Igelkott', '', '');
INSERT INTO species VALUES (7, 'Kanin', '', '');
INSERT INTO species VALUES (8, 'Duva', '', '');
INSERT INTO species VALUES (9, 'Iller', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Orm', '', '');
INSERT INTO species VALUES (12, 'Sköldpadda', '', '');
INSERT INTO species VALUES (13, 'Reptil', '', '');
INSERT INTO species VALUES (14, 'Kyckling', '', '');
INSERT INTO species VALUES (15, 'Uggla', '', '');
INSERT INTO species VALUES (16, 'Get', '', '');
INSERT INTO species VALUES (17, 'Gås', '', '');
INSERT INTO species VALUES (18, 'Ökenråtta', '', '');
INSERT INTO species VALUES (19, 'Nymfparakit/nymfkakadua', '', '');
INSERT INTO species VALUES (20, 'Marsvin', '', '');
INSERT INTO species VALUES (21, 'Guldfisk', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Kamel', '', '');
INSERT INTO species VALUES (24, 'Häst', '', '');
INSERT INTO species VALUES (25, 'Ponny', '', '');
INSERT INTO species VALUES (26, 'Åsna', '', '');
INSERT INTO species VALUES (27, 'Lama', '', '');
INSERT INTO species VALUES (28, 'Gris', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Kastrera/Sterilisera', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Tillfällig vaccination', '');
INSERT INTO vaccinationtype VALUES (2, 'Första vaccination', '');
INSERT INTO vaccinationtype VALUES (3, 'Andra vaccination', '');
INSERT INTO vaccinationtype VALUES (4, 'Booster', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukemi', '');
INSERT INTO vaccinationtype VALUES (6, 'Kennelhosta', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirus', '');
