DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Perro)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Perro callejero)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Gato abandonado)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Gato callejero)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Diversos)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Animal externo)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Negro', NULL);
INSERT INTO basecolour VALUES (2, 'Blanco', NULL);
INSERT INTO basecolour VALUES (3, 'Negro y Blanco', NULL);
INSERT INTO basecolour VALUES (4, 'Pelirrojo', NULL);
INSERT INTO basecolour VALUES (5, 'Blanco y Negro', NULL);
INSERT INTO basecolour VALUES (6, 'Torti', NULL);
INSERT INTO basecolour VALUES (7, 'Atigrado', NULL);
INSERT INTO basecolour VALUES (8, 'Canela', NULL);
INSERT INTO basecolour VALUES (9, 'Negro y Canela', NULL);
INSERT INTO basecolour VALUES (10, 'Canela y Negro', NULL);
INSERT INTO basecolour VALUES (11, 'Marrón', NULL);
INSERT INTO basecolour VALUES (12, 'Marrón y Negro', NULL);
INSERT INTO basecolour VALUES (13, 'Negro y Marrón', NULL);
INSERT INTO basecolour VALUES (14, 'Manchado', NULL);
INSERT INTO basecolour VALUES (15, 'Manchado y Negro', NULL);
INSERT INTO basecolour VALUES (16, 'Manchado y Blanco', NULL);
INSERT INTO basecolour VALUES (17, 'Negro y Manchado', NULL);
INSERT INTO basecolour VALUES (18, 'Blanco y Manchado', NULL);
INSERT INTO basecolour VALUES (19, 'Tricolor', NULL);
INSERT INTO basecolour VALUES (20, 'Con lunares', NULL);
INSERT INTO basecolour VALUES (21, 'Con lunares y Blanco', NULL);
INSERT INTO basecolour VALUES (22, 'Blanco y Con lunares', NULL);
INSERT INTO basecolour VALUES (23, 'Crema', NULL);
INSERT INTO basecolour VALUES (24, 'Canela y Blanco', NULL);
INSERT INTO basecolour VALUES (26, 'Blanco y Canela', NULL);
INSERT INTO basecolour VALUES (27, 'Torti y Blanco', NULL);
INSERT INTO basecolour VALUES (28, 'Atigrado y Blanco', NULL);
INSERT INTO basecolour VALUES (29, 'Pelirrojo y Blanco', NULL);
INSERT INTO basecolour VALUES (30, 'Gris', NULL);
INSERT INTO basecolour VALUES (31, 'Gris y Blanco', NULL);
INSERT INTO basecolour VALUES (32, 'Blanco y Gris', NULL);
INSERT INTO basecolour VALUES (33, 'Blanco y Torti', NULL);
INSERT INTO basecolour VALUES (35, 'Marrón y Blanco', NULL);
INSERT INTO basecolour VALUES (36, 'Azul', NULL);
INSERT INTO basecolour VALUES (37, 'Blanco y Atigrado', NULL);
INSERT INTO basecolour VALUES (38, 'Amarillo y Gris', NULL);
INSERT INTO basecolour VALUES (39, 'Multicolor', NULL);
INSERT INTO basecolour VALUES (40, 'Blanco y Marrón', NULL);
INSERT INTO basecolour VALUES (41, 'Verde', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Lebrel Afgano', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Malamute de Alaska', '', '', 1);
INSERT INTO breed VALUES (7, 'Bulldog Americano', '', '', 1);
INSERT INTO breed VALUES (8, 'Perro Esquimal Americano', '', '', 1);
INSERT INTO breed VALUES (9, 'Staffordshire Terrier Americano', '', '', 1);
INSERT INTO breed VALUES (10, 'Perro de Agua Americano', '', '', 1);
INSERT INTO breed VALUES (11, 'Pastor de Anatolia', '', '', 1);
INSERT INTO breed VALUES (12, 'Boyero de Appenzell', '', '', 1);
INSERT INTO breed VALUES (13, 'Boyero Australiano', '', '', 1);
INSERT INTO breed VALUES (14, 'Kelpie Australiano', '', '', 1);
INSERT INTO breed VALUES (15, 'Pastor Australiano', '', '', 1);
INSERT INTO breed VALUES (16, 'Terrier Australiano', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Sabueso Basset', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Collie Barbudo', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Pastor Belga', '', '', 1);
INSERT INTO breed VALUES (24, 'Pastor Belga Laeknois', '', '', 1);
INSERT INTO breed VALUES (25, 'Pastor Belga Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Pastor Belga Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Boyero de Montaña Bernés', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichón de Pelo Rizado', '', '', 1);
INSERT INTO breed VALUES (29, 'Sabueso Negro y Fuego', '', '', 1);
INSERT INTO breed VALUES (30, 'Labrador Retriever Negro', '', '', 1);
INSERT INTO breed VALUES (31, 'Blackmouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Perro de San Huberto', '', '', 1);
INSERT INTO breed VALUES (33, 'Sabueso Bluetick', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Lebrel Ruso Barsoi', '', '', 1);
INSERT INTO breed VALUES (37, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (38, 'Bouvier de Flandes', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Pastor de Brie', '', '', 1);
INSERT INTO breed VALUES (42, 'Spaniel Bretón', '', '', 1);
INSERT INTO breed VALUES (43, 'Grifón de Bruselas', '', '', 1);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Perro de Canaan', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso', '', '', 1);
INSERT INTO breed VALUES (49, 'Dingo Americano', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Cur', '', '', 1);
INSERT INTO breed VALUES (51, 'Boyero', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Perdiguero Chesapeake Bay', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Perro Crestado de China', '', '', 1);
INSERT INTO breed VALUES (56, 'Perro Fu Chino', '', '', 1);
INSERT INTO breed VALUES (57, 'Labrador Retriever Chocolate', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockerpoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Sabueso', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi Galés', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tuléar', '', '', 1);
INSERT INTO breed VALUES (66, 'Teckel', '', '', 1);
INSERT INTO breed VALUES (67, 'Dálmata', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Doberman Pincher', '', '', 1);
INSERT INTO breed VALUES (70, 'Dogo Argentino', '', '', 1);
INSERT INTO breed VALUES (71, 'Dogo de Burdeos', '', '', 1);
INSERT INTO breed VALUES (72, 'Pastor Holandés', '', '', 1);
INSERT INTO breed VALUES (73, 'Bulldog Inglés', '', '', 1);
INSERT INTO breed VALUES (74, 'Cocker Spaniel Inglés', '', '', 1);
INSERT INTO breed VALUES (75, 'Rastreador Inglés', '', '', 1);
INSERT INTO breed VALUES (76, 'Pointer Inglés', '', '', 1);
INSERT INTO breed VALUES (77, 'Setter Inglés', '', '', 1);
INSERT INTO breed VALUES (78, 'Pastor Inglés', '', '', 1);
INSERT INTO breed VALUES (79, 'Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (80, 'Toy Spaniel Inglés', '', '', 1);
INSERT INTO breed VALUES (81, 'Boyero de Entlebuch', '', '', 1);
INSERT INTO breed VALUES (82, 'Perro Esquimal', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila Brasileño', '', '', 1);
INSERT INTO breed VALUES (85, 'Perro Finlandés de Laponia', '', '', 1);
INSERT INTO breed VALUES (86, 'Spitz Finlandés', '', '', 1);
INSERT INTO breed VALUES (87, 'Labrador Retriever de Pelo Liso', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Bulldog Francés', '', '', 1);
INSERT INTO breed VALUES (91, 'Pinscher Alemán', '', '', 1);
INSERT INTO breed VALUES (92, 'Pastor Alemán', '', '', 1);
INSERT INTO breed VALUES (93, 'Pointer Alemán de Pelo Corto', '', '', 1);
INSERT INTO breed VALUES (94, 'Pointer Alemán de Pelo Largo', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Irlandés', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Gran Danés', '', '', 1);
INSERT INTO breed VALUES (99, 'Perro de Montaña de los Pirineos', '', '', 1);
INSERT INTO breed VALUES (100, 'Gran Boyero Suizo', '', '', 1);
INSERT INTO breed VALUES (101, 'Galgo', '', '', 1);
INSERT INTO breed VALUES (102, 'Bichón Habanero', '', '', 1);
INSERT INTO breed VALUES (103, 'Sabueso', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Podenco Ibicenco', '', '', 1);
INSERT INTO breed VALUES (107, 'Illyrian Sheepdog', '', '', 1);
INSERT INTO breed VALUES (108, 'Setter Irlandés', '', '', 1);
INSERT INTO breed VALUES (109, 'Terrier Irlandés', '', '', 1);
INSERT INTO breed VALUES (110, 'Perro de Agua Irlandés', '', '', 1);
INSERT INTO breed VALUES (111, 'Lobero irlandés', '', '', 1);
INSERT INTO breed VALUES (112, 'Galgo Italiano', '', '', 1);
INSERT INTO breed VALUES (113, 'Spinone Italiano', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Chin Japonés', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo Coreano', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Japonés', '', '', 1);
INSERT INTO breed VALUES (118, 'Perro Oso de Carelia', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Terrier Kerry Blue', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Terrier Lakeland', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Lowchen', '', '', 1);
INSERT INTO breed VALUES (131, 'Bichón Maltés', '', '', 1);
INSERT INTO breed VALUES (132, 'Terrier Manchester', '', '', 1);
INSERT INTO breed VALUES (133, 'Pastor de Maremma', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Pinscher Miniatura', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Perro de Montaña', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (140, 'Mastín Napolitano', '', '', 1);
INSERT INTO breed VALUES (141, 'Perro Cantor de Nueva Guinea', '', '', 1);
INSERT INTO breed VALUES (142, 'Terranova', '', '', 1);
INSERT INTO breed VALUES (143, 'Terrier Norfolk', '', '', 1);
INSERT INTO breed VALUES (144, 'Terrier Noruego', '', '', 1);
INSERT INTO breed VALUES (145, 'Buhund Noruego', '', '', 1);
INSERT INTO breed VALUES (146, 'Cazador de Alces Noruego Gris', '', '', 1);
INSERT INTO breed VALUES (147, 'Lundehund Noruego', '', '', 1);
INSERT INTO breed VALUES (148, 'Retriever de Nueva Escocia', '', '', 1);
INSERT INTO breed VALUES (149, 'Viejo Pastor Inglés', '', '', 1);
INSERT INTO breed VALUES (150, 'Perro de Nutria', '', '', 1);
INSERT INTO breed VALUES (151, 'Epagneul Papillón', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier', '', '', 1);
INSERT INTO breed VALUES (153, 'Pequinés', '', '', 1);
INSERT INTO breed VALUES (154, 'Perro Sin Pelo del Perú', '', '', 1);
INSERT INTO breed VALUES (155, 'Pequeño Basset Grifón Vendeano', '', '', 1);
INSERT INTO breed VALUES (156, 'Perro del Faraón', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Podengo Portugués', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Pastor Polaco de la Llanura', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomerania', '', '', 1);
INSERT INTO breed VALUES (163, 'Caniche', '', '', 1);
INSERT INTO breed VALUES (164, 'Perro de Agua Portugués', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Carlino', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Ridgeback de Rodesia', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'San Bernardo', '', '', 1);
INSERT INTO breed VALUES (176, 'Samoyedo', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Lebrel Escocés', '', '', 1);
INSERT INTO breed VALUES (180, 'Terrier Escocés', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Pastor', '', '', 1);
INSERT INTO breed VALUES (185, 'Ovejero', '', '', 1);
INSERT INTO breed VALUES (186, 'Pastor de Shetland', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Husky Siberiano', '', '', 1);
INSERT INTO breed VALUES (190, 'Terrier Sedoso Australiano', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi o Galgo Árabe', '', '', 1);
INSERT INTO breed VALUES (193, 'Foxterrier de Pelo Corto', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bullterrier', '', '', 1);
INSERT INTO breed VALUES (197, 'Pastor de Rusia Meridional', '', '', 1);
INSERT INTO breed VALUES (198, 'Perro de los Visigodos', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Perro Tailandés', '', '', 1);
INSERT INTO breed VALUES (201, 'Mastín Tibetano', '', '', 1);
INSERT INTO breed VALUES (202, 'Spaniel Tibetano', '', '', 1);
INSERT INTO breed VALUES (203, 'Terrier Tibetano', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Sabueso Treeing Walker', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Braco de Weimar', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Terrier Galés', '', '', 1);
INSERT INTO breed VALUES (211, 'Springer Spaniel Galés', '', '', 1);
INSERT INTO breed VALUES (212, 'Terrier West Highland Blanco', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'Pastor Alemán Blanco', '', '', 1);
INSERT INTO breed VALUES (216, 'Grifón de Pelo Duro', '', '', 1);
INSERT INTO breed VALUES (217, 'Terrier de Pelo Duro', '', '', 1);
INSERT INTO breed VALUES (218, 'Labrador Retriever Amarillo', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier', '', '', 1);
INSERT INTO breed VALUES (220, 'Perro Pelon Mexicano - Xoloitzquintle', '', '', 1);
INSERT INTO breed VALUES (221, 'Abisinio', '', '', 2);
INSERT INTO breed VALUES (222, 'Curl Americano', '', '', 2);
INSERT INTO breed VALUES (223, 'Pelo Corto Americano', '', '', 2);
INSERT INTO breed VALUES (224, 'American Wirehair', '', '', 2);
INSERT INTO breed VALUES (225, 'Siamés tradicional', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinés', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengala', '', '', 2);
INSERT INTO breed VALUES (228, 'Sagrado de Birmania', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'British Shorthair', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmés', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Gato Galano', '', '', 2);
INSERT INTO breed VALUES (235, 'Sphynx - Gato Esfinge', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Persa Dilute Calico', '', '', 2);
INSERT INTO breed VALUES (242, 'Persa Dilute Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (243, 'Doméstico de pelo largo', '', '', 2);
INSERT INTO breed VALUES (252, 'Doméstico de pelo mediano', '', '', 2);
INSERT INTO breed VALUES (261, 'Doméstico de pelo corto', '', '', 2);
INSERT INTO breed VALUES (271, 'Mau Egipcio', '', '', 2);
INSERT INTO breed VALUES (272, 'Exótico de pelo corto', '', '', 2);
INSERT INTO breed VALUES (273, 'Gato Polidactilo', '', '', 2);
INSERT INTO breed VALUES (274, 'Habana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayo', '', '', 2);
INSERT INTO breed VALUES (276, 'Bobtail Japonés', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanés', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Bosque de Noruega', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Oriental de pelo largo', '', '', 2);
INSERT INTO breed VALUES (285, 'Oriental de pelo corto', '', '', 2);
INSERT INTO breed VALUES (286, 'Oriental Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'Persa', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Azul Ruso', '', '', 2);
INSERT INTO breed VALUES (292, 'Fold Escocés', '', '', 2);
INSERT INTO breed VALUES (293, 'Rex Selkirk', '', '', 2);
INSERT INTO breed VALUES (294, 'Siamés', '', '', 2);
INSERT INTO breed VALUES (295, 'Siberiano', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapur', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somalí', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphynx', '', '', 2);
INSERT INTO breed VALUES (300, 'Atigrado', '', '', 2);
INSERT INTO breed VALUES (307, 'Tigre', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonquinés', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (311, 'Angora Turco', '', '', 2);
INSERT INTO breed VALUES (312, 'Van Turco', '', '', 2);
INSERT INTO breed VALUES (313, 'Tuxedo', '', '', 2);
INSERT INTO breed VALUES (314, 'Americano', '', '', 7);
INSERT INTO breed VALUES (315, 'Conejo American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'Conejo American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Conejo Angora', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Holandés', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'Belier Inglés', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Habana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayo', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'Conejo de Nueva Zelanda', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polaco', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Plateado', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Canela', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Pura Sangre Árabe', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Burro/Mula', '', '', 26);
INSERT INTO breed VALUES (361, 'Borrador', '', '', 24);
INSERT INTO breed VALUES (362, 'Caballo de paso', '', '', 24);
INSERT INTO breed VALUES (363, 'Cruzado', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruano de Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Poni', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Hurón', '', '', 3);
INSERT INTO breed VALUES (381, 'Jerbo', '', '', 18);
INSERT INTO breed VALUES (382, 'Cobaya', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Erizo', '', '', 6);
INSERT INTO breed VALUES (385, 'Ratón', '', '', 4);
INSERT INTO breed VALUES (386, 'Perro de la Pradera', '', '', 5);
INSERT INTO breed VALUES (387, 'Rata', '', '', 5);
INSERT INTO breed VALUES (388, 'Mofeta', '', '', 5);
INSERT INTO breed VALUES (389, 'Petauro del Azúcar', '', '', 5);
INSERT INTO breed VALUES (390, 'Puerco Vietnamita', '', '', 28);
INSERT INTO breed VALUES (391, 'Puerco Vietnamita', '', '', 28);
INSERT INTO breed VALUES (392, 'Lagarto Gecko', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Lagarto', '', '', 13);
INSERT INTO breed VALUES (395, 'Culebra', '', '', 13);
INSERT INTO breed VALUES (396, 'Tortuga', '', '', 13);
INSERT INTO breed VALUES (397, 'Pez', '', '', 21);
INSERT INTO breed VALUES (398, 'Loro Gris Africano (Yaco)', '', '', 3);
INSERT INTO breed VALUES (399, 'Loro del Amazonas', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Periquito Australiano', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Canario', '', '', 3);
INSERT INTO breed VALUES (404, 'Pollo', '', '', 3);
INSERT INTO breed VALUES (405, 'Cockatiel', '', '', 3);
INSERT INTO breed VALUES (406, 'Cacatúa', '', '', 3);
INSERT INTO breed VALUES (407, 'Conuro', '', '', 3);
INSERT INTO breed VALUES (408, 'Paloma', '', '', 3);
INSERT INTO breed VALUES (409, 'Pato', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emú', '', '', 3);
INSERT INTO breed VALUES (412, 'Pinzón', '', '', 3);
INSERT INTO breed VALUES (413, 'Oca', '', '', 3);
INSERT INTO breed VALUES (414, 'Guineo', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lori', '', '', 3);
INSERT INTO breed VALUES (417, 'Agapornis', '', '', 3);
INSERT INTO breed VALUES (418, 'Loro del Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Avestruz', '', '', 3);
INSERT INTO breed VALUES (421, 'Perico', '', '', 3);
INSERT INTO breed VALUES (422, 'Loro', '', '', 3);
INSERT INTO breed VALUES (423, 'Periquito de Anteojos', '', '', 3);
INSERT INTO breed VALUES (424, 'Pavo Real', '', '', 3);
INSERT INTO breed VALUES (425, 'Faisán', '', '', 3);
INSERT INTO breed VALUES (426, 'Paloma', '', '', 3);
INSERT INTO breed VALUES (427, 'Loro de cabeza azul', '', '', 3);
INSERT INTO breed VALUES (428, 'Loro del Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Loro Quaker', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Periquito de collar', '', '', 3);
INSERT INTO breed VALUES (432, 'Periquito Oriental', '', '', 3);
INSERT INTO breed VALUES (433, 'Pico Blando (Otros)', '', '', 3);
INSERT INTO breed VALUES (434, 'Cisne', '', '', 3);
INSERT INTO breed VALUES (435, 'Tucán', '', '', 3);
INSERT INTO breed VALUES (436, 'Pavo', '', '', 3);
INSERT INTO breed VALUES (437, 'Vaca', '', '', 16);
INSERT INTO breed VALUES (438, 'Cabra', '', '', 16);
INSERT INTO breed VALUES (439, 'Oveja', '', '', 16);
INSERT INTO breed VALUES (440, 'Llama', '', '', 16);
INSERT INTO breed VALUES (441, 'Cerdo (Granja)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation';
INSERT INTO configuration VALUES ('Organisation', 'Organización');
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Animales sin microchip', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (37, 'Animales sin multimedia', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (38, 'Animales nunca vacunados', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (39, 'Animales no esterilizados de más de 6 meses', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (40, 'Gatos no diagnosticados con FIV/leucemia', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (41, 'Cifras mensuales de animales', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Cifras');
INSERT INTO customreport VALUES (42, 'Animales de estancia prolongada', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Cifras');
INSERT INTO customreport VALUES (43, 'Inventario del refugio', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventarios');
INSERT INTO customreport VALUES (44, 'Inventario detallado del refugio', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventarios');
INSERT INTO customreport VALUES (45, 'Animales no pertenecientes a una camada', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Camadas');
INSERT INTO customreport VALUES (46, 'Entradas/salidas', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimientos');
INSERT INTO customreport VALUES (47, 'Resumen de entradas/salidas', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimientos');
INSERT INTO customreport VALUES (48, 'Informe de entradas al refugio', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimientos');
INSERT INTO customreport VALUES (49, 'Volumen de adopciones por colaborador', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Colaboradores');
INSERT INTO customreport VALUES (50, 'Tiempo Medio con el Colaborador Antes de la Adopción', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Colaboradores');
INSERT INTO customreport VALUES (51, 'Inventario del colaborador', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Colaboradores');
INSERT INTO customreport VALUES (52, 'Informe de animales devueltos', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Devoluciones');
INSERT INTO customreport VALUES (53, 'Animales devueltos antes de 6 meses', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Devoluciones');
INSERT INTO customreport VALUES (54, 'Animales devueltos tras 6 meses', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Devoluciones');
INSERT INTO customreport VALUES (55, 'Nombre más común', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (56, 'Razones de la Muerte del Animal', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (57, 'Areas de Entrada Comunes de Animales', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (58, 'Areas de Adopción Comunes de Animales', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (59, 'Tiempo medio en la lista de espera', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (60, 'Donaciones mensuales', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos financieros');
INSERT INTO customreport VALUES (61, 'Donaciones mensuales por especie', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos financieros');
INSERT INTO customreport VALUES (62, 'Adopciones mensuales por especie', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de movimientos');
INSERT INTO customreport VALUES (63, 'Adopciones Mensuales Por Ubicación', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de movimientos');
INSERT INTO customreport VALUES (64, 'Razones de entrada de los animales', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de movimientos');
INSERT INTO customreport VALUES (65, 'Razones de Retorno de Animales', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de movimientos');
INSERT INTO customreport VALUES (66, 'Búsqueda de criterios por contacto', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventarios');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Muerto al llegar', '');
INSERT INTO deathreason VALUES (2, 'Muerto', '');
INSERT INTO deathreason VALUES (3, 'Saludable', '');
INSERT INTO deathreason VALUES (4, 'Enfermo/Herido', '');
INSERT INTO deathreason VALUES (5, 'Orden judicial', '');
INSERT INTO deathreason VALUES (6, 'Eutanasia', '');
INSERT INTO deathreason VALUES (7, 'Silvestre', '');
INSERT INTO deathreason VALUES (8, 'Mordedura', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Separación', '');
INSERT INTO entryreason VALUES (2, 'Alergias', '');
INSERT INTO entryreason VALUES (3, 'Mordedura', '');
INSERT INTO entryreason VALUES (4, 'No sociable', '');
INSERT INTO entryreason VALUES (5, 'Falta de espacio', '');
INSERT INTO entryreason VALUES (6, 'Muerto', '');
INSERT INTO entryreason VALUES (7, 'Callejero', '');
INSERT INTO entryreason VALUES (8, 'Enfermo/Herido', '');
INSERT INTO entryreason VALUES (9, 'Falta de medios', '');
INSERT INTO entryreason VALUES (10, 'Maltrato', '');
INSERT INTO entryreason VALUES (11, 'Abandonado', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Sin Ubicaciones', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Hembra');
INSERT INTO lksex VALUES (1, 'Macho');
INSERT INTO lksex VALUES (2, 'Desconocido');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Muy grande');
INSERT INTO lksize VALUES (1, 'Grande');
INSERT INTO lksize VALUES (2, 'Medio');
INSERT INTO lksize VALUES (3, 'Pequeño');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Corto');
INSERT INTO lkcoattype VALUES (1, 'Largo');
INSERT INTO lkcoattype VALUES (2, 'Áspero');
INSERT INTO lkcoattype VALUES (3, 'Rizado');
INSERT INTO lkcoattype VALUES (4, 'Mechones');
INSERT INTO lkcoattype VALUES (5, 'Sin pelo');
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Ninguno');
INSERT INTO lksmovementtype VALUES (1, 'Adopción');
INSERT INTO lksmovementtype VALUES (2, 'Acogida');
INSERT INTO lksmovementtype VALUES (3, 'Transferir');
INSERT INTO lksmovementtype VALUES (4, 'Huido');
INSERT INTO lksmovementtype VALUES (5, 'Reclamado');
INSERT INTO lksmovementtype VALUES (6, 'Robado');
INSERT INTO lksmovementtype VALUES (7, 'Reinsertado');
INSERT INTO lksmovementtype VALUES (8, 'Colaborador');
INSERT INTO lksmovementtype VALUES (9, 'Reserva');
INSERT INTO lksmovementtype VALUES (10, 'Reserva cancelada');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Animal');
INSERT INTO lksmedialink VALUES (1, 'Animal perdido');
INSERT INTO lksmedialink VALUES (2, 'Animal encontrado');
INSERT INTO lksmedialink VALUES (3, 'Contacto');
INSERT INTO lksmedialink VALUES (4, 'Movimiento');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Ninguno');
INSERT INTO lksdiarylink VALUES (1, 'Animal');
INSERT INTO lksdiarylink VALUES (2, 'Contacto');
INSERT INTO lksdiarylink VALUES (3, 'Animal perdido');
INSERT INTO lksdiarylink VALUES (4, 'Animal encontrado');
INSERT INTO lksdiarylink VALUES (5, 'Lista de espera');
INSERT INTO lksdiarylink VALUES (6, 'Movimiento');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Animal');
INSERT INTO lksfieldlink VALUES (1, 'Contacto');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Si/No');
INSERT INTO lksfieldtype VALUES (1, 'Texto');
INSERT INTO lksfieldtype VALUES (2, 'Notas');
INSERT INTO lksfieldtype VALUES (3, 'Número');
INSERT INTO lksfieldtype VALUES (4, 'Fecha');
INSERT INTO lksfieldtype VALUES (5, 'Dinero');
INSERT INTO lksfieldtype VALUES (6, 'Buscar');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Animal');
INSERT INTO lksloglink VALUES (1, 'Contacto');
INSERT INTO lksloglink VALUES (2, 'Animal perdido');
INSERT INTO lksloglink VALUES (3, 'Animal encontrado');
INSERT INTO lksloglink VALUES (4, 'Lista de espera');
INSERT INTO lksloglink VALUES (5, 'Movimiento');
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Urgente');
INSERT INTO lkurgency VALUES (2, 'Alta');
INSERT INTO lkurgency VALUES (3, 'Medio');
INSERT INTO lkurgency VALUES (4, 'Baja');
INSERT INTO lkurgency VALUES (5, 'Más bajo');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Mordedura', '');
INSERT INTO logtype VALUES (2, 'Denuncia', '');
INSERT INTO logtype VALUES (3, 'Historia', '');
INSERT INTO logtype VALUES (4, 'Peso', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Perro', '', '');
INSERT INTO species VALUES (2, 'Gato', '', '');
INSERT INTO species VALUES (3, 'Periquito', '', '');
INSERT INTO species VALUES (4, 'Ratón', '', '');
INSERT INTO species VALUES (5, 'Rata', '', '');
INSERT INTO species VALUES (6, 'Erizo', '', '');
INSERT INTO species VALUES (7, 'Conejo', '', '');
INSERT INTO species VALUES (8, 'Paloma', '', '');
INSERT INTO species VALUES (9, 'Hurón', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Culebra', '', '');
INSERT INTO species VALUES (12, 'Tortuga', '', '');
INSERT INTO species VALUES (13, 'Galapago', '', '');
INSERT INTO species VALUES (14, 'Pollo', '', '');
INSERT INTO species VALUES (15, 'Búho', '', '');
INSERT INTO species VALUES (16, 'Cabra', '', '');
INSERT INTO species VALUES (17, 'Oca', '', '');
INSERT INTO species VALUES (18, 'Jerbo', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'Cobaya', '', '');
INSERT INTO species VALUES (21, 'Pez', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Camello', '', '');
INSERT INTO species VALUES (24, 'Caballo', '', '');
INSERT INTO species VALUES (25, 'Poni', '', '');
INSERT INTO species VALUES (26, 'Burro', '', '');
INSERT INTO species VALUES (27, 'Llama', '', '');
INSERT INTO species VALUES (28, 'Pig', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Esterilización', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Vacuna periódica', '');
INSERT INTO vaccinationtype VALUES (2, 'Primera vacuna', '');
INSERT INTO vaccinationtype VALUES (3, 'Segunda vacuna', '');
INSERT INTO vaccinationtype VALUES (4, 'Rabia', '');
INSERT INTO vaccinationtype VALUES (5, 'Leucemia', '');
INSERT INTO vaccinationtype VALUES (6, 'Tos perrera', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirosis', '');
