DELETE FROM accounts;
INSERT INTO accounts VALUES (1, 'Receita::Doação', 'Doações recebidas (misc)', 5, 1, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (2, 'Receita::Adopção', 'Taxa de doações para adopção', 5, 2, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (3, 'Receitas::Lista de espera', 'Doações para a lista de espera', 5, 3, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (4, 'Receita::DoaçãoEntrada', 'Doações para animais que entram no canil', 5, 4, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (5, 'Receita::Patrocinio', 'Doações de patrocinadores', 5, 5, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (6, 'Receitas::Loja', 'Receitas da loja online', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (7, 'Receitas::Lucros', 'Juros bancários em conta', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (8, 'Receitas::BalançosAbertura', 'Opening balances', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (9, 'Banco::Actual', 'Conta corrente bancária', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (10, 'Banco::Depósito', 'Conta bancária de depósito', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (11, 'Banco::Poupanças', 'Conta poupança', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (12, 'Activo::Loja', 'Permissas', 8, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (13, 'Despesas::Telefone', 'Contas de telefone', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (14, 'Despesas::Electricidade', 'Contas de Electricidade', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (15, 'Despesas::Água', 'Contas da água', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (16, 'Despesas::Gás', 'Contas do Gás', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (17, 'Despesas::Correspondência', 'Despesas de correspondência', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (18, 'Despesas::Imóvel', 'Despesas do imóvel', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (19, 'Despesas::Comida', 'Custos com a alimentação dos animais', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'C (Cão)', NULL);
INSERT INTO animaltype VALUES (10, 'V (Cão vadio)', NULL);
INSERT INTO animaltype VALUES (11, 'I (Gato indesejado)', NULL);
INSERT INTO animaltype VALUES (12, 'V (Gato vadio)', NULL);
INSERT INTO animaltype VALUES (13, 'D (Diverso)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Animal não pertencente ao canil)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Preto', NULL);
INSERT INTO basecolour VALUES (2, 'Branco', NULL);
INSERT INTO basecolour VALUES (3, 'Preto e Branco', NULL);
INSERT INTO basecolour VALUES (4, 'Avermelhado', NULL);
INSERT INTO basecolour VALUES (5, 'Branco e preto', NULL);
INSERT INTO basecolour VALUES (6, 'Torti', NULL);
INSERT INTO basecolour VALUES (7, 'Listado', NULL);
INSERT INTO basecolour VALUES (8, 'Bronzeado', NULL);
INSERT INTO basecolour VALUES (9, 'Preto e amarelo', NULL);
INSERT INTO basecolour VALUES (10, 'Amarelo e Preto', NULL);
INSERT INTO basecolour VALUES (11, 'Castanho', NULL);
INSERT INTO basecolour VALUES (12, 'Castanho e preto', NULL);
INSERT INTO basecolour VALUES (13, 'Preto e castanho', NULL);
INSERT INTO basecolour VALUES (14, 'Malhado', NULL);
INSERT INTO basecolour VALUES (15, 'Preto com manchas', NULL);
INSERT INTO basecolour VALUES (16, 'Branco com manchas', NULL);
INSERT INTO basecolour VALUES (17, 'Preto com manchas', NULL);
INSERT INTO basecolour VALUES (18, 'Branco com manchas', NULL);
INSERT INTO basecolour VALUES (19, 'Tricolor', NULL);
INSERT INTO basecolour VALUES (20, 'Figado', NULL);
INSERT INTO basecolour VALUES (21, 'Fígado e Branco', NULL);
INSERT INTO basecolour VALUES (22, 'Branco e Fígado', NULL);
INSERT INTO basecolour VALUES (23, 'Creme', NULL);
INSERT INTO basecolour VALUES (24, 'Amarelo e branco', NULL);
INSERT INTO basecolour VALUES (26, 'Branco e amarelo', NULL);
INSERT INTO basecolour VALUES (27, 'Tartaruga e branco', NULL);
INSERT INTO basecolour VALUES (28, 'Listado e branco', NULL);
INSERT INTO basecolour VALUES (29, 'Avermelhado e branco', NULL);
INSERT INTO basecolour VALUES (30, 'Cinzento', NULL);
INSERT INTO basecolour VALUES (31, 'Cinzento e branco', NULL);
INSERT INTO basecolour VALUES (32, 'Branco e cinzento', NULL);
INSERT INTO basecolour VALUES (33, 'Branco e tartaruga', NULL);
INSERT INTO basecolour VALUES (35, 'Castanho e branco', NULL);
INSERT INTO basecolour VALUES (36, 'Azul', NULL);
INSERT INTO basecolour VALUES (37, 'Branco e listado', NULL);
INSERT INTO basecolour VALUES (38, 'Amarelo e cinzento', NULL);
INSERT INTO basecolour VALUES (39, 'Vários', NULL);
INSERT INTO basecolour VALUES (40, 'Branco e castanho', NULL);
INSERT INTO basecolour VALUES (41, 'Verde', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Afghan Hound', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Malamute do Alasca', '', '', 1);
INSERT INTO breed VALUES (7, 'Bulldog Americano', '', '', 1);
INSERT INTO breed VALUES (8, 'American Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (9, 'Staffordshire Terrier Americano', '', '', 1);
INSERT INTO breed VALUES (10, 'American Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolian Shepherd', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzell Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (13, 'Australian Cattle Dog/Blue Heeler', '', '', 1);
INSERT INTO breed VALUES (14, 'Australian Kelpie', '', '', 1);
INSERT INTO breed VALUES (15, 'Australian Shepherd', '', '', 1);
INSERT INTO breed VALUES (16, 'Australian Terrier', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgian Shepherd Dog Sheepdog', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgian Shepherd Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgian Shepherd Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgian Shepherd Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Bernese Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon Frise', '', '', 1);
INSERT INTO breed VALUES (29, 'Black and Tan Coonhound', '', '', 1);
INSERT INTO breed VALUES (30, 'Labrador Retriever Preto', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Cão de caça', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Borzoi', '', '', 1);
INSERT INTO breed VALUES (37, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (38, 'Bouvier des Flanders', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Brittany Spaniel', '', '', 1);
INSERT INTO breed VALUES (43, 'Brussels Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Canaan', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso Mastiff', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopardo', '', '', 1);
INSERT INTO breed VALUES (51, 'Cattle', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bay Retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chinês Crested', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinês Foo', '', '', 1);
INSERT INTO breed VALUES (57, 'Chocolate Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Dachshund', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmata', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Doberman Pinscher', '', '', 1);
INSERT INTO breed VALUES (70, 'Dogo Argentino', '', '', 1);
INSERT INTO breed VALUES (71, 'Dogue de Bordeaux', '', '', 1);
INSERT INTO breed VALUES (72, 'Shepherd Alemão', '', '', 1);
INSERT INTO breed VALUES (73, 'Bulldog Inglês', '', '', 1);
INSERT INTO breed VALUES (74, 'Cocker Spaniel Inglês', '', '', 1);
INSERT INTO breed VALUES (75, 'Inglês Coonhound', '', '', 1);
INSERT INTO breed VALUES (76, 'Pointer Inglês', '', '', 1);
INSERT INTO breed VALUES (77, 'Setter Inglês', '', '', 1);
INSERT INTO breed VALUES (78, 'Shepherd Inglês', '', '', 1);
INSERT INTO breed VALUES (79, 'Springer Spaniel Inglês', '', '', 1);
INSERT INTO breed VALUES (80, 'Toy Spaniel Inglês', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila Brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Finnish Lapphund', '', '', 1);
INSERT INTO breed VALUES (86, 'Copy text   \t Finnish Spitz', '', '', 1);
INSERT INTO breed VALUES (87, 'Retriever de Pêlo Curto', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Bulldog Francês', '', '', 1);
INSERT INTO breed VALUES (91, 'Pinscher Alemão', '', '', 1);
INSERT INTO breed VALUES (92, 'Shepherd Dog Alemão', '', '', 1);
INSERT INTO breed VALUES (93, 'Pointer de Pêlo Curto Alemão', '', '', 1);
INSERT INTO breed VALUES (94, 'Pointer de Pêlo Arame Alemão', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Great Dane', '', '', 1);
INSERT INTO breed VALUES (99, 'Great Pyrenees', '', '', 1);
INSERT INTO breed VALUES (100, 'Greater Swiss Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Havanese', '', '', 1);
INSERT INTO breed VALUES (103, 'Hound', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibizan Hound', '', '', 1);
INSERT INTO breed VALUES (107, 'Illyrian Sheepdog', '', '', 1);
INSERT INTO breed VALUES (108, 'Setter Irlandês', '', '', 1);
INSERT INTO breed VALUES (109, 'Terrier Irlandês', '', '', 1);
INSERT INTO breed VALUES (110, 'Spaniel de Água Irlandês', '', '', 1);
INSERT INTO breed VALUES (111, 'Wolfhound Irlandês', '', '', 1);
INSERT INTO breed VALUES (112, 'Greyhound Italiano', '', '', 1);
INSERT INTO breed VALUES (113, 'Spinone Italiano', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Chin Japonês', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Dog', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelian Bear Dog', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue Terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Löwchen', '', '', 1);
INSERT INTO breed VALUES (131, 'Maltês', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremma Sheepdog', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Pinscher Miniatura', '', '', 1);
INSERT INTO breed VALUES (137, 'Cur da Montanha', '', '', 1);
INSERT INTO breed VALUES (138, 'Cão da Montanha', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (140, 'Neapolitan Mastiff', '', '', 1);
INSERT INTO breed VALUES (141, 'Cão Cantante da Nova Guiné', '', '', 1);
INSERT INTO breed VALUES (142, 'Newfoundland Dog', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich Terrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Norwegian Buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Norwegian Elkhound', '', '', 1);
INSERT INTO breed VALUES (147, 'Lundehund Norueguês', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia Duck-Tolling Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Old English Sheepdog', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhound', '', '', 1);
INSERT INTO breed VALUES (151, 'Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier (Fell Terrier)', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekingese', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruvian Inca Orchid', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit Basset Griffon Vendeen', '', '', 1);
INSERT INTO breed VALUES (156, 'Pharaoh Hound', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Podengo Português', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Lowland Sheepdog Polaco', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Poodle', '', '', 1);
INSERT INTO breed VALUES (164, 'Cão D''Agua Português', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Pug', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Terrier Rato', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesian Ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'São Bernardo', '', '', 1);
INSERT INTO breed VALUES (176, 'Samoyed', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Deerhound Escocês', '', '', 1);
INSERT INTO breed VALUES (180, 'Terrier Scottie Escocês', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Cão de Ovelhas', '', '', 1);
INSERT INTO breed VALUES (185, 'Pastor', '', '', 1);
INSERT INTO breed VALUES (186, 'Shetland Cão de Ovelhas Sheltie', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Husky da Sibéria', '', '', 1);
INSERT INTO breed VALUES (190, 'Terrier Seda', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Smooth Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'Ovcharka do Sul da Rússia', '', '', 1);
INSERT INTO breed VALUES (198, 'Vallhund Sueco', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Mastiff Tibetano', '', '', 1);
INSERT INTO breed VALUES (202, 'Spaniel Tibetano', '', '', 1);
INSERT INTO breed VALUES (203, 'Terrier Tibetano', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimaraner', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier Westie', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'Shepherd Branco Alemão', '', '', 1);
INSERT INTO breed VALUES (216, 'Pointing Griffon Cabelo de Arame', '', '', 1);
INSERT INTO breed VALUES (217, 'Terrier Cabelo de Arame', '', '', 1);
INSERT INTO breed VALUES (218, 'Labrador Retriever Amarelo', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier Yorkie', '', '', 1);
INSERT INTO breed VALUES (220, 'Xoloitzcuintle/Mexican Hairless', '', '', 1);
INSERT INTO breed VALUES (221, 'Abyssinian', '', '', 2);
INSERT INTO breed VALUES (222, 'Encaracolado Americano', '', '', 2);
INSERT INTO breed VALUES (223, 'Pêlo Curto Americano', '', '', 2);
INSERT INTO breed VALUES (224, 'Pêlo de Arame Americano', '', '', 2);
INSERT INTO breed VALUES (225, 'Siamês Applehead', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinês', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengal', '', '', 2);
INSERT INTO breed VALUES (228, 'Birman', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'Pêlo Curto Inglês', '', '', 2);
INSERT INTO breed VALUES (232, 'Birmanês', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Calico', '', '', 2);
INSERT INTO breed VALUES (235, 'Sem Pêlo Canadiano', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Dilute Calico', '', '', 2);
INSERT INTO breed VALUES (242, 'Dilute Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (243, 'Pêlo Grande Doméstico', '', '', 2);
INSERT INTO breed VALUES (252, 'Pêlo Médio Doméstico', '', '', 2);
INSERT INTO breed VALUES (261, 'Pêlo Curto Doméstico', '', '', 2);
INSERT INTO breed VALUES (271, 'Mau Egípcio', '', '', 2);
INSERT INTO breed VALUES (272, 'Pêlo Curto Exótico', '', '', 2);
INSERT INTO breed VALUES (273, 'Extra-Toes Cat (Hemingway Polydactyl)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Bobtail Japonês', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanês', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manês', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Gato da Floresta Norueguês', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Pêlo Longo Oriental', '', '', 2);
INSERT INTO breed VALUES (285, 'Pêlo Curto Oriental', '', '', 2);
INSERT INTO breed VALUES (286, 'Tabby Oriental', '', '', 2);
INSERT INTO breed VALUES (287, 'Persa', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Azul Russo', '', '', 2);
INSERT INTO breed VALUES (292, 'Fold # Escocês', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siamês', '', '', 2);
INSERT INTO breed VALUES (295, 'Sibéria', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somálio', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphynx (hairless cat)', '', '', 2);
INSERT INTO breed VALUES (300, 'Listado', '', '', 2);
INSERT INTO breed VALUES (307, 'Tigre', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkinese', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (311, 'Angora Turco', '', '', 2);
INSERT INTO breed VALUES (312, 'Van Turco', '', '', 2);
INSERT INTO breed VALUES (313, 'Tuxedo', '', '', 2);
INSERT INTO breed VALUES (314, 'Americano', '', '', 7);
INSERT INTO breed VALUES (315, 'Fuzzy Lop Americano', '', '', 7);
INSERT INTO breed VALUES (316, 'Sable Americano', '', '', 7);
INSERT INTO breed VALUES (317, 'Coelho Angora', '', '', 7);
INSERT INTO breed VALUES (318, 'Hare Belga', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Petite Britânico', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Californiano', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Holandês', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'Lop Inglês', '', '', 7);
INSERT INTO breed VALUES (332, 'Spot Inglês', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Branco Flórida', '', '', 7);
INSERT INTO breed VALUES (335, 'Lop Francês', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Lop Holandês', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'Nova Zelândia', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polaco', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Prata', '', '', 7);
INSERT INTO breed VALUES (354, 'Fox Prata', '', '', 7);
INSERT INTO breed VALUES (355, 'Marten Prata', '', '', 7);
INSERT INTO breed VALUES (356, 'Bronzeado', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Árabe', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Mula/Burro', '', '', 26);
INSERT INTO breed VALUES (361, 'Rascunho', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Foxtrotter do Missouri', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Acomodações', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Walker do Tennessee', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Ferret', '', '', 3);
INSERT INTO breed VALUES (381, 'Gerbil', '', '', 18);
INSERT INTO breed VALUES (382, 'Porco da Guiné', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Hedgehog', '', '', 6);
INSERT INTO breed VALUES (385, 'Rato', '', '', 4);
INSERT INTO breed VALUES (386, 'Prairie Dog', '', '', 5);
INSERT INTO breed VALUES (387, 'Rato', '', '', 5);
INSERT INTO breed VALUES (388, 'Skunk', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (391, 'Pot Bellied Vietnamita', '', '', 28);
INSERT INTO breed VALUES (392, 'Gecko', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Lagarto', '', '', 13);
INSERT INTO breed VALUES (395, 'Cobra', '', '', 13);
INSERT INTO breed VALUES (396, 'Tartaruga', '', '', 13);
INSERT INTO breed VALUES (397, 'Peixe', '', '', 21);
INSERT INTO breed VALUES (398, 'Cinzento Africano', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazonas', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Budgie/Budgerigar', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Canario', '', '', 3);
INSERT INTO breed VALUES (404, 'Galinha', '', '', 3);
INSERT INTO breed VALUES (405, 'Cockatiel', '', '', 3);
INSERT INTO breed VALUES (406, 'Cockatoo', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Dove', '', '', 3);
INSERT INTO breed VALUES (409, 'Pato', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Finch', '', '', 3);
INSERT INTO breed VALUES (413, 'Goose', '', '', 3);
INSERT INTO breed VALUES (414, 'Guinea fowl', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lory/Lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Ostrich', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakeet (Other)', '', '', 3);
INSERT INTO breed VALUES (422, 'Parrot (Other)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Peacock/Pea fowl', '', '', 3);
INSERT INTO breed VALUES (425, 'Pheasant', '', '', 3);
INSERT INTO breed VALUES (426, 'Pigeon', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Swan', '', '', 3);
INSERT INTO breed VALUES (435, 'Toucan', '', '', 3);
INSERT INTO breed VALUES (436, 'Turquia', '', '', 3);
INSERT INTO breed VALUES (437, 'Vaca', '', '', 16);
INSERT INTO breed VALUES (438, 'Cabra', '', '', 16);
INSERT INTO breed VALUES (439, 'Ovelha', '', '', 16);
INSERT INTO breed VALUES (440, 'Lama', '', '', 16);
INSERT INTO breed VALUES (441, 'Porco', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%Name';
INSERT INTO configuration VALUES ('Organisation', 'Organização');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Bébé');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Jovem Adulto');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Adulto');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Mais velho');
DELETE FROM costtype;
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Animais sem Chip', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditar');
INSERT INTO customreport VALUES (37, 'Animais sem Foto', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditar');
INSERT INTO customreport VALUES (38, 'Animais nunca vacinaos', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditar');
INSERT INTO customreport VALUES (39, 'Animais não castrados com mais de 6 meses', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditar');
INSERT INTO customreport VALUES (40, 'Gatos sem teste combi', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditar');
INSERT INTO customreport VALUES (41, 'Figuras de animais mensais', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Imagens');
INSERT INTO customreport VALUES (42, 'Animais de longa data', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Imagens');
INSERT INTO customreport VALUES (43, 'Inventário do Canil', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventários');
INSERT INTO customreport VALUES (44, 'Inventário Detalhado do Canil', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventários');
INSERT INTO customreport VALUES (45, 'Animais sem serem de ninhadas', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Ninhadas');
INSERT INTO customreport VALUES (46, 'Entradas / Saídas', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimentos');
INSERT INTO customreport VALUES (47, 'Sumário de Entradas / Saídas', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimentos');
INSERT INTO customreport VALUES (48, 'Relatório de Entradas', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimentos');
INSERT INTO customreport VALUES (49, 'Volume de Adopções por Comerciante', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Comerciantes');
INSERT INTO customreport VALUES (50, 'Tempo médio no comerciante antes da adopção', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Comerciantes');
INSERT INTO customreport VALUES (51, 'Inventório do comerciante', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Comerciantes');
INSERT INTO customreport VALUES (52, 'Relatório de Animais Devolvidos', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Devoluções');
INSERT INTO customreport VALUES (53, 'Devoluções de Animais em menos de 6 meses', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Devoluções');
INSERT INTO customreport VALUES (54, 'Devoluções de Animais depois de 6 meses', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Devoluções');
INSERT INTO customreport VALUES (55, 'Nome mais comum', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estatísticas');
INSERT INTO customreport VALUES (56, 'Rasões da Morte do Animal', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estatísticas');
INSERT INTO customreport VALUES (57, 'Áreas mais comuns de entrada de animais', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estatísticas');
INSERT INTO customreport VALUES (58, 'Áreas mais comuns de adopção de animais', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estatísticas');
INSERT INTO customreport VALUES (59, 'Tempo médio na lista de espera', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estatísticas');
INSERT INTO customreport VALUES (60, 'Doações Mensais', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos Financeiros');
INSERT INTO customreport VALUES (61, 'Doações Mensais por Raça', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos Financeiros');
INSERT INTO customreport VALUES (62, 'Adopções Mensais por Raça', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de Movimentos');
INSERT INTO customreport VALUES (63, 'Adopções Mensais por Localização', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de Movimentos');
INSERT INTO customreport VALUES (64, 'Motivos da Entrada do Animal', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de Movimentos');
INSERT INTO customreport VALUES (65, 'Motivos da Devolução do Animal', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de Movimentos');
INSERT INTO customreport VALUES (66, 'Critério de correspondêcia de dono', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventários');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Vivos à chegada', '');
INSERT INTO deathreason VALUES (2, 'Morreu', '');
INSERT INTO deathreason VALUES (3, 'Saudável', '');
INSERT INTO deathreason VALUES (4, 'Doente / Ferido', '');
INSERT INTO deathreason VALUES (5, 'Pedido', '');
INSERT INTO deathreason VALUES (6, 'Abate', '');
INSERT INTO deathreason VALUES (7, 'Selvagem', '');
INSERT INTO deathreason VALUES (8, 'Mordedor', '');
DELETE FROM diet;
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Doação', '');
INSERT INTO donationtype VALUES (2, 'Taxa de Adopção', '');
INSERT INTO donationtype VALUES (3, 'Lista de Espera de Doações', '');
INSERT INTO donationtype VALUES (4, 'Doações de Entrada', '');
INSERT INTO donationtype VALUES (5, 'Fiança de animal', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Separação de casamento/relação', '');
INSERT INTO entryreason VALUES (2, 'Alergias', '');
INSERT INTO entryreason VALUES (3, 'Mordedor', '');
INSERT INTO entryreason VALUES (4, 'Incapaz de acasalar', '');
INSERT INTO entryreason VALUES (5, 'Acomodação Inadequada', '');
INSERT INTO entryreason VALUES (6, 'Morreu', '');
INSERT INTO entryreason VALUES (7, 'Vagueando', '');
INSERT INTO entryreason VALUES (8, 'Doente / Ferido', '');
INSERT INTO entryreason VALUES (9, 'Incapaz de pagar', '');
INSERT INTO entryreason VALUES (10, 'Abuso', '');
INSERT INTO entryreason VALUES (11, 'Abandonado', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Sem Localizações', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Femea');
INSERT INTO lksex VALUES (1, 'Macho');
INSERT INTO lksex VALUES (2, 'Desconhecido(a)');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Muito Grande');
INSERT INTO lksize VALUES (1, 'Grande');
INSERT INTO lksize VALUES (2, 'Médio');
INSERT INTO lksize VALUES (3, 'Pequeno');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Curto');
INSERT INTO lkcoattype VALUES (1, 'Longo');
INSERT INTO lkcoattype VALUES (2, 'Áspero');
INSERT INTO lkcoattype VALUES (3, '# Encaracolado');
INSERT INTO lkcoattype VALUES (4, 'Amarrado');
INSERT INTO lkcoattype VALUES (5, 'Sem pêlo');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Nenhum');
INSERT INTO lksmovementtype VALUES (1, 'Adopção');
INSERT INTO lksmovementtype VALUES (2, 'Adoptado');
INSERT INTO lksmovementtype VALUES (3, 'Transferência');
INSERT INTO lksmovementtype VALUES (4, 'Escapou');
INSERT INTO lksmovementtype VALUES (5, 'Reclamado');
INSERT INTO lksmovementtype VALUES (6, 'Roubado');
INSERT INTO lksmovementtype VALUES (7, 'Libertado para a natureza');
INSERT INTO lksmovementtype VALUES (8, 'Revendedor');
INSERT INTO lksmovementtype VALUES (9, 'Reserva');
INSERT INTO lksmovementtype VALUES (10, 'Reserva Cancelada');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Animal');
INSERT INTO lksmedialink VALUES (1, 'Animal Perdido');
INSERT INTO lksmedialink VALUES (2, 'Animal Encontrado');
INSERT INTO lksmedialink VALUES (3, 'Dono');
INSERT INTO lksmedialink VALUES (4, 'Movimento');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Nenhum');
INSERT INTO lksdiarylink VALUES (1, 'Animal');
INSERT INTO lksdiarylink VALUES (2, 'Dono');
INSERT INTO lksdiarylink VALUES (3, 'Animal Perdido');
INSERT INTO lksdiarylink VALUES (4, 'Animal Encontrado');
INSERT INTO lksdiarylink VALUES (5, 'Lista de Espera');
INSERT INTO lksdiarylink VALUES (6, 'Movimento');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'One-Off');
INSERT INTO lksdonationfreq VALUES (1, 'Semanal');
INSERT INTO lksdonationfreq VALUES (2, 'Mensal');
INSERT INTO lksdonationfreq VALUES (3, 'Trimestral');
INSERT INTO lksdonationfreq VALUES (4, 'Semestral');
INSERT INTO lksdonationfreq VALUES (5, 'Anual');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Animal');
INSERT INTO lksfieldlink VALUES (1, 'Dono');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Sim/Não');
INSERT INTO lksfieldtype VALUES (1, 'Texto');
INSERT INTO lksfieldtype VALUES (2, 'Notas');
INSERT INTO lksfieldtype VALUES (3, 'Número');
INSERT INTO lksfieldtype VALUES (4, 'Data');
INSERT INTO lksfieldtype VALUES (5, 'Dinheiro');
INSERT INTO lksfieldtype VALUES (6, 'Procura');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Animal');
INSERT INTO lksloglink VALUES (1, 'Dono');
INSERT INTO lksloglink VALUES (2, 'Animal Perdido');
INSERT INTO lksloglink VALUES (3, 'Animal Encontrado');
INSERT INTO lksloglink VALUES (4, 'Lista de Espera');
INSERT INTO lksloglink VALUES (5, 'Movimento');
DELETE FROM lksyesno;
DELETE FROM lksynun;
DELETE FROM lksposneg;
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Urgente');
INSERT INTO lkurgency VALUES (2, 'Alta');
INSERT INTO lkurgency VALUES (3, 'Médio');
INSERT INTO lkurgency VALUES (4, 'Baixa');
INSERT INTO lkurgency VALUES (5, 'Mais Baixa');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Dentada', '');
INSERT INTO logtype VALUES (2, 'Reclamação', '');
INSERT INTO logtype VALUES (3, 'Histórico', '');
INSERT INTO logtype VALUES (4, 'Peso', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Cão', '', '');
INSERT INTO species VALUES (2, 'Gato', '', '');
INSERT INTO species VALUES (3, 'Ave', '', '');
INSERT INTO species VALUES (4, 'Rato', '', '');
INSERT INTO species VALUES (5, 'Rato', '', '');
INSERT INTO species VALUES (6, 'Hedgehog', '', '');
INSERT INTO species VALUES (7, 'Coelho', '', '');
INSERT INTO species VALUES (8, 'Dove', '', '');
INSERT INTO species VALUES (9, 'Ferret', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Cobra', '', '');
INSERT INTO species VALUES (12, 'Tortoise', '', '');
INSERT INTO species VALUES (13, 'Terrapin', '', '');
INSERT INTO species VALUES (14, 'Galinha', '', '');
INSERT INTO species VALUES (15, 'Owl', '', '');
INSERT INTO species VALUES (16, 'Cabra', '', '');
INSERT INTO species VALUES (17, 'Goose', '', '');
INSERT INTO species VALUES (18, 'Gerbil', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'Porco da Guiné', '', '');
INSERT INTO species VALUES (21, 'Goldfish', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Camel', '', '');
INSERT INTO species VALUES (24, 'Cavalo', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Burro', '', '');
INSERT INTO species VALUES (27, 'Lama', '', '');
INSERT INTO species VALUES (28, 'Porco', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Castrar', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Vacinação Temporária', '');
INSERT INTO vaccinationtype VALUES (2, 'Primeira Vacina', '');
INSERT INTO vaccinationtype VALUES (3, 'Segunda Vacina', '');
INSERT INTO vaccinationtype VALUES (4, '# Intensificador', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukaemia', '');
INSERT INTO vaccinationtype VALUES (6, 'Kennel Cough', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirose', '');
