DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Dog)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Stray Dog)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Unwanted Cat)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Stray Cat)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Miscellaneous)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Non Shelter Animal)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Czarny', NULL);
INSERT INTO basecolour VALUES (2, 'Biały', NULL);
INSERT INTO basecolour VALUES (3, 'Czarny i biały', NULL);
INSERT INTO basecolour VALUES (4, 'Czerwony', NULL);
INSERT INTO basecolour VALUES (5, 'Biały i czarny', NULL);
INSERT INTO basecolour VALUES (6, 'Szylkret', NULL);
INSERT INTO basecolour VALUES (7, 'Tabby', NULL);
INSERT INTO basecolour VALUES (8, 'Rdzawobrązowy', NULL);
INSERT INTO basecolour VALUES (9, 'Czarny i rdzawobrązowy', NULL);
INSERT INTO basecolour VALUES (10, 'Rdzawobrązowy i czarny', NULL);
INSERT INTO basecolour VALUES (11, 'Brązowy', NULL);
INSERT INTO basecolour VALUES (12, 'Brązowy i czarny', NULL);
INSERT INTO basecolour VALUES (13, 'Czarny i brązowy', NULL);
INSERT INTO basecolour VALUES (14, 'Pręgowany', NULL);
INSERT INTO basecolour VALUES (15, 'Pręgowany i czarny', NULL);
INSERT INTO basecolour VALUES (16, 'Pręgowany i biały', NULL);
INSERT INTO basecolour VALUES (17, 'Czarny i pręgowany', NULL);
INSERT INTO basecolour VALUES (18, 'Biały i pręgowany', NULL);
INSERT INTO basecolour VALUES (19, 'Trikolor', NULL);
INSERT INTO basecolour VALUES (20, 'Wątrobiany', NULL);
INSERT INTO basecolour VALUES (21, 'Wątrobiany i biały', NULL);
INSERT INTO basecolour VALUES (22, 'Biały i wątrobiany', NULL);
INSERT INTO basecolour VALUES (23, 'Kremowy', NULL);
INSERT INTO basecolour VALUES (24, 'Rdzawobrązowy i biały', NULL);
INSERT INTO basecolour VALUES (26, 'Biały i rdzawobrązowy', NULL);
INSERT INTO basecolour VALUES (27, 'Szylkret i biały', NULL);
INSERT INTO basecolour VALUES (28, 'Tabby i biały', NULL);
INSERT INTO basecolour VALUES (29, 'Czerwony i biały', NULL);
INSERT INTO basecolour VALUES (30, 'Szary', NULL);
INSERT INTO basecolour VALUES (31, 'Szary i biały', NULL);
INSERT INTO basecolour VALUES (32, 'Biały i szary', NULL);
INSERT INTO basecolour VALUES (33, 'Biały i szylkret', NULL);
INSERT INTO basecolour VALUES (35, 'Brązowy i biały', NULL);
INSERT INTO basecolour VALUES (36, 'Niebieski', NULL);
INSERT INTO basecolour VALUES (37, 'Biały i tabby', NULL);
INSERT INTO basecolour VALUES (38, 'Żółty i szary', NULL);
INSERT INTO basecolour VALUES (39, 'Różni', NULL);
INSERT INTO basecolour VALUES (40, 'Biały i brązowy', NULL);
INSERT INTO basecolour VALUES (41, 'Zielony', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Pinczer małpi/Affenpinczer', '', '', 1);
INSERT INTO breed VALUES (2, 'Chart afgański', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Alaskan Malamute', '', '', 1);
INSERT INTO breed VALUES (7, 'Buldog amerykański', '', '', 1);
INSERT INTO breed VALUES (8, 'Amerykański pies eskimoski', '', '', 1);
INSERT INTO breed VALUES (9, 'Amerykański Staffordshire Terrier', '', '', 1);
INSERT INTO breed VALUES (10, 'Amerykański spaniel dowodny', '', '', 1);
INSERT INTO breed VALUES (11, 'Owczarek anatolijski', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzeller', '', '', 1);
INSERT INTO breed VALUES (13, 'Australijski pies pasterski', '', '', 1);
INSERT INTO breed VALUES (14, 'Kelpie australijski', '', '', 1);
INSERT INTO breed VALUES (15, 'Owczarek australijski', '', '', 1);
INSERT INTO breed VALUES (16, 'Terier australijski', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Owczarek belgijski', '', '', 1);
INSERT INTO breed VALUES (24, 'Owczarek belgijski Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Owczarek belgijski Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Owczarek belgijski Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Berneński pies pasterski', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon Frise', '', '', 1);
INSERT INTO breed VALUES (29, 'Czarny i Brązowy Coonhound', '', '', 1);
INSERT INTO breed VALUES (30, 'Czarny labrador retriever', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Bloodhound', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Chart rosyjski borzoj', '', '', 1);
INSERT INTO breed VALUES (37, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (38, 'Bouvier des Flanders', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Bokser', '', '', 1);
INSERT INTO breed VALUES (41, 'Owczarek francuski Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Еpagneul bretoński', '', '', 1);
INSERT INTO breed VALUES (43, 'Gryfonik brukselski', '', '', 1);
INSERT INTO breed VALUES (44, 'Bulterier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Canaan Dog', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso', '', '', 1);
INSERT INTO breed VALUES (49, 'Pies z Karoliny', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Zaganiający pies', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bay Retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chiński grzywacz', '', '', 1);
INSERT INTO breed VALUES (56, 'Chiński foo dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Czekolada labrador retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Jamnik', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatyńczyk', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Doberman', '', '', 1);
INSERT INTO breed VALUES (70, 'Dog argentyński', '', '', 1);
INSERT INTO breed VALUES (71, 'Dogue de Bordeaux', '', '', 1);
INSERT INTO breed VALUES (72, 'Owczarek holenderski', '', '', 1);
INSERT INTO breed VALUES (73, 'Buldog angielski', '', '', 1);
INSERT INTO breed VALUES (74, 'Cocker spaniel angielski', '', '', 1);
INSERT INTO breed VALUES (75, 'Angielski coonhound', '', '', 1);
INSERT INTO breed VALUES (76, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'Seter angielski', '', '', 1);
INSERT INTO breed VALUES (78, 'Owczarek angielski', '', '', 1);
INSERT INTO breed VALUES (79, 'Springer spaniel angielski', '', '', 1);
INSERT INTO breed VALUES (80, 'King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher', '', '', 1);
INSERT INTO breed VALUES (82, 'Pies eskimoski', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Mastiff brazylijski', '', '', 1);
INSERT INTO breed VALUES (85, 'Suomenlapinkoira', '', '', 1);
INSERT INTO breed VALUES (86, 'Szpic fiński', '', '', 1);
INSERT INTO breed VALUES (87, 'Flat-coated Retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Foksterier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Buldog francuski', '', '', 1);
INSERT INTO breed VALUES (91, 'Pinczer niemiecki', '', '', 1);
INSERT INTO breed VALUES (92, 'Owczarek niemiecki', '', '', 1);
INSERT INTO breed VALUES (93, 'Wyżeł niemiecki krótkowłosy', '', '', 1);
INSERT INTO breed VALUES (94, 'Wyżeł niemiecki szorstkowłosy', '', '', 1);
INSERT INTO breed VALUES (95, 'Irish Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Seter szkocki/Gordon', '', '', 1);
INSERT INTO breed VALUES (98, 'Dog niemiecki', '', '', 1);
INSERT INTO breed VALUES (99, 'Pirenejski pies górski', '', '', 1);
INSERT INTO breed VALUES (100, 'Duży szwajcarski pies pasterski', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Hawańczyk', '', '', 1);
INSERT INTO breed VALUES (103, 'Chart', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Podenco z Ibizy', '', '', 1);
INSERT INTO breed VALUES (107, 'Szarplaninac', '', '', 1);
INSERT INTO breed VALUES (108, 'Seter irlandzki', '', '', 1);
INSERT INTO breed VALUES (109, 'Terier irlandzki', '', '', 1);
INSERT INTO breed VALUES (110, 'Irlandzki spaniel dowodny', '', '', 1);
INSERT INTO breed VALUES (111, 'Wilczarz irlandzki', '', '', 1);
INSERT INTO breed VALUES (112, 'Charcik włoski', '', '', 1);
INSERT INTO breed VALUES (113, 'Wyżeł włoski szorstkowłosy', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Chin japoński', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Inu', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelski pies na niedżwiedzie', '', '', 1);
INSERT INTO breed VALUES (119, 'Szpic wilczy niemiecki/Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue Terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Lwi piesek', '', '', 1);
INSERT INTO breed VALUES (131, 'Maltańczyk', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremmano-Abruzzese', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastif', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Pinczer miniaturowy', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Pies górski', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (140, 'Mastif napolitański', '', '', 1);
INSERT INTO breed VALUES (141, 'Śpiewający pies z Nowej Gwinei', '', '', 1);
INSERT INTO breed VALUES (142, 'Nowofundland', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich Terrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Norsk Buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Elkhund', '', '', 1);
INSERT INTO breed VALUES (147, 'Norsk Lundehund', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia Duck-Tolling Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Owczarek staroangielski/Bobtail', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhound', '', '', 1);
INSERT INTO breed VALUES (151, 'Spaniel kontynentalny miniaturowy/Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier (Fell Terrier)', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekińczyk', '', '', 1);
INSERT INTO breed VALUES (154, 'Nagi pies peruwiański', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit Basset Griffon Vendeen', '', '', 1);
INSERT INTO breed VALUES (156, 'Pies Faraona', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Podengo portugalski', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polski owczarek nizinny', '', '', 1);
INSERT INTO breed VALUES (162, 'Szpic miniaturowy/Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Pudel', '', '', 1);
INSERT INTO breed VALUES (164, 'Portugalski pies dowodny', '', '', 1);
INSERT INTO breed VALUES (165, 'Pies kanaryjski', '', '', 1);
INSERT INTO breed VALUES (166, 'Mops', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesian Ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Chart perski/Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'Bernardyn', '', '', 1);
INSERT INTO breed VALUES (176, 'Samoyed', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Sznaucer', '', '', 1);
INSERT INTO breed VALUES (179, 'Chart szkocki', '', '', 1);
INSERT INTO breed VALUES (180, 'Terier szkocki', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Seter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Owczarek', '', '', 1);
INSERT INTO breed VALUES (185, 'Pies pasterski', '', '', 1);
INSERT INTO breed VALUES (186, 'Owczarek szetlandzki/Sheltie', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Husky syberyjski', '', '', 1);
INSERT INTO breed VALUES (190, 'Australian Silky Terrier', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Chart arabski/Slougi', '', '', 1);
INSERT INTO breed VALUES (193, 'Foksterier krótkowłosy', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Szpic', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'Owczarek południoworosyjski/Jużak', '', '', 1);
INSERT INTO breed VALUES (198, 'Västgötaspets', '', '', 1);
INSERT INTO breed VALUES (199, 'Terier', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Mastif tybetański', '', '', 1);
INSERT INTO breed VALUES (202, 'Spaniel tybetański', '', '', 1);
INSERT INTO breed VALUES (203, 'Terier tybetański', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Wyżeł węgierski', '', '', 1);
INSERT INTO breed VALUES (208, 'Wyżeł weimarski', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Terier walijski', '', '', 1);
INSERT INTO breed VALUES (211, 'Springer spaniel walijski', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier', '', '', 1);
INSERT INTO breed VALUES (213, 'Irish Soft Coated Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'Biały owczarek szwajcarski', '', '', 1);
INSERT INTO breed VALUES (216, 'Gończy francuski szorstkowłosy', '', '', 1);
INSERT INTO breed VALUES (217, 'Szorstkowłosy terier', '', '', 1);
INSERT INTO breed VALUES (218, 'Żółty Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier', '', '', 1);
INSERT INTO breed VALUES (220, 'Nagi pies meksykański', '', '', 1);
INSERT INTO breed VALUES (221, 'Abisyński', '', '', 2);
INSERT INTO breed VALUES (222, 'Amerykański Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'Amerykański krótkowłosy', '', '', 2);
INSERT INTO breed VALUES (224, 'Amerykański szorstkowłosy', '', '', 2);
INSERT INTO breed VALUES (225, 'Syjamski tradycyjny (applehead)', '', '', 2);
INSERT INTO breed VALUES (226, 'Balijski', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengalski', '', '', 2);
INSERT INTO breed VALUES (228, 'Birmański', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombajski', '', '', 2);
INSERT INTO breed VALUES (231, 'Brytyjski krótkowłosy', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmański', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Tricolor', '', '', 2);
INSERT INTO breed VALUES (235, 'Kanadskij sfinks', '', '', 2);
INSERT INTO breed VALUES (236, 'Kartuzki', '', '', 2);
INSERT INTO breed VALUES (237, 'Szynszyla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Tricolor rozjaśniony', '', '', 2);
INSERT INTO breed VALUES (242, 'Szylkret rozjaśniony', '', '', 2);
INSERT INTO breed VALUES (243, 'Kot domowy długowłosy', '', '', 2);
INSERT INTO breed VALUES (252, 'Kot domowy półdługi włos', '', '', 2);
INSERT INTO breed VALUES (261, 'Kot domowy krótkowłosy', '', '', 2);
INSERT INTO breed VALUES (271, 'Egipski Mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Egzotyczny krótkowłosy', '', '', 2);
INSERT INTO breed VALUES (273, 'Hemingway Polydactyl', '', '', 2);
INSERT INTO breed VALUES (274, 'Hawański', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalajski', '', '', 2);
INSERT INTO breed VALUES (276, 'Japoński bobtail', '', '', 2);
INSERT INTO breed VALUES (277, 'Jawajski', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Norweski Leśny', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Orientalny długowłosy', '', '', 2);
INSERT INTO breed VALUES (285, 'Orientalny krótkowłosy', '', '', 2);
INSERT INTO breed VALUES (286, 'Orientalny tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'Perski', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Rosyjski niebieski', '', '', 2);
INSERT INTO breed VALUES (292, 'Szkocki Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Syjamski', '', '', 2);
INSERT INTO breed VALUES (295, 'Syberyjski', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapurski', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somalijski', '', '', 2);
INSERT INTO breed VALUES (299, 'Sfinks (nagi kot)', '', '', 2);
INSERT INTO breed VALUES (300, 'Tabby', '', '', 2);
INSERT INTO breed VALUES (307, 'Tygrys', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkijski', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Szylkret', '', '', 2);
INSERT INTO breed VALUES (311, 'Turecka Angora', '', '', 2);
INSERT INTO breed VALUES (312, 'Turecki Van', '', '', 2);
INSERT INTO breed VALUES (313, 'Smoking (Tuxedo)', '', '', 2);
INSERT INTO breed VALUES (314, 'American', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angora Rabbit', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Królik', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Szynszyla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Holenderski', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Hawański', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalajski', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polish', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silver', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Rdzawobrązowy', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabian', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Donkey/Mule', '', '', 26);
INSERT INTO breed VALUES (361, 'Draft', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Szynszyla', '', '', 10);
INSERT INTO breed VALUES (380, 'Fretka', '', '', 3);
INSERT INTO breed VALUES (381, 'Myszoskoczek', '', '', 18);
INSERT INTO breed VALUES (382, 'Świnka morska', '', '', 20);
INSERT INTO breed VALUES (383, 'Chomik', '', '', 22);
INSERT INTO breed VALUES (384, 'Hedgehog', '', '', 6);
INSERT INTO breed VALUES (385, 'Mysz', '', '', 4);
INSERT INTO breed VALUES (386, 'Prairie Dog', '', '', 5);
INSERT INTO breed VALUES (387, 'Szczur', '', '', 5);
INSERT INTO breed VALUES (388, 'Skunk', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (391, 'Vietnamese Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (392, 'Gekon', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Jaszczurka', '', '', 13);
INSERT INTO breed VALUES (395, 'Wąż', '', '', 13);
INSERT INTO breed VALUES (396, 'Żółw', '', '', 13);
INSERT INTO breed VALUES (397, 'Ryba', '', '', 21);
INSERT INTO breed VALUES (398, 'African Grey', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazonka', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Papużka falista', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Kanarek', '', '', 3);
INSERT INTO breed VALUES (404, 'Chicken', '', '', 3);
INSERT INTO breed VALUES (405, 'Cockatiel', '', '', 3);
INSERT INTO breed VALUES (406, 'Cockatoo', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Dove', '', '', 3);
INSERT INTO breed VALUES (409, 'Duck', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Finch', '', '', 3);
INSERT INTO breed VALUES (413, 'Gęś', '', '', 3);
INSERT INTO breed VALUES (414, 'Guinea fowl', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lory/Lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Ostrich', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakeet (Other)', '', '', 3);
INSERT INTO breed VALUES (422, 'Parrot (Other)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Peacock/Pea fowl', '', '', 3);
INSERT INTO breed VALUES (425, 'Pheasant', '', '', 3);
INSERT INTO breed VALUES (426, 'Pigeon', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Swan', '', '', 3);
INSERT INTO breed VALUES (435, 'Toucan', '', '', 3);
INSERT INTO breed VALUES (436, 'Turkey', '', '', 3);
INSERT INTO breed VALUES (437, 'Krowa', '', '', 16);
INSERT INTO breed VALUES (438, 'Koza', '', '', 16);
INSERT INTO breed VALUES (439, 'Owca', '', '', 16);
INSERT INTO breed VALUES (440, 'Llama', '', '', 16);
INSERT INTO breed VALUES (441, 'Pig (Farm)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%';
INSERT INTO configuration VALUES ('Organisation', 'Organizacja');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Baby');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Young Adult');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Dorosły');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Senior');
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Non-Microchipped Animals', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (37, 'Animals Without Photo Media', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (38, 'Animals Never Vaccinated', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (39, 'Non-Neutered/Spayed Animals Aged Over 6 Months', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (40, 'Cats Not Combi-Tested', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (41, 'Monthly Animal Figures', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (42, 'Long Term Animals', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (43, 'Shelter Inventory', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (44, 'Detailed Shelter Inventory', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (45, 'Animals Not Part Of A Litter', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Litters');
INSERT INTO customreport VALUES (46, 'In/Out', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (47, 'In/Out Summary', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (48, 'Transfer In Report', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (49, 'Volume Of Adoptions Per Retailer', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (50, 'Average Time At Retailer Before Adoption', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (51, 'Retailer Inventory', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (52, 'Returned Animals Report', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (53, 'Animals Returned Within 6 Months', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (54, 'Animals Returned After 6 Months', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (55, 'Most Common Name', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (56, 'Animal Death Reasons', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (57, 'Most Common Animal Entry Areas', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (58, 'Most Common Animal Adoption Areas', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (59, 'Average Time On Waiting List', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (60, 'Monthly Donations', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Financial Graphs');
INSERT INTO customreport VALUES (61, 'Monthly Donations By Species', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Financial Graphs');
INSERT INTO customreport VALUES (62, 'Monthly Adoptions By Species', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (63, 'Monthly Adoptions By Location', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (64, 'Animal Entry Reasons', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (65, 'Animal Return Reasons', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (66, 'Owner Criteria Matching', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Dead On Arrival', '');
INSERT INTO deathreason VALUES (2, 'Zgon', '');
INSERT INTO deathreason VALUES (3, 'Healthy', '');
INSERT INTO deathreason VALUES (4, 'Sick/Injured', '');
INSERT INTO deathreason VALUES (5, 'Requested', '');
INSERT INTO deathreason VALUES (6, 'Culling', '');
INSERT INTO deathreason VALUES (7, 'Feral', '');
INSERT INTO deathreason VALUES (8, 'Biting', '');
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Donation', '');
INSERT INTO donationtype VALUES (2, 'Adoption Fee', '');
INSERT INTO donationtype VALUES (3, 'Waiting List Donation', '');
INSERT INTO donationtype VALUES (4, 'Entry Donation', '');
INSERT INTO donationtype VALUES (5, 'Animal Sponsorship', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Marriage/Relationship split', '');
INSERT INTO entryreason VALUES (2, 'Allergies', '');
INSERT INTO entryreason VALUES (3, 'Biting', '');
INSERT INTO entryreason VALUES (4, 'Unable to Cope', '');
INSERT INTO entryreason VALUES (5, 'Unsuitable Accomodation', '');
INSERT INTO entryreason VALUES (6, 'Zgon', '');
INSERT INTO entryreason VALUES (7, 'Stray', '');
INSERT INTO entryreason VALUES (8, 'Sick/Injured', '');
INSERT INTO entryreason VALUES (9, 'Unable to Afford', '');
INSERT INTO entryreason VALUES (10, 'Abuse', '');
INSERT INTO entryreason VALUES (11, 'Abandoned', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'No Locations', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Samica');
INSERT INTO lksex VALUES (1, 'Samiec');
INSERT INTO lksex VALUES (2, 'Nieznany/a');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Bardzo duży');
INSERT INTO lksize VALUES (1, 'Duży');
INSERT INTO lksize VALUES (2, 'Średni');
INSERT INTO lksize VALUES (3, 'Mały');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Krótka');
INSERT INTO lkcoattype VALUES (1, 'Długa');
INSERT INTO lkcoattype VALUES (2, 'Szorstka');
INSERT INTO lkcoattype VALUES (3, 'Kręcona');
INSERT INTO lkcoattype VALUES (4, 'Filcowata');
INSERT INTO lkcoattype VALUES (5, 'Nagi');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Brak');
INSERT INTO lksmovementtype VALUES (1, 'Adoption');
INSERT INTO lksmovementtype VALUES (2, 'Foster');
INSERT INTO lksmovementtype VALUES (3, 'Transfer');
INSERT INTO lksmovementtype VALUES (4, 'Uciekł/a');
INSERT INTO lksmovementtype VALUES (5, 'Reclaimed');
INSERT INTO lksmovementtype VALUES (6, 'Skradzione');
INSERT INTO lksmovementtype VALUES (7, 'Released To Wild');
INSERT INTO lksmovementtype VALUES (8, 'Sprzedawca');
INSERT INTO lksmovementtype VALUES (9, 'Reservation');
INSERT INTO lksmovementtype VALUES (10, 'Cancelled Reservation');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Zwierzę');
INSERT INTO lksmedialink VALUES (1, 'Lost Animal');
INSERT INTO lksmedialink VALUES (2, 'Found Animal');
INSERT INTO lksmedialink VALUES (3, 'Owner');
INSERT INTO lksmedialink VALUES (4, 'Movement');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Brak');
INSERT INTO lksdiarylink VALUES (1, 'Zwierzę');
INSERT INTO lksdiarylink VALUES (2, 'Owner');
INSERT INTO lksdiarylink VALUES (3, 'Lost Animal');
INSERT INTO lksdiarylink VALUES (4, 'Found Animal');
INSERT INTO lksdiarylink VALUES (5, 'Waiting List');
INSERT INTO lksdiarylink VALUES (6, 'Movement');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'One-Off');
INSERT INTO lksdonationfreq VALUES (1, 'Weekly');
INSERT INTO lksdonationfreq VALUES (2, 'Monthly');
INSERT INTO lksdonationfreq VALUES (3, 'Quarterly');
INSERT INTO lksdonationfreq VALUES (4, 'Half-Yearly');
INSERT INTO lksdonationfreq VALUES (5, 'Annually');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Zwierzę');
INSERT INTO lksfieldlink VALUES (1, 'Owner');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Tak/Nie');
INSERT INTO lksfieldtype VALUES (1, 'Tekst');
INSERT INTO lksfieldtype VALUES (2, 'Notes');
INSERT INTO lksfieldtype VALUES (3, 'Numer');
INSERT INTO lksfieldtype VALUES (4, 'Data');
INSERT INTO lksfieldtype VALUES (5, 'Money');
INSERT INTO lksfieldtype VALUES (6, 'Lookup');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Zwierzę');
INSERT INTO lksloglink VALUES (1, 'Owner');
INSERT INTO lksloglink VALUES (2, 'Lost Animal');
INSERT INTO lksloglink VALUES (3, 'Found Animal');
INSERT INTO lksloglink VALUES (4, 'Waiting List');
INSERT INTO lksloglink VALUES (5, 'Movement');
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Urgent');
INSERT INTO lkurgency VALUES (2, 'High');
INSERT INTO lkurgency VALUES (3, 'Średni');
INSERT INTO lkurgency VALUES (4, 'Low');
INSERT INTO lkurgency VALUES (5, 'Lowest');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Bite', '');
INSERT INTO logtype VALUES (2, 'Complaint', '');
INSERT INTO logtype VALUES (3, 'Historia', '');
INSERT INTO logtype VALUES (4, 'Waga', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Dog', '', '');
INSERT INTO species VALUES (2, 'Cat', '', '');
INSERT INTO species VALUES (3, 'Ptak', '', '');
INSERT INTO species VALUES (4, 'Mysz', '', '');
INSERT INTO species VALUES (5, 'Szczur', '', '');
INSERT INTO species VALUES (6, 'Hedgehog', '', '');
INSERT INTO species VALUES (7, 'Królik', '', '');
INSERT INTO species VALUES (8, 'Dove', '', '');
INSERT INTO species VALUES (9, 'Fretka', '', '');
INSERT INTO species VALUES (10, 'Szynszyla', '', '');
INSERT INTO species VALUES (11, 'Wąż', '', '');
INSERT INTO species VALUES (12, 'Tortoise', '', '');
INSERT INTO species VALUES (13, 'Terrapin', '', '');
INSERT INTO species VALUES (14, 'Chicken', '', '');
INSERT INTO species VALUES (15, 'Owl', '', '');
INSERT INTO species VALUES (16, 'Koza', '', '');
INSERT INTO species VALUES (17, 'Gęś', '', '');
INSERT INTO species VALUES (18, 'Myszoskoczek', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'Świnka morska', '', '');
INSERT INTO species VALUES (21, 'Goldfish', '', '');
INSERT INTO species VALUES (22, 'Chomik', '', '');
INSERT INTO species VALUES (23, 'Camel', '', '');
INSERT INTO species VALUES (24, 'Koń', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Donkey', '', '');
INSERT INTO species VALUES (27, 'Llama', '', '');
INSERT INTO species VALUES (28, 'Świnia', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Neuter/Spay', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Temporary Vaccination', '');
INSERT INTO vaccinationtype VALUES (2, 'First Vaccination', '');
INSERT INTO vaccinationtype VALUES (3, 'Second Vaccination', '');
INSERT INTO vaccinationtype VALUES (4, 'Booster', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukaemia', '');
INSERT INTO vaccinationtype VALUES (6, 'Kennel Cough', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirus', '');
