DELETE FROM accounts;
INSERT INTO accounts VALUES (1, 'Income::Donation', 'Incoming donations (misc)', 5, 1, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (2, 'Income::Adoption', 'Adoption fee donations', 5, 2, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (3, 'Income::WaitingList', 'Waiting list donations', 5, 3, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (4, 'Income::EntryDonation', 'Donations for animals entering the shelter', 5, 4, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (5, 'Income::Sponsorship', 'Sponsorship donations', 5, 5, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (6, 'Income::Shop', 'Income from an on-site shop', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (7, 'Income::Interest', 'Bank account interest', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (8, 'Income::OpeningBalances', 'Opening balances', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (9, 'Bank::Current', 'Bank current account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (10, 'Bank::Deposit', 'Bank deposit account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (11, 'Bank::Savings', 'Bank savings account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (12, 'Asset::Premises', 'Premises', 8, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (13, 'Expenses::Phone', 'Telephone Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (14, 'Expenses::Electricity', 'Electricity Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (15, 'Expenses::Water', 'Water Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (16, 'Expenses::Gas', 'Gas Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (17, 'Expenses::Postage', 'Postage costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (18, 'Expenses::Stationary', 'Stationary costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (19, 'Expenses::Food', 'Animal food costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Chien)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Chien errant)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Chat indésirable)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Chat errant)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Divers)', NULL);
INSERT INTO animaltype VALUES (40, 'N (animal extra-refuge)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Noir', NULL);
INSERT INTO basecolour VALUES (2, 'Blanc', NULL);
INSERT INTO basecolour VALUES (3, 'Noir et blanc', NULL);
INSERT INTO basecolour VALUES (4, 'Roux', NULL);
INSERT INTO basecolour VALUES (5, 'Blanc et noir', NULL);
INSERT INTO basecolour VALUES (6, 'Écaille de tortue', NULL);
INSERT INTO basecolour VALUES (7, 'Tigré', NULL);
INSERT INTO basecolour VALUES (8, 'Fauve', NULL);
INSERT INTO basecolour VALUES (9, 'Noir et fauve', NULL);
INSERT INTO basecolour VALUES (10, 'Fauve et noir', NULL);
INSERT INTO basecolour VALUES (11, 'Marron', NULL);
INSERT INTO basecolour VALUES (12, 'Marron et noir', NULL);
INSERT INTO basecolour VALUES (13, 'Noir et marron', NULL);
INSERT INTO basecolour VALUES (14, 'Bringé', NULL);
INSERT INTO basecolour VALUES (15, 'Bringé et noir', NULL);
INSERT INTO basecolour VALUES (16, 'Bringé et blanc', NULL);
INSERT INTO basecolour VALUES (17, 'Noir et bringé', NULL);
INSERT INTO basecolour VALUES (18, 'Blanc et bringé', NULL);
INSERT INTO basecolour VALUES (19, 'Tricolor', NULL);
INSERT INTO basecolour VALUES (20, 'Chocolat', NULL);
INSERT INTO basecolour VALUES (21, 'Chocolat et blanc', NULL);
INSERT INTO basecolour VALUES (22, 'Blanc et chocolat', NULL);
INSERT INTO basecolour VALUES (23, 'Crème', NULL);
INSERT INTO basecolour VALUES (24, 'Fauve et blanc', NULL);
INSERT INTO basecolour VALUES (26, 'Blanc et fauve', NULL);
INSERT INTO basecolour VALUES (27, 'Écaille de tortue et blanc', NULL);
INSERT INTO basecolour VALUES (28, 'Tigré et blanc', NULL);
INSERT INTO basecolour VALUES (29, 'Roux et blanc', NULL);
INSERT INTO basecolour VALUES (30, 'Gris', NULL);
INSERT INTO basecolour VALUES (31, 'Gris et blanc', NULL);
INSERT INTO basecolour VALUES (32, 'Blanc et gris', NULL);
INSERT INTO basecolour VALUES (33, 'Blanc et écaille de tortue', NULL);
INSERT INTO basecolour VALUES (35, 'Marron et blanc', NULL);
INSERT INTO basecolour VALUES (36, 'Bleu', NULL);
INSERT INTO basecolour VALUES (37, 'Blanc et tigré', NULL);
INSERT INTO basecolour VALUES (38, 'Jaune et gris', NULL);
INSERT INTO basecolour VALUES (39, 'Divers', NULL);
INSERT INTO basecolour VALUES (40, 'Blanc et marron', NULL);
INSERT INTO basecolour VALUES (41, 'Vert', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Lévrier Afghan', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash (Berger d''Anatolie)', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Malamute d''Alaska', '', '', 1);
INSERT INTO breed VALUES (7, 'Bouledogue Américain', '', '', 1);
INSERT INTO breed VALUES (8, 'Esquimau Américain', '', '', 1);
INSERT INTO breed VALUES (9, 'American Staffordshire Terrier', '', '', 1);
INSERT INTO breed VALUES (10, 'Chien d''eau américain', '', '', 1);
INSERT INTO breed VALUES (11, 'Berger d''Anatolie', '', '', 1);
INSERT INTO breed VALUES (12, 'Bouvier d''Appenzell', '', '', 1);
INSERT INTO breed VALUES (13, 'Bouvier Australien', '', '', 1);
INSERT INTO breed VALUES (14, 'Kelpie Australien', '', '', 1);
INSERT INTO breed VALUES (15, 'Berger Australien', '', '', 1);
INSERT INTO breed VALUES (16, 'Terrier Australien', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Colley barbu', '', '', 1);
INSERT INTO breed VALUES (21, 'Berger de Beauce', '', '', 1);
INSERT INTO breed VALUES (22, 'Terrier Bedlington', '', '', 1);
INSERT INTO breed VALUES (23, 'Berger Belge Groenendael', '', '', 1);
INSERT INTO breed VALUES (24, 'Berger Belge Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Berger Belge Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Berger Belge Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Bouvier Bernois', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon frisé', '', '', 1);
INSERT INTO breed VALUES (29, 'Coonhound Noir et Feu', '', '', 1);
INSERT INTO breed VALUES (30, 'Labrador Retriever Noir', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Chien de Saint Hubert (Bloodhound)', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Barzoï', '', '', 1);
INSERT INTO breed VALUES (37, 'Terrier de Boston', '', '', 1);
INSERT INTO breed VALUES (38, 'Bouvier des Flandres', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Berger de Brie (Briard)', '', '', 1);
INSERT INTO breed VALUES (42, 'Épagneul Breton', '', '', 1);
INSERT INTO breed VALUES (43, 'Griffon Bruxellois', '', '', 1);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Chien de Canaan', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso', '', '', 1);
INSERT INTO breed VALUES (49, 'Chien de la Caroline', '', '', 1);
INSERT INTO breed VALUES (50, 'Chien Léopard Catahoula', '', '', 1);
INSERT INTO breed VALUES (51, 'Bouvier Australien', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Retriever de la baie de Chesapeake', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chien Chinois à Crête', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinese Foo Dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Labrador Retriever Chocolat', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow-Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Colley', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Dachshund', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatien', '', '', 1);
INSERT INTO breed VALUES (68, 'Terrier Dandi Dinmont', '', '', 1);
INSERT INTO breed VALUES (69, 'Doberman Pinscher', '', '', 1);
INSERT INTO breed VALUES (70, 'Dogue Argentin', '', '', 1);
INSERT INTO breed VALUES (71, 'Dogue de Bordeaux', '', '', 1);
INSERT INTO breed VALUES (72, 'Berger Hollandais', '', '', 1);
INSERT INTO breed VALUES (73, 'Bouledogue Anglais', '', '', 1);
INSERT INTO breed VALUES (74, 'Cocker Spaniel Anglais', '', '', 1);
INSERT INTO breed VALUES (75, 'Coonhound Anglais', '', '', 1);
INSERT INTO breed VALUES (76, 'Pointer Anglais', '', '', 1);
INSERT INTO breed VALUES (77, 'Setter Anglais', '', '', 1);
INSERT INTO breed VALUES (78, 'Berger Anglais (Bobtail)', '', '', 1);
INSERT INTO breed VALUES (79, 'Springer Spaniel Anglais', '', '', 1);
INSERT INTO breed VALUES (80, 'Épagneul King Charles', '', '', 1);
INSERT INTO breed VALUES (81, 'Bouvier de l''Entlebuch', '', '', 1);
INSERT INTO breed VALUES (82, 'Esquimau', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila Brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Chien Finnois de Laponie', '', '', 1);
INSERT INTO breed VALUES (86, 'Spitz Finlandais', '', '', 1);
INSERT INTO breed VALUES (87, 'Retriever à poil plat', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox-Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Bouledogue Français', '', '', 1);
INSERT INTO breed VALUES (91, 'Pinscher Allemand', '', '', 1);
INSERT INTO breed VALUES (92, 'Berger Allemand', '', '', 1);
INSERT INTO breed VALUES (93, 'Braque Allemand à poil court', '', '', 1);
INSERT INTO breed VALUES (94, 'Braque Allemand à poil dur', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Setter Gordon', '', '', 1);
INSERT INTO breed VALUES (98, 'Grand Danois', '', '', 1);
INSERT INTO breed VALUES (99, 'Chien de Montagne des Pyrénées', '', '', 1);
INSERT INTO breed VALUES (100, 'Grand Bouvier Suisse', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound (Lévrier)', '', '', 1);
INSERT INTO breed VALUES (102, 'Bichon Havanais', '', '', 1);
INSERT INTO breed VALUES (103, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Podenco d''Ibiza', '', '', 1);
INSERT INTO breed VALUES (107, 'Chien de berger yougoslave', '', '', 1);
INSERT INTO breed VALUES (108, 'Setter Irlandais', '', '', 1);
INSERT INTO breed VALUES (109, 'Terrier Irlandais', '', '', 1);
INSERT INTO breed VALUES (110, 'Épagneul d''eau Irlandais', '', '', 1);
INSERT INTO breed VALUES (111, 'Lévrier Irlandais', '', '', 1);
INSERT INTO breed VALUES (112, 'Petit Lévrier Italien', '', '', 1);
INSERT INTO breed VALUES (113, 'Spinone', '', '', 1);
INSERT INTO breed VALUES (114, 'Terrier Jack Russell', '', '', 1);
INSERT INTO breed VALUES (115, 'Épagneul Japonais', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo Coréen', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai', '', '', 1);
INSERT INTO breed VALUES (118, 'Chien d''Ours de Carélie', '', '', 1);
INSERT INTO breed VALUES (119, 'Spitz Loup', '', '', 1);
INSERT INTO breed VALUES (120, 'Terrier Kerry Blue', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Retriever du Labrador', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Chien de Leonberg', '', '', 1);
INSERT INTO breed VALUES (130, 'Petit Chien Lion', '', '', 1);
INSERT INTO breed VALUES (131, 'Bichon Maltais', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Berger de la Maremme et des Abruzzes', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Pinscher Nain', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Chien de montagne', '', '', 1);
INSERT INTO breed VALUES (139, 'Épagneul de Munster', '', '', 1);
INSERT INTO breed VALUES (140, 'Matin Napolitain', '', '', 1);
INSERT INTO breed VALUES (141, 'Chien Chanteur de Nouvelle Guinée', '', '', 1);
INSERT INTO breed VALUES (142, 'Terre Neuve', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich Terrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Buhund Norvégien', '', '', 1);
INSERT INTO breed VALUES (146, 'Chien d''Élan Norvégien', '', '', 1);
INSERT INTO breed VALUES (147, 'Chien Norvégien de Macareux', '', '', 1);
INSERT INTO breed VALUES (148, 'Retriever de la Nouvelle Écosse', '', '', 1);
INSERT INTO breed VALUES (149, 'Chien de Berger Anglais Ancestral', '', '', 1);
INSERT INTO breed VALUES (150, 'Chien à Loutre', '', '', 1);
INSERT INTO breed VALUES (151, 'Épagneul Nain Continental Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Terrier Patterdale', '', '', 1);
INSERT INTO breed VALUES (153, 'Épagneul Pékinois', '', '', 1);
INSERT INTO breed VALUES (154, 'Chien Nu du Pérou', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit Basset Griffon Vendéen', '', '', 1);
INSERT INTO breed VALUES (156, 'Chien du Pharaon', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier (Pitbull)', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Chien de Garenne Portugais', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer Anglais', '', '', 1);
INSERT INTO breed VALUES (161, 'Berger Polonais de Plaine', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Caniche', '', '', 1);
INSERT INTO breed VALUES (164, 'Chien d''Eau Portugais', '', '', 1);
INSERT INTO breed VALUES (165, 'Dogue des Canaries', '', '', 1);
INSERT INTO breed VALUES (166, 'Carlin', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Chien de Rhodesie à Crète Dorsale', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'Saint Bernard', '', '', 1);
INSERT INTO breed VALUES (176, 'Samoyède', '', '', 1);
INSERT INTO breed VALUES (177, 'Samoyed', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Lévrier Écossais', '', '', 1);
INSERT INTO breed VALUES (180, 'Terrier Écossais', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Chien de Berger', '', '', 1);
INSERT INTO breed VALUES (185, 'Berger', '', '', 1);
INSERT INTO breed VALUES (186, 'Chien de Berger des Shetland', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Husky de Sibérie', '', '', 1);
INSERT INTO breed VALUES (190, 'Terrier Australien à poil soyeux', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Fox Terrier à poil lisse', '', '', 1);
INSERT INTO breed VALUES (194, 'Épagneul', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'Berger de Russie Méridionale', '', '', 1);
INSERT INTO breed VALUES (198, 'Vallhund Suédois', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Chien Thaïlandais à Crête Dorsale', '', '', 1);
INSERT INTO breed VALUES (201, 'Dogue du Tibet', '', '', 1);
INSERT INTO breed VALUES (202, 'Épagneul Tibétain', '', '', 1);
INSERT INTO breed VALUES (203, 'Terrier Tibétain', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Fox Terrier Nain', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Braque Hongrois', '', '', 1);
INSERT INTO breed VALUES (208, 'Braque de Weimar', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier', '', '', 1);
INSERT INTO breed VALUES (213, 'Terrier Irlandais à poil doux', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'Berger Blanc Suisse', '', '', 1);
INSERT INTO breed VALUES (216, 'Griffon à poil dur Korthals', '', '', 1);
INSERT INTO breed VALUES (217, 'Fox Terrier à poil dur', '', '', 1);
INSERT INTO breed VALUES (218, 'Retriever du Labrador Sable', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier', '', '', 1);
INSERT INTO breed VALUES (220, 'Chien nu Mexicain', '', '', 1);
INSERT INTO breed VALUES (221, 'Abyssin', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'American Shorthair', '', '', 2);
INSERT INTO breed VALUES (224, 'American Wirehair', '', '', 2);
INSERT INTO breed VALUES (225, 'Siamois Apple Head', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinais', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengal', '', '', 2);
INSERT INTO breed VALUES (228, 'Sacré de Birmanie', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'British Shorthair', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmese', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (235, 'Chat Nu Canadien', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Calico Dilué', '', '', 2);
INSERT INTO breed VALUES (242, 'Écaille de Tortue Dilué', '', '', 2);
INSERT INTO breed VALUES (243, 'Domestique à poil long', '', '', 2);
INSERT INTO breed VALUES (252, 'Domestique à poil mi-long', '', '', 2);
INSERT INTO breed VALUES (261, 'Domestique à poil court', '', '', 2);
INSERT INTO breed VALUES (271, 'Mau Égyptien', '', '', 2);
INSERT INTO breed VALUES (272, 'Exotic Shorthair', '', '', 2);
INSERT INTO breed VALUES (273, 'Chat Polydactyle (Chat d''Hemingway)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayen', '', '', 2);
INSERT INTO breed VALUES (276, 'Bobtail Japonais', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanais', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Chat des Forêts Norvégiennes', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Oriental à poil long', '', '', 2);
INSERT INTO breed VALUES (285, 'Oriental à poil court', '', '', 2);
INSERT INTO breed VALUES (286, 'Oriental tigré', '', '', 2);
INSERT INTO breed VALUES (287, 'Persan', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Bleu Russe', '', '', 2);
INSERT INTO breed VALUES (292, 'Scottish Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siamois', '', '', 2);
INSERT INTO breed VALUES (295, 'Sibérien', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somali', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphynx (chat nu)', '', '', 2);
INSERT INTO breed VALUES (300, 'Tigré', '', '', 2);
INSERT INTO breed VALUES (307, 'Tigre', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkinois', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Écaille de tortue', '', '', 2);
INSERT INTO breed VALUES (311, 'Angora Turc', '', '', 2);
INSERT INTO breed VALUES (312, 'Turc de Van', '', '', 2);
INSERT INTO breed VALUES (313, 'Tuxedo', '', '', 2);
INSERT INTO breed VALUES (314, 'Américain', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Lapin Angora', '', '', 7);
INSERT INTO breed VALUES (318, 'Lièvre Belge', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne d''Argent', '', '', 7);
INSERT INTO breed VALUES (324, 'Géant papillon', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème d''Argent', '', '', 7);
INSERT INTO breed VALUES (328, 'Hollandais', '', '', 7);
INSERT INTO breed VALUES (329, 'Nain', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'Bélier Anglais', '', '', 7);
INSERT INTO breed VALUES (332, 'Papillon Anglais', '', '', 7);
INSERT INTO breed VALUES (333, 'Géant des Flandres', '', '', 7);
INSERT INTO breed VALUES (334, 'Lapin de Floride', '', '', 7);
INSERT INTO breed VALUES (335, 'Bélier Français', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayen', '', '', 7);
INSERT INTO breed VALUES (339, 'Bélier Hollandais', '', '', 7);
INSERT INTO breed VALUES (340, 'Blanc de Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Nain Angora', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Bélier', '', '', 7);
INSERT INTO breed VALUES (344, 'Bélier Nain', '', '', 7);
INSERT INTO breed VALUES (345, 'Rex Nain', '', '', 7);
INSERT INTO breed VALUES (346, 'Nain Hollandais', '', '', 7);
INSERT INTO breed VALUES (347, 'Nouvelle Zélande', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polonais', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silver', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Fauve', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabe', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Âne', '', '', 26);
INSERT INTO breed VALUES (361, 'Draft', '', '', 24);
INSERT INTO breed VALUES (362, 'Cheval d''allure', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade (Croisé)', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Paso Péruvien', '', '', 24);
INSERT INTO breed VALUES (372, 'Poney', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarter horse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Furet', '', '', 3);
INSERT INTO breed VALUES (381, 'Gerbilles', '', '', 18);
INSERT INTO breed VALUES (382, 'Cochon de Guinée', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Hérisson', '', '', 6);
INSERT INTO breed VALUES (385, 'Souris', '', '', 4);
INSERT INTO breed VALUES (386, 'Chien de Prairie', '', '', 5);
INSERT INTO breed VALUES (387, 'Rat', '', '', 5);
INSERT INTO breed VALUES (388, 'Cochon d''Inde (Cobaye)', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Cochon Nain', '', '', 28);
INSERT INTO breed VALUES (391, 'Cochon Nain Vietnamien', '', '', 28);
INSERT INTO breed VALUES (392, 'Gecko', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguane', '', '', 13);
INSERT INTO breed VALUES (394, 'Lézard', '', '', 13);
INSERT INTO breed VALUES (395, 'Serpent', '', '', 13);
INSERT INTO breed VALUES (396, 'Tortue', '', '', 13);
INSERT INTO breed VALUES (397, 'Poisson', '', '', 21);
INSERT INTO breed VALUES (398, 'Gris d''Afrique', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazone', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Perruche ondulée', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Canari', '', '', 3);
INSERT INTO breed VALUES (404, 'Poule', '', '', 3);
INSERT INTO breed VALUES (405, 'Calopsitte élégante', '', '', 3);
INSERT INTO breed VALUES (406, 'Cacatoès', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Colombe', '', '', 3);
INSERT INTO breed VALUES (409, 'Canard', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Pinson', '', '', 3);
INSERT INTO breed VALUES (413, 'Oie', '', '', 3);
INSERT INTO breed VALUES (414, 'Pintade (Poule de Guinée)', '', '', 3);
INSERT INTO breed VALUES (415, 'poule guinée pintade', '', '', 3);
INSERT INTO breed VALUES (416, 'Lori', '', '', 3);
INSERT INTO breed VALUES (417, 'Inséparable', '', '', 3);
INSERT INTO breed VALUES (418, 'Ara', '', '', 3);
INSERT INTO breed VALUES (419, 'Mainate', '', '', 3);
INSERT INTO breed VALUES (420, 'Autruche', '', '', 3);
INSERT INTO breed VALUES (421, 'Perruche (Autre)', '', '', 3);
INSERT INTO breed VALUES (422, 'Perroquet (Autre)', '', '', 3);
INSERT INTO breed VALUES (423, 'Perruche', '', '', 3);
INSERT INTO breed VALUES (424, 'Paon', '', '', 3);
INSERT INTO breed VALUES (425, 'Faisan', '', '', 3);
INSERT INTO breed VALUES (426, 'Pigeon', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Youyou du Sénégal', '', '', 3);
INSERT INTO breed VALUES (429, 'Perruche Moine', '', '', 3);
INSERT INTO breed VALUES (430, 'Nandou d''Amérique', '', '', 3);
INSERT INTO breed VALUES (431, 'Perruche à collier (Psittacula)', '', '', 3);
INSERT INTO breed VALUES (432, 'Pennant', '', '', 3);
INSERT INTO breed VALUES (433, 'Toucan (Autre)', '', '', 3);
INSERT INTO breed VALUES (434, 'Cygne', '', '', 3);
INSERT INTO breed VALUES (435, 'Toucan', '', '', 3);
INSERT INTO breed VALUES (436, 'Dinde', '', '', 3);
INSERT INTO breed VALUES (437, 'Vache', '', '', 16);
INSERT INTO breed VALUES (438, 'Chèvre', '', '', 16);
INSERT INTO breed VALUES (439, 'Mouton', '', '', 16);
INSERT INTO breed VALUES (440, 'Lama', '', '', 16);
INSERT INTO breed VALUES (441, 'Cochon', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%Name';
INSERT INTO configuration VALUES ('Organisation', 'Nom du refuge');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Bébé');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Jeune adulte');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Adulte');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Sénior');
DELETE FROM costtype;
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Animaux sans transpondeur', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditer');
INSERT INTO customreport VALUES (37, 'Animaux sans photo', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditer');
INSERT INTO customreport VALUES (38, 'Animaux jamais vaccinés', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditer');
INSERT INTO customreport VALUES (39, 'Animaux entiers agés de plus de 6 mois', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditer');
INSERT INTO customreport VALUES (40, 'Chats non-testés FIV/FLV', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditer');
INSERT INTO customreport VALUES (41, 'Chiffres mensuels', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Chiffres');
INSERT INTO customreport VALUES (42, 'Animaux long terme', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Chiffres');
INSERT INTO customreport VALUES (43, 'Inventaire du refuge', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventaires');
INSERT INTO customreport VALUES (44, 'Inventaire détaillé du refuge', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventaires');
INSERT INTO customreport VALUES (45, 'Animaux ne faisant pas partie d''une portée', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Portées');
INSERT INTO customreport VALUES (46, 'Entrée/Sortie', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mouvements');
INSERT INTO customreport VALUES (47, 'Sommaire entrée/sortie', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mouvements');
INSERT INTO customreport VALUES (48, 'Rapport des transferts entrants', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Mouvements');
INSERT INTO customreport VALUES (49, 'Volume d''adoption par revendeur', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Revendeurs');
INSERT INTO customreport VALUES (50, 'Temps moyen chez le revendeur avant adoption', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Revendeurs');
INSERT INTO customreport VALUES (51, 'Inventaire revendeur', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Revendeurs');
INSERT INTO customreport VALUES (52, 'Rapport des animaux retournés', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retours');
INSERT INTO customreport VALUES (53, 'Animaux retournés dans les 6 mois', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retours');
INSERT INTO customreport VALUES (54, 'Animaux retournés après 6 mois', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retours');
INSERT INTO customreport VALUES (55, 'Noms les plus courants', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiques');
INSERT INTO customreport VALUES (56, 'Motifs des décès', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiques');
INSERT INTO customreport VALUES (57, 'Zones d''admission les plus courantes', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiques');
INSERT INTO customreport VALUES (58, 'Zones d''adoption les plus courantes', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiques');
INSERT INTO customreport VALUES (59, 'Temps moyen dans la liste d''attente', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiques');
INSERT INTO customreport VALUES (60, 'Dons mensuels', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphiques financier');
INSERT INTO customreport VALUES (61, 'Dons mensuels par espèce', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphiques financier');
INSERT INTO customreport VALUES (62, 'Adoptions mensuelles par espèce', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphiques des mouvements');
INSERT INTO customreport VALUES (63, 'Dons mensuels par localisation', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphiques des mouvements');
INSERT INTO customreport VALUES (64, 'Motifs d''admission', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphiques des mouvements');
INSERT INTO customreport VALUES (65, 'Motifs des retours', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Graphiques des mouvements');
INSERT INTO customreport VALUES (66, 'Comparer les critères des contacts', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventaires');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Mort à l''arrivée', '');
INSERT INTO deathreason VALUES (2, 'Mort', '');
INSERT INTO deathreason VALUES (3, 'Sain', '');
INSERT INTO deathreason VALUES (4, 'Malade/Blessé', '');
INSERT INTO deathreason VALUES (5, 'Requis', '');
INSERT INTO deathreason VALUES (6, 'Abattage', '');
INSERT INTO deathreason VALUES (7, 'Sauvage', '');
INSERT INTO deathreason VALUES (8, 'Morsure', '');
DELETE FROM diet;
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Don', '');
INSERT INTO donationtype VALUES (2, 'Frais d''adoption', '');
INSERT INTO donationtype VALUES (3, 'Accompte pour mise sur liste d''attente', '');
INSERT INTO donationtype VALUES (4, 'Saisie du don', '');
INSERT INTO donationtype VALUES (5, 'Parrainage', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Divorce/Séparation', '');
INSERT INTO entryreason VALUES (2, 'Allergies', '');
INSERT INTO entryreason VALUES (3, 'Morsure', '');
INSERT INTO entryreason VALUES (4, 'Ne peut assumer', '');
INSERT INTO entryreason VALUES (5, 'Logement insalubre', '');
INSERT INTO entryreason VALUES (6, 'Mort', '');
INSERT INTO entryreason VALUES (7, 'Errant', '');
INSERT INTO entryreason VALUES (8, 'Malade/Blessé', '');
INSERT INTO entryreason VALUES (9, 'Ne peut financer', '');
INSERT INTO entryreason VALUES (10, 'Abus', '');
INSERT INTO entryreason VALUES (11, 'Abandonné', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Pas d''emplacement', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Femelle');
INSERT INTO lksex VALUES (1, 'Mâle');
INSERT INTO lksex VALUES (2, 'Inconnu');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Très grand');
INSERT INTO lksize VALUES (1, 'Grand');
INSERT INTO lksize VALUES (2, 'Moyen');
INSERT INTO lksize VALUES (3, 'Petit');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Court');
INSERT INTO lkcoattype VALUES (1, 'Long');
INSERT INTO lkcoattype VALUES (2, 'Rugueux');
INSERT INTO lkcoattype VALUES (3, 'Frisé');
INSERT INTO lkcoattype VALUES (4, 'Cordé');
INSERT INTO lkcoattype VALUES (5, 'Nu');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Aucun(e)');
INSERT INTO lksmovementtype VALUES (1, 'Adoption');
INSERT INTO lksmovementtype VALUES (2, 'Famille d''accueil');
INSERT INTO lksmovementtype VALUES (3, 'Transfert');
INSERT INTO lksmovementtype VALUES (4, 'Echappé(e)');
INSERT INTO lksmovementtype VALUES (5, 'Réclamé');
INSERT INTO lksmovementtype VALUES (6, 'Volé');
INSERT INTO lksmovementtype VALUES (7, 'Remis en liberté');
INSERT INTO lksmovementtype VALUES (8, 'Revendeur');
INSERT INTO lksmovementtype VALUES (9, 'Réservation');
INSERT INTO lksmovementtype VALUES (10, 'Réservation annulée');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Animal');
INSERT INTO lksmedialink VALUES (1, 'Animal perdu');
INSERT INTO lksmedialink VALUES (2, 'Animal trouvé');
INSERT INTO lksmedialink VALUES (3, 'Propriétaire');
INSERT INTO lksmedialink VALUES (4, 'Mouvement');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Aucun(e)');
INSERT INTO lksdiarylink VALUES (1, 'Animal');
INSERT INTO lksdiarylink VALUES (2, 'Propriétaire');
INSERT INTO lksdiarylink VALUES (3, 'Animal perdu');
INSERT INTO lksdiarylink VALUES (4, 'Animal trouvé');
INSERT INTO lksdiarylink VALUES (5, 'Liste d''atttente');
INSERT INTO lksdiarylink VALUES (6, 'Mouvement');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'Unique');
INSERT INTO lksdonationfreq VALUES (1, 'Hebdomadaire');
INSERT INTO lksdonationfreq VALUES (2, 'Mensuel');
INSERT INTO lksdonationfreq VALUES (3, 'Trimestriel');
INSERT INTO lksdonationfreq VALUES (4, 'Semestriel');
INSERT INTO lksdonationfreq VALUES (5, 'Annuel');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Animal');
INSERT INTO lksfieldlink VALUES (1, 'Propriétaire');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Oui/Non');
INSERT INTO lksfieldtype VALUES (1, 'Texte');
INSERT INTO lksfieldtype VALUES (2, 'Remarques');
INSERT INTO lksfieldtype VALUES (3, 'Numéro');
INSERT INTO lksfieldtype VALUES (4, 'Date');
INSERT INTO lksfieldtype VALUES (5, 'Argent');
INSERT INTO lksfieldtype VALUES (6, 'Requête');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Animal');
INSERT INTO lksloglink VALUES (1, 'Propriétaire');
INSERT INTO lksloglink VALUES (2, 'Animal perdu');
INSERT INTO lksloglink VALUES (3, 'Animal trouvé');
INSERT INTO lksloglink VALUES (4, 'Liste d''atttente');
INSERT INTO lksloglink VALUES (5, 'Mouvement');
DELETE FROM lksyesno;
DELETE FROM lksynun;
DELETE FROM lksposneg;
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Urgent');
INSERT INTO lkurgency VALUES (2, 'Haut');
INSERT INTO lkurgency VALUES (3, 'Moyen');
INSERT INTO lkurgency VALUES (4, 'Bas');
INSERT INTO lkurgency VALUES (5, 'Minimum');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Morsure', '');
INSERT INTO logtype VALUES (2, 'Plainte', '');
INSERT INTO logtype VALUES (3, 'Historique', '');
INSERT INTO logtype VALUES (4, 'Poids', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Chien', '', '');
INSERT INTO species VALUES (2, 'Chat', '', '');
INSERT INTO species VALUES (3, 'Oiseau', '', '');
INSERT INTO species VALUES (4, 'Souris', '', '');
INSERT INTO species VALUES (5, 'Rat', '', '');
INSERT INTO species VALUES (6, 'Hérisson', '', '');
INSERT INTO species VALUES (7, 'Lapin', '', '');
INSERT INTO species VALUES (8, 'Colombe', '', '');
INSERT INTO species VALUES (9, 'Furet', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Serpent', '', '');
INSERT INTO species VALUES (12, 'Tortue', '', '');
INSERT INTO species VALUES (13, 'Reptile', '', '');
INSERT INTO species VALUES (14, 'Poule', '', '');
INSERT INTO species VALUES (15, 'Hibou', '', '');
INSERT INTO species VALUES (16, 'Chèvre', '', '');
INSERT INTO species VALUES (17, 'Oie', '', '');
INSERT INTO species VALUES (18, 'Gerbilles', '', '');
INSERT INTO species VALUES (19, 'Calopsitte élégante', '', '');
INSERT INTO species VALUES (20, 'Cochon de Guinée', '', '');
INSERT INTO species VALUES (21, 'Poisson rouge', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Chameau', '', '');
INSERT INTO species VALUES (24, 'Cheval', '', '');
INSERT INTO species VALUES (25, 'Poney', '', '');
INSERT INTO species VALUES (26, 'Âne', '', '');
INSERT INTO species VALUES (27, 'Lama', '', '');
INSERT INTO species VALUES (28, 'Cochon', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Stérilisée/Castré', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Vaccination temporaire', '');
INSERT INTO vaccinationtype VALUES (2, 'Primo vaccination', '');
INSERT INTO vaccinationtype VALUES (3, 'Seconde vaccination', '');
INSERT INTO vaccinationtype VALUES (4, 'Rappel', '');
INSERT INTO vaccinationtype VALUES (5, 'Leucémie', '');
INSERT INTO vaccinationtype VALUES (6, 'Toux du chenil', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirus', '');
