DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Aïdi', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akita - Inu', '', '', 1);
INSERT INTO breed VALUES (5, 'Arigeois', '', '', 1);
INSERT INTO breed VALUES (6, 'Azawakh', '', '', 1);
INSERT INTO breed VALUES (7, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (8, 'Basset Artesiano de Normandía', '', '', 1);
INSERT INTO breed VALUES (9, 'Basset Azul de Gasconia', '', '', 1);
INSERT INTO breed VALUES (10, 'Basset de Artois', '', '', 1);
INSERT INTO breed VALUES (11, 'Basset Leonado de Bretaña', '', '', 1);
INSERT INTO breed VALUES (12, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (13, 'Bearder Collie  - Collie Barbudo', '', '', 1);
INSERT INTO breed VALUES (14, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (15, 'Bichón de Pelo Rizado', '', '', 1);
INSERT INTO breed VALUES (16, 'Bichón Habanero', '', '', 1);
INSERT INTO breed VALUES (17, 'Bichón Boloñés', '', '', 1);
INSERT INTO breed VALUES (18, 'Bichón Maltés', '', '', 1);
INSERT INTO breed VALUES (19, 'Billy', '', '', 1);
INSERT INTO breed VALUES (20, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (22, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (24, 'Boyero de Appenzell', '', '', 1);
INSERT INTO breed VALUES (25, 'Boyero de Asia Central', '', '', 1);
INSERT INTO breed VALUES (26, 'Boyero de Australia', '', '', 1);
INSERT INTO breed VALUES (27, 'Boyero de Entlebuch', '', '', 1);
INSERT INTO breed VALUES (28, 'Boyero de Flandes', '', '', 1);
INSERT INTO breed VALUES (29, 'Boyero de Montaña Bernés', '', '', 1);
INSERT INTO breed VALUES (30, 'Braco de Ariege', '', '', 1);
INSERT INTO breed VALUES (31, 'Braco de Auvergne', '', '', 1);
INSERT INTO breed VALUES (32, 'Braco de Bourbonnais', '', '', 1);
INSERT INTO breed VALUES (33, 'Braco de Weimar', '', '', 1);
INSERT INTO breed VALUES (34, 'Braco de Ariege', '', '', 1);
INSERT INTO breed VALUES (35, 'Braco Dupuy', '', '', 1);
INSERT INTO breed VALUES (36, 'Braco Eslovaco de Pelo Duro', '', '', 1);
INSERT INTO breed VALUES (37, 'Braco Francés de Gasconia', '', '', 1);
INSERT INTO breed VALUES (38, 'Braco Francés de los Pirineos', '', '', 1);
INSERT INTO breed VALUES (39, 'Braco Húngaro de Pelo Duro', '', '', 1);
INSERT INTO breed VALUES (40, 'Braco Italiano', '', '', 1);
INSERT INTO breed VALUES (41, 'Briquet Grifón Vendeano', '', '', 1);
INSERT INTO breed VALUES (42, 'Broholmer', '', '', 1);
INSERT INTO breed VALUES (43, 'Buhund Noruego', '', '', 1);
INSERT INTO breed VALUES (44, 'Bulldog', '', '', 1);
INSERT INTO breed VALUES (45, 'Bulldog Francés', '', '', 1);
INSERT INTO breed VALUES (46, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (47, 'Bullterrier', '', '', 1);
INSERT INTO breed VALUES (48, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (49, 'Caniche', '', '', 1);
INSERT INTO breed VALUES (50, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (51, 'Cazador de Alces Noruego Gris', '', '', 1);
INSERT INTO breed VALUES (52, 'Cazador de Alces Noruego Negro', '', '', 1);
INSERT INTO breed VALUES (53, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (54, 'Chow - Chow', '', '', 1);
INSERT INTO breed VALUES (55, 'Cirneco del Etna', '', '', 1);
INSERT INTO breed VALUES (56, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (57, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (58, 'Cocker Spaniel Americano', '', '', 1);
INSERT INTO breed VALUES (59, 'Collie de Pelo Largo', '', '', 1);
INSERT INTO breed VALUES (60, 'Collie de Pelo Corto', '', '', 1);
INSERT INTO breed VALUES (61, 'Corso', '', '', 1);
INSERT INTO breed VALUES (62, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (63, 'Dálmata', '', '', 1);
INSERT INTO breed VALUES (64, 'Dandie Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (65, 'Dobermann', '', '', 1);
INSERT INTO breed VALUES (66, 'Dogo Argentino', '', '', 1);
INSERT INTO breed VALUES (67, 'Dogo de Burdeos', '', '', 1);
INSERT INTO breed VALUES (68, 'Dogo del Tibet', '', '', 1);
INSERT INTO breed VALUES (69, 'Dogo Mallorquín', '', '', 1);
INSERT INTO breed VALUES (70, 'Drever', '', '', 1);
INSERT INTO breed VALUES (71, 'Eurásico', '', '', 1);
INSERT INTO breed VALUES (72, 'Fila Brasileiro', '', '', 1);
INSERT INTO breed VALUES (73, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (74, 'Foxhound Americano', '', '', 1);
INSERT INTO breed VALUES (75, 'Foxterrier de Pelo Corto', '', '', 1);
INSERT INTO breed VALUES (76, 'Foxterrier de Pelo Duro', '', '', 1);
INSERT INTO breed VALUES (77, 'Galgo Español', '', '', 1);
INSERT INTO breed VALUES (78, 'Galgo Italiano', '', '', 1);
INSERT INTO breed VALUES (79, 'Galgo Húngaro', '', '', 1);
INSERT INTO breed VALUES (80, 'Glen of Imaal Irlandés', '', '', 1);
INSERT INTO breed VALUES (81, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (82, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (83, 'Gos d`Atura Catalán', '', '', 1);
INSERT INTO breed VALUES (84, 'Gran Basset Grifón Vendeano', '', '', 1);
INSERT INTO breed VALUES (85, 'Gran Boyero Suizo', '', '', 1);
INSERT INTO breed VALUES (86, 'Gran Danés', '', '', 1);
INSERT INTO breed VALUES (87, 'Gran Gascón de Saintongeois', '', '', 1);
INSERT INTO breed VALUES (88, 'Gran Grifón Vendeano', '', '', 1);
INSERT INTO breed VALUES (89, 'Gran Münsterlander Pointer', '', '', 1);
INSERT INTO breed VALUES (90, 'Gran Sabueso Anglo Francés Blanco y Negro', '', '', 1);
INSERT INTO breed VALUES (91, 'Gran Sabueso Anglo Francés Tricolor', '', '', 1);
INSERT INTO breed VALUES (92, 'Gran Sabueso Azul de Gasconia', '', '', 1);
INSERT INTO breed VALUES (93, 'Greyhound - Galgo', '', '', 1);
INSERT INTO breed VALUES (94, 'Grifón Azul de Gasconia', '', '', 1);
INSERT INTO breed VALUES (95, 'Grifón Belga', '', '', 1);
INSERT INTO breed VALUES (96, 'Grifón de Bruselas', '', '', 1);
INSERT INTO breed VALUES (97, 'Grifón de Pelo Duro', '', '', 1);
INSERT INTO breed VALUES (98, 'Grifón de Pelo Lanoso', '', '', 1);
INSERT INTO breed VALUES (99, 'Grifón del Nivernais', '', '', 1);
INSERT INTO breed VALUES (100, 'Grifón Leonado de Bretaña', '', '', 1);
INSERT INTO breed VALUES (101, 'Harrier', '', '', 1);
INSERT INTO breed VALUES (102, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (103, 'Jindo Coreano', '', '', 1);
INSERT INTO breed VALUES (104, 'Kai', '', '', 1);
INSERT INTO breed VALUES (105, 'Kelpie Australiano', '', '', 1);
INSERT INTO breed VALUES (106, 'King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (107, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (108, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (109, 'Kromfohrlaender', '', '', 1);
INSERT INTO breed VALUES (110, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (111, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (112, 'Laika del Este Siberiano', '', '', 1);
INSERT INTO breed VALUES (113, 'Laika del Oeste Siberiano', '', '', 1);
INSERT INTO breed VALUES (114, 'Laika Ruso Europea', '', '', 1);
INSERT INTO breed VALUES (115, 'Landseer', '', '', 1);
INSERT INTO breed VALUES (116, 'Lebrel Afgano', '', '', 1);
INSERT INTO breed VALUES (117, 'Lebrel Arabe - Sloughi', '', '', 1);
INSERT INTO breed VALUES (118, 'Lebrel Escocés', '', '', 1);
INSERT INTO breed VALUES (119, 'Lebrel Polaco', '', '', 1);
INSERT INTO breed VALUES (120, 'Lebrel Ruso - Barsoi', '', '', 1);
INSERT INTO breed VALUES (121, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (122, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (123, 'Lobero irlandés', '', '', 1);
INSERT INTO breed VALUES (124, 'Lundehund noruego', '', '', 1);
INSERT INTO breed VALUES (125, 'Malamute de Alaska', '', '', 1);
INSERT INTO breed VALUES (126, 'Mastín', '', '', 1);
INSERT INTO breed VALUES (127, 'Mastín de los Pirineos', '', '', 1);
INSERT INTO breed VALUES (128, 'Mastín Español', '', '', 1);
INSERT INTO breed VALUES (129, 'Mastín Napolitano', '', '', 1);
INSERT INTO breed VALUES (130, 'Montañero de los Alpes - Basset Alpino', '', '', 1);
INSERT INTO breed VALUES (131, 'Mops - Pug - Doguillo - Carlino', '', '', 1);
INSERT INTO breed VALUES (132, 'Mudi', '', '', 1);
INSERT INTO breed VALUES (133, 'Ovejero Alemán', '', '', 1);
INSERT INTO breed VALUES (134, 'Ovejero Belga - Groenendael', '', '', 1);
INSERT INTO breed VALUES (135, 'Ovejero belga - Laekenois', '', '', 1);
INSERT INTO breed VALUES (136, 'Ovejero belga - Malinois', '', '', 1);
INSERT INTO breed VALUES (137, 'Ovejero belga - Tervueren', '', '', 1);
INSERT INTO breed VALUES (138, 'Pastor Australiano', '', '', 1);
INSERT INTO breed VALUES (139, 'Pastor Bergamasco', '', '', 1);
INSERT INTO breed VALUES (140, 'Pastor Croata', '', '', 1);
INSERT INTO breed VALUES (141, 'Pastor de Anatolia', '', '', 1);
INSERT INTO breed VALUES (142, 'Pastor de Beauce', '', '', 1);
INSERT INTO breed VALUES (143, 'Pastor de Brie - Briard', '', '', 1);
INSERT INTO breed VALUES (144, 'Pastor de Islandia', '', '', 1);
INSERT INTO breed VALUES (145, 'Pastor de Karst', '', '', 1);
INSERT INTO breed VALUES (146, 'Pastor de los Pirineos de Cara Rapada', '', '', 1);
INSERT INTO breed VALUES (147, 'Pastor de los Pirineos de Pelo Largo', '', '', 1);
INSERT INTO breed VALUES (148, 'Pastor de Rusia Meridional', '', '', 1);
INSERT INTO breed VALUES (149, 'Pastor de Shetland', '', '', 1);
INSERT INTO breed VALUES (150, 'Pastor del Cáucaso', '', '', 1);
INSERT INTO breed VALUES (151, 'Pastor Holandés', '', '', 1);
INSERT INTO breed VALUES (152, 'Pastor Mallorquín', '', '', 1);
INSERT INTO breed VALUES (153, 'Pastor Maremmano Abruzzense', '', '', 1);
INSERT INTO breed VALUES (154, 'Pastor Picardo', '', '', 1);
INSERT INTO breed VALUES (155, 'Pastor Polaco de la Llanura', '', '', 1);
INSERT INTO breed VALUES (156, 'Pastor Polaco de Podhale', '', '', 1);
INSERT INTO breed VALUES (157, 'Pastor Portugués', '', '', 1);
INSERT INTO breed VALUES (158, 'Pequeño Basset Grifón Vendeano', '', '', 1);
INSERT INTO breed VALUES (159, 'Pequeño Brabazón', '', '', 1);
INSERT INTO breed VALUES (160, 'Pequeño Gascón Saintongeois', '', '', 1);
INSERT INTO breed VALUES (161, 'Pequeño Munsterlander Pointer', '', '', 1);
INSERT INTO breed VALUES (162, 'Pequeño Perro Holandés de Caza Acuática', '', '', 1);
INSERT INTO breed VALUES (163, 'Pequeño Perro León', '', '', 1);
INSERT INTO breed VALUES (164, 'Pequeño Sabueso Azul de Gasconia', '', '', 1);
INSERT INTO breed VALUES (165, 'Pequinés', '', '', 1);
INSERT INTO breed VALUES (166, 'Perdiguero Alemán', '', '', 1);
INSERT INTO breed VALUES (167, 'Perdiguero de Burgos', '', '', 1);
INSERT INTO breed VALUES (168, 'Perdiguero de Drente', '', '', 1);
INSERT INTO breed VALUES (169, 'Perdiguero Frisón', '', '', 1);
INSERT INTO breed VALUES (170, 'Perdiguero Portugués', '', '', 1);
INSERT INTO breed VALUES (171, 'Perro Crestado de China', '', '', 1);
INSERT INTO breed VALUES (172, 'Perro Crestado de Rodesia', '', '', 1);
INSERT INTO breed VALUES (173, 'Perro de Agua Americano', '', '', 1);
INSERT INTO breed VALUES (174, 'Perro de Agua de Romagna', '', '', 1);
INSERT INTO breed VALUES (175, 'Perro de Agua Español', '', '', 1);
INSERT INTO breed VALUES (176, 'Perro de Agua Francés', '', '', 1);
INSERT INTO breed VALUES (177, 'Perro de Agua Frisón', '', '', 1);
INSERT INTO breed VALUES (178, 'Perro de Agua Irlandés', '', '', 1);
INSERT INTO breed VALUES (179, 'Perro de Agua Portugués', '', '', 1);
INSERT INTO breed VALUES (180, 'Perro de Canaán', '', '', 1);
INSERT INTO breed VALUES (181, 'Perro de Castro Laboreiro', '', '', 1);
INSERT INTO breed VALUES (182, 'Perro de Groenlandia', '', '', 1);
INSERT INTO breed VALUES (183, 'Perro de la Montaña de los Pirineos', '', '', 1);
INSERT INTO breed VALUES (184, 'Perro de la Sierra de la Estrella', '', '', 1);
INSERT INTO breed VALUES (185, 'Perro de los Visigodos', '', '', 1);
INSERT INTO breed VALUES (186, 'Perro de Muestra Checo de Pelo Aspero', '', '', 1);
INSERT INTO breed VALUES (187, 'Perro de Muestra de Saint German', '', '', 1);
INSERT INTO breed VALUES (188, 'Perro de Nutria', '', '', 1);
INSERT INTO breed VALUES (189, 'Perro de Osos de Carelia', '', '', 1);
INSERT INTO breed VALUES (190, 'Perro de Renos de Laponia', '', '', 1);
INSERT INTO breed VALUES (191, 'Perro de San Huberto', '', '', 1);
INSERT INTO breed VALUES (192, 'Perro del Faraón', '', '', 1);
INSERT INTO breed VALUES (193, 'Perro Finlandés de Laponia', '', '', 1);
INSERT INTO breed VALUES (194, 'Perro Lobo Checoeslovaco', '', '', 1);
INSERT INTO breed VALUES (195, 'Perro Lobo de Saarlos', '', '', 1);
INSERT INTO breed VALUES (196, 'Perro para Alces Gris Mayor', '', '', 1);
INSERT INTO breed VALUES (197, 'Perro Pelón Mexicano', '', '', 1);
INSERT INTO breed VALUES (198, 'Perro Rastreador Negro y Fuego', '', '', 1);
INSERT INTO breed VALUES (199, 'Perro Sin Pelo del Perú', '', '', 1);
INSERT INTO breed VALUES (200, 'Perro Sueco de Laponia', '', '', 1);
INSERT INTO breed VALUES (201, 'Perro Tailandés', '', '', 1);
INSERT INTO breed VALUES (202, 'Perro Tejonero de Westfalia', '', '', 1);
INSERT INTO breed VALUES (203, 'Pinscher', '', '', 1);
INSERT INTO breed VALUES (204, 'Pinscher Austríaco de Pelo Corto', '', '', 1);
INSERT INTO breed VALUES (205, 'Pinscher Enano', '', '', 1);
INSERT INTO breed VALUES (206, 'Podenco Canario', '', '', 1);
INSERT INTO breed VALUES (207, 'Podenco Ibicenco', '', '', 1);
INSERT INTO breed VALUES (208, 'Podenco Portugués', '', '', 1);
INSERT INTO breed VALUES (209, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (210, 'Pointer Alemán de Pelo Alambre', '', '', 1);
INSERT INTO breed VALUES (211, 'Pointer Alemán de Pelo Cerdoso', '', '', 1);
INSERT INTO breed VALUES (212, 'Pointer Alemán de Pelo Corto', '', '', 1);
INSERT INTO breed VALUES (213, 'Pointer Alemán de Pelo Largo', '', '', 1);
INSERT INTO breed VALUES (214, 'Poitevin', '', '', 1);
INSERT INTO breed VALUES (215, 'Porcelaine', '', '', 1);
INSERT INTO breed VALUES (216, 'Pudelpointer', '', '', 1);
INSERT INTO breed VALUES (217, 'Puli', '', '', 1);
INSERT INTO breed VALUES (218, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (219, 'Rafeiro do Alentejo', '', '', 1);
INSERT INTO breed VALUES (220, 'Rastreador Montañés de Baviera', '', '', 1);
INSERT INTO breed VALUES (221, 'Retriever - Cobrador de Pelo Liso', '', '', 1);
INSERT INTO breed VALUES (222, 'Retriever de la Bahía de Chesapeake', '', '', 1);
INSERT INTO breed VALUES (223, 'Retriever de Nueva Escocia', '', '', 1);
INSERT INTO breed VALUES (224, 'Retriever de Pelo Rizado', '', '', 1);
INSERT INTO breed VALUES (225, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (226, 'Sabueso Alemán', '', '', 1);
INSERT INTO breed VALUES (227, 'Sabueso Anglo Francés Mediano', '', '', 1);
INSERT INTO breed VALUES (228, 'Sabueso Artesiano', '', '', 1);
INSERT INTO breed VALUES (229, 'Sabueso Austríaco Negro y Fuego', '', '', 1);
INSERT INTO breed VALUES (230, 'Sabueso Basset', '', '', 1);
INSERT INTO breed VALUES (231, 'Sabueso Bosnio de Pelo Duro', '', '', 1);
INSERT INTO breed VALUES (232, 'Sabueso Bruno de Jura', '', '', 1);
INSERT INTO breed VALUES (233, 'Sabueso de Berna', '', '', 1);
INSERT INTO breed VALUES (234, 'Sabueso de Hamilton', '', '', 1);
INSERT INTO breed VALUES (235, 'Sabueso de Hannover', '', '', 1);
INSERT INTO breed VALUES (236, 'Sabueso Helénico', '', '', 1);
INSERT INTO breed VALUES (237, 'Sabueso de Hygen', '', '', 1);
INSERT INTO breed VALUES (238, 'Sabueso de Istria de Pelo Duro', '', '', 1);
INSERT INTO breed VALUES (239, 'Sabueso de Istria de Pelo Corto', '', '', 1);
INSERT INTO breed VALUES (240, 'Sabueso de Lucerna', '', '', 1);
INSERT INTO breed VALUES (241, 'Sabueso de Schwiz', '', '', 1);
INSERT INTO breed VALUES (242, 'Sabueso de Smaland', '', '', 1);
INSERT INTO breed VALUES (243, 'Sabueso de Transilvania', '', '', 1);
INSERT INTO breed VALUES (244, 'Sabueso del Tirol', '', '', 1);
INSERT INTO breed VALUES (245, 'Sabueso Eslovaco', '', '', 1);
INSERT INTO breed VALUES (246, 'Sabueso Español', '', '', 1);
INSERT INTO breed VALUES (247, 'Sabueso Finlandés', '', '', 1);
INSERT INTO breed VALUES (248, 'Sabueso Francés Blanco y Naranja', '', '', 1);
INSERT INTO breed VALUES (249, 'Sabueso Francés Blanco y Negro', '', '', 1);
INSERT INTO breed VALUES (250, 'Sabueso Francés Tricolor', '', '', 1);
INSERT INTO breed VALUES (251, 'Sabueso Halden', '', '', 1);
INSERT INTO breed VALUES (252, 'Sabueso Italiano de Pelo Duro', '', '', 1);
INSERT INTO breed VALUES (253, 'Sabueso Italiano de Pelo Raso', '', '', 1);
INSERT INTO breed VALUES (254, 'Sabueso Noruego', '', '', 1);
INSERT INTO breed VALUES (255, 'Sabueso Polaco', '', '', 1);
INSERT INTO breed VALUES (256, 'Sabueso Schiller', '', '', 1);
INSERT INTO breed VALUES (257, 'Sabueso Serbio', '', '', 1);
INSERT INTO breed VALUES (258, 'Sabueso Serbio de  Montaña', '', '', 1);
INSERT INTO breed VALUES (259, 'Sabueso Suizo Pequeño', '', '', 1);
INSERT INTO breed VALUES (260, 'Sabueso Tricolor Serbio', '', '', 1);
INSERT INTO breed VALUES (261, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (262, 'Samoyedo', '', '', 1);
INSERT INTO breed VALUES (263, 'San Bernardo', '', '', 1);
INSERT INTO breed VALUES (264, 'Sarplaninac', '', '', 1);
INSERT INTO breed VALUES (265, 'Schapendoes', '', '', 1);
INSERT INTO breed VALUES (266, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (267, 'Schnauzer Gigante', '', '', 1);
INSERT INTO breed VALUES (268, 'Schnauzer Mediano', '', '', 1);
INSERT INTO breed VALUES (269, 'Schnauzer Miniatura', '', '', 1);
INSERT INTO breed VALUES (270, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (271, 'Setter', '', '', 1);
INSERT INTO breed VALUES (272, 'Setter Irlandés Rojo', '', '', 1);
INSERT INTO breed VALUES (273, 'Setter Irlandés Rojo y Blanco', '', '', 1);
INSERT INTO breed VALUES (274, 'Shar - Pei', '', '', 1);
INSERT INTO breed VALUES (275, 'Shiba - Inu', '', '', 1);
INSERT INTO breed VALUES (276, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (277, 'Shikoku', '', '', 1);
INSERT INTO breed VALUES (278, 'Siberian Husky', '', '', 1);
INSERT INTO breed VALUES (279, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (280, 'Smous Holandés', '', '', 1);
INSERT INTO breed VALUES (281, 'Spaniel Azul de Picardía', '', '', 1);
INSERT INTO breed VALUES (282, 'Spaniel Bretón', '', '', 1);
INSERT INTO breed VALUES (283, 'Spaniel Continental Enano de Compañía', '', '', 1);
INSERT INTO breed VALUES (284, 'Spaniel de Campo', '', '', 1);
INSERT INTO breed VALUES (285, 'Spaniel de Pont Audemer', '', '', 1);
INSERT INTO breed VALUES (286, 'Spaniel Francés', '', '', 1);
INSERT INTO breed VALUES (287, 'Spaniel Picardo', '', '', 1);
INSERT INTO breed VALUES (288, 'Spaniel Tibetano', '', '', 1);
INSERT INTO breed VALUES (289, 'Spinone Italiano', '', '', 1);
INSERT INTO breed VALUES (290, 'Spitz Alemán', '', '', 1);
INSERT INTO breed VALUES (291, 'Spitz de Norbotten', '', '', 1);
INSERT INTO breed VALUES (292, 'Spitz Finlandés', '', '', 1);
INSERT INTO breed VALUES (293, 'Spitz Japonés', '', '', 1);
INSERT INTO breed VALUES (294, 'Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (295, 'Springer Spaniel Galés', '', '', 1);
INSERT INTO breed VALUES (296, 'Staffordshire Bullterrier', '', '', 1);
INSERT INTO breed VALUES (297, 'Staffordshire Terrier Americano', '', '', 1);
INSERT INTO breed VALUES (298, 'Sussex Spaniel', '', '', 1);
INSERT INTO breed VALUES (299, 'Tchuvatch Eslovaco', '', '', 1);
INSERT INTO breed VALUES (300, 'Teckel', '', '', 1);
INSERT INTO breed VALUES (301, 'Terranova', '', '', 1);
INSERT INTO breed VALUES (302, 'Terrier Australiano', '', '', 1);
INSERT INTO breed VALUES (303, 'Terrier Brasileiro', '', '', 1);
INSERT INTO breed VALUES (304, 'Terrier Cazador Alemán', '', '', 1);
INSERT INTO breed VALUES (305, 'Terrier Checo', '', '', 1);
INSERT INTO breed VALUES (306, 'Terrier del Reverendo Jack Russell', '', '', 1);
INSERT INTO breed VALUES (307, 'Terrier Escocés', '', '', 1);
INSERT INTO breed VALUES (308, 'Terrier Irlandés', '', '', 1);
INSERT INTO breed VALUES (309, 'Terrier Japonés', '', '', 1);
INSERT INTO breed VALUES (310, 'Terrier Kerry Blue', '', '', 1);
INSERT INTO breed VALUES (311, 'Terrier Lakeland', '', '', 1);
INSERT INTO breed VALUES (312, 'Terrier Manchester', '', '', 1);
INSERT INTO breed VALUES (313, 'Terrier Negro', '', '', 1);
INSERT INTO breed VALUES (314, 'Terrier Norfolk', '', '', 1);
INSERT INTO breed VALUES (315, 'Terrier Noruego', '', '', 1);
INSERT INTO breed VALUES (316, 'Terrier Sedoso Australiano', '', '', 1);
INSERT INTO breed VALUES (317, 'Terrier West Highland Blanco', '', '', 1);
INSERT INTO breed VALUES (318, 'Terrier Wheaten', '', '', 1);
INSERT INTO breed VALUES (319, 'Tibetan Terrier', '', '', 1);
INSERT INTO breed VALUES (320, 'Tosa - Inu', '', '', 1);
INSERT INTO breed VALUES (321, 'Toy Terrier Negro y Fuego', '', '', 1);
INSERT INTO breed VALUES (322, 'Viejo Pastor Inglés', '', '', 1);
INSERT INTO breed VALUES (323, 'Viejo Pointer Danés', '', '', 1);
INSERT INTO breed VALUES (324, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (325, 'Volpino italiano', '', '', 1);
INSERT INTO breed VALUES (326, 'Welsh Corgi Cardigan', '', '', 1);
INSERT INTO breed VALUES (327, 'Welsh Corgi Pembroke', '', '', 1);
INSERT INTO breed VALUES (328, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (329, 'Yorkshire Terrier', '', '', 1);
DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Perro)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Perro callejero)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Gato abandonado)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Gato callejero)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Diversos)', NULL);
INSERT INTO animaltype VALUES (14, 'C (Animal con problemas)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Animal externo)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Negro', NULL);
INSERT INTO basecolour VALUES (2, 'Blanco', NULL);
INSERT INTO basecolour VALUES (3, 'Negro y Blanco', NULL);
INSERT INTO basecolour VALUES (4, 'Pelirrojo', NULL);
INSERT INTO basecolour VALUES (5, 'Blanco y Negro', NULL);
INSERT INTO basecolour VALUES (6, 'Torti', NULL);
INSERT INTO basecolour VALUES (7, 'Atigrado', NULL);
INSERT INTO basecolour VALUES (8, 'Canela', NULL);
INSERT INTO basecolour VALUES (9, 'Negro y Canela', NULL);
INSERT INTO basecolour VALUES (10, 'Canela y Negro', NULL);
INSERT INTO basecolour VALUES (11, 'Marrón', NULL);
INSERT INTO basecolour VALUES (12, 'Marrón y Negro', NULL);
INSERT INTO basecolour VALUES (13, 'Negro y Marrón', NULL);
INSERT INTO basecolour VALUES (14, 'Manchado', NULL);
INSERT INTO basecolour VALUES (15, 'Manchado y Negro', NULL);
INSERT INTO basecolour VALUES (16, 'Manchado y Blanco', NULL);
INSERT INTO basecolour VALUES (17, 'Negro y Manchado', NULL);
INSERT INTO basecolour VALUES (18, 'Blanco y Manchado', NULL);
INSERT INTO basecolour VALUES (19, 'Tricolor', NULL);
INSERT INTO basecolour VALUES (20, 'Con lunares', NULL);
INSERT INTO basecolour VALUES (21, 'Con lunares y Blanco', NULL);
INSERT INTO basecolour VALUES (22, 'Blanco y Con lunares', NULL);
INSERT INTO basecolour VALUES (23, 'Crema', NULL);
INSERT INTO basecolour VALUES (24, 'Canela y Blanco', NULL);
INSERT INTO basecolour VALUES (26, 'Blanco y Canela', NULL);
INSERT INTO basecolour VALUES (27, 'Torti y Blanco', NULL);
INSERT INTO basecolour VALUES (28, 'Atigrado y Blanco', NULL);
INSERT INTO basecolour VALUES (29, 'Pelirrojo y Blanco', NULL);
INSERT INTO basecolour VALUES (30, 'Gris', NULL);
INSERT INTO basecolour VALUES (31, 'Gris y Blanco', NULL);
INSERT INTO basecolour VALUES (32, 'Blanco y Gris', NULL);
INSERT INTO basecolour VALUES (33, 'Blanco y Torti', NULL);
INSERT INTO basecolour VALUES (35, 'Marrón y Blanco', NULL);
INSERT INTO basecolour VALUES (36, 'Azul', NULL);
INSERT INTO basecolour VALUES (37, 'Blanco y Atigrado', NULL);
INSERT INTO basecolour VALUES (38, 'Amarillo y Gris', NULL);
INSERT INTO basecolour VALUES (39, 'Multicolor', NULL);
INSERT INTO basecolour VALUES (40, 'Blanco y Marrón', NULL);
INSERT INTO basecolour VALUES (41, 'Verde', NULL);
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Animales sin microchip', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (37, 'Animales sin foto', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (38, 'Animales que nunca han sido vacunados', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (39, 'Animales no esterilizados de más de 6 meses', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (40, 'Gatos sin test combi', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditoría');
INSERT INTO customreport VALUES (41, 'Animales por mes', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Listados');
INSERT INTO customreport VALUES (42, 'Animales de larga estancia', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Listados');
INSERT INTO customreport VALUES (43, 'Inventario del refugio', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventarios');
INSERT INTO customreport VALUES (44, 'Inventario detallado del refugio', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventarios');
INSERT INTO customreport VALUES (45, 'Animales no pertenecientes a una camada', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Camadas');
INSERT INTO customreport VALUES (46, 'Entradas/salidas', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimientos');
INSERT INTO customreport VALUES (47, 'Resumen de entradas/salidas', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimientos');
INSERT INTO customreport VALUES (48, 'Informe de entradas al refugio', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimientos');
INSERT INTO customreport VALUES (49, 'Volumen de adopciones por colaborador', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Colaboradores');
INSERT INTO customreport VALUES (50, 'Tiempo medio de espera en el colaborador antes de la adopción', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Colaboradores');
INSERT INTO customreport VALUES (51, 'Inventario del colaborador', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Colaboradores');
INSERT INTO customreport VALUES (52, 'Informe de animales devueltos', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Devoluciones');
INSERT INTO customreport VALUES (53, 'Animales devueltos antes de 6 meses', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Devoluciones');
INSERT INTO customreport VALUES (54, 'Animales devueltos tras 6 meses', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Devoluciones');
INSERT INTO customreport VALUES (55, 'Nombres más habituales', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (56, 'Razones de fallecimiento de los animales', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (57, 'Zonas de procedencia de los animales más habituales', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (58, 'Zonas de adopción de los animales más habituales', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (59, 'Tiempo medio en la lista de espera', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Estadísticas');
INSERT INTO customreport VALUES (60, 'Donaciones mensuales', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos financieros');
INSERT INTO customreport VALUES (61, 'Donaciones mensuales por especie', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos financieros');
INSERT INTO customreport VALUES (62, 'Adopciones mensuales por especie', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de movimientos');
INSERT INTO customreport VALUES (63, 'Adopciones mensuales por zonas', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de movimientos');
INSERT INTO customreport VALUES (64, 'Razones de entrada de los animales', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de movimientos');
INSERT INTO customreport VALUES (65, 'Razones de devolución de los animales', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Gráficos de movimientos');
INSERT INTO customreport VALUES (66, 'Búsqueda de criterios por contacto', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventarios');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Muerto al llegar', '');
INSERT INTO deathreason VALUES (2, 'Muerto', '');
INSERT INTO deathreason VALUES (3, 'Saludable', '');
INSERT INTO deathreason VALUES (4, 'Enfermo/Herido', '');
INSERT INTO deathreason VALUES (5, 'Orden judicial', '');
INSERT INTO deathreason VALUES (6, 'Eutanasia', '');
INSERT INTO deathreason VALUES (7, 'Silvestre', '');
INSERT INTO deathreason VALUES (8, 'Mordedura', '');
DELETE FROM donationtype;
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Separación', '');
INSERT INTO entryreason VALUES (2, 'Alergia', '');
INSERT INTO entryreason VALUES (3, 'Mordedura', '');
INSERT INTO entryreason VALUES (4, 'No sociable', '');
INSERT INTO entryreason VALUES (5, 'Falta de espacio', '');
INSERT INTO entryreason VALUES (6, 'Fallecimiento', '');
INSERT INTO entryreason VALUES (7, 'Callejero', '');
INSERT INTO entryreason VALUES (8, 'Enfermo/Herido', '');
INSERT INTO entryreason VALUES (9, 'Falta de medios', '');
INSERT INTO entryreason VALUES (10, 'Malos tratos', '');
INSERT INTO entryreason VALUES (11, 'Abandonado', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Sin zonas', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Hembra');
INSERT INTO lksex VALUES (1, 'Macho');
INSERT INTO lksex VALUES (2, 'Desconocido');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Muy grande');
INSERT INTO lksize VALUES (1, 'Grande');
INSERT INTO lksize VALUES (2, 'Mediano');
INSERT INTO lksize VALUES (3, 'Pequeño');
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Ninguno');
INSERT INTO lksmovementtype VALUES (1, 'Adopción');
INSERT INTO lksmovementtype VALUES (2, 'Acogida');
INSERT INTO lksmovementtype VALUES (3, 'Traslado');
INSERT INTO lksmovementtype VALUES (4, 'Huido');
INSERT INTO lksmovementtype VALUES (5, 'Buscado');
INSERT INTO lksmovementtype VALUES (6, 'Robado');
INSERT INTO lksmovementtype VALUES (7, 'Reinsertado');
INSERT INTO lksmovementtype VALUES (8, 'Colaborador');
INSERT INTO lksmovementtype VALUES (9, 'Reserva');
INSERT INTO lksmovementtype VALUES (10, 'Reserva cancelada');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Animal');
INSERT INTO lksmedialink VALUES (1, 'Animal perdido');
INSERT INTO lksmedialink VALUES (2, 'Animal encontrado');
INSERT INTO lksmedialink VALUES (3, 'Contacto');
INSERT INTO lksmedialink VALUES (4, 'Movimiento');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Ninguno');
INSERT INTO lksdiarylink VALUES (1, 'Animal');
INSERT INTO lksdiarylink VALUES (2, 'Contacto');
INSERT INTO lksdiarylink VALUES (3, 'Animal perdido');
INSERT INTO lksdiarylink VALUES (4, 'Animal encontrado');
INSERT INTO lksdiarylink VALUES (5, 'Lista de espera');
INSERT INTO lksdiarylink VALUES (6, 'Movimiento');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Animal');
INSERT INTO lksloglink VALUES (1, 'Contacto');
INSERT INTO lksloglink VALUES (2, 'Animal perdido');
INSERT INTO lksloglink VALUES (3, 'Animal encontrado');
INSERT INTO lksloglink VALUES (4, 'Lista de espera');
INSERT INTO lksloglink VALUES (5, 'Movimiento');
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Urgente');
INSERT INTO lkurgency VALUES (2, 'Alta');
INSERT INTO lkurgency VALUES (3, 'Media');
INSERT INTO lkurgency VALUES (4, 'Baja');
INSERT INTO lkurgency VALUES (5, 'No urgente');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Mordedura', '');
INSERT INTO logtype VALUES (2, 'Denuncia', '');
INSERT INTO logtype VALUES (3, 'Historia', '');
INSERT INTO logtype VALUES (4, 'Peso', '');
DELETE FROM medicalpaymenttype;
DELETE FROM species;
INSERT INTO species VALUES (1, 'Perro', '', '');
INSERT INTO species VALUES (2, 'Gato', '', '');
INSERT INTO species VALUES (3, 'Periquito', '', '');
INSERT INTO species VALUES (4, 'Ratón', '', '');
INSERT INTO species VALUES (5, 'Rata', '', '');
INSERT INTO species VALUES (6, 'Erizo', '', '');
INSERT INTO species VALUES (7, 'Conejo', '', '');
INSERT INTO species VALUES (8, 'Paloma', '', '');
INSERT INTO species VALUES (9, 'Hurón', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Culebra', '', '');
INSERT INTO species VALUES (12, 'Tortuga', '', '');
INSERT INTO species VALUES (13, 'Galapago', '', '');
INSERT INTO species VALUES (14, 'Pollo', '', '');
INSERT INTO species VALUES (15, 'Búho', '', '');
INSERT INTO species VALUES (16, 'Cabra', '', '');
INSERT INTO species VALUES (17, 'Oca', '', '');
INSERT INTO species VALUES (18, 'Jerbo', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'Cobaya', '', '');
INSERT INTO species VALUES (21, 'Pez', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Camello', '', '');
INSERT INTO species VALUES (24, 'Caballo', '', '');
INSERT INTO species VALUES (25, 'Poni', '', '');
INSERT INTO species VALUES (26, 'Burro', '', '');
INSERT INTO species VALUES (27, 'Llama', '', '');
INSERT INTO species VALUES (28, 'Pig', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Esterilización', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Vacuna periódica', '');
INSERT INTO vaccinationtype VALUES (2, 'Primera vacuna', '');
INSERT INTO vaccinationtype VALUES (3, 'Segunda vacuna', '');
INSERT INTO vaccinationtype VALUES (4, 'Rabia', '');
INSERT INTO vaccinationtype VALUES (5, 'Leucemia', '');
INSERT INTO vaccinationtype VALUES (6, 'Tos perrera', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirosis', '');
