DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Dog)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Stray Dog)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Unwanted Cat)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Stray Cat)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Miscellaneous)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Non Shelter Animal)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Чёрный', NULL);
INSERT INTO basecolour VALUES (2, 'Белый', NULL);
INSERT INTO basecolour VALUES (3, 'Чёрный с белым', NULL);
INSERT INTO basecolour VALUES (4, 'Рыжий', NULL);
INSERT INTO basecolour VALUES (5, 'Белый с чёрным', NULL);
INSERT INTO basecolour VALUES (6, 'Черепаховый', NULL);
INSERT INTO basecolour VALUES (7, 'Рисунчатый (табби)', NULL);
INSERT INTO basecolour VALUES (8, 'Желтовато-коричневый', NULL);
INSERT INTO basecolour VALUES (9, 'Чёрный с подпалинами', NULL);
INSERT INTO basecolour VALUES (10, 'Палевый с чёрным', NULL);
INSERT INTO basecolour VALUES (11, 'Коричневый', NULL);
INSERT INTO basecolour VALUES (12, 'Коричневый с чёрным', NULL);
INSERT INTO basecolour VALUES (13, 'Чёрный с коричневым', NULL);
INSERT INTO basecolour VALUES (14, 'Тигровый', NULL);
INSERT INTO basecolour VALUES (15, 'Тигровый с чёрным', NULL);
INSERT INTO basecolour VALUES (16, 'Тигровый с белым', NULL);
INSERT INTO basecolour VALUES (17, 'Чёрный с тигровым', NULL);
INSERT INTO basecolour VALUES (18, 'Белый с тигровым', NULL);
INSERT INTO basecolour VALUES (19, 'Трехцветный', NULL);
INSERT INTO basecolour VALUES (20, 'Бурый', NULL);
INSERT INTO basecolour VALUES (21, 'Бурый с белым', NULL);
INSERT INTO basecolour VALUES (22, 'Белый с бурым', NULL);
INSERT INTO basecolour VALUES (23, 'Кремовый', NULL);
INSERT INTO basecolour VALUES (24, 'Палевый с белым', NULL);
INSERT INTO basecolour VALUES (26, 'Белый с палевым', NULL);
INSERT INTO basecolour VALUES (27, 'Черепаховый с белым', NULL);
INSERT INTO basecolour VALUES (28, 'Рисунчатый (табби) с белым', NULL);
INSERT INTO basecolour VALUES (29, 'Рыжий с белым', NULL);
INSERT INTO basecolour VALUES (30, 'Серый', NULL);
INSERT INTO basecolour VALUES (31, 'Серый с белым', NULL);
INSERT INTO basecolour VALUES (32, 'Белый с серым', NULL);
INSERT INTO basecolour VALUES (33, 'Белый с черепаховым', NULL);
INSERT INTO basecolour VALUES (35, 'Коричневый с белым', NULL);
INSERT INTO basecolour VALUES (36, 'Голубой', NULL);
INSERT INTO basecolour VALUES (37, 'Белый с рисунчатым (табби)', NULL);
INSERT INTO basecolour VALUES (38, 'Желтый с серым', NULL);
INSERT INTO basecolour VALUES (39, 'Разнообразный', NULL);
INSERT INTO basecolour VALUES (40, 'Белый с коричневым', NULL);
INSERT INTO basecolour VALUES (41, 'Зелёный', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Аффенпинчер', '', '', 1);
INSERT INTO breed VALUES (2, 'Афганская борзая', '', '', 1);
INSERT INTO breed VALUES (3, 'Ирландский терьер', '', '', 1);
INSERT INTO breed VALUES (4, 'Акбаш', '', '', 1);
INSERT INTO breed VALUES (5, 'Акита', '', '', 1);
INSERT INTO breed VALUES (6, 'Аляскинский маламут', '', '', 1);
INSERT INTO breed VALUES (7, 'Американский бульдог', '', '', 1);
INSERT INTO breed VALUES (8, 'Американская эскимосская собака', '', '', 1);
INSERT INTO breed VALUES (9, 'Американский стаффордширский терьер', '', '', 1);
INSERT INTO breed VALUES (10, 'Американский водяной спаниель', '', '', 1);
INSERT INTO breed VALUES (11, 'Анатолийская пастушья собака', '', '', 1);
INSERT INTO breed VALUES (12, 'Аппенцеллер', '', '', 1);
INSERT INTO breed VALUES (13, 'Австралийская пастушья собака/Голубой хилер', '', '', 1);
INSERT INTO breed VALUES (14, 'Австралийский келпи', '', '', 1);
INSERT INTO breed VALUES (15, 'Австралийская овчарка', '', '', 1);
INSERT INTO breed VALUES (16, 'Австралийский терьер', '', '', 1);
INSERT INTO breed VALUES (17, 'Басенджи', '', '', 1);
INSERT INTO breed VALUES (18, 'Бассет-хаунд', '', '', 1);
INSERT INTO breed VALUES (19, 'Бигль', '', '', 1);
INSERT INTO breed VALUES (20, 'Бородатый колли', '', '', 1);
INSERT INTO breed VALUES (21, 'Босерон', '', '', 1);
INSERT INTO breed VALUES (22, 'Бедлингтон терьер', '', '', 1);
INSERT INTO breed VALUES (23, 'Бельгийская овчарка', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgian Shepherd Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Бельгийская овчарка малинуа', '', '', 1);
INSERT INTO breed VALUES (26, 'Бельгийская овчарка тервюрен', '', '', 1);
INSERT INTO breed VALUES (27, 'Бернский зенненхунд', '', '', 1);
INSERT INTO breed VALUES (28, 'Бишон фризе', '', '', 1);
INSERT INTO breed VALUES (29, 'Черно-подпалый кунхаунд', '', '', 1);
INSERT INTO breed VALUES (30, 'Чёрный лабрадор ретривер', '', '', 1);
INSERT INTO breed VALUES (31, 'Желтая с чеpной маской южная гончая', '', '', 1);
INSERT INTO breed VALUES (32, 'Бладхаунд', '', '', 1);
INSERT INTO breed VALUES (33, 'Крапчато-голубой кунхаунд', '', '', 1);
INSERT INTO breed VALUES (34, 'Бордер колли', '', '', 1);
INSERT INTO breed VALUES (35, 'Бордер терьер', '', '', 1);
INSERT INTO breed VALUES (36, 'Русская псовая борзая', '', '', 1);
INSERT INTO breed VALUES (37, 'Бостон терьер', '', '', 1);
INSERT INTO breed VALUES (38, 'Фландрский бувье', '', '', 1);
INSERT INTO breed VALUES (39, 'Бойкин-спаниель', '', '', 1);
INSERT INTO breed VALUES (40, 'Боксер', '', '', 1);
INSERT INTO breed VALUES (41, 'Бриар', '', '', 1);
INSERT INTO breed VALUES (42, 'Бретонский эпаньоль', '', '', 1);
INSERT INTO breed VALUES (43, 'Брюссельский гриффон', '', '', 1);
INSERT INTO breed VALUES (44, 'Бультерьер', '', '', 1);
INSERT INTO breed VALUES (45, 'Бульмастиф', '', '', 1);
INSERT INTO breed VALUES (46, 'Керн терьер', '', '', 1);
INSERT INTO breed VALUES (47, 'Ханаанская собака', '', '', 1);
INSERT INTO breed VALUES (48, 'Кане корсо', '', '', 1);
INSERT INTO breed VALUES (49, 'Каролинская собака', '', '', 1);
INSERT INTO breed VALUES (50, 'Леопардовая собака Катахулы', '', '', 1);
INSERT INTO breed VALUES (51, 'Скотогонная собака', '', '', 1);
INSERT INTO breed VALUES (52, 'Кавалер кинг чарльз спаниель', '', '', 1);
INSERT INTO breed VALUES (53, 'Чесапикский ретривер', '', '', 1);
INSERT INTO breed VALUES (54, 'Чихуахуа', '', '', 1);
INSERT INTO breed VALUES (55, 'Китайская хохлатая собачка', '', '', 1);
INSERT INTO breed VALUES (56, 'Китайский Фу Дог', '', '', 1);
INSERT INTO breed VALUES (57, 'Шоколадный лабрадор ретривер', '', '', 1);
INSERT INTO breed VALUES (58, 'Чау-чау', '', '', 1);
INSERT INTO breed VALUES (59, 'Кламбер-спаниель', '', '', 1);
INSERT INTO breed VALUES (60, 'Кокерпудель', '', '', 1);
INSERT INTO breed VALUES (61, 'Кокер-спаниель', '', '', 1);
INSERT INTO breed VALUES (62, 'Колли', '', '', 1);
INSERT INTO breed VALUES (63, 'Кунхаунд', '', '', 1);
INSERT INTO breed VALUES (64, 'Корги', '', '', 1);
INSERT INTO breed VALUES (65, 'Котон де тулеар/Мадагаскарский бишон', '', '', 1);
INSERT INTO breed VALUES (66, 'Такса', '', '', 1);
INSERT INTO breed VALUES (67, 'Далматин', '', '', 1);
INSERT INTO breed VALUES (68, 'Денди динмонт терьер', '', '', 1);
INSERT INTO breed VALUES (69, 'Доберман', '', '', 1);
INSERT INTO breed VALUES (70, 'Аргентинский дог', '', '', 1);
INSERT INTO breed VALUES (71, 'Бордоский дог', '', '', 1);
INSERT INTO breed VALUES (72, 'Голландская овчарка', '', '', 1);
INSERT INTO breed VALUES (73, 'Английский бульдог', '', '', 1);
INSERT INTO breed VALUES (74, 'Английский кокер-спаниель', '', '', 1);
INSERT INTO breed VALUES (75, 'Английский кунхаунд', '', '', 1);
INSERT INTO breed VALUES (76, 'Английский пойнтер', '', '', 1);
INSERT INTO breed VALUES (77, 'Английский сеттер', '', '', 1);
INSERT INTO breed VALUES (78, 'Английская овчарка', '', '', 1);
INSERT INTO breed VALUES (79, 'Английский спрингер-спаниель', '', '', 1);
INSERT INTO breed VALUES (80, 'Кинг-чарльз-спаниель/Английский той-спаниель', '', '', 1);
INSERT INTO breed VALUES (81, 'Энтельбухер', '', '', 1);
INSERT INTO breed VALUES (82, 'Эскимосская собака', '', '', 1);
INSERT INTO breed VALUES (83, 'Филд-спаниель', '', '', 1);
INSERT INTO breed VALUES (84, 'Бразильский мастиф', '', '', 1);
INSERT INTO breed VALUES (85, 'Финский лаппхунд', '', '', 1);
INSERT INTO breed VALUES (86, 'Финский шпиц', '', '', 1);
INSERT INTO breed VALUES (87, 'Гладкошерстный ретривер', '', '', 1);
INSERT INTO breed VALUES (88, 'Фокстерьер', '', '', 1);
INSERT INTO breed VALUES (89, 'Фоксхаунд', '', '', 1);
INSERT INTO breed VALUES (90, 'Французский бульдог', '', '', 1);
INSERT INTO breed VALUES (91, 'Немецкий пинчер', '', '', 1);
INSERT INTO breed VALUES (92, 'Немецкая овчарка', '', '', 1);
INSERT INTO breed VALUES (93, 'Курцхаар', '', '', 1);
INSERT INTO breed VALUES (94, 'Дратхаар', '', '', 1);
INSERT INTO breed VALUES (95, 'Глен оф имаал терьер', '', '', 1);
INSERT INTO breed VALUES (96, 'Золотистый ретривер', '', '', 1);
INSERT INTO breed VALUES (97, 'Сеттер-гордон/Шотландский сеттер', '', '', 1);
INSERT INTO breed VALUES (98, 'Немецкий дог', '', '', 1);
INSERT INTO breed VALUES (99, 'Пиренейская горная собака', '', '', 1);
INSERT INTO breed VALUES (100, 'Большой швейцарский зенненхунд', '', '', 1);
INSERT INTO breed VALUES (101, 'Грейхаунд', '', '', 1);
INSERT INTO breed VALUES (102, 'Гаванский бишон', '', '', 1);
INSERT INTO breed VALUES (103, 'Гончая', '', '', 1);
INSERT INTO breed VALUES (104, 'Ховаварт', '', '', 1);
INSERT INTO breed VALUES (105, 'Хаски', '', '', 1);
INSERT INTO breed VALUES (106, 'Ивицкая борзая', '', '', 1);
INSERT INTO breed VALUES (107, 'Шаpпланинац/Илирийская овчарка', '', '', 1);
INSERT INTO breed VALUES (108, 'Ирландский сеттер', '', '', 1);
INSERT INTO breed VALUES (109, 'Ирландский терьер', '', '', 1);
INSERT INTO breed VALUES (110, 'Ирландский водяной спаниель', '', '', 1);
INSERT INTO breed VALUES (111, 'Ирландский волкодав', '', '', 1);
INSERT INTO breed VALUES (112, 'Левретка/Итальянская борзая', '', '', 1);
INSERT INTO breed VALUES (113, 'Итальянский спиноне', '', '', 1);
INSERT INTO breed VALUES (114, 'Джек рассел терьер', '', '', 1);
INSERT INTO breed VALUES (115, 'Японский хин', '', '', 1);
INSERT INTO breed VALUES (116, 'Корейская собака хиндо', '', '', 1);
INSERT INTO breed VALUES (117, 'Кай', '', '', 1);
INSERT INTO breed VALUES (118, 'Карельская медвежья собака', '', '', 1);
INSERT INTO breed VALUES (119, 'Вольф-шпиц/Кеесхонд', '', '', 1);
INSERT INTO breed VALUES (120, 'Керри-блю-терьер', '', '', 1);
INSERT INTO breed VALUES (121, 'Кисю/Кюсю', '', '', 1);
INSERT INTO breed VALUES (122, 'Комондор', '', '', 1);
INSERT INTO breed VALUES (123, 'Кувас', '', '', 1);
INSERT INTO breed VALUES (124, 'Кай лео', '', '', 1);
INSERT INTO breed VALUES (125, 'Лабрадор ретривер', '', '', 1);
INSERT INTO breed VALUES (126, 'Лейкленд терьер', '', '', 1);
INSERT INTO breed VALUES (127, 'Ланкаширский хилер', '', '', 1);
INSERT INTO breed VALUES (128, 'Лхасский апсо', '', '', 1);
INSERT INTO breed VALUES (129, 'Леонбергер', '', '', 1);
INSERT INTO breed VALUES (130, 'Львиная собачка/Левхен', '', '', 1);
INSERT INTO breed VALUES (131, 'Мальтийская болонка', '', '', 1);
INSERT INTO breed VALUES (132, 'Манчестерский терьер', '', '', 1);
INSERT INTO breed VALUES (133, 'Маремма-абруцкая овчарка', '', '', 1);
INSERT INTO breed VALUES (134, 'Мастиф', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Миниатюрный пинчер', '', '', 1);
INSERT INTO breed VALUES (137, 'Горная гончая', '', '', 1);
INSERT INTO breed VALUES (138, 'Горная собака', '', '', 1);
INSERT INTO breed VALUES (139, 'Мюнстерлендер', '', '', 1);
INSERT INTO breed VALUES (140, 'Неаполитанский мастиф', '', '', 1);
INSERT INTO breed VALUES (141, 'Новогвинейская поющая собака', '', '', 1);
INSERT INTO breed VALUES (142, 'Ньюфаундленд', '', '', 1);
INSERT INTO breed VALUES (143, 'Норфолк терьер', '', '', 1);
INSERT INTO breed VALUES (144, 'Норвич терьер', '', '', 1);
INSERT INTO breed VALUES (145, 'Норвежский бухунд', '', '', 1);
INSERT INTO breed VALUES (146, 'Норвежский элкхаунд/Эльгхунд', '', '', 1);
INSERT INTO breed VALUES (147, 'Норвежский лундехунд', '', '', 1);
INSERT INTO breed VALUES (148, 'Новошотландский ретривер', '', '', 1);
INSERT INTO breed VALUES (149, 'Бобтейл/Староанглийская овчарка', '', '', 1);
INSERT INTO breed VALUES (150, 'Оттерхаунд/Выдровая гончая', '', '', 1);
INSERT INTO breed VALUES (151, 'Папильон', '', '', 1);
INSERT INTO breed VALUES (152, 'Паттердейл-терьер', '', '', 1);
INSERT INTO breed VALUES (153, 'Пекинес', '', '', 1);
INSERT INTO breed VALUES (154, 'Перуанская голая собака', '', '', 1);
INSERT INTO breed VALUES (155, 'Малый вандейский бассет-гриффон', '', '', 1);
INSERT INTO breed VALUES (156, 'Фараонова собака', '', '', 1);
INSERT INTO breed VALUES (157, 'Питбультерьер', '', '', 1);
INSERT INTO breed VALUES (158, 'Плоттхаунд', '', '', 1);
INSERT INTO breed VALUES (159, 'Португальский поденгу', '', '', 1);
INSERT INTO breed VALUES (160, 'Пойнтер', '', '', 1);
INSERT INTO breed VALUES (161, 'Польская низинная овчарка', '', '', 1);
INSERT INTO breed VALUES (162, 'Померанский шпиц', '', '', 1);
INSERT INTO breed VALUES (163, 'Пудель', '', '', 1);
INSERT INTO breed VALUES (164, 'Португальская водяная собака', '', '', 1);
INSERT INTO breed VALUES (165, 'Канарская собака', '', '', 1);
INSERT INTO breed VALUES (166, 'Мопс', '', '', 1);
INSERT INTO breed VALUES (167, 'Пули', '', '', 1);
INSERT INTO breed VALUES (168, 'Пуми', '', '', 1);
INSERT INTO breed VALUES (169, 'Рэт-терьер/Tерьeр-крысолов', '', '', 1);
INSERT INTO breed VALUES (170, 'Кpасный кунхаунд', '', '', 1);
INSERT INTO breed VALUES (171, 'Ретривер', '', '', 1);
INSERT INTO breed VALUES (172, 'Родезийский риджбек', '', '', 1);
INSERT INTO breed VALUES (173, 'Ротвейлер', '', '', 1);
INSERT INTO breed VALUES (174, 'Салюки/Персидская борзая', '', '', 1);
INSERT INTO breed VALUES (175, 'Сенбернар', '', '', 1);
INSERT INTO breed VALUES (176, 'Самоедская лайка', '', '', 1);
INSERT INTO breed VALUES (177, 'Шкиперке', '', '', 1);
INSERT INTO breed VALUES (178, 'Шнауцер', '', '', 1);
INSERT INTO breed VALUES (179, 'Дирхаунд', '', '', 1);
INSERT INTO breed VALUES (180, 'Шотландский терьер/Скотч-терьер', '', '', 1);
INSERT INTO breed VALUES (181, 'Силихэм-терьер', '', '', 1);
INSERT INTO breed VALUES (182, 'Сеттер', '', '', 1);
INSERT INTO breed VALUES (183, 'Шар-пей', '', '', 1);
INSERT INTO breed VALUES (184, 'Овчарка', '', '', 1);
INSERT INTO breed VALUES (185, 'Пастушья собака', '', '', 1);
INSERT INTO breed VALUES (186, 'Шелти/Шетландская овчарка', '', '', 1);
INSERT INTO breed VALUES (187, 'Шиба-ину', '', '', 1);
INSERT INTO breed VALUES (188, 'Ши-тцу', '', '', 1);
INSERT INTO breed VALUES (189, 'Сибирский хаски', '', '', 1);
INSERT INTO breed VALUES (190, 'Силки-терьер', '', '', 1);
INSERT INTO breed VALUES (191, 'Скай-терьер', '', '', 1);
INSERT INTO breed VALUES (192, 'Слюги/Арабская борзая', '', '', 1);
INSERT INTO breed VALUES (193, 'Гладкошерстный фокстерьер', '', '', 1);
INSERT INTO breed VALUES (194, 'Спаниель', '', '', 1);
INSERT INTO breed VALUES (195, 'Шпиц', '', '', 1);
INSERT INTO breed VALUES (196, 'Стаффордширский бультерьер', '', '', 1);
INSERT INTO breed VALUES (197, 'Южнорусская овчарка', '', '', 1);
INSERT INTO breed VALUES (198, 'Шведский вальхунд', '', '', 1);
INSERT INTO breed VALUES (199, 'Терьер', '', '', 1);
INSERT INTO breed VALUES (200, 'Тайский риджбек', '', '', 1);
INSERT INTO breed VALUES (201, 'Тибетский мастиф', '', '', 1);
INSERT INTO breed VALUES (202, 'Тибетский спаниель', '', '', 1);
INSERT INTO breed VALUES (203, 'Тибетский терьер', '', '', 1);
INSERT INTO breed VALUES (204, 'Тоза', '', '', 1);
INSERT INTO breed VALUES (205, 'Той-фокстерьер', '', '', 1);
INSERT INTO breed VALUES (206, 'Древесная енотовая гончая/Кунхаунд Уолкера', '', '', 1);
INSERT INTO breed VALUES (207, 'Выжла', '', '', 1);
INSERT INTO breed VALUES (208, 'Веймаранер', '', '', 1);
INSERT INTO breed VALUES (209, 'Вельш корги', '', '', 1);
INSERT INTO breed VALUES (210, 'Вельштерьер', '', '', 1);
INSERT INTO breed VALUES (211, 'Вельш спрингер спаниель', '', '', 1);
INSERT INTO breed VALUES (212, 'Вест-хайленд-вайт-терьер', '', '', 1);
INSERT INTO breed VALUES (213, 'Пшеничный терьер', '', '', 1);
INSERT INTO breed VALUES (214, 'Уиппет', '', '', 1);
INSERT INTO breed VALUES (215, 'Белая швейцарская овчарка', '', '', 1);
INSERT INTO breed VALUES (216, 'Французский жесткошерстный гриффон', '', '', 1);
INSERT INTO breed VALUES (217, 'Жесткошерстный терьер', '', '', 1);
INSERT INTO breed VALUES (218, 'Жёлтый лабрадор ретривер', '', '', 1);
INSERT INTO breed VALUES (219, 'Йоркширский терьер', '', '', 1);
INSERT INTO breed VALUES (220, 'Мексиканская голая собака', '', '', 1);
INSERT INTO breed VALUES (221, 'Абиссинская кошка', '', '', 2);
INSERT INTO breed VALUES (222, 'Американский керл', '', '', 2);
INSERT INTO breed VALUES (223, 'Американская короткошерстная', '', '', 2);
INSERT INTO breed VALUES (224, 'Американская жесткошерстная', '', '', 2);
INSERT INTO breed VALUES (225, 'Яблокоголовый (традиционный) сиам', '', '', 2);
INSERT INTO breed VALUES (226, 'Балинез/Балийская кошка', '', '', 2);
INSERT INTO breed VALUES (227, 'Бенгальская кошка', '', '', 2);
INSERT INTO breed VALUES (228, 'Бирманская кошка/Священная бирма', '', '', 2);
INSERT INTO breed VALUES (229, 'Американский бобтейл', '', '', 2);
INSERT INTO breed VALUES (230, 'Бомбейская кошка', '', '', 2);
INSERT INTO breed VALUES (231, 'Британская короткошерстная', '', '', 2);
INSERT INTO breed VALUES (232, 'Бурманская кошка', '', '', 2);
INSERT INTO breed VALUES (233, 'Бурмилла', '', '', 2);
INSERT INTO breed VALUES (234, 'Калико', '', '', 2);
INSERT INTO breed VALUES (235, 'Канадский сфинкс', '', '', 2);
INSERT INTO breed VALUES (236, 'Картезианская кошка', '', '', 2);
INSERT INTO breed VALUES (237, 'Шиншилла', '', '', 2);
INSERT INTO breed VALUES (238, 'Корниш-рекс', '', '', 2);
INSERT INTO breed VALUES (239, 'Кимрик', '', '', 2);
INSERT INTO breed VALUES (240, 'Девон-рекс', '', '', 2);
INSERT INTO breed VALUES (241, 'Разбавленная трехцветная', '', '', 2);
INSERT INTO breed VALUES (242, 'Разбавленная черепаховая', '', '', 2);
INSERT INTO breed VALUES (243, 'Домашняя длинношерстная', '', '', 2);
INSERT INTO breed VALUES (252, 'Домашняя средней длинны шерсти', '', '', 2);
INSERT INTO breed VALUES (261, 'Домашняя короткошерстная', '', '', 2);
INSERT INTO breed VALUES (271, 'Египетский мау', '', '', 2);
INSERT INTO breed VALUES (272, 'Экзотическая короткошерстная', '', '', 2);
INSERT INTO breed VALUES (273, 'Многопальчатая кошка (Гемингвейский полидактиль)', '', '', 2);
INSERT INTO breed VALUES (274, 'Гавана', '', '', 2);
INSERT INTO breed VALUES (275, 'Гималайская кошка', '', '', 2);
INSERT INTO breed VALUES (276, 'Японский бобтейл', '', '', 2);
INSERT INTO breed VALUES (277, 'Яванская кошка', '', '', 2);
INSERT INTO breed VALUES (278, 'Корат', '', '', 2);
INSERT INTO breed VALUES (279, 'Мейн-кун', '', '', 2);
INSERT INTO breed VALUES (280, 'Мэнкс', '', '', 2);
INSERT INTO breed VALUES (281, 'Манчкин', '', '', 2);
INSERT INTO breed VALUES (282, 'Норвежская лесная кошка', '', '', 2);
INSERT INTO breed VALUES (283, 'Оцикет', '', '', 2);
INSERT INTO breed VALUES (284, 'Ориентальная длинношерстная', '', '', 2);
INSERT INTO breed VALUES (285, 'Ориентальная короткошерстная', '', '', 2);
INSERT INTO breed VALUES (286, 'Ориентальная рисунчатая', '', '', 2);
INSERT INTO breed VALUES (287, 'Персидская кошка', '', '', 2);
INSERT INTO breed VALUES (288, 'Пикси-Боб', '', '', 2);
INSERT INTO breed VALUES (289, 'Рагамаффин', '', '', 2);
INSERT INTO breed VALUES (290, 'Рэгдолл', '', '', 2);
INSERT INTO breed VALUES (291, 'Русская голубая', '', '', 2);
INSERT INTO breed VALUES (292, 'Шотландская вислоухая кошка/Скоттиш-фолд', '', '', 2);
INSERT INTO breed VALUES (293, 'Селкирк-рекс', '', '', 2);
INSERT INTO breed VALUES (294, 'Сиамская кошка', '', '', 2);
INSERT INTO breed VALUES (295, 'Сибирская кошка', '', '', 2);
INSERT INTO breed VALUES (296, 'Сингапурская кошка', '', '', 2);
INSERT INTO breed VALUES (297, 'Сноу-шу', '', '', 2);
INSERT INTO breed VALUES (298, 'Сомалийская кошка', '', '', 2);
INSERT INTO breed VALUES (299, 'Сфинкс (голая кошка)', '', '', 2);
INSERT INTO breed VALUES (300, 'Рисунчатый (табби)', '', '', 2);
INSERT INTO breed VALUES (307, 'Тигровая', '', '', 2);
INSERT INTO breed VALUES (308, 'Тонкинская кошка', '', '', 2);
INSERT INTO breed VALUES (309, 'Торби', '', '', 2);
INSERT INTO breed VALUES (310, 'Черепаховая кошка', '', '', 2);
INSERT INTO breed VALUES (311, 'Турецкая ангора', '', '', 2);
INSERT INTO breed VALUES (312, 'Турецкий ван', '', '', 2);
INSERT INTO breed VALUES (313, 'Смокинг', '', '', 2);
INSERT INTO breed VALUES (314, 'American', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angora Rabbit', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Кролик', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Шиншилла', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Dutch', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Гавана', '', '', 7);
INSERT INTO breed VALUES (338, 'Гималайская кошка', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polish', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silver', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Желтовато-коричневый', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabian', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Donkey/Mule', '', '', 26);
INSERT INTO breed VALUES (361, 'Draft', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Шиншилла', '', '', 10);
INSERT INTO breed VALUES (380, 'Хорек (фретка)', '', '', 3);
INSERT INTO breed VALUES (381, 'Песчанка', '', '', 18);
INSERT INTO breed VALUES (382, 'Морская свинка', '', '', 20);
INSERT INTO breed VALUES (383, 'Хомяк', '', '', 22);
INSERT INTO breed VALUES (384, 'Ёж', '', '', 6);
INSERT INTO breed VALUES (385, 'Мышь', '', '', 4);
INSERT INTO breed VALUES (386, 'Prairie Dog', '', '', 5);
INSERT INTO breed VALUES (387, 'Крыса', '', '', 5);
INSERT INTO breed VALUES (388, 'Skunk', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (391, 'Vietnamese Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (392, 'Гекон', '', '', 13);
INSERT INTO breed VALUES (393, 'Игуана', '', '', 13);
INSERT INTO breed VALUES (394, 'Ящерица', '', '', 13);
INSERT INTO breed VALUES (395, 'Змея', '', '', 13);
INSERT INTO breed VALUES (396, 'Черепаха', '', '', 13);
INSERT INTO breed VALUES (397, 'Рыба', '', '', 21);
INSERT INTO breed VALUES (398, 'Жако/Африканский серый попугай', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Волнистый попугай', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Канарейка', '', '', 3);
INSERT INTO breed VALUES (404, 'Цыпленок', '', '', 3);
INSERT INTO breed VALUES (405, 'Попугай', '', '', 3);
INSERT INTO breed VALUES (406, 'Какаду', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Голубь', '', '', 3);
INSERT INTO breed VALUES (409, 'Утка', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Эму', '', '', 3);
INSERT INTO breed VALUES (412, 'Зяблик', '', '', 3);
INSERT INTO breed VALUES (413, 'Гусь', '', '', 3);
INSERT INTO breed VALUES (414, 'Guinea fowl', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lory/Lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Ара', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Страус', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakeet (Other)', '', '', 3);
INSERT INTO breed VALUES (422, 'Parrot (Other)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Peacock/Pea fowl', '', '', 3);
INSERT INTO breed VALUES (425, 'Фазан', '', '', 3);
INSERT INTO breed VALUES (426, 'Голубь', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Swan', '', '', 3);
INSERT INTO breed VALUES (435, 'Тукан', '', '', 3);
INSERT INTO breed VALUES (436, 'Индейка', '', '', 3);
INSERT INTO breed VALUES (437, 'Корова', '', '', 16);
INSERT INTO breed VALUES (438, 'Коза', '', '', 16);
INSERT INTO breed VALUES (439, 'Овца', '', '', 16);
INSERT INTO breed VALUES (440, 'Llama', '', '', 16);
INSERT INTO breed VALUES (441, 'Pig (Farm)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%';
INSERT INTO configuration VALUES ('Organisation', 'Организация');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Baby');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Young Adult');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Взрослый');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Senior');
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Non-Microchipped Animals', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (37, 'Animals Without Photo Media', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (38, 'Animals Never Vaccinated', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (39, 'Non-Neutered/Spayed Animals Aged Over 6 Months', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (40, 'Cats Not Combi-Tested', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (41, 'Monthly Animal Figures', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (42, 'Long Term Animals', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (43, 'Shelter Inventory', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (44, 'Detailed Shelter Inventory', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (45, 'Animals Not Part Of A Litter', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Litters');
INSERT INTO customreport VALUES (46, 'In/Out', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (47, 'In/Out Summary', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (48, 'Transfer In Report', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (49, 'Volume Of Adoptions Per Retailer', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (50, 'Average Time At Retailer Before Adoption', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (51, 'Retailer Inventory', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (52, 'Returned Animals Report', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (53, 'Animals Returned Within 6 Months', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (54, 'Animals Returned After 6 Months', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (55, 'Most Common Name', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (56, 'Animal Death Reasons', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (57, 'Most Common Animal Entry Areas', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (58, 'Most Common Animal Adoption Areas', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (59, 'Average Time On Waiting List', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistics');
INSERT INTO customreport VALUES (60, 'Monthly Donations', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Financial Graphs');
INSERT INTO customreport VALUES (61, 'Monthly Donations By Species', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Financial Graphs');
INSERT INTO customreport VALUES (62, 'Monthly Adoptions By Species', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (63, 'Monthly Adoptions By Location', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (64, 'Animal Entry Reasons', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (65, 'Animal Return Reasons', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (66, 'Owner Criteria Matching', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Dead On Arrival', '');
INSERT INTO deathreason VALUES (2, 'Died', '');
INSERT INTO deathreason VALUES (3, 'Healthy', '');
INSERT INTO deathreason VALUES (4, 'Sick/Injured', '');
INSERT INTO deathreason VALUES (5, 'Requested', '');
INSERT INTO deathreason VALUES (6, 'Culling', '');
INSERT INTO deathreason VALUES (7, 'Feral', '');
INSERT INTO deathreason VALUES (8, 'Biting', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Marriage/Relationship split', '');
INSERT INTO entryreason VALUES (2, 'Allergies', '');
INSERT INTO entryreason VALUES (3, 'Biting', '');
INSERT INTO entryreason VALUES (4, 'Unable to Cope', '');
INSERT INTO entryreason VALUES (5, 'Unsuitable Accomodation', '');
INSERT INTO entryreason VALUES (6, 'Died', '');
INSERT INTO entryreason VALUES (7, 'Stray', '');
INSERT INTO entryreason VALUES (8, 'Sick/Injured', '');
INSERT INTO entryreason VALUES (9, 'Unable to Afford', '');
INSERT INTO entryreason VALUES (10, 'Abuse', '');
INSERT INTO entryreason VALUES (11, 'Abandoned', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'No Locations', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Female');
INSERT INTO lksex VALUES (1, 'Male');
INSERT INTO lksex VALUES (2, 'Unknown');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Very Large');
INSERT INTO lksize VALUES (1, 'Large');
INSERT INTO lksize VALUES (2, 'Medium');
INSERT INTO lksize VALUES (3, 'Small');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Short');
INSERT INTO lkcoattype VALUES (1, 'Long');
INSERT INTO lkcoattype VALUES (2, 'Rough');
INSERT INTO lkcoattype VALUES (3, 'Curly');
INSERT INTO lkcoattype VALUES (4, 'Corded');
INSERT INTO lkcoattype VALUES (5, 'Hairless');
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'None');
INSERT INTO lksmovementtype VALUES (1, 'Adoption');
INSERT INTO lksmovementtype VALUES (2, 'Foster');
INSERT INTO lksmovementtype VALUES (3, 'Transfer');
INSERT INTO lksmovementtype VALUES (4, 'Escaped');
INSERT INTO lksmovementtype VALUES (5, 'Reclaimed');
INSERT INTO lksmovementtype VALUES (6, 'Stolen');
INSERT INTO lksmovementtype VALUES (7, 'Released To Wild');
INSERT INTO lksmovementtype VALUES (8, 'Retailer');
INSERT INTO lksmovementtype VALUES (9, 'Reservation');
INSERT INTO lksmovementtype VALUES (10, 'Cancelled Reservation');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Animal');
INSERT INTO lksmedialink VALUES (1, 'Lost Animal');
INSERT INTO lksmedialink VALUES (2, 'Found Animal');
INSERT INTO lksmedialink VALUES (3, 'Owner');
INSERT INTO lksmedialink VALUES (4, 'Movement');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'None');
INSERT INTO lksdiarylink VALUES (1, 'Animal');
INSERT INTO lksdiarylink VALUES (2, 'Owner');
INSERT INTO lksdiarylink VALUES (3, 'Lost Animal');
INSERT INTO lksdiarylink VALUES (4, 'Found Animal');
INSERT INTO lksdiarylink VALUES (5, 'Waiting List');
INSERT INTO lksdiarylink VALUES (6, 'Movement');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Animal');
INSERT INTO lksfieldlink VALUES (1, 'Owner');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Yes/No');
INSERT INTO lksfieldtype VALUES (1, 'Text');
INSERT INTO lksfieldtype VALUES (2, 'Notes');
INSERT INTO lksfieldtype VALUES (3, 'Number');
INSERT INTO lksfieldtype VALUES (4, 'Date');
INSERT INTO lksfieldtype VALUES (5, 'Money');
INSERT INTO lksfieldtype VALUES (6, 'Lookup');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Animal');
INSERT INTO lksloglink VALUES (1, 'Owner');
INSERT INTO lksloglink VALUES (2, 'Lost Animal');
INSERT INTO lksloglink VALUES (3, 'Found Animal');
INSERT INTO lksloglink VALUES (4, 'Waiting List');
INSERT INTO lksloglink VALUES (5, 'Movement');
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Urgent');
INSERT INTO lkurgency VALUES (2, 'High');
INSERT INTO lkurgency VALUES (3, 'Medium');
INSERT INTO lkurgency VALUES (4, 'Low');
INSERT INTO lkurgency VALUES (5, 'Lowest');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Bite', '');
INSERT INTO logtype VALUES (2, 'Complaint', '');
INSERT INTO logtype VALUES (3, 'History', '');
INSERT INTO logtype VALUES (4, 'Weight', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Dog', '', '');
INSERT INTO species VALUES (2, 'Cat', '', '');
INSERT INTO species VALUES (3, 'Bird', '', '');
INSERT INTO species VALUES (4, 'Мышь', '', '');
INSERT INTO species VALUES (5, 'Крыса', '', '');
INSERT INTO species VALUES (6, 'Ёж', '', '');
INSERT INTO species VALUES (7, 'Rabbit', '', '');
INSERT INTO species VALUES (8, 'Голубь', '', '');
INSERT INTO species VALUES (9, 'Хорек (фретка)', '', '');
INSERT INTO species VALUES (10, 'Шиншилла', '', '');
INSERT INTO species VALUES (11, 'Змея', '', '');
INSERT INTO species VALUES (12, 'Tortoise', '', '');
INSERT INTO species VALUES (13, 'Terrapin', '', '');
INSERT INTO species VALUES (14, 'Цыпленок', '', '');
INSERT INTO species VALUES (15, 'Owl', '', '');
INSERT INTO species VALUES (16, 'Коза', '', '');
INSERT INTO species VALUES (17, 'Гусь', '', '');
INSERT INTO species VALUES (18, 'Песчанка', '', '');
INSERT INTO species VALUES (19, 'Попугай', '', '');
INSERT INTO species VALUES (20, 'Морская свинка', '', '');
INSERT INTO species VALUES (21, 'Goldfish', '', '');
INSERT INTO species VALUES (22, 'Хомяк', '', '');
INSERT INTO species VALUES (23, 'Camel', '', '');
INSERT INTO species VALUES (24, 'Horse', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Donkey', '', '');
INSERT INTO species VALUES (27, 'Llama', '', '');
INSERT INTO species VALUES (28, 'Pig', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Neuter/Spay', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Temporary Vaccination', '');
INSERT INTO vaccinationtype VALUES (2, 'First Vaccination', '');
INSERT INTO vaccinationtype VALUES (3, 'Second Vaccination', '');
INSERT INTO vaccinationtype VALUES (4, 'Booster', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukaemia', '');
INSERT INTO vaccinationtype VALUES (6, 'Kennel Cough', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirus', '');
