DELETE FROM accounts;
INSERT INTO accounts VALUES (10, 'Τράπεζα::Καταθέσεις', 'Τραπεζικός λογαριασμός καταθέσεων', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (11, 'Τράπεζα::Αποταμιεύσεις', 'Τραπεζικός λογαριασμός αποταμιεύσεων', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (12, 'Περιουσία::Εγκαταστάσεις', 'Εγκαταστάσεις', 8, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (13, 'Έξοδα::Τηλεφώνου', 'Τηλεφωνικοί λογαριασμοί', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (14, 'Έξοδα::Ηλεκτρικού', 'Λογαριασμοί ηλεκτρικού', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (15, 'Έξοδα::Νερό', 'Λαγαριασμοί νερού', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (16, 'Έξοδα::Καυσίμων', 'Λογαριασμοί καυσίμων', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (17, 'Έξοδα::Ταχυδρομικά', 'Ταχυδρομικές δαπάνες', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (18, 'Έξοδα::Αναλώσιμα', 'Κόστος αναλώσιμων', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (19, 'Έξοδα::Τροφή', 'Κόστος τροφής ζώων', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (1, 'Έσοδα::Δωρεά', 'Εισερχόμενες δωρεές (διάφορα)', 5, 1, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (2, 'Έσοδα::Υιοθεσίες', 'Δωρεές από τέλη υιοθεσίας', 5, 2, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (3, 'Έσοδα::Λίστα αναμονής', 'Λίστα αναμονής δωρεών', 5, 3, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (4, 'Έσοδα::ΤέληΕισαγωγής', 'Δωρεές για ζώα που εισάγονται στο καταφύγιο', 5, 4, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (5, 'Έσοδα::Χορηγία', 'Δωρεές χορηγιών', 5, 5, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (6, 'Έσοδα::Κατάστημα', 'Έσοδα από ηλεκτρονικό κατάστημα', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (7, 'Έσοδα::Τόκος', 'Τόκος τραπεζικού λογαριασμού', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (8, 'Έσοδα::Απόμεταφορά', 'Άνοιγμα ισοζυγίου από μεταφορά', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (9, 'Τράπεζα:τρέχουσα', 'Τρέχων λογαριασμός τραπέζης', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
DELETE FROM animaltype;
INSERT INTO animaltype VALUES (10, 'F (Αδέσποτος Σκύλος)', NULL);
INSERT INTO animaltype VALUES (11, 'Α (Ανεπιθύμητη γάτα)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Αδέσποτη Γάτα)', NULL);
INSERT INTO animaltype VALUES (13, 'Δ (Διάφορα)', NULL);
INSERT INTO animaltype VALUES (2, 'Σ (Σκύλος)', NULL);
INSERT INTO animaltype VALUES (40, 'Ν (Δεν είναι ζώο καταφυγίου)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Μαύρο', NULL);
INSERT INTO basecolour VALUES (10, 'Ανοιχτικαστανό και μαύρο', NULL);
INSERT INTO basecolour VALUES (11, 'Καφέ', NULL);
INSERT INTO basecolour VALUES (12, 'Καφέ και Μαύρο', NULL);
INSERT INTO basecolour VALUES (13, 'Μαύρο και Καφέ', NULL);
INSERT INTO basecolour VALUES (14, 'Καστανόχρωμο με πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (15, 'Καστανόχρωμο με πιτσιλιές και μαύρο', NULL);
INSERT INTO basecolour VALUES (16, 'Καστανόχρωμο με πιτσιλιές και λευκό', NULL);
INSERT INTO basecolour VALUES (17, 'Μαύρο και καστανόχρωμο με πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (18, 'Λευκό και καστανόχρωμο με πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (19, 'Τρίχρωμο', NULL);
INSERT INTO basecolour VALUES (2, 'Λευκό', NULL);
INSERT INTO basecolour VALUES (20, 'Βαθυκόκκινο', NULL);
INSERT INTO basecolour VALUES (21, 'Βαθυκόκκινο και λευκό', NULL);
INSERT INTO basecolour VALUES (22, 'Λευκό και βαθυκόκκινο', NULL);
INSERT INTO basecolour VALUES (23, 'Κρεμ', NULL);
INSERT INTO basecolour VALUES (24, 'Ανοιχτοκαστανό και λευκό', NULL);
INSERT INTO basecolour VALUES (26, 'Λευκό και ανοιχτοκαστανό', NULL);
INSERT INTO basecolour VALUES (27, 'Λευκό με χρωματιστές πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (28, 'Τιγρέ και λευκό', NULL);
INSERT INTO basecolour VALUES (29, 'Πυρρόξανθο και λευκό', NULL);
INSERT INTO basecolour VALUES (3, 'Μαύρο και άσπρο', NULL);
INSERT INTO basecolour VALUES (30, 'Γκρί', NULL);
INSERT INTO basecolour VALUES (31, 'Γκρί και Λευκό', NULL);
INSERT INTO basecolour VALUES (32, 'Λευκό και Γκρί', NULL);
INSERT INTO basecolour VALUES (33, 'Λευκό και πιτσιλωτό', NULL);
INSERT INTO basecolour VALUES (35, 'Καφέ και λευκό', NULL);
INSERT INTO basecolour VALUES (36, 'Μπλέ', NULL);
INSERT INTO basecolour VALUES (37, 'Λευκό και πιτσιλωτό', NULL);
INSERT INTO basecolour VALUES (38, 'Κίιτρινο και γκρί', NULL);
INSERT INTO basecolour VALUES (39, 'Ποικιλόχρωμο', NULL);
INSERT INTO basecolour VALUES (4, 'Πυρρόξανθο', NULL);
INSERT INTO basecolour VALUES (40, 'Λευκό και καφέ', NULL);
INSERT INTO basecolour VALUES (41, 'Πράσινο', NULL);
INSERT INTO basecolour VALUES (42, 'Μελί', NULL);
INSERT INTO basecolour VALUES (43, 'Μαύρο με χρωματιστές πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (44, 'Μπλε με χρωματιστές πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (45, 'Σοκολατί', NULL);
INSERT INTO basecolour VALUES (46, 'Σοκολατί με χρωματιστές πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (47, 'Cinnamon', NULL);
INSERT INTO basecolour VALUES (48, 'Κανελλί με χρωματιστές πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (49, 'Μπεζ', NULL);
INSERT INTO basecolour VALUES (5, 'Άσπρο και Μαύρο', NULL);
INSERT INTO basecolour VALUES (50, 'Μπεζ με πολύχρωμες πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (51, 'Χρυσαφί', NULL);
INSERT INTO basecolour VALUES (52, 'Ανοιχτό Μελί', NULL);
INSERT INTO basecolour VALUES (53, 'Lilac', NULL);
INSERT INTO basecolour VALUES (54, 'Lilac με χρωματιστές πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (55, 'Ροδοκόκκινο', NULL);
INSERT INTO basecolour VALUES (56, 'Φώκια', NULL);
INSERT INTO basecolour VALUES (57, 'Ασημί', NULL);
INSERT INTO basecolour VALUES (58, 'Καστανό', NULL);
INSERT INTO basecolour VALUES (59, 'Καστανό με πολύχρωμες πιτσιλιές', NULL);
INSERT INTO basecolour VALUES (6, 'Χελωνίτσα', NULL);
INSERT INTO basecolour VALUES (7, 'Τιγρέ', NULL);
INSERT INTO basecolour VALUES (8, 'Ανοιχτοκαστανό', NULL);
INSERT INTO basecolour VALUES (9, 'Μαύρο και ανοιχτοκαστανό', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (100, 'Greater Swiss Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Havanese', '', '', 1);
INSERT INTO breed VALUES (103, 'Hound', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibizan Hound', '', '', 1);
INSERT INTO breed VALUES (107, 'Illyrian Sheepdog', '', '', 1);
INSERT INTO breed VALUES (108, 'Irish Setter', '', '', 1);
INSERT INTO breed VALUES (109, 'Irish Terrier', '', '', 1);
INSERT INTO breed VALUES (10, 'American Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (110, 'Irish Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (111, 'Irish Wolfhound', '', '', 1);
INSERT INTO breed VALUES (112, 'Italian Greyhound', '', '', 1);
INSERT INTO breed VALUES (113, 'Italian Spinone', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Japanese Chin', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Dog', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelian Bear Dog', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshond', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolian Shepherd', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue Terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzell Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (130, 'Löwchen', '', '', 1);
INSERT INTO breed VALUES (131, 'Maltese', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremma Sheepdog', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Miniature Pinscher', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (13, 'Australian Cattle Dog/Blue Heeler', '', '', 1);
INSERT INTO breed VALUES (140, 'Neapolitan Mastiff', '', '', 1);
INSERT INTO breed VALUES (141, 'New Guinea Singing Dog', '', '', 1);
INSERT INTO breed VALUES (142, 'Newfoundland Dog', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich Terrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Norwegian Buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Norwegian Elkhound', '', '', 1);
INSERT INTO breed VALUES (147, 'Norwegian Lundehund', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia Duck-Tolling Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Old English Sheepdog', '', '', 1);
INSERT INTO breed VALUES (14, 'Australian Kelpie', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhound', '', '', 1);
INSERT INTO breed VALUES (151, 'Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier (Fell Terrier)', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekingese', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruvian Inca Orchid', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit Basset Griffon Vendeen', '', '', 1);
INSERT INTO breed VALUES (156, 'Pharaoh Hound', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Portugese Podengo', '', '', 1);
INSERT INTO breed VALUES (15, 'Australian Shepherd', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polish Lowland Sheepdog', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Poodle', '', '', 1);
INSERT INTO breed VALUES (164, 'Portuguese Water Dog', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Pug', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (16, 'Australian Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesian Ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'Saint Bernard St. Bernard', '', '', 1);
INSERT INTO breed VALUES (176, 'Samoyed', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Scottish Deerhound', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (180, 'Scottish Terrier Scottie', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Sheep Dog', '', '', 1);
INSERT INTO breed VALUES (185, 'Shepherd', '', '', 1);
INSERT INTO breed VALUES (186, 'Shetland Sheepdog Sheltie', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Siberian Husky', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (190, 'Silky Terrier', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Smooth Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'South Russian Ovcharka', '', '', 1);
INSERT INTO breed VALUES (198, 'Swedish Vallhund', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Tibetan Mastiff', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibetan Spaniel', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibetan Terrier', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimaraner', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier Westie', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'White German Shepherd', '', '', 1);
INSERT INTO breed VALUES (216, 'Wire-haired Pointing Griffon', '', '', 1);
INSERT INTO breed VALUES (217, 'Wirehaired Terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'Yellow Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier Yorkie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (220, 'Xoloitzcuintle/Mexican Hairless', '', '', 1);
INSERT INTO breed VALUES (221, 'Abyssinian', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'American Shorthair', '', '', 2);
INSERT INTO breed VALUES (224, 'American Wirehair', '', '', 2);
INSERT INTO breed VALUES (225, 'Applehead Siamese', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinese', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengal', '', '', 2);
INSERT INTO breed VALUES (228, 'Birman', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'British Shorthair', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmese', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Calico', '', '', 2);
INSERT INTO breed VALUES (235, 'Canadian Hairless', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (23, 'Belgian Shepherd Dog Sheepdog', '', '', 1);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (243, 'Domestic Long Hair', '', '', 2);
INSERT INTO breed VALUES (24, 'Belgian Shepherd Laekenois', '', '', 1);
INSERT INTO breed VALUES (252, 'Domestic Medium Hair', '', '', 2);
INSERT INTO breed VALUES (25, 'Belgian Shepherd Malinois', '', '', 1);
INSERT INTO breed VALUES (261, 'Domestic Short Hair', '', '', 2);
INSERT INTO breed VALUES (26, 'Belgian Shepherd Tervuren', '', '', 1);
INSERT INTO breed VALUES (271, 'Egyptian Mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Exotic Shorthair', '', '', 2);
INSERT INTO breed VALUES (273, 'Extra-Toes Cat (Hemingway Polydactyl)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Japanese Bobtail', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (27, 'Bernese Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Norwegian Forest Cat', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Oriental Long Hair', '', '', 2);
INSERT INTO breed VALUES (285, 'Oriental Short Hair', '', '', 2);
INSERT INTO breed VALUES (286, 'Oriental Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'Persian', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (28, 'Bichon Frise', '', '', 1);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Russian Blue', '', '', 2);
INSERT INTO breed VALUES (292, 'Scottish Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siamese', '', '', 2);
INSERT INTO breed VALUES (295, 'Siberian', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somali', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphynx (hairless cat)', '', '', 2);
INSERT INTO breed VALUES (29, 'Black and Tan Coonhound', '', '', 1);
INSERT INTO breed VALUES (2, 'Afghan Hound', '', '', 1);
INSERT INTO breed VALUES (307, 'Tiger', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkinese', '', '', 2);
INSERT INTO breed VALUES (30, 'Black Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (311, 'Turkish Angora', '', '', 2);
INSERT INTO breed VALUES (312, 'Turkish Van', '', '', 2);
INSERT INTO breed VALUES (314, 'American', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angora Rabbit', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Dutch', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (32, 'Bloodhound', '', '', 1);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polish', '', '', 7);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Μεταξένιο', '', '', 7);
INSERT INTO breed VALUES (353, 'Ασημί', '', '', 7);
INSERT INTO breed VALUES (354, 'Αλεπού πολικών περιοχών', '', '', 7);
INSERT INTO breed VALUES (355, 'Κουνέλι Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Ανοιχτοκαστανό', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabian', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (360, 'Donkey/Mule', '', '', 26);
INSERT INTO breed VALUES (361, 'Ergas;iaw', '', '', 24);
INSERT INTO breed VALUES (362, 'Ήρεμος Καλπασμός', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (36, 'Borzoi', '', '', 1);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (37, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (380, 'Ferret', '', '', 3);
INSERT INTO breed VALUES (381, 'Gerbil', '', '', 18);
INSERT INTO breed VALUES (382, 'Guinea Pig', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Hedgehog', '', '', 6);
INSERT INTO breed VALUES (385, 'Ποντίκι', '', '', 4);
INSERT INTO breed VALUES (386, 'Κυνόμυς', '', '', 5);
INSERT INTO breed VALUES (387, 'Αρουραίος', '', '', 5);
INSERT INTO breed VALUES (388, 'Βρομοκούναβο', '', '', 5);
INSERT INTO breed VALUES (389, 'Ιπτάμενος σκίουρος ζάχαρης', '', '', 5);
INSERT INTO breed VALUES (38, 'Bouvier des Flanders', '', '', 1);
INSERT INTO breed VALUES (390, 'Χοίρος Pot bellied', '', '', 28);
INSERT INTO breed VALUES (391, 'Χοίρος Βιετναμέζικος Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (392, 'Σαύρα', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Σαύρα', '', '', 13);
INSERT INTO breed VALUES (395, 'Φίδι', '', '', 13);
INSERT INTO breed VALUES (396, 'Χελώνα', '', '', 13);
INSERT INTO breed VALUES (397, 'Ψάρι', '', '', 21);
INSERT INTO breed VALUES (398, 'Αφρικανικός γκρίζος', '', '', 3);
INSERT INTO breed VALUES (399, 'Παπαγάλος Αμαζόνα', '', '', 3);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Μελοψίττακος ο κυματοειδής', '', '', 3);
INSERT INTO breed VALUES (402, 'Παπαγάλος Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Καναρίνι', '', '', 3);
INSERT INTO breed VALUES (404, 'Κοτόπουλο', '', '', 3);
INSERT INTO breed VALUES (405, 'Παπαγάλος Μαύρη κακατούα', '', '', 3);
INSERT INTO breed VALUES (406, 'Κακατούα', '', '', 3);
INSERT INTO breed VALUES (407, 'Παπαγάλος Κονούρα', '', '', 3);
INSERT INTO breed VALUES (408, 'Περιστέρι', '', '', 3);
INSERT INTO breed VALUES (409, 'Πάπια', '', '', 3);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (410, 'Παπαγάλος eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Σπίνος', '', '', 3);
INSERT INTO breed VALUES (413, 'Χήνα', '', '', 3);
INSERT INTO breed VALUES (414, 'Πουλί της Γουινέας', '', '', 3);
INSERT INTO breed VALUES (415, 'Παπαγάλος Ν. Ζηλανδίας', '', '', 3);
INSERT INTO breed VALUES (416, 'Παπαγάλος ψιττακός Αυστραλίας', '', '', 3);
INSERT INTO breed VALUES (417, 'Παπαγάλος Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Παπαγάλος Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Μάινα', '', '', 3);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (420, 'Στρουθοκάμηλος', '', '', 3);
INSERT INTO breed VALUES (421, 'Παπαγάλος', '', '', 3);
INSERT INTO breed VALUES (422, 'Ψιττακός', '', '', 3);
INSERT INTO breed VALUES (423, 'Παπαγαλάκια', '', '', 3);
INSERT INTO breed VALUES (424, 'Παγώνι', '', '', 3);
INSERT INTO breed VALUES (425, 'Φασιανός', '', '', 3);
INSERT INTO breed VALUES (426, 'Περιστέρι', '', '', 3);
INSERT INTO breed VALUES (427, 'Παπαγάλος Μεξικού Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Παπαγάλος Αφροτροπικός - Σενεγαλάκι', '', '', 3);
INSERT INTO breed VALUES (429, 'Παπαγάλος Αργεντινής Quaker', '', '', 3);
INSERT INTO breed VALUES (42, 'Brittany Spaniel', '', '', 1);
INSERT INTO breed VALUES (430, 'ρέα Αμερικάνα', '', '', 3);
INSERT INTO breed VALUES (431, 'Παπαγάλος ringneck', '', '', 3);
INSERT INTO breed VALUES (432, 'Παπαγάλος rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Πουλί softbill (άλλα)', '', '', 3);
INSERT INTO breed VALUES (434, 'Κύκνος', '', '', 3);
INSERT INTO breed VALUES (435, 'Πουλί Toucan', '', '', 3);
INSERT INTO breed VALUES (436, 'Γαλοπούλα', '', '', 3);
INSERT INTO breed VALUES (437, 'Αγελάδα', '', '', 16);
INSERT INTO breed VALUES (438, 'Γίδα', '', '', 16);
INSERT INTO breed VALUES (439, 'Πρόβατο', '', '', 16);
INSERT INTO breed VALUES (43, 'Brussels Griffon', '', '', 1);
INSERT INTO breed VALUES (440, 'Λάμα', '', '', 16);
INSERT INTO breed VALUES (441, 'Χοίρος (Φάρμα)', '', '', 28);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Canaan Dog', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso Mastiff', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina Dog', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Cattle Dog', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bay Retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chinese Crested Dog', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinese Foo Dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Chocolate Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Dachshund', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatian', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Doberman Pinscher', '', '', 1);
INSERT INTO breed VALUES (6, 'Alaskan Malamute', '', '', 1);
INSERT INTO breed VALUES (70, 'Dogo Argentino', '', '', 1);
INSERT INTO breed VALUES (71, 'Dogue de Bordeaux', '', '', 1);
INSERT INTO breed VALUES (72, 'Dutch Shepherd', '', '', 1);
INSERT INTO breed VALUES (73, 'English Bulldog', '', '', 1);
INSERT INTO breed VALUES (74, 'English Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (75, 'English Coonhound', '', '', 1);
INSERT INTO breed VALUES (76, 'English Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'English Setter', '', '', 1);
INSERT INTO breed VALUES (78, 'English Shepherd', '', '', 1);
INSERT INTO breed VALUES (79, 'English Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (7, 'American Bulldog', '', '', 1);
INSERT INTO breed VALUES (80, 'English Toy Spaniel', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila Brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Finnish Lapphund', '', '', 1);
INSERT INTO breed VALUES (86, 'Finnish Spitz', '', '', 1);
INSERT INTO breed VALUES (87, 'Flat-coated Retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (8, 'American Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (90, 'French Bulldog', '', '', 1);
INSERT INTO breed VALUES (91, 'German Pinscher', '', '', 1);
INSERT INTO breed VALUES (92, 'German Shepherd Dog', '', '', 1);
INSERT INTO breed VALUES (93, 'German Shorthaired Pointer', '', '', 1);
INSERT INTO breed VALUES (94, 'German Wirehaired Pointer', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Great Dane', '', '', 1);
INSERT INTO breed VALUES (99, 'Great Pyrenees', '', '', 1);
INSERT INTO breed VALUES (9, 'American Staffordshire Terrier', '', '', 1);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%Name';
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Νεογέννητο');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Νεαρό ενήλικο');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Ενήλικο');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Ηλικιωμένος');
INSERT INTO configuration VALUES ('Organisation', 'Οργανισμός');
DELETE FROM costtype;
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Ζώα χωρίς μικροτσίπ', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Επιθε');
INSERT INTO customreport VALUES (37, 'Ζώα χωρίς φωτογραφία', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Επιθε');
INSERT INTO customreport VALUES (38, 'Ζώα που ποτέ δεν εμβολιάστηκαν', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Επιθε');
INSERT INTO customreport VALUES (39, 'Μη στειρωμένα ζώα ηλικίας άνω των 6 μηνών', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Επιθε');
INSERT INTO customreport VALUES (40, 'Γάτες χωρίς πολλαπλό τεστ', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Επιθε');
INSERT INTO customreport VALUES (41, 'Μηνιαίος αριθμός ζώων', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Αριθμοί');
INSERT INTO customreport VALUES (42, 'Ζώα μακράς διαμονής', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Αριθμοί');
INSERT INTO customreport VALUES (43, 'Κατάσταση καταφυγίου', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Καταστάσεις');
INSERT INTO customreport VALUES (44, 'Αναλυτική κατάσταση καταφυγίου', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Καταστάσεις');
INSERT INTO customreport VALUES (45, 'Ζώα που δεν είναι μέλη μιας γέννας', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Γέννες');
INSERT INTO customreport VALUES (46, 'Εισερχόμενα/εξερχόμενα', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Μετακινήσεις');
INSERT INTO customreport VALUES (47, 'Σύνοψη εισερχόμενων/εξερχόμενων', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Μετακινήσεις');
INSERT INTO customreport VALUES (48, 'Αναφορά εισερχόμενων', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Μετακινήσεις');
INSERT INTO customreport VALUES (49, 'Πλήθος υιοθεσιών ανά πωλητή λιανικής', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Μεταπωλητές');
INSERT INTO customreport VALUES (50, 'Μέσος χρόνος παραμονής σε πωλητή λιανικής πριν την υιοθεσία', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Μεταπωλητές');
INSERT INTO customreport VALUES (51, 'Κατάσταση πωλητή λιανικής', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Μεταπωλητές');
INSERT INTO customreport VALUES (52, 'Αναφορά επιστραφέντων ζώων', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Επιστροφές');
INSERT INTO customreport VALUES (53, 'Ζώα επιστραφέντα εντός 6 μηνών', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Επιστροφές');
INSERT INTO customreport VALUES (54, 'Ζώα επιστραφέντα έπειτα από 6 μήνες', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Επιστροφές');
INSERT INTO customreport VALUES (55, 'Πιο συνηθισμένο όνομα', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Στατιστικά');
INSERT INTO customreport VALUES (56, 'Αιτίες θανάτου ζώου', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Στατιστικά');
INSERT INTO customreport VALUES (57, 'Πιο συνηθισμένες περιοχές εισδοχής', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Στατιστικά');
INSERT INTO customreport VALUES (58, 'Πιο συνηθισμένες περιοχές υιοθεσίας', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Στατιστικά');
INSERT INTO customreport VALUES (59, 'Μέσος χρόνος στην λίστα αναμονής', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Στατιστικά');
INSERT INTO customreport VALUES (60, 'Μηνιαίες Δωρεές', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Γραφήματα οικονομικά');
INSERT INTO customreport VALUES (61, 'Μηνιαίες δωρεές ανά είδος ζώου', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Γραφήματα οικονομικά');
INSERT INTO customreport VALUES (62, 'Μηνιαίες υιοθεσίες ανά είδος ζώου', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Γραφήματα μετακινήσεων');
INSERT INTO customreport VALUES (63, 'Μηνιαίες υιοθεσίες ανά περιοχή', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Γραφήματα μετακινήσεων');
INSERT INTO customreport VALUES (64, 'Λόγοι εισαγωγής ζώου', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Γραφήματα μετακινήσεων');
INSERT INTO customreport VALUES (65, 'Λόγοι επιστροφής ζώου', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Γραφήματα μετακινήσεων');
INSERT INTO customreport VALUES (66, 'Κριτήρια επιλογής ιδιοκτήτη', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Καταστάσεις');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Θάνατος κατά την άφιξη', '');
INSERT INTO deathreason VALUES (2, 'Απεβίωσε', '');
INSERT INTO deathreason VALUES (3, 'Υγιής', '');
INSERT INTO deathreason VALUES (4, 'Άρρωστο/τραυματισμένο', '');
INSERT INTO deathreason VALUES (5, 'Ζητήθηκε', '');
INSERT INTO deathreason VALUES (6, 'Επιλογή', '');
INSERT INTO deathreason VALUES (7, 'Άγριο', '');
INSERT INTO deathreason VALUES (8, 'Δαγκώνει', '');
DELETE FROM diet;
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Δωρεά', '');
INSERT INTO donationtype VALUES (2, 'Τέλη υιοθεσίας', '');
INSERT INTO donationtype VALUES (3, 'Λίστα αναμονής υιοθεσιών', '');
INSERT INTO donationtype VALUES (4, 'Δωρεά εισαγωγής', '');
INSERT INTO donationtype VALUES (5, 'Χορηγία ζώου', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Διάλυση γάμου/σχέσης', '');
INSERT INTO entryreason VALUES (10, 'Κακοποιημένο', '');
INSERT INTO entryreason VALUES (11, 'Εγκαταλειμμένο', '');
INSERT INTO entryreason VALUES (2, 'Αλλεργίες', '');
INSERT INTO entryreason VALUES (3, 'Δαγκώνει', '');
INSERT INTO entryreason VALUES (4, 'Δεν μπορεί να ανταπεξέλθει', '');
INSERT INTO entryreason VALUES (5, 'Ακατάλληλη εγκατάσταση διαμονής', '');
INSERT INTO entryreason VALUES (6, 'Απεβίωσε', '');
INSERT INTO entryreason VALUES (7, 'Αδέσποτο', '');
INSERT INTO entryreason VALUES (8, 'Άρρωστο/τραυματισμένο', '');
INSERT INTO entryreason VALUES (9, 'Δεν μπορεί να ανταπεξέλθει οικονομικά', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Χωρίς τοποθεσίες', '');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Κοντό');
INSERT INTO lkcoattype VALUES (1, 'Μακρύ');
INSERT INTO lkcoattype VALUES (2, 'Σκληρό');
INSERT INTO lkcoattype VALUES (3, 'Μπουκλες');
INSERT INTO lkcoattype VALUES (4, 'Κοτσιδες');
INSERT INTO lkcoattype VALUES (5, 'Χωρίς τρίχωμα');
DELETE FROM lksaccounttype;
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Κανένα');
INSERT INTO lksdiarylink VALUES (1, 'Ζώο');
INSERT INTO lksdiarylink VALUES (2, 'Ιδιοκτήτης');
INSERT INTO lksdiarylink VALUES (3, 'Χαμένο Ζώο');
INSERT INTO lksdiarylink VALUES (4, 'Ευρεθέν ζώο');
INSERT INTO lksdiarylink VALUES (5, 'Λίστα αναμονής');
INSERT INTO lksdiarylink VALUES (6, 'Μετακίνηση');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'Άπαξ');
INSERT INTO lksdonationfreq VALUES (1, 'Εβδομαδιαία');
INSERT INTO lksdonationfreq VALUES (2, 'Μηνιαία');
INSERT INTO lksdonationfreq VALUES (3, 'Τριμηνιαίο');
INSERT INTO lksdonationfreq VALUES (4, 'Εξαμηνιαίως');
INSERT INTO lksdonationfreq VALUES (5, 'Ετησίως');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Θηλυκό');
INSERT INTO lksex VALUES (1, 'Αρσενικό');
INSERT INTO lksex VALUES (2, 'Άγνωστο');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Ζώο');
INSERT INTO lksfieldlink VALUES (1, 'Ιδιοκτήτης');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Ναί/Όχι');
INSERT INTO lksfieldtype VALUES (1, 'Κείμενο');
INSERT INTO lksfieldtype VALUES (2, 'Σημειώσεις');
INSERT INTO lksfieldtype VALUES (3, 'Νούμερο');
INSERT INTO lksfieldtype VALUES (4, 'Ημερομηνία');
INSERT INTO lksfieldtype VALUES (5, 'Χρήματα');
INSERT INTO lksfieldtype VALUES (6, 'Αναζήτηση');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Πολύ μεγάλο');
INSERT INTO lksize VALUES (1, 'Μεγάλο');
INSERT INTO lksize VALUES (2, 'Μεσαίο');
INSERT INTO lksize VALUES (3, 'Μικρό');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Ζώο');
INSERT INTO lksloglink VALUES (1, 'Ιδιοκτήτης');
INSERT INTO lksloglink VALUES (2, 'Χαμένο Ζώο');
INSERT INTO lksloglink VALUES (3, 'Ευρεθέν ζώο');
INSERT INTO lksloglink VALUES (4, 'Λίστα αναμονής');
INSERT INTO lksloglink VALUES (5, 'Μετακίνηση');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Ζώο');
INSERT INTO lksmedialink VALUES (1, 'Χαμένο Ζώο');
INSERT INTO lksmedialink VALUES (2, 'Ευρεθέν ζώο');
INSERT INTO lksmedialink VALUES (3, 'Ιδιοκτήτης');
INSERT INTO lksmedialink VALUES (4, 'Μετακίνηση');
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Κανένα');
INSERT INTO lksmovementtype VALUES (1, 'Υιοθεσία');
INSERT INTO lksmovementtype VALUES (10, 'Ακύρωση κράτησης');
INSERT INTO lksmovementtype VALUES (2, 'Ανάδοχος');
INSERT INTO lksmovementtype VALUES (3, 'Μεταβίβαση');
INSERT INTO lksmovementtype VALUES (4, 'Δραπέτευσε');
INSERT INTO lksmovementtype VALUES (5, 'Ζητήθηκε επανάκτηση');
INSERT INTO lksmovementtype VALUES (6, 'Κλεμμένο');
INSERT INTO lksmovementtype VALUES (7, 'Απελευθέρωση στη φύση');
INSERT INTO lksmovementtype VALUES (8, 'Πωλητής Λιανικής');
INSERT INTO lksmovementtype VALUES (9, 'Κράτηση');
DELETE FROM lksposneg;
DELETE FROM lksyesno;
DELETE FROM lksynun;
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Επείγον');
INSERT INTO lkurgency VALUES (2, 'Υψηλο');
INSERT INTO lkurgency VALUES (3, 'Μεσαίο');
INSERT INTO lkurgency VALUES (4, 'Χαμηλό');
INSERT INTO lkurgency VALUES (5, 'Χαμηλότερο');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Δάγκωμα', '');
INSERT INTO logtype VALUES (2, 'Παράπονο', '');
INSERT INTO logtype VALUES (3, 'Ιστορικό', '');
INSERT INTO logtype VALUES (4, 'Βάρος', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Σκύλος', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Φίδι', '', '');
INSERT INTO species VALUES (12, 'Χελώνα', '', '');
INSERT INTO species VALUES (13, 'Χελώνα terrapin', '', '');
INSERT INTO species VALUES (14, 'Κοτόπουλο', '', '');
INSERT INTO species VALUES (15, 'Κουκουβάγια', '', '');
INSERT INTO species VALUES (16, 'Γίδα', '', '');
INSERT INTO species VALUES (17, 'Χήνα', '', '');
INSERT INTO species VALUES (18, 'Gerbil', '', '');
INSERT INTO species VALUES (19, 'Παπαγάλος Μαύρη κακατούα', '', '');
INSERT INTO species VALUES (2, 'Γάτα', '', '');
INSERT INTO species VALUES (20, 'Guinea Pig', '', '');
INSERT INTO species VALUES (21, 'Χρυσόψαρο', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Καμήλα', '', '');
INSERT INTO species VALUES (24, 'Άλογο', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Γαιδούρι', '', '');
INSERT INTO species VALUES (27, 'Λάμα', '', '');
INSERT INTO species VALUES (28, 'Χοίρος', '', '');
INSERT INTO species VALUES (3, 'Πτηνό', '', '');
INSERT INTO species VALUES (4, 'Ποντίκι', '', '');
INSERT INTO species VALUES (5, 'Αρουραίος', '', '');
INSERT INTO species VALUES (6, 'Hedgehog', '', '');
INSERT INTO species VALUES (7, 'Λαγός', '', '');
INSERT INTO species VALUES (8, 'Περιστέρι', '', '');
INSERT INTO species VALUES (9, 'Ferret', '', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Προσωρινός εμβολιασμός', '');
INSERT INTO vaccinationtype VALUES (2, 'Πρώτος εμβολιασμός', '');
INSERT INTO vaccinationtype VALUES (3, 'Δεύτερος εμβολιασμός', '');
INSERT INTO vaccinationtype VALUES (4, 'Ενισχυτική δόση', '');
INSERT INTO vaccinationtype VALUES (5, 'Λευχαιμία', '');
INSERT INTO vaccinationtype VALUES (6, 'Βήχας κυνοτροφείου', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvo ιός', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Στείρωση', '');
