DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (כלב)', NULL);
INSERT INTO animaltype VALUES (10, 'F (כלב תועה)', NULL);
INSERT INTO animaltype VALUES (11, 'U (חתול לא רצוי)', NULL);
INSERT INTO animaltype VALUES (12, 'S (חתול תועה)', NULL);
INSERT INTO animaltype VALUES (13, 'M (שונות)', NULL);
INSERT INTO animaltype VALUES (40, 'N (חיית מחמד שאינה במקלט)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'שחור', NULL);
INSERT INTO basecolour VALUES (2, 'לבן', NULL);
INSERT INTO basecolour VALUES (3, 'שחור ולבן', NULL);
INSERT INTO basecolour VALUES (4, 'ג''ינג''י', NULL);
INSERT INTO basecolour VALUES (5, 'לבן ושחור', NULL);
INSERT INTO basecolour VALUES (6, 'טורטי', NULL);
INSERT INTO basecolour VALUES (7, 'טאבי', NULL);
INSERT INTO basecolour VALUES (8, 'חום־צהבהב', NULL);
INSERT INTO basecolour VALUES (9, 'שחור וחום־צהבהב', NULL);
INSERT INTO basecolour VALUES (10, 'חום־צהבהב ושחור', NULL);
INSERT INTO basecolour VALUES (11, 'חום', NULL);
INSERT INTO basecolour VALUES (12, 'חום ושחור', NULL);
INSERT INTO basecolour VALUES (13, 'שחור וחום', NULL);
INSERT INTO basecolour VALUES (14, 'מנומר', NULL);
INSERT INTO basecolour VALUES (15, 'מנומר ושחור', NULL);
INSERT INTO basecolour VALUES (16, 'מנומר ולבן', NULL);
INSERT INTO basecolour VALUES (17, 'שחור ומנומר', NULL);
INSERT INTO basecolour VALUES (18, 'לבן ומנומר', NULL);
INSERT INTO basecolour VALUES (19, 'תלת־צבעי', NULL);
INSERT INTO basecolour VALUES (20, 'חום כהה', NULL);
INSERT INTO basecolour VALUES (21, 'חום כהה ולבן', NULL);
INSERT INTO basecolour VALUES (22, 'לבן וחום כהה', NULL);
INSERT INTO basecolour VALUES (23, 'קרם', NULL);
INSERT INTO basecolour VALUES (24, 'חום־צהבהב ולבן', NULL);
INSERT INTO basecolour VALUES (26, 'לבן וחום־צהבהב', NULL);
INSERT INTO basecolour VALUES (27, 'טורטי ולבן', NULL);
INSERT INTO basecolour VALUES (28, 'טאבי ולבן', NULL);
INSERT INTO basecolour VALUES (29, 'ג''ינג''י ולבן', NULL);
INSERT INTO basecolour VALUES (30, 'אפור', NULL);
INSERT INTO basecolour VALUES (31, 'אפור ולבן', NULL);
INSERT INTO basecolour VALUES (32, 'לבן ואפור', NULL);
INSERT INTO basecolour VALUES (33, 'לבן וטורטי', NULL);
INSERT INTO basecolour VALUES (35, 'חום ולבן', NULL);
INSERT INTO basecolour VALUES (36, 'כחול', NULL);
INSERT INTO basecolour VALUES (37, 'לבן וטאבי', NULL);
INSERT INTO basecolour VALUES (38, 'צהוב ואפור', NULL);
INSERT INTO basecolour VALUES (39, 'מגוון', NULL);
INSERT INTO basecolour VALUES (40, 'לבן וחום', NULL);
INSERT INTO basecolour VALUES (41, 'ירוק', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'אפנפינצ''ר', '', '', 1);
INSERT INTO breed VALUES (2, 'אפגני', '', '', 1);
INSERT INTO breed VALUES (3, 'איירדייל טרייר', '', '', 1);
INSERT INTO breed VALUES (4, 'אקבש', '', '', 1);
INSERT INTO breed VALUES (5, 'אקיטה', '', '', 1);
INSERT INTO breed VALUES (6, 'אלסקן מלמוט', '', '', 1);
INSERT INTO breed VALUES (7, 'בולדוג אמריקאי', '', '', 1);
INSERT INTO breed VALUES (8, 'כלב אסקימו אמריקאי', '', '', 1);
INSERT INTO breed VALUES (9, 'אמסטף', '', '', 1);
INSERT INTO breed VALUES (10, 'American Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolian Shepherd', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzell Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (13, 'כלב בקר אוסטרלי/רועה אוסטרלי', '', '', 1);
INSERT INTO breed VALUES (14, 'Australian Kelpie', '', '', 1);
INSERT INTO breed VALUES (15, 'רועה אוסטרלי', '', '', 1);
INSERT INTO breed VALUES (16, 'Australian Terrier', '', '', 1);
INSERT INTO breed VALUES (17, 'בסנג''י', '', '', 1);
INSERT INTO breed VALUES (18, 'באסט', '', '', 1);
INSERT INTO breed VALUES (19, 'בייגל', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgian Shepherd Dog Sheepdog', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgian Shepherd Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgian Shepherd Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgian Shepherd Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'כלב ברנזי', '', '', 1);
INSERT INTO breed VALUES (28, 'בישון פריזה', '', '', 1);
INSERT INTO breed VALUES (29, 'Black and Tan Coonhound', '', '', 1);
INSERT INTO breed VALUES (30, 'לברדור רטריבר שחור', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Bloodhound', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'בורדר קולי', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'בורזוי', '', '', 1);
INSERT INTO breed VALUES (37, 'בוסטון טרייר', '', '', 1);
INSERT INTO breed VALUES (38, 'Bouvier des Flanders', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'בוקסר', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Brittany Spaniel', '', '', 1);
INSERT INTO breed VALUES (43, 'Brussels Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'קאירן טרייר', '', '', 1);
INSERT INTO breed VALUES (47, 'רועה כנעני', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso Mastiff', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina Dog', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Cattle Dog', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bay Retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'צ''יוואווה', '', '', 1);
INSERT INTO breed VALUES (55, 'סיני מצויץ', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinese Foo Dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Chocolate Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'צ''או צ''או', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'קוקר ספניאל', '', '', 1);
INSERT INTO breed VALUES (62, 'קולי', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'תחש', '', '', 1);
INSERT INTO breed VALUES (67, 'דלמטי', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'דוברמן', '', '', 1);
INSERT INTO breed VALUES (70, 'דוגו ארגנטינו', '', '', 1);
INSERT INTO breed VALUES (71, 'דוג דה בורדו', '', '', 1);
INSERT INTO breed VALUES (72, 'Dutch Shepherd', '', '', 1);
INSERT INTO breed VALUES (73, 'בולדוג אנגלי', '', '', 1);
INSERT INTO breed VALUES (74, 'קוקר ספניאל אנגלי', '', '', 1);
INSERT INTO breed VALUES (75, 'English Coonhound', '', '', 1);
INSERT INTO breed VALUES (76, 'English Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'סטר אנגלי', '', '', 1);
INSERT INTO breed VALUES (78, 'English Shepherd', '', '', 1);
INSERT INTO breed VALUES (79, 'ספרינגר ספניאל אנגלי', '', '', 1);
INSERT INTO breed VALUES (80, 'English Toy Spaniel', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila Brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Finnish Lapphund', '', '', 1);
INSERT INTO breed VALUES (86, 'Finnish Spitz', '', '', 1);
INSERT INTO breed VALUES (87, 'Flat-coated Retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'בולדוג צרפתי', '', '', 1);
INSERT INTO breed VALUES (91, 'German Pinscher', '', '', 1);
INSERT INTO breed VALUES (92, 'רועה גרמני', '', '', 1);
INSERT INTO breed VALUES (93, 'פוינטר גרמני קצר שיער', '', '', 1);
INSERT INTO breed VALUES (94, 'German Wirehaired Pointer', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'גולדן רטריבר', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'דני ענק', '', '', 1);
INSERT INTO breed VALUES (99, 'פירנאי', '', '', 1);
INSERT INTO breed VALUES (100, 'Greater Swiss Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (101, 'גרייהאונד', '', '', 1);
INSERT INTO breed VALUES (102, 'הוואנז', '', '', 1);
INSERT INTO breed VALUES (103, 'Hound', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibizan Hound', '', '', 1);
INSERT INTO breed VALUES (107, 'Illyrian Sheepdog', '', '', 1);
INSERT INTO breed VALUES (108, 'סטר אירי', '', '', 1);
INSERT INTO breed VALUES (109, 'Irish Terrier', '', '', 1);
INSERT INTO breed VALUES (110, 'Irish Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (111, 'וולפהאונד אירי', '', '', 1);
INSERT INTO breed VALUES (112, 'גרייהאונד איטלקי', '', '', 1);
INSERT INTO breed VALUES (113, 'Italian Spinone', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Japanese Chin', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Dog', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelian Bear Dog', '', '', 1);
INSERT INTO breed VALUES (119, 'קיסהאונד', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue Terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'לברדור רטריבר', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'להאסה אפסו', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Löwchen', '', '', 1);
INSERT INTO breed VALUES (131, 'מלטזי', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremma Sheepdog', '', '', 1);
INSERT INTO breed VALUES (134, 'מסטיף', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'פינצ''ר ננסי', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (140, 'Neapolitan Mastiff', '', '', 1);
INSERT INTO breed VALUES (141, 'New Guinea Singing Dog', '', '', 1);
INSERT INTO breed VALUES (142, 'כלב ניופאונדלנד', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich Terrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Norwegian Buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'אלקהאונד נורבגי', '', '', 1);
INSERT INTO breed VALUES (147, 'Norwegian Lundehund', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia Duck-Tolling Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'כלב צאן אנגלי עתיק', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhound', '', '', 1);
INSERT INTO breed VALUES (151, 'פפילון', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier (Fell Terrier)', '', '', 1);
INSERT INTO breed VALUES (153, 'פקינז', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruvian Inca Orchid', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit Basset Griffon Vendeen', '', '', 1);
INSERT INTO breed VALUES (156, 'האונד פרעה', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Portugese Podengo', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polish Lowland Sheepdog', '', '', 1);
INSERT INTO breed VALUES (162, 'פומרניאן', '', '', 1);
INSERT INTO breed VALUES (163, 'פודל', '', '', 1);
INSERT INTO breed VALUES (164, 'Portuguese Water Dog', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'פאג', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'רודז''יאן רידג''בק', '', '', 1);
INSERT INTO breed VALUES (173, 'רוטוויילר', '', '', 1);
INSERT INTO breed VALUES (174, 'סלוקי', '', '', 1);
INSERT INTO breed VALUES (175, 'סאן ברנרד', '', '', 1);
INSERT INTO breed VALUES (176, 'סאמוייד', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Scottish Deerhound', '', '', 1);
INSERT INTO breed VALUES (180, 'טרייר סקוטי', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Sheep Dog', '', '', 1);
INSERT INTO breed VALUES (185, 'Shepherd', '', '', 1);
INSERT INTO breed VALUES (186, 'שלטי', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'שי צו', '', '', 1);
INSERT INTO breed VALUES (189, 'האסקי סיבירי', '', '', 1);
INSERT INTO breed VALUES (190, 'Silky Terrier', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Smooth Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'South Russian Ovcharka', '', '', 1);
INSERT INTO breed VALUES (198, 'Swedish Vallhund', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'מסטיף טיבטי', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibetan Spaniel', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibetan Terrier', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'ויימרנר', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier Westie', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'ויפט', '', '', 1);
INSERT INTO breed VALUES (215, 'רועה גרמני לבן', '', '', 1);
INSERT INTO breed VALUES (216, 'Wire-haired Pointing Griffon', '', '', 1);
INSERT INTO breed VALUES (217, 'Wirehaired Terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'לברדור רטריבר צהוב', '', '', 1);
INSERT INTO breed VALUES (219, 'יורקשייר טרייר', '', '', 1);
INSERT INTO breed VALUES (220, 'Xoloitzcuintle/Mexican Hairless', '', '', 1);
INSERT INTO breed VALUES (221, 'אבסיני (חבשי)', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'אמריקאי קצר שיער', '', '', 2);
INSERT INTO breed VALUES (224, 'אמריקאי מקורזל', '', '', 2);
INSERT INTO breed VALUES (225, 'Applehead Siamese', '', '', 2);
INSERT INTO breed VALUES (226, 'בלינזי', '', '', 2);
INSERT INTO breed VALUES (227, 'בנגלי', '', '', 2);
INSERT INTO breed VALUES (228, 'בירמן', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'בומביי', '', '', 2);
INSERT INTO breed VALUES (231, 'בריטי קצר שער', '', '', 2);
INSERT INTO breed VALUES (232, 'בורמזי', '', '', 2);
INSERT INTO breed VALUES (233, 'בורמילה', '', '', 2);
INSERT INTO breed VALUES (234, 'Calico', '', '', 2);
INSERT INTO breed VALUES (235, 'Canadian Hairless', '', '', 2);
INSERT INTO breed VALUES (236, 'שארטרה', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'קורניש רקס', '', '', 2);
INSERT INTO breed VALUES (239, 'קימריק', '', '', 2);
INSERT INTO breed VALUES (240, 'דבון רקס', '', '', 2);
INSERT INTO breed VALUES (241, 'Dilute Calico', '', '', 2);
INSERT INTO breed VALUES (242, 'Dilute Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (243, 'Domestic Long Hair', '', '', 2);
INSERT INTO breed VALUES (252, 'Domestic Medium Hair', '', '', 2);
INSERT INTO breed VALUES (261, 'Domestic Short Hair', '', '', 2);
INSERT INTO breed VALUES (271, 'מאו מצרי', '', '', 2);
INSERT INTO breed VALUES (272, 'אקזוטי קצר שער', '', '', 2);
INSERT INTO breed VALUES (273, 'Extra-Toes Cat (Hemingway Polydactyl)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Japanese Bobtail', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'קוראט', '', '', 2);
INSERT INTO breed VALUES (279, 'מיין קון', '', '', 2);
INSERT INTO breed VALUES (280, 'מנקס', '', '', 2);
INSERT INTO breed VALUES (281, 'מנצ''קין', '', '', 2);
INSERT INTO breed VALUES (282, 'חתול יערות נורבגי', '', '', 2);
INSERT INTO breed VALUES (283, 'אוסיקט', '', '', 2);
INSERT INTO breed VALUES (284, 'אוריינטלי ארוך שער', '', '', 2);
INSERT INTO breed VALUES (285, 'אוריינטלי קצר שער', '', '', 2);
INSERT INTO breed VALUES (286, 'Oriental Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'פרסי', '', '', 2);
INSERT INTO breed VALUES (288, 'פיקסי־בוב', '', '', 2);
INSERT INTO breed VALUES (289, 'ראגמאפין', '', '', 2);
INSERT INTO breed VALUES (290, 'רגדול', '', '', 2);
INSERT INTO breed VALUES (291, 'רוסי כחול', '', '', 2);
INSERT INTO breed VALUES (292, 'סקוטי שמוט אוזניים', '', '', 2);
INSERT INTO breed VALUES (293, 'סלקירק רקס', '', '', 2);
INSERT INTO breed VALUES (294, 'סיאמי', '', '', 2);
INSERT INTO breed VALUES (295, 'סיבירי', '', '', 2);
INSERT INTO breed VALUES (296, 'סינגפורה', '', '', 2);
INSERT INTO breed VALUES (297, 'סנואו־שו', '', '', 2);
INSERT INTO breed VALUES (298, 'סומלי', '', '', 2);
INSERT INTO breed VALUES (299, 'ספינקס (חתול חסר שער)', '', '', 2);
INSERT INTO breed VALUES (300, 'טאבי', '', '', 2);
INSERT INTO breed VALUES (307, 'Tiger', '', '', 2);
INSERT INTO breed VALUES (308, 'טונקינזי', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (311, 'אנגורה', '', '', 2);
INSERT INTO breed VALUES (312, 'ואן טורקי', '', '', 2);
INSERT INTO breed VALUES (313, 'Tuxedo', '', '', 2);
INSERT INTO breed VALUES (314, 'American', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angora Rabbit', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Dutch', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polish', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silver', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'חום־צהבהב', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'ערבי', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'חמור/פרד', '', '', 26);
INSERT INTO breed VALUES (361, 'Draft', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'מוסטנג', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'פוני', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'חמוס', '', '', 3);
INSERT INTO breed VALUES (381, 'גרביל', '', '', 18);
INSERT INTO breed VALUES (382, 'קביה', '', '', 20);
INSERT INTO breed VALUES (383, 'אוגר', '', '', 22);
INSERT INTO breed VALUES (384, 'קיפוד', '', '', 6);
INSERT INTO breed VALUES (385, 'עכבר', '', '', 4);
INSERT INTO breed VALUES (386, 'נובחנית', '', '', 5);
INSERT INTO breed VALUES (387, 'עכברוש', '', '', 5);
INSERT INTO breed VALUES (388, 'בואש', '', '', 5);
INSERT INTO breed VALUES (389, 'כיסן דואה', '', '', 5);
INSERT INTO breed VALUES (390, 'חזיר ננסי', '', '', 28);
INSERT INTO breed VALUES (391, 'חזיר ננסי ויאטנמי', '', '', 28);
INSERT INTO breed VALUES (392, 'שממית', '', '', 13);
INSERT INTO breed VALUES (393, 'איגואנה', '', '', 13);
INSERT INTO breed VALUES (394, 'לטאה', '', '', 13);
INSERT INTO breed VALUES (395, 'נחש', '', '', 13);
INSERT INTO breed VALUES (396, 'צב', '', '', 13);
INSERT INTO breed VALUES (397, 'דג', '', '', 21);
INSERT INTO breed VALUES (398, 'אפרור אפריקני', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Budgie/Budgerigar', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Canary', '', '', 3);
INSERT INTO breed VALUES (404, 'עוף', '', '', 3);
INSERT INTO breed VALUES (405, 'Cockatiel', '', '', 3);
INSERT INTO breed VALUES (406, 'Cockatoo', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'יונה', '', '', 3);
INSERT INTO breed VALUES (409, 'ברווז', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Finch', '', '', 3);
INSERT INTO breed VALUES (413, 'אווז', '', '', 3);
INSERT INTO breed VALUES (414, 'Guinea fowl', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lory/Lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Ostrich', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakeet (Other)', '', '', 3);
INSERT INTO breed VALUES (422, 'תוכי (אחר)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Peacock/Pea fowl', '', '', 3);
INSERT INTO breed VALUES (425, 'Pheasant', '', '', 3);
INSERT INTO breed VALUES (426, 'Pigeon', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'ננדו', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'ברבור', '', '', 3);
INSERT INTO breed VALUES (435, 'Toucan', '', '', 3);
INSERT INTO breed VALUES (436, 'תרנגול הודו', '', '', 3);
INSERT INTO breed VALUES (437, 'פרה', '', '', 16);
INSERT INTO breed VALUES (438, 'עז', '', '', 16);
INSERT INTO breed VALUES (439, 'כבשה', '', '', 16);
INSERT INTO breed VALUES (440, 'לאמה', '', '', 16);
INSERT INTO breed VALUES (441, 'חזיר (חווה)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%';
INSERT INTO configuration VALUES ('Organisation', 'ארגון');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'תינוק');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'נוער');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'בגיר');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'קשיש');
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'חיות מחמד ללא שבב', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (37, 'חיות מחמד ללא מדיה/תמונות', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (38, 'חיות מחמד שטרם חוסנו', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (39, 'חיות מחמד שאינן מסורסות/מעוקרות שגילן מעל חצי שנה', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (40, 'Cats Not Combi-Tested', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (41, 'Monthly Animal Figures', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (42, 'חיות מחמד לטווח ארוך', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (43, 'מאגר בית המחסה', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'מאגרים');
INSERT INTO customreport VALUES (44, 'מאגר מפורט של בית המחסה', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'מאגרים');
INSERT INTO customreport VALUES (45, 'חיות שאינן חלק מהמלטות', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'המלטות');
INSERT INTO customreport VALUES (46, 'כניסה\\יציאה', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'העברות');
INSERT INTO customreport VALUES (47, 'תקצירי כניסה/יציאה', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'העברות');
INSERT INTO customreport VALUES (48, 'Transfer In Report', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'העברות');
INSERT INTO customreport VALUES (49, 'נפח האימוצים לפי קמעונאי', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'קמעונאים');
INSERT INTO customreport VALUES (50, 'הזמן הממוצע אצל הקמעונאי בטרם האימוץ', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'קמעונאים');
INSERT INTO customreport VALUES (51, 'מאגר הקמעונאים', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'קמעונאים');
INSERT INTO customreport VALUES (52, 'יומן חיות המחמד שהוחזרו', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'החזרות');
INSERT INTO customreport VALUES (53, 'חיות מחמד שהוחזרו תוך חצי שנה', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'החזרות');
INSERT INTO customreport VALUES (54, 'חיות מחמד שהוחזרו לאחר חצי שנה', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'החזרות');
INSERT INTO customreport VALUES (55, 'השם הנפוץ ביותר', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'סטטיסטיקה');
INSERT INTO customreport VALUES (56, 'סיבות מות חיות המחמד', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'סטטיסטיקה');
INSERT INTO customreport VALUES (57, 'האזורים הנפוצים ביותר להכנסת חיות מחמד', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'סטטיסטיקה');
INSERT INTO customreport VALUES (58, 'האזורים הנפוצים ביותר לאימוץ חיות מחמד', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'סטטיסטיקה');
INSERT INTO customreport VALUES (59, 'הזמן הממוצע ברשימת המתנה', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'סטטיסטיקה');
INSERT INTO customreport VALUES (60, 'תרומות חודשיות', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'גרפים כלכליים');
INSERT INTO customreport VALUES (61, 'תרומות חודשיות לפי זן', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'גרפים כלכליים');
INSERT INTO customreport VALUES (62, 'אימוצים חודשיים לפי זן', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'גרפים להעברות');
INSERT INTO customreport VALUES (63, 'אימוצים חודשיים לפי מיקום', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'גרפים להעברות');
INSERT INTO customreport VALUES (64, 'הסיבות לכניסת חיית המחמד', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'גרפים להעברות');
INSERT INTO customreport VALUES (65, 'סיבות להחזרות חיות המחמד', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'גרפים להעברות');
INSERT INTO customreport VALUES (66, 'התאמת בעלים לקריטריונים', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'מאגרים');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'מת עם הגעתו', '');
INSERT INTO deathreason VALUES (2, 'מת', '');
INSERT INTO deathreason VALUES (3, 'בריא', '');
INSERT INTO deathreason VALUES (4, 'חולה/פצוע', '');
INSERT INTO deathreason VALUES (5, 'מבוקש', '');
INSERT INTO deathreason VALUES (6, 'חולשה', '');
INSERT INTO deathreason VALUES (7, 'פראות', '');
INSERT INTO deathreason VALUES (8, 'נשיכה', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'קרע בנישואים/מערכת יחסים', '');
INSERT INTO entryreason VALUES (2, 'אלרגיות', '');
INSERT INTO entryreason VALUES (3, 'נשיכה', '');
INSERT INTO entryreason VALUES (4, 'חוסר יכולת התמודדות', '');
INSERT INTO entryreason VALUES (5, 'חוסר הסתגלות', '');
INSERT INTO entryreason VALUES (6, 'מת', '');
INSERT INTO entryreason VALUES (7, 'תועה', '');
INSERT INTO entryreason VALUES (8, 'חולה/פצוע', '');
INSERT INTO entryreason VALUES (9, 'תחזוקה יקרה מדי', '');
INSERT INTO entryreason VALUES (10, 'התעללות', '');
INSERT INTO entryreason VALUES (11, 'נטישה', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'אין מיקומים', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'נקבה');
INSERT INTO lksex VALUES (1, 'זכר');
INSERT INTO lksex VALUES (2, 'לא ידוע');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'גדול מאוד');
INSERT INTO lksize VALUES (1, 'גדול');
INSERT INTO lksize VALUES (2, 'בינוני');
INSERT INTO lksize VALUES (3, 'קטן');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'קצרה');
INSERT INTO lkcoattype VALUES (1, 'ארוכה');
INSERT INTO lkcoattype VALUES (2, 'גסה');
INSERT INTO lkcoattype VALUES (3, 'מקורזלת');
INSERT INTO lkcoattype VALUES (4, 'סבוך');
INSERT INTO lkcoattype VALUES (5, 'נטול שיער');
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'ללא');
INSERT INTO lksmovementtype VALUES (1, 'אימוץ');
INSERT INTO lksmovementtype VALUES (2, 'אימוץ זמני');
INSERT INTO lksmovementtype VALUES (3, 'העברה');
INSERT INTO lksmovementtype VALUES (4, 'ברח');
INSERT INTO lksmovementtype VALUES (5, 'נדרש על ידי הבעלים');
INSERT INTO lksmovementtype VALUES (6, 'גנוב');
INSERT INTO lksmovementtype VALUES (7, 'שוחרר לחופשי');
INSERT INTO lksmovementtype VALUES (8, 'קמעונאי');
INSERT INTO lksmovementtype VALUES (9, 'שימור');
INSERT INTO lksmovementtype VALUES (10, 'ביטול הזמנה');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'חיית מחמד');
INSERT INTO lksmedialink VALUES (1, 'חיית מחמד שאבדה');
INSERT INTO lksmedialink VALUES (2, 'חיית מחמד שנמצאה');
INSERT INTO lksmedialink VALUES (3, 'בעלים');
INSERT INTO lksmedialink VALUES (4, 'העברה');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'ללא');
INSERT INTO lksdiarylink VALUES (1, 'חיית מחמד');
INSERT INTO lksdiarylink VALUES (2, 'בעלים');
INSERT INTO lksdiarylink VALUES (3, 'חיית מחמד שאבדה');
INSERT INTO lksdiarylink VALUES (4, 'חיית מחמד שנמצאה');
INSERT INTO lksdiarylink VALUES (5, 'רשימת המתנה');
INSERT INTO lksdiarylink VALUES (6, 'העברה');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'One-Off');
INSERT INTO lksdonationfreq VALUES (1, 'Weekly');
INSERT INTO lksdonationfreq VALUES (2, 'Monthly');
INSERT INTO lksdonationfreq VALUES (3, 'Quarterly');
INSERT INTO lksdonationfreq VALUES (4, 'Half-Yearly');
INSERT INTO lksdonationfreq VALUES (5, 'Annually');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'חיית מחמד');
INSERT INTO lksfieldlink VALUES (1, 'בעלים');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'כן/לא');
INSERT INTO lksfieldtype VALUES (1, 'טקסט');
INSERT INTO lksfieldtype VALUES (2, 'הערות');
INSERT INTO lksfieldtype VALUES (3, 'מספר');
INSERT INTO lksfieldtype VALUES (4, 'תאריך');
INSERT INTO lksfieldtype VALUES (5, 'כסף');
INSERT INTO lksfieldtype VALUES (6, 'חיפוש');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'חיית מחמד');
INSERT INTO lksloglink VALUES (1, 'בעלים');
INSERT INTO lksloglink VALUES (2, 'חיית מחמד שאבדה');
INSERT INTO lksloglink VALUES (3, 'חיית מחמד שנמצאה');
INSERT INTO lksloglink VALUES (4, 'רשימת המתנה');
INSERT INTO lksloglink VALUES (5, 'העברה');
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'דחופה');
INSERT INTO lkurgency VALUES (2, 'גבוהה');
INSERT INTO lkurgency VALUES (3, 'בינוני');
INSERT INTO lkurgency VALUES (4, 'נמוכה');
INSERT INTO lkurgency VALUES (5, 'הנמוכה ביותר');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'נשיכה', '');
INSERT INTO logtype VALUES (2, 'תלונה', '');
INSERT INTO logtype VALUES (3, 'היסטוריה', '');
INSERT INTO logtype VALUES (4, 'משקל', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'כלב', '', '');
INSERT INTO species VALUES (2, 'חתול', '', '');
INSERT INTO species VALUES (3, 'ציפור', '', '');
INSERT INTO species VALUES (4, 'עכבר', '', '');
INSERT INTO species VALUES (5, 'עכברוש', '', '');
INSERT INTO species VALUES (6, 'קיפוד', '', '');
INSERT INTO species VALUES (7, 'ארנב', '', '');
INSERT INTO species VALUES (8, 'יונה', '', '');
INSERT INTO species VALUES (9, 'חמוס', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'נחש', '', '');
INSERT INTO species VALUES (12, 'צב', '', '');
INSERT INTO species VALUES (13, 'צב ים', '', '');
INSERT INTO species VALUES (14, 'עוף', '', '');
INSERT INTO species VALUES (15, 'ינשוף', '', '');
INSERT INTO species VALUES (16, 'עז', '', '');
INSERT INTO species VALUES (17, 'אווז', '', '');
INSERT INTO species VALUES (18, 'גרביל', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'קביה', '', '');
INSERT INTO species VALUES (21, 'דג זהב', '', '');
INSERT INTO species VALUES (22, 'אוגר', '', '');
INSERT INTO species VALUES (23, 'גמל', '', '');
INSERT INTO species VALUES (24, 'סוס', '', '');
INSERT INTO species VALUES (25, 'פוני', '', '');
INSERT INTO species VALUES (26, 'קוף', '', '');
INSERT INTO species VALUES (27, 'לאמה', '', '');
INSERT INTO species VALUES (28, 'חזיר', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'עיקור/סירוס', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'חיסון זמני', '');
INSERT INTO vaccinationtype VALUES (2, 'חיסון ראשון', '');
INSERT INTO vaccinationtype VALUES (3, 'חיסון שני', '');
INSERT INTO vaccinationtype VALUES (4, 'חיסון דחף', '');
INSERT INTO vaccinationtype VALUES (5, 'לוקמיה', '');
INSERT INTO vaccinationtype VALUES (6, 'שעלת המכלאות', '');
INSERT INTO vaccinationtype VALUES (7, 'וירוס הפרוו', '');
