DELETE FROM accounts;
INSERT INTO accounts VALUES (1, 'Donazione', 'Donazioni in ingresso (miste)', 5, 1, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (2, 'Adozione', 'Donazioni per tasse di adozione', 5, 2, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (3, 'Lista d''attesa', 'Donazioni in lista d''attesa', 5, 3, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (4, 'Inserisci Donazione', 'Donazioni per animali in ingresso al rifugio', 5, 4, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (5, 'Sponsorizzazioni', 'Donazioni da sponsor', 5, 5, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (6, 'Negozio', 'Entrate da negozio sul posto', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (7, 'Interessi', 'Interessi da conto corrente', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (8, 'Income::OpeningBalances', 'Opening balances', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (9, 'Bank::Current', 'Conto Corrente Bancario', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (10, 'Deposito', 'Bank deposit account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (11, 'Risparmi', 'Bank savings account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (12, 'Asset::Premises', 'Premises', 8, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (13, 'Telefono', 'Bollette telefoniche', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (14, 'Elettricità', 'Bollette elettricità', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (15, 'Acqua', 'Bollette acqua', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (16, 'Gas', 'Bollette del gas', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (17, 'Posta', 'Costi postali', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (18, 'Cancelleria', 'Costi di cancelleria', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (19, 'Cibo', 'Costi cibo per animali', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Cane)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Cane randagio)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Gatto abbandonato)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Gatto randagio)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Misto)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Animali non del rifugio)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Nero', NULL);
INSERT INTO basecolour VALUES (2, 'Bianco', NULL);
INSERT INTO basecolour VALUES (3, 'Bianco e nero', NULL);
INSERT INTO basecolour VALUES (4, 'Rossiccio', NULL);
INSERT INTO basecolour VALUES (5, 'Bianco e Nero', NULL);
INSERT INTO basecolour VALUES (6, 'Torti', NULL);
INSERT INTO basecolour VALUES (7, 'Striato', NULL);
INSERT INTO basecolour VALUES (8, 'Marroncino chiaro', NULL);
INSERT INTO basecolour VALUES (9, 'Nero e Marroncino chiaro', NULL);
INSERT INTO basecolour VALUES (10, 'Marroncino chiaro e Nero', NULL);
INSERT INTO basecolour VALUES (11, 'Marrone', NULL);
INSERT INTO basecolour VALUES (12, 'Marrone e Nero', NULL);
INSERT INTO basecolour VALUES (13, 'Nero e Marrone', NULL);
INSERT INTO basecolour VALUES (14, 'Tigrato', NULL);
INSERT INTO basecolour VALUES (15, 'Tigrato e Nero', NULL);
INSERT INTO basecolour VALUES (16, 'Tigrato e Bianco', NULL);
INSERT INTO basecolour VALUES (17, 'Nero e Tigrato', NULL);
INSERT INTO basecolour VALUES (18, 'Bianco e Tigrato', NULL);
INSERT INTO basecolour VALUES (19, 'Tricolore', NULL);
INSERT INTO basecolour VALUES (20, 'Bordeaux', NULL);
INSERT INTO basecolour VALUES (21, 'Bordeaux e Bianco', NULL);
INSERT INTO basecolour VALUES (22, 'Bianco e Bordeaux', NULL);
INSERT INTO basecolour VALUES (23, 'Crema', NULL);
INSERT INTO basecolour VALUES (24, 'Marroncino chiaro e Bianco', NULL);
INSERT INTO basecolour VALUES (26, 'Bianco e Marroncino chiaro', NULL);
INSERT INTO basecolour VALUES (27, 'Torti e Bianco', NULL);
INSERT INTO basecolour VALUES (28, 'Striato e Bianco', NULL);
INSERT INTO basecolour VALUES (29, 'Rossicio e Bianco', NULL);
INSERT INTO basecolour VALUES (30, 'Grigio', NULL);
INSERT INTO basecolour VALUES (31, 'Grigio e Bianco', NULL);
INSERT INTO basecolour VALUES (32, 'Bianco e Grigio', NULL);
INSERT INTO basecolour VALUES (33, 'Bianco e Torti', NULL);
INSERT INTO basecolour VALUES (35, 'Marrone e Bianco', NULL);
INSERT INTO basecolour VALUES (36, 'Blu', NULL);
INSERT INTO basecolour VALUES (37, 'Bianco e Striato', NULL);
INSERT INTO basecolour VALUES (38, 'Giallo e Grigio', NULL);
INSERT INTO basecolour VALUES (39, 'Vario', NULL);
INSERT INTO basecolour VALUES (40, 'Bianco e Marrone', NULL);
INSERT INTO basecolour VALUES (41, 'Verde', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Afghan Hound', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Alaskan Malamute', '', '', 1);
INSERT INTO breed VALUES (7, 'American Bulldog', '', '', 1);
INSERT INTO breed VALUES (8, 'American Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (9, 'American Staffordshire Terrier', '', '', 1);
INSERT INTO breed VALUES (10, 'American Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolian Shepherd', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzell Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (13, 'Australian Cattle Dog/Blue Heeler', '', '', 1);
INSERT INTO breed VALUES (14, 'Australian Kelpie', '', '', 1);
INSERT INTO breed VALUES (15, 'Australian Shepherd', '', '', 1);
INSERT INTO breed VALUES (16, 'Australian Terrier', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Bassotto Segugio', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgian Shepherd Dog Sheepdog', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgian Shepherd Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgian Shepherd Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgian Shepherd Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Bernese Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon Frise', '', '', 1);
INSERT INTO breed VALUES (29, 'Coonhound Nero e Marroncino chiaro', '', '', 1);
INSERT INTO breed VALUES (30, 'Labrador Retriever Nero', '', '', 1);
INSERT INTO breed VALUES (31, 'Cur Muso Nero', '', '', 1);
INSERT INTO breed VALUES (32, 'Bloodhound o Cane di Sant Uberto', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Borzoi o Levriero Russo', '', '', 1);
INSERT INTO breed VALUES (37, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (38, 'Bovaro delle Fiandre', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard o Pastore della Brie', '', '', 1);
INSERT INTO breed VALUES (42, 'Brittany Spaniel', '', '', 1);
INSERT INTO breed VALUES (43, 'Brussels Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Canaan Dog', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso Mastiff', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina Dog', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Cattle Dog', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bay Retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chinese Crested Dog', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinese Foo Dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Chocolate Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Dachshund', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmata', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Doberman Pinscher', '', '', 1);
INSERT INTO breed VALUES (70, 'Dogo Argentino', '', '', 1);
INSERT INTO breed VALUES (71, 'Dogue de Bordeaux', '', '', 1);
INSERT INTO breed VALUES (72, 'Dutch Shepherd', '', '', 1);
INSERT INTO breed VALUES (73, 'Bulldog Inglese', '', '', 1);
INSERT INTO breed VALUES (74, 'Cocker Spaniel Inglese', '', '', 1);
INSERT INTO breed VALUES (75, 'Coonhound Inglese', '', '', 1);
INSERT INTO breed VALUES (76, 'Pointer Inglese', '', '', 1);
INSERT INTO breed VALUES (77, 'Setter Inglese', '', '', 1);
INSERT INTO breed VALUES (78, 'Shepherd Inglese', '', '', 1);
INSERT INTO breed VALUES (79, 'Springer Spaniel Inglese', '', '', 1);
INSERT INTO breed VALUES (80, 'Toy Spaniel Inglese', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila Brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Lapphund Finlandese', '', '', 1);
INSERT INTO breed VALUES (86, 'Spitz Finlandese', '', '', 1);
INSERT INTO breed VALUES (87, 'Flat-coated Retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Bulldog Francese', '', '', 1);
INSERT INTO breed VALUES (91, 'Pinscher Tedesco', '', '', 1);
INSERT INTO breed VALUES (92, 'Shepherd Dog Tedesco', '', '', 1);
INSERT INTO breed VALUES (93, 'Shorthaired Pointer Tedesco', '', '', 1);
INSERT INTO breed VALUES (94, 'Wirehaired Pointer Tedesco', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Great Dane', '', '', 1);
INSERT INTO breed VALUES (99, 'Great Pyrenees', '', '', 1);
INSERT INTO breed VALUES (100, 'Grande Bovaro Svizzero', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Havanese', '', '', 1);
INSERT INTO breed VALUES (103, 'Segugio', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibizan Hound', '', '', 1);
INSERT INTO breed VALUES (107, 'Illyrian Sheepdog', '', '', 1);
INSERT INTO breed VALUES (108, 'Setter Irlandese', '', '', 1);
INSERT INTO breed VALUES (109, 'Terrier Irlandese', '', '', 1);
INSERT INTO breed VALUES (110, 'Water Spaniel Irlandese', '', '', 1);
INSERT INTO breed VALUES (111, 'Wolfhound Irlandese', '', '', 1);
INSERT INTO breed VALUES (112, 'Greyhound Italiano', '', '', 1);
INSERT INTO breed VALUES (113, 'Spinone Italiano', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Japanese Chin', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Dog', '', '', 1);
INSERT INTO breed VALUES (118, 'Cane da orso della Carelia', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue Terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Löwchen', '', '', 1);
INSERT INTO breed VALUES (131, 'Maltese', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremmano', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastino', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Pinscher Nano', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (140, 'Mastino Napoletano', '', '', 1);
INSERT INTO breed VALUES (141, 'New Guinea Singing Dog', '', '', 1);
INSERT INTO breed VALUES (142, 'Newfoundland Dog', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Terrier Norvegese', '', '', 1);
INSERT INTO breed VALUES (145, 'Buhund Norvegese', '', '', 1);
INSERT INTO breed VALUES (146, 'Elkhound Norvegese', '', '', 1);
INSERT INTO breed VALUES (147, 'Lundehund Norvegese', '', '', 1);
INSERT INTO breed VALUES (148, 'Nuova Scozia Duck-Tolling Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Old English Sheepdog', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhound', '', '', 1);
INSERT INTO breed VALUES (151, 'Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier (Fell Terrier)', '', '', 1);
INSERT INTO breed VALUES (153, 'Pechinese', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruvian Inca Orchid', '', '', 1);
INSERT INTO breed VALUES (155, 'Piccolo Bassotto Griffon Vendeen', '', '', 1);
INSERT INTO breed VALUES (156, 'Pastore Pharaoh', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Segugio Plott', '', '', 1);
INSERT INTO breed VALUES (159, 'Portugese Podengo', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polish Lowland Sheepdog', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Poodle', '', '', 1);
INSERT INTO breed VALUES (164, 'Portuguese Water Dog', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Pug', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesian Ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'San Bernardo', '', '', 1);
INSERT INTO breed VALUES (176, 'Samoyed', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Scottish Deerhound', '', '', 1);
INSERT INTO breed VALUES (180, 'Scottish Terrier Scottie', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Cane Pastore', '', '', 1);
INSERT INTO breed VALUES (185, 'Pastore', '', '', 1);
INSERT INTO breed VALUES (186, 'Shetland Pastore Sheltie', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Husky Siberiano', '', '', 1);
INSERT INTO breed VALUES (190, 'Silky Terrier', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Smooth Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'South Russian Ovcharka', '', '', 1);
INSERT INTO breed VALUES (198, 'Vallhund Svedese', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Mastino Tibetano', '', '', 1);
INSERT INTO breed VALUES (202, 'Spaniel Tibetano', '', '', 1);
INSERT INTO breed VALUES (203, 'Terrier Tibetano', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimaraner', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier Westie', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'White German Shepherd', '', '', 1);
INSERT INTO breed VALUES (216, 'Wire-haired Pointing Griffon', '', '', 1);
INSERT INTO breed VALUES (217, 'Wirehaired Terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'Yellow Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier Yorkie', '', '', 1);
INSERT INTO breed VALUES (220, 'Xoloitzcuintle/Mexican Hairless', '', '', 1);
INSERT INTO breed VALUES (221, 'Abyssinian', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'American Shorthair', '', '', 2);
INSERT INTO breed VALUES (224, 'American Wirehair', '', '', 2);
INSERT INTO breed VALUES (225, 'Applehead Siamese', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinese', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengal', '', '', 2);
INSERT INTO breed VALUES (228, 'Birmano', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'Shorthair Britannico', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmese', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Calico', '', '', 2);
INSERT INTO breed VALUES (235, 'Hairless Canadese', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Dilute Calico', '', '', 2);
INSERT INTO breed VALUES (242, 'Dilute Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (243, 'Domestico a pelo lungo', '', '', 2);
INSERT INTO breed VALUES (252, 'Domestic a pelo medio', '', '', 2);
INSERT INTO breed VALUES (261, 'Domestic a pelo raso', '', '', 2);
INSERT INTO breed VALUES (271, 'Mau Egiziano', '', '', 2);
INSERT INTO breed VALUES (272, 'Shorthair Esotico', '', '', 2);
INSERT INTO breed VALUES (273, 'Extra-Toes Gatto (Hemingway Polydactyl)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Bobtail Giapponese', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Norwegian Forest Cat', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Orientale a pelo lungo', '', '', 2);
INSERT INTO breed VALUES (285, 'Orientale a pelo corto', '', '', 2);
INSERT INTO breed VALUES (286, 'Orientale tigrato', '', '', 2);
INSERT INTO breed VALUES (287, 'Persiano', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Russian Blue', '', '', 2);
INSERT INTO breed VALUES (292, 'Scottish Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siamese', '', '', 2);
INSERT INTO breed VALUES (295, 'Siberiano', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somalo', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphynx (hairless cat)', '', '', 2);
INSERT INTO breed VALUES (300, 'Striato', '', '', 2);
INSERT INTO breed VALUES (307, 'Tigre', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkinese', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (311, 'Angora Turco', '', '', 2);
INSERT INTO breed VALUES (312, 'Van Turco', '', '', 2);
INSERT INTO breed VALUES (313, 'Tuxedo', '', '', 2);
INSERT INTO breed VALUES (314, 'Americano', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Coniglio Angora', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'olandese', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'Lop Inglese', '', '', 7);
INSERT INTO breed VALUES (332, 'Spot Inglese', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'Lop Francese', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Lop Oldandese', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Dwarf Olandese', '', '', 7);
INSERT INTO breed VALUES (347, 'Nuova Zelanda', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polacco', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satinato', '', '', 7);
INSERT INTO breed VALUES (353, 'Argento', '', '', 7);
INSERT INTO breed VALUES (354, 'Volpe argentata', '', '', 7);
INSERT INTO breed VALUES (355, 'Coniglio argentato', '', '', 7);
INSERT INTO breed VALUES (356, 'Marroncino chiaro', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabo', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Asino/Mulo', '', '', 26);
INSERT INTO breed VALUES (361, 'Bozza', '', '', 24);
INSERT INTO breed VALUES (362, 'Sella', '', '', 24);
INSERT INTO breed VALUES (363, 'Classe', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Ferret', '', '', 3);
INSERT INTO breed VALUES (381, 'Gerbil', '', '', 18);
INSERT INTO breed VALUES (382, 'Guinea Pig', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Hedgehog', '', '', 6);
INSERT INTO breed VALUES (385, 'Topo', '', '', 4);
INSERT INTO breed VALUES (386, 'Prairie Dog', '', '', 5);
INSERT INTO breed VALUES (387, 'Ratto', '', '', 5);
INSERT INTO breed VALUES (388, 'Puzzola', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Maialino', '', '', 28);
INSERT INTO breed VALUES (391, 'maialino vietnamita', '', '', 28);
INSERT INTO breed VALUES (392, 'Gecko', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Lucertola', '', '', 13);
INSERT INTO breed VALUES (395, 'Serpente', '', '', 13);
INSERT INTO breed VALUES (396, 'Tartaruga', '', '', 13);
INSERT INTO breed VALUES (397, 'Pesce', '', '', 21);
INSERT INTO breed VALUES (398, 'Grigio africano', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Budgie/Budgerigar', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Canarino', '', '', 3);
INSERT INTO breed VALUES (404, 'Pollo', '', '', 3);
INSERT INTO breed VALUES (405, 'Cocorito', '', '', 3);
INSERT INTO breed VALUES (406, 'Cockatoo', '', '', 3);
INSERT INTO breed VALUES (407, 'Pappagallo', '', '', 3);
INSERT INTO breed VALUES (408, 'Colomba', '', '', 3);
INSERT INTO breed VALUES (409, 'Anatra', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Finguello', '', '', 3);
INSERT INTO breed VALUES (413, 'Oca', '', '', 3);
INSERT INTO breed VALUES (414, 'Uccello della Guinea', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lory/Lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Inseparabili', '', '', 3);
INSERT INTO breed VALUES (418, 'Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Struzzo', '', '', 3);
INSERT INTO breed VALUES (421, 'Parrocchetto', '', '', 3);
INSERT INTO breed VALUES (422, 'Pappagallo', '', '', 3);
INSERT INTO breed VALUES (423, 'Pappagallino', '', '', 3);
INSERT INTO breed VALUES (424, 'Pavone', '', '', 3);
INSERT INTO breed VALUES (425, 'Fagiano', '', '', 3);
INSERT INTO breed VALUES (426, 'Piccione', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Altro)', '', '', 3);
INSERT INTO breed VALUES (434, 'Cigno', '', '', 3);
INSERT INTO breed VALUES (435, 'Tucano', '', '', 3);
INSERT INTO breed VALUES (436, 'Turchia', '', '', 3);
INSERT INTO breed VALUES (437, 'Mucca', '', '', 16);
INSERT INTO breed VALUES (438, 'Capra', '', '', 16);
INSERT INTO breed VALUES (439, 'Pecora', '', '', 16);
INSERT INTO breed VALUES (440, 'Lama', '', '', 16);
INSERT INTO breed VALUES (441, 'Maiale (Fattoria)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%Name';
INSERT INTO configuration VALUES ('Organisation', 'Organizzazione');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Piccolo');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Giovane Adulto');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Adulto');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Anziano');
DELETE FROM costtype;
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Animali senza microchips', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Monitoraggio');
INSERT INTO customreport VALUES (37, 'Animali senza foto', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Monitoraggio');
INSERT INTO customreport VALUES (38, 'Animali mai vaccinati', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Monitoraggio');
INSERT INTO customreport VALUES (39, 'Animali non castrati/sterilizzati di età superiore ai 6 mesi', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Monitoraggio');
INSERT INTO customreport VALUES (40, 'Gatti non controllati al Combi-Test', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Monitoraggio');
INSERT INTO customreport VALUES (41, 'Immagini mensili di animali', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Immagini');
INSERT INTO customreport VALUES (42, 'Animali a lungo termine', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Immagini');
INSERT INTO customreport VALUES (43, 'Inventario del Rifugio', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventari');
INSERT INTO customreport VALUES (44, 'Inventario dettagliato del Rifugio', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventari');
INSERT INTO customreport VALUES (45, 'Animali che non fa parte di una cucciolata', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Cucciolata');
INSERT INTO customreport VALUES (46, 'In/Out', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimenti');
INSERT INTO customreport VALUES (47, 'Riepilogo In/Out', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimenti');
INSERT INTO customreport VALUES (48, 'Trasferimento in relazione', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movimenti');
INSERT INTO customreport VALUES (49, 'Volume delle adozioni per rivenditore', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Rivenditori');
INSERT INTO customreport VALUES (50, 'Tempo medio al rivenditore prima dell''adozione', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Rivenditori');
INSERT INTO customreport VALUES (51, 'Inventario rivenditore', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Rivenditori');
INSERT INTO customreport VALUES (52, 'Rapporto animali restituiti', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Restituzioni');
INSERT INTO customreport VALUES (53, 'Animali restituiti entro 6 mesi', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Restituzioni');
INSERT INTO customreport VALUES (54, 'Animali restituiti dopo 6 mesi', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Restituzioni');
INSERT INTO customreport VALUES (55, 'Nome più comune', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiche');
INSERT INTO customreport VALUES (56, 'Motivazioni per animali deceduti', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiche');
INSERT INTO customreport VALUES (57, 'Area d''ingresso della maggior parte degli animali', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiche');
INSERT INTO customreport VALUES (58, 'Area d''adozione della maggior parte degli animali', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiche');
INSERT INTO customreport VALUES (59, 'Tempo medio nella lista di attesa', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Statistiche');
INSERT INTO customreport VALUES (60, 'Donazioni mensili', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafici finanziari');
INSERT INTO customreport VALUES (61, 'Donazioni mensili per specie', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafici finanziari');
INSERT INTO customreport VALUES (62, 'Adozioni mensili per specie', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafici dei movimenti');
INSERT INTO customreport VALUES (63, 'Adozioni mensli per luogo', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafici dei movimenti');
INSERT INTO customreport VALUES (64, 'Motivi d''entrata dell''animale', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafici dei movimenti');
INSERT INTO customreport VALUES (65, 'Motivi della restituzione dell''animale', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafici dei movimenti');
INSERT INTO customreport VALUES (66, 'Criteri del proprietario combacianti', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventari');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Morto all''arrivo', '');
INSERT INTO deathreason VALUES (2, 'Deceduto', '');
INSERT INTO deathreason VALUES (3, 'Sano', '');
INSERT INTO deathreason VALUES (4, 'Ammalato/Ferito', '');
INSERT INTO deathreason VALUES (5, 'Richiesto', '');
INSERT INTO deathreason VALUES (6, 'Abbattimento', '');
INSERT INTO deathreason VALUES (7, 'Selvatico', '');
INSERT INTO deathreason VALUES (8, 'Morsi', '');
DELETE FROM diet;
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Donazione', '');
INSERT INTO donationtype VALUES (2, 'Adozione libera', '');
INSERT INTO donationtype VALUES (3, 'Lista d''attesa donazioni', '');
INSERT INTO donationtype VALUES (4, 'Registrazione donazione', '');
INSERT INTO donationtype VALUES (5, 'Sponsorizzazione animale', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Matrimonio/Relazione sfumata', '');
INSERT INTO entryreason VALUES (2, 'Allergie', '');
INSERT INTO entryreason VALUES (3, 'Morsi', '');
INSERT INTO entryreason VALUES (4, 'Impossibile da gestire', '');
INSERT INTO entryreason VALUES (5, 'Sistemazione inadatta', '');
INSERT INTO entryreason VALUES (6, 'Deceduto', '');
INSERT INTO entryreason VALUES (7, 'Randagio', '');
INSERT INTO entryreason VALUES (8, 'Ammalato/Ferito', '');
INSERT INTO entryreason VALUES (9, 'Non può permetterselo', '');
INSERT INTO entryreason VALUES (10, 'Abuso', '');
INSERT INTO entryreason VALUES (11, 'Abbandonato', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Nessun luogo', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Femmina');
INSERT INTO lksex VALUES (1, 'Maschio');
INSERT INTO lksex VALUES (2, 'Sconosciuto');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Molto grande');
INSERT INTO lksize VALUES (1, 'Grande');
INSERT INTO lksize VALUES (2, 'Medio');
INSERT INTO lksize VALUES (3, 'Piccolo');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Corto');
INSERT INTO lkcoattype VALUES (1, 'Lungo');
INSERT INTO lkcoattype VALUES (2, 'Ruvido');
INSERT INTO lkcoattype VALUES (3, 'Arricciato');
INSERT INTO lkcoattype VALUES (4, 'cordato');
INSERT INTO lkcoattype VALUES (5, 'senza peli');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Nessuno');
INSERT INTO lksmovementtype VALUES (1, 'Adozione');
INSERT INTO lksmovementtype VALUES (2, 'Adottivo');
INSERT INTO lksmovementtype VALUES (3, 'Trasferimento');
INSERT INTO lksmovementtype VALUES (4, 'Fuggito');
INSERT INTO lksmovementtype VALUES (5, 'Bonificato');
INSERT INTO lksmovementtype VALUES (6, 'Rubati');
INSERT INTO lksmovementtype VALUES (7, 'Rilasciato alla natura');
INSERT INTO lksmovementtype VALUES (8, 'Rivenditore');
INSERT INTO lksmovementtype VALUES (9, 'Prenotazione');
INSERT INTO lksmovementtype VALUES (10, 'Prenotazione cancellata');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Animale');
INSERT INTO lksmedialink VALUES (1, 'Animale perso');
INSERT INTO lksmedialink VALUES (2, 'Animale trovato');
INSERT INTO lksmedialink VALUES (3, 'Proprietario');
INSERT INTO lksmedialink VALUES (4, 'Movimento');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Nessuno');
INSERT INTO lksdiarylink VALUES (1, 'Animale');
INSERT INTO lksdiarylink VALUES (2, 'Proprietario');
INSERT INTO lksdiarylink VALUES (3, 'Animale perso');
INSERT INTO lksdiarylink VALUES (4, 'Animale trovato');
INSERT INTO lksdiarylink VALUES (5, 'Lista d''attesa');
INSERT INTO lksdiarylink VALUES (6, 'Movimento');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'Una volta');
INSERT INTO lksdonationfreq VALUES (1, 'Settimanalmente');
INSERT INTO lksdonationfreq VALUES (2, 'Mensilmente');
INSERT INTO lksdonationfreq VALUES (3, 'Trimestralmente');
INSERT INTO lksdonationfreq VALUES (4, 'Semestralmente');
INSERT INTO lksdonationfreq VALUES (5, 'Annualmente');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Animale');
INSERT INTO lksfieldlink VALUES (1, 'Proprietario');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Sì/no');
INSERT INTO lksfieldtype VALUES (1, 'Testo');
INSERT INTO lksfieldtype VALUES (2, 'Note');
INSERT INTO lksfieldtype VALUES (3, 'Numero');
INSERT INTO lksfieldtype VALUES (4, 'Data');
INSERT INTO lksfieldtype VALUES (5, 'Soldi');
INSERT INTO lksfieldtype VALUES (6, 'Ricerca');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Animale');
INSERT INTO lksloglink VALUES (1, 'Proprietario');
INSERT INTO lksloglink VALUES (2, 'Animale perso');
INSERT INTO lksloglink VALUES (3, 'Animale trovato');
INSERT INTO lksloglink VALUES (4, 'Lista d''attesa');
INSERT INTO lksloglink VALUES (5, 'Movimento');
DELETE FROM lksyesno;
DELETE FROM lksynun;
DELETE FROM lksposneg;
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Urgente');
INSERT INTO lkurgency VALUES (2, 'Alto');
INSERT INTO lkurgency VALUES (3, 'Medio');
INSERT INTO lkurgency VALUES (4, 'Basso');
INSERT INTO lkurgency VALUES (5, 'Il più basso');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Morso', '');
INSERT INTO logtype VALUES (2, 'Reclamo', '');
INSERT INTO logtype VALUES (3, 'Storia', '');
INSERT INTO logtype VALUES (4, 'Peso', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Cane', '', '');
INSERT INTO species VALUES (2, 'Gatto', '', '');
INSERT INTO species VALUES (3, 'Uccello', '', '');
INSERT INTO species VALUES (4, 'Topo', '', '');
INSERT INTO species VALUES (5, 'Ratto', '', '');
INSERT INTO species VALUES (6, 'Hedgehog', '', '');
INSERT INTO species VALUES (7, 'Coniglio', '', '');
INSERT INTO species VALUES (8, 'Colomba', '', '');
INSERT INTO species VALUES (9, 'Ferret', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Serpente', '', '');
INSERT INTO species VALUES (12, 'Tortora', '', '');
INSERT INTO species VALUES (13, 'Tartaruga', '', '');
INSERT INTO species VALUES (14, 'Pollo', '', '');
INSERT INTO species VALUES (15, 'Gufo', '', '');
INSERT INTO species VALUES (16, 'Capra', '', '');
INSERT INTO species VALUES (17, 'Oca', '', '');
INSERT INTO species VALUES (18, 'Gerbil', '', '');
INSERT INTO species VALUES (19, 'Cocorito', '', '');
INSERT INTO species VALUES (20, 'Guinea Pig', '', '');
INSERT INTO species VALUES (21, 'Pesce rosso', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Cammello', '', '');
INSERT INTO species VALUES (24, 'Cavallo', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Asino', '', '');
INSERT INTO species VALUES (27, 'Lama', '', '');
INSERT INTO species VALUES (28, 'Maiale', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Neutro/Sterilizzato', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Vaccinazione temporanea', '');
INSERT INTO vaccinationtype VALUES (2, 'Prima vaccinazione', '');
INSERT INTO vaccinationtype VALUES (3, 'Seconda vaccinazione', '');
INSERT INTO vaccinationtype VALUES (4, 'Sostenitore', '');
INSERT INTO vaccinationtype VALUES (5, 'Leucemia', '');
INSERT INTO vaccinationtype VALUES (6, 'Tosse canina', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirus', '');
