DELETE FROM accounts;
INSERT INTO accounts VALUES (1, 'Príjem::Dar', 'Rôzne dary', 5, 1, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (2, 'Príjem::Adopcia', 'Adopčné poplatky', 5, 2, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (3, 'Príjem::Zoznam čakajúcich', 'Príspevky zo zoznamu čakajúcich', 5, 3, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (4, 'Príjem::Príspevok pri príjme psa', 'Príspevky pri zvieratách, ktoré boli prijaté do útulku', 5, 4, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (5, 'Príjem::Sponzoring', 'Dary od sponzorov', 5, 5, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (6, 'Príjem::E-shop', 'Príjem z e-shopu', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (7, 'Príjem::Príspevok na účet', 'Príspevok na účet', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (8, 'Príjem::Vstupný vklad', 'Vstupný vklad', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (9, 'Banka::Bežný účet', 'Bežný účet v banke', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (10, 'Banka::Vklad', 'Bankový vklad', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (11, 'Banka::Sporenie', 'Sporenie v banke', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (12, 'Asset::Premises', 'Premises', 8, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (13, 'Výdavky::Telefón', 'Účty za telefón', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (14, 'Výdavky::Elektrina', 'Účty za elektrinu', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (15, 'Výdavky::Voda', 'Účty za vodu', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (16, 'Výdavky::Plyn', 'Účty za plyn', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (17, 'Výdavky::Poštovné', 'Poštovné', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (18, 'Expenses::Stationary', 'Stationary costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (19, 'Výdavky::Potrava', 'Výdavky na potravu', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'P (Pes)', NULL);
INSERT INTO animaltype VALUES (10, 'F (zatúlaný pes)', NULL);
INSERT INTO animaltype VALUES (11, 'N (Nechcená mačka)', NULL);
INSERT INTO animaltype VALUES (12, 'S (zatúlaná mačka)', NULL);
INSERT INTO animaltype VALUES (13, 'R (Rôzny)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Neumiestnené zviera)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Čierna', NULL);
INSERT INTO basecolour VALUES (2, 'Biela', NULL);
INSERT INTO basecolour VALUES (3, 'Čiernobiela', NULL);
INSERT INTO basecolour VALUES (4, 'Hrdzavá', NULL);
INSERT INTO basecolour VALUES (5, 'Bieločierna', NULL);
INSERT INTO basecolour VALUES (6, 'Korytnačinová', NULL);
INSERT INTO basecolour VALUES (7, 'Pruhovaná mačka', NULL);
INSERT INTO basecolour VALUES (8, 'Svetlohnedá', NULL);
INSERT INTO basecolour VALUES (9, 'Čierna a svetlohnedá', NULL);
INSERT INTO basecolour VALUES (10, 'Svetlohnedá a čierna', NULL);
INSERT INTO basecolour VALUES (11, 'Hnedá', NULL);
INSERT INTO basecolour VALUES (12, 'Hnedočierna', NULL);
INSERT INTO basecolour VALUES (13, 'Čiernohnedá', NULL);
INSERT INTO basecolour VALUES (14, 'Strakatá', NULL);
INSERT INTO basecolour VALUES (15, 'Tigrovaná a čierna', NULL);
INSERT INTO basecolour VALUES (16, 'Tigrovaná a biela', NULL);
INSERT INTO basecolour VALUES (17, 'Čierna a tigrovaná', NULL);
INSERT INTO basecolour VALUES (18, 'Biela a tigrovaná', NULL);
INSERT INTO basecolour VALUES (19, 'Trojfarebná', NULL);
INSERT INTO basecolour VALUES (20, 'Tmavohnedá', NULL);
INSERT INTO basecolour VALUES (21, 'Tmavohnedá a biela', NULL);
INSERT INTO basecolour VALUES (22, 'Biela a tmavohnedá', NULL);
INSERT INTO basecolour VALUES (23, 'Krémová', NULL);
INSERT INTO basecolour VALUES (24, 'Svetlohnedá a biela', NULL);
INSERT INTO basecolour VALUES (26, 'Biela a svetlohnedá', NULL);
INSERT INTO basecolour VALUES (27, 'Korytnačinová a biela', NULL);
INSERT INTO basecolour VALUES (28, 'Strakatá a biela', NULL);
INSERT INTO basecolour VALUES (29, 'Ryšavá a biela', NULL);
INSERT INTO basecolour VALUES (30, 'Šedá', NULL);
INSERT INTO basecolour VALUES (31, 'Šedobiela', NULL);
INSERT INTO basecolour VALUES (32, 'Bielošedá', NULL);
INSERT INTO basecolour VALUES (33, 'Biela a korytnačinová', NULL);
INSERT INTO basecolour VALUES (35, 'Hnedobiela', NULL);
INSERT INTO basecolour VALUES (36, 'Modrá', NULL);
INSERT INTO basecolour VALUES (37, 'Biela a strakatá', NULL);
INSERT INTO basecolour VALUES (38, 'Žltosivé', NULL);
INSERT INTO basecolour VALUES (39, 'Rôzna', NULL);
INSERT INTO basecolour VALUES (40, 'Bielohnedá', NULL);
INSERT INTO basecolour VALUES (41, 'Zelená', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Opičí pes', '', '', 1);
INSERT INTO breed VALUES (2, 'Afgánsky chrt', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale teriér', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Aljašský malamut', '', '', 1);
INSERT INTO breed VALUES (7, 'Americký Bulldog', '', '', 1);
INSERT INTO breed VALUES (8, 'American Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (9, 'Americký stafordšírsky teriér', '', '', 1);
INSERT INTO breed VALUES (10, 'Americký vodný španiel', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolský pastiersky pes', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzell Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (13, 'Austrálsky dobytkársky pes', '', '', 1);
INSERT INTO breed VALUES (14, 'Austrálska kelpia', '', '', 1);
INSERT INTO breed VALUES (15, 'Austrálsky ovčiak', '', '', 1);
INSERT INTO breed VALUES (16, 'Austrálsky teriér', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Baset', '', '', 1);
INSERT INTO breed VALUES (19, 'Bígl', '', '', 1);
INSERT INTO breed VALUES (20, 'Bradatá kólia', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlingtonský teriér', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgický ovčiak', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgický ovčiak Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgický ovčiak Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgický ovčiak Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Bernský salašnícky pes', '', '', 1);
INSERT INTO breed VALUES (28, 'Bišon', '', '', 1);
INSERT INTO breed VALUES (29, 'Čierno-trieslový coonhaund', '', '', 1);
INSERT INTO breed VALUES (30, 'Čierny labrador', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Svätohubertský pes - Bloodhound', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border kólia', '', '', 1);
INSERT INTO breed VALUES (35, 'Border teriér', '', '', 1);
INSERT INTO breed VALUES (36, 'Chrt', '', '', 1);
INSERT INTO breed VALUES (37, 'Boston teriér', '', '', 1);
INSERT INTO breed VALUES (38, 'Flámsky bouvier', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin španiel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Brittany Spaniel', '', '', 1);
INSERT INTO breed VALUES (43, 'Brusselský Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bulteriér', '', '', 1);
INSERT INTO breed VALUES (45, 'Bulmastif', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn teriér', '', '', 1);
INSERT INTO breed VALUES (47, 'Kanaánsky pes', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso Mastiff', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolínsky pes', '', '', 1);
INSERT INTO breed VALUES (50, 'Louisianský leopardí pes', '', '', 1);
INSERT INTO breed VALUES (51, 'Austrálsky dobytkársky pes', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles španiel', '', '', 1);
INSERT INTO breed VALUES (53, 'Retríver zo zálivu Chesapeake', '', '', 1);
INSERT INTO breed VALUES (54, 'Čivava', '', '', 1);
INSERT INTO breed VALUES (55, 'Čínsky chocholatý pes', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinese Foo Dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Čokoládový labrador', '', '', 1);
INSERT INTO breed VALUES (58, 'Čau - čau', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber španiel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Kokršpaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Kólia', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Waleský korgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Jazvečík', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatínec', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Doberman Pinscher', '', '', 1);
INSERT INTO breed VALUES (70, 'Argentínska doga', '', '', 1);
INSERT INTO breed VALUES (71, 'Bordeauxská doga', '', '', 1);
INSERT INTO breed VALUES (72, 'Holandský ovčiak', '', '', 1);
INSERT INTO breed VALUES (73, 'Anglický buldog', '', '', 1);
INSERT INTO breed VALUES (74, 'Anglický kokršpaniel', '', '', 1);
INSERT INTO breed VALUES (75, 'Anglický mývalý lovecký pes', '', '', 1);
INSERT INTO breed VALUES (76, 'Anglický Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'Anglický seter', '', '', 1);
INSERT INTO breed VALUES (78, 'Anglický ovčiak', '', '', 1);
INSERT INTO breed VALUES (79, 'Anglický špringeršpaniel', '', '', 1);
INSERT INTO breed VALUES (80, 'English Toy Spaniel', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimácky pes', '', '', 1);
INSERT INTO breed VALUES (83, 'Poľný španiel', '', '', 1);
INSERT INTO breed VALUES (84, 'Brazílska fila', '', '', 1);
INSERT INTO breed VALUES (85, 'Finnish Lapphund', '', '', 1);
INSERT INTO breed VALUES (86, 'Finnish Spitz', '', '', 1);
INSERT INTO breed VALUES (87, 'Flat-coated Retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Foxteriér', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'Francúzsky buldoček', '', '', 1);
INSERT INTO breed VALUES (91, 'Nemecký pinč', '', '', 1);
INSERT INTO breed VALUES (92, 'Nemecký ovčiak', '', '', 1);
INSERT INTO breed VALUES (93, 'German Shorthaired Pointer', '', '', 1);
INSERT INTO breed VALUES (94, 'German Wirehaired Pointer', '', '', 1);
INSERT INTO breed VALUES (95, 'Teriér z Glen of Imaal', '', '', 1);
INSERT INTO breed VALUES (96, 'Zlatý retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Doga', '', '', 1);
INSERT INTO breed VALUES (99, 'Pyrenejský horský pes', '', '', 1);
INSERT INTO breed VALUES (100, 'Veľký švajčiarsky salašnícky pes', '', '', 1);
INSERT INTO breed VALUES (101, 'Anglický chrt', '', '', 1);
INSERT INTO breed VALUES (102, 'Havanese', '', '', 1);
INSERT INTO breed VALUES (103, 'Lovecký pes', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibizan Hound', '', '', 1);
INSERT INTO breed VALUES (107, 'Illyrian Sheepdog', '', '', 1);
INSERT INTO breed VALUES (108, 'Írsky seter', '', '', 1);
INSERT INTO breed VALUES (109, 'Írsky teriér', '', '', 1);
INSERT INTO breed VALUES (110, 'Írsky vodný pes', '', '', 1);
INSERT INTO breed VALUES (111, 'Írsky vlkodav', '', '', 1);
INSERT INTO breed VALUES (112, 'Taliansky chrtík', '', '', 1);
INSERT INTO breed VALUES (113, 'Italian Spinone', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Teriér', '', '', 1);
INSERT INTO breed VALUES (115, 'Japonský španiel', '', '', 1);
INSERT INTO breed VALUES (116, 'Kórejský jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Dog', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelský medvedí pes', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerský modrý teriér', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakelandský teriér', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Levíček', '', '', 1);
INSERT INTO breed VALUES (131, 'Maltézsky', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchesterský teriér', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremma', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Trpasličí pinč', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Horský pes', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (140, 'Neapolitan Mastiff', '', '', 1);
INSERT INTO breed VALUES (141, 'Novoguinejský spievajúci pes', '', '', 1);
INSERT INTO breed VALUES (142, 'Novofundlandský pes', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolkský teriér', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich teriér', '', '', 1);
INSERT INTO breed VALUES (145, 'Nórsky buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Nórsky losí pes', '', '', 1);
INSERT INTO breed VALUES (147, 'Nórsky Lundehund', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia Duck-Tolling Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Bobtail', '', '', 1);
INSERT INTO breed VALUES (150, 'Vydrí pes', '', '', 1);
INSERT INTO breed VALUES (151, 'Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale teriér', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekingský palácový psík', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruvian Inca Orchid', '', '', 1);
INSERT INTO breed VALUES (155, 'Malý hrubosrstý vendéenský baset', '', '', 1);
INSERT INTO breed VALUES (156, 'Faraónsky chrt', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plottov durič', '', '', 1);
INSERT INTO breed VALUES (159, 'Portugalský podengo', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polish Lowland Sheepdog', '', '', 1);
INSERT INTO breed VALUES (162, 'Nemecký trpaslíči špic Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Pudlík', '', '', 1);
INSERT INTO breed VALUES (164, 'Portuguese Water Dog', '', '', 1);
INSERT INTO breed VALUES (165, 'Kanárska doga', '', '', 1);
INSERT INTO breed VALUES (166, 'Mopslík', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbonov Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodézsky ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rotvajler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'Bernardín', '', '', 1);
INSERT INTO breed VALUES (176, 'Samojed', '', '', 1);
INSERT INTO breed VALUES (177, 'Šiperka', '', '', 1);
INSERT INTO breed VALUES (178, 'Bradáč', '', '', 1);
INSERT INTO breed VALUES (179, 'Škótsky jelení pes', '', '', 1);
INSERT INTO breed VALUES (180, 'Škótsky teriér', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham teriér', '', '', 1);
INSERT INTO breed VALUES (182, 'Seter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Ovčiarsky pes', '', '', 1);
INSERT INTO breed VALUES (185, 'Ovčiak', '', '', 1);
INSERT INTO breed VALUES (186, 'Šeltia', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Sibírsky Husky', '', '', 1);
INSERT INTO breed VALUES (190, 'Silky teriér', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye teriér', '', '', 1);
INSERT INTO breed VALUES (192, 'Arabský chrt - Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Hladkosrstý foxteriér', '', '', 1);
INSERT INTO breed VALUES (194, 'Španiel', '', '', 1);
INSERT INTO breed VALUES (195, 'Špic', '', '', 1);
INSERT INTO breed VALUES (196, 'Stafordšírský bullteriér', '', '', 1);
INSERT INTO breed VALUES (197, 'South Russian Ovcharka', '', '', 1);
INSERT INTO breed VALUES (198, 'Švédský valhaund', '', '', 1);
INSERT INTO breed VALUES (199, 'Teriér', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Tibetská doga', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibetský španiel', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibetský teriér', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Foxteriér toy', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vyžla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimarský stavač', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh teriér', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh springer španiel', '', '', 1);
INSERT INTO breed VALUES (212, 'Westhighlandský biely teriér', '', '', 1);
INSERT INTO breed VALUES (213, 'Jemnosrstý pšeničný teriér', '', '', 1);
INSERT INTO breed VALUES (214, 'Vipet', '', '', 1);
INSERT INTO breed VALUES (215, 'Biely švajčiarsky ovčiak', '', '', 1);
INSERT INTO breed VALUES (216, 'Wire-haired Pointing Griffon', '', '', 1);
INSERT INTO breed VALUES (217, 'Wirehaired Terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'Yellow Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshirský teriér', '', '', 1);
INSERT INTO breed VALUES (220, 'Xoloitzcuintle/Mexican Hairless', '', '', 1);
INSERT INTO breed VALUES (221, 'Abyssinian', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'American Shorthair', '', '', 2);
INSERT INTO breed VALUES (224, 'American Wirehair', '', '', 2);
INSERT INTO breed VALUES (225, 'Applehead Siamese', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinese', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengálska', '', '', 2);
INSERT INTO breed VALUES (228, 'Birman', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'Britská krátkosrstá', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmese', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Calico', '', '', 2);
INSERT INTO breed VALUES (235, 'Canadian Hairless', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Dilute Calico', '', '', 2);
INSERT INTO breed VALUES (242, 'Dilute Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (243, 'Domáca dlhosrstá', '', '', 2);
INSERT INTO breed VALUES (252, 'Domáca', '', '', 2);
INSERT INTO breed VALUES (261, 'Domáca krátkosrstá', '', '', 2);
INSERT INTO breed VALUES (271, 'Egyptská Mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Exotic Shorthair', '', '', 2);
INSERT INTO breed VALUES (273, 'Extra-Toes Cat (Hemingway Polydactyl)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Japanese Bobtail', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Mainská mývalia', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Norwegian Forest Cat', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Oriental Long Hair', '', '', 2);
INSERT INTO breed VALUES (285, 'Oriental Short Hair', '', '', 2);
INSERT INTO breed VALUES (286, 'Oriental Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'Perzská', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Ruská modrá', '', '', 2);
INSERT INTO breed VALUES (292, 'Scottish Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siamská', '', '', 2);
INSERT INTO breed VALUES (295, 'Siberian', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somali', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphynx', '', '', 2);
INSERT INTO breed VALUES (300, 'Pruhovaná mačka', '', '', 2);
INSERT INTO breed VALUES (307, 'Tiger', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkinese', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (311, 'Turkish Angora', '', '', 2);
INSERT INTO breed VALUES (312, 'Turkish Van', '', '', 2);
INSERT INTO breed VALUES (313, 'Tuxedo', '', '', 2);
INSERT INTO breed VALUES (314, 'American', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angorský králik', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Kalifornská', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Dutch', '', '', 7);
INSERT INTO breed VALUES (329, 'Zakrslý', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polish', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silver', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Svetlohnedá', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabian', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Donkey/Mule', '', '', 26);
INSERT INTO breed VALUES (361, 'Draft', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Fretka', '', '', 3);
INSERT INTO breed VALUES (381, 'Pieskomil', '', '', 18);
INSERT INTO breed VALUES (382, 'Morča', '', '', 20);
INSERT INTO breed VALUES (383, 'Škrečok', '', '', 22);
INSERT INTO breed VALUES (384, 'Ježko', '', '', 6);
INSERT INTO breed VALUES (385, 'Myš', '', '', 4);
INSERT INTO breed VALUES (386, 'Prairie Dog', '', '', 5);
INSERT INTO breed VALUES (387, 'Potkan', '', '', 5);
INSERT INTO breed VALUES (388, 'Skunk', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (391, 'Vietnamese Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (392, 'Gecko', '', '', 13);
INSERT INTO breed VALUES (393, 'Leguán', '', '', 13);
INSERT INTO breed VALUES (394, 'Jašterica', '', '', 13);
INSERT INTO breed VALUES (395, 'Had', '', '', 13);
INSERT INTO breed VALUES (396, 'Korytnačka', '', '', 13);
INSERT INTO breed VALUES (397, 'Ryba', '', '', 21);
INSERT INTO breed VALUES (398, 'African Grey', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Budgie/Budgerigar', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Kanárik', '', '', 3);
INSERT INTO breed VALUES (404, 'Sliepka', '', '', 3);
INSERT INTO breed VALUES (405, 'Cockatiel', '', '', 3);
INSERT INTO breed VALUES (406, 'Kakadu', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Holubica', '', '', 3);
INSERT INTO breed VALUES (409, 'Kačka', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Pinka', '', '', 3);
INSERT INTO breed VALUES (413, 'Hus', '', '', 3);
INSERT INTO breed VALUES (414, 'Perlička', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lori', '', '', 3);
INSERT INTO breed VALUES (417, 'Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Ostrich', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakeet (Other)', '', '', 3);
INSERT INTO breed VALUES (422, 'Parrot (Other)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Peacock/Pea fowl', '', '', 3);
INSERT INTO breed VALUES (425, 'Pheasant', '', '', 3);
INSERT INTO breed VALUES (426, 'Holub', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Swan', '', '', 3);
INSERT INTO breed VALUES (435, 'Tukan', '', '', 3);
INSERT INTO breed VALUES (436, 'Moriak', '', '', 3);
INSERT INTO breed VALUES (437, 'Krava', '', '', 16);
INSERT INTO breed VALUES (438, 'Koza', '', '', 16);
INSERT INTO breed VALUES (439, 'Ovca', '', '', 16);
INSERT INTO breed VALUES (440, 'Lama', '', '', 16);
INSERT INTO breed VALUES (441, 'Prasa', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%';
INSERT INTO configuration VALUES ('Organisation', 'Organizácia');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Mláďa');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Junior');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Dospelé');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Senior');
DELETE FROM costtype;
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Zvieratá bez mikročipu', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Kontrola');
INSERT INTO customreport VALUES (37, 'Zvieratá bez fotografie', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Kontrola');
INSERT INTO customreport VALUES (38, 'Nevakcinované zvieratá', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Kontrola');
INSERT INTO customreport VALUES (39, 'Nekastrované zvieratá nad 6 mesiacov', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Kontrola');
INSERT INTO customreport VALUES (40, 'Mačky bez Combi-Test', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Kontrola');
INSERT INTO customreport VALUES (41, 'Mesačné prehľady zvierat', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Prehľady');
INSERT INTO customreport VALUES (42, 'Stálice útulku', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Prehľady');
INSERT INTO customreport VALUES (43, 'Osadenstvo útulku', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Osadenstvo');
INSERT INTO customreport VALUES (44, 'Detaily osadenstva v útulku', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Osadenstvo');
INSERT INTO customreport VALUES (45, 'Zvieratá, ktoré nie sú súčasťou vrhu', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Vrhy');
INSERT INTO customreport VALUES (46, 'Dnu/Von', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Pohyby');
INSERT INTO customreport VALUES (47, 'Dnu/Von Zhrnutie', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Pohyby');
INSERT INTO customreport VALUES (48, 'Presuny v reporte', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Pohyby');
INSERT INTO customreport VALUES (49, 'Množstvo adopcií prostredníctvom sprostredkovateľa', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Sprostredkovatelia');
INSERT INTO customreport VALUES (50, 'Priemerný čas u sprostredkovateľa pred adopciou', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Sprostredkovatelia');
INSERT INTO customreport VALUES (51, 'Osadenstvo u sprostredkovateľa', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Sprostredkovatelia');
INSERT INTO customreport VALUES (52, 'Report vrátených zvierat', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Návraty');
INSERT INTO customreport VALUES (53, 'Zvieratá vrátené do 6 mesiacov', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Návraty');
INSERT INTO customreport VALUES (54, 'Zvieratá vrátené po 6 mesiacoch', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Návraty');
INSERT INTO customreport VALUES (55, 'Najbežnejšie meno', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Štatistiky');
INSERT INTO customreport VALUES (56, 'Dôvody úhynu zvierat', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Štatistiky');
INSERT INTO customreport VALUES (57, 'Najbežnejšie oblasti príjmu zvierat', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Štatistiky');
INSERT INTO customreport VALUES (58, 'Najbežnejšie oblasti adopcie zvierat', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Štatistiky');
INSERT INTO customreport VALUES (59, 'Priemerný doba v zozname čakajúcich', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Štatistiky');
INSERT INTO customreport VALUES (60, 'Mesačné príspevky', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Finančné grafy');
INSERT INTO customreport VALUES (61, 'Mesačné príspevky podľa druhov', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Finančné grafy');
INSERT INTO customreport VALUES (62, 'Mesačné adopcie podľa druhov', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafy pohybov');
INSERT INTO customreport VALUES (63, 'Mesačné adopcie podľa miesta umiestnenia', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafy pohybov');
INSERT INTO customreport VALUES (64, 'Dôvody príjmu zvieraťa', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafy pohybov');
INSERT INTO customreport VALUES (65, 'Dôvody vrátenia zvieraťa', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Grafy pohybov');
INSERT INTO customreport VALUES (66, 'Kritériá zhody majiteľov', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Osadenstvo');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Prijaté uhynuté', '');
INSERT INTO deathreason VALUES (2, 'Uhynuté', '');
INSERT INTO deathreason VALUES (3, 'Zdravé', '');
INSERT INTO deathreason VALUES (4, 'Choré/poranené', '');
INSERT INTO deathreason VALUES (5, 'Požadované', '');
INSERT INTO deathreason VALUES (6, 'Redukovanie', '');
INSERT INTO deathreason VALUES (7, 'Divé', '');
INSERT INTO deathreason VALUES (8, 'Hryzúce', '');
DELETE FROM diet;
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Príspevok', '');
INSERT INTO donationtype VALUES (2, 'Adopčný poplatok', '');
INSERT INTO donationtype VALUES (3, 'Dary prostr. zoznamu čakajúcich', '');
INSERT INTO donationtype VALUES (4, 'Príspevok pri prijatí', '');
INSERT INTO donationtype VALUES (5, 'Sponzorstvo tohto zvieraťa', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Rozvod / rozchod', '');
INSERT INTO entryreason VALUES (2, 'Alergie', '');
INSERT INTO entryreason VALUES (3, 'Hryzúce', '');
INSERT INTO entryreason VALUES (4, 'Neschopnosť postarať sa', '');
INSERT INTO entryreason VALUES (5, 'Nevhodné ubytovanie', '');
INSERT INTO entryreason VALUES (6, 'Uhynuté', '');
INSERT INTO entryreason VALUES (7, 'Túlavé', '');
INSERT INTO entryreason VALUES (8, 'Choré/poranené', '');
INSERT INTO entryreason VALUES (9, 'Veľké výdaje', '');
INSERT INTO entryreason VALUES (10, 'Týrané', '');
INSERT INTO entryreason VALUES (11, 'Opustené', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Nezadané umiestnenie', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Samica');
INSERT INTO lksex VALUES (1, 'Samec');
INSERT INTO lksex VALUES (2, 'Neznáme');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Veľmi veľké');
INSERT INTO lksize VALUES (1, 'Veľké');
INSERT INTO lksize VALUES (2, 'Stredné');
INSERT INTO lksize VALUES (3, 'Malé');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Krátka');
INSERT INTO lkcoattype VALUES (1, 'Dlhá');
INSERT INTO lkcoattype VALUES (2, 'Drsný');
INSERT INTO lkcoattype VALUES (3, 'Vlnitá');
INSERT INTO lkcoattype VALUES (4, 'S dredmi');
INSERT INTO lkcoattype VALUES (5, 'Bezsrsté');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Žiadne');
INSERT INTO lksmovementtype VALUES (1, 'Adopcia');
INSERT INTO lksmovementtype VALUES (2, 'Domáca opatera');
INSERT INTO lksmovementtype VALUES (3, 'Premiestnenie');
INSERT INTO lksmovementtype VALUES (4, 'Utečené');
INSERT INTO lksmovementtype VALUES (5, 'Odobraté');
INSERT INTO lksmovementtype VALUES (6, 'Ukradnuté');
INSERT INTO lksmovementtype VALUES (7, 'Vypustené do prírody');
INSERT INTO lksmovementtype VALUES (8, 'Sprostredkovateľ');
INSERT INTO lksmovementtype VALUES (9, 'Rezervácia');
INSERT INTO lksmovementtype VALUES (10, 'Zrušená rezervácia');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Zviera');
INSERT INTO lksmedialink VALUES (1, 'Stratené zviera');
INSERT INTO lksmedialink VALUES (2, 'Nájdené zviera');
INSERT INTO lksmedialink VALUES (3, 'Majiteľ');
INSERT INTO lksmedialink VALUES (4, 'Pohyb');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Žiadne');
INSERT INTO lksdiarylink VALUES (1, 'Zviera');
INSERT INTO lksdiarylink VALUES (2, 'Majiteľ');
INSERT INTO lksdiarylink VALUES (3, 'Stratené zviera');
INSERT INTO lksdiarylink VALUES (4, 'Nájdené zviera');
INSERT INTO lksdiarylink VALUES (5, 'Zoznam čakajúcich');
INSERT INTO lksdiarylink VALUES (6, 'Pohyb');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'Jednorázovo');
INSERT INTO lksdonationfreq VALUES (1, 'Týždenne');
INSERT INTO lksdonationfreq VALUES (2, 'Mesačne');
INSERT INTO lksdonationfreq VALUES (3, 'Štvrťročne');
INSERT INTO lksdonationfreq VALUES (4, 'Polročne');
INSERT INTO lksdonationfreq VALUES (5, 'Každoročne');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Zviera');
INSERT INTO lksfieldlink VALUES (1, 'Majiteľ');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Áno/nie');
INSERT INTO lksfieldtype VALUES (1, 'Text');
INSERT INTO lksfieldtype VALUES (2, 'Poznámnky');
INSERT INTO lksfieldtype VALUES (3, 'Číslo');
INSERT INTO lksfieldtype VALUES (4, 'Dátum');
INSERT INTO lksfieldtype VALUES (5, 'Peniaze');
INSERT INTO lksfieldtype VALUES (6, 'Zoznam');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Zviera');
INSERT INTO lksloglink VALUES (1, 'Majiteľ');
INSERT INTO lksloglink VALUES (2, 'Stratené zviera');
INSERT INTO lksloglink VALUES (3, 'Nájdené zviera');
INSERT INTO lksloglink VALUES (4, 'Zoznam čakajúcich');
INSERT INTO lksloglink VALUES (5, 'Pohyb');
DELETE FROM lksyesno;
DELETE FROM lksynun;
DELETE FROM lksposneg;
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Veľmi súrne');
INSERT INTO lkurgency VALUES (2, 'Súrne');
INSERT INTO lkurgency VALUES (3, 'Stredné');
INSERT INTO lkurgency VALUES (4, 'Malá naliehavosť');
INSERT INTO lkurgency VALUES (5, 'Najnižšia naliehavosť');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Uhryznutie', '');
INSERT INTO logtype VALUES (2, 'Sťažnosť', '');
INSERT INTO logtype VALUES (3, 'História', '');
INSERT INTO logtype VALUES (4, 'Váha', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Pes', '', '');
INSERT INTO species VALUES (2, 'Mačka', '', '');
INSERT INTO species VALUES (3, 'Vták', '', '');
INSERT INTO species VALUES (4, 'Myš', '', '');
INSERT INTO species VALUES (5, 'Potkan', '', '');
INSERT INTO species VALUES (6, 'Ježko', '', '');
INSERT INTO species VALUES (7, 'Zajac', '', '');
INSERT INTO species VALUES (8, 'Holubica', '', '');
INSERT INTO species VALUES (9, 'Fretka', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Had', '', '');
INSERT INTO species VALUES (12, 'Suchozemská korytnačka', '', '');
INSERT INTO species VALUES (13, 'Sladkovodná korytnačka', '', '');
INSERT INTO species VALUES (14, 'Sliepka', '', '');
INSERT INTO species VALUES (15, 'Sova', '', '');
INSERT INTO species VALUES (16, 'Koza', '', '');
INSERT INTO species VALUES (17, 'Hus', '', '');
INSERT INTO species VALUES (18, 'Pieskomil', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'Morča', '', '');
INSERT INTO species VALUES (21, 'Zlatá rybka', '', '');
INSERT INTO species VALUES (22, 'Škrečok', '', '');
INSERT INTO species VALUES (23, 'Ťava', '', '');
INSERT INTO species VALUES (24, 'Kôň', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Somár', '', '');
INSERT INTO species VALUES (27, 'Lama', '', '');
INSERT INTO species VALUES (28, 'Prasa domáci miláčik', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Kastrácia/Sterilizácia', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Dočasná vakcinácia', '');
INSERT INTO vaccinationtype VALUES (2, 'Prvá vakcinácia', '');
INSERT INTO vaccinationtype VALUES (3, 'Druhá vakcinácia', '');
INSERT INTO vaccinationtype VALUES (4, 'Druhá injekcia', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukémia', '');
INSERT INTO vaccinationtype VALUES (6, 'Kotercový kašeľ', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvoviróza', '');
