DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'K (Köpek)', NULL);
INSERT INTO animaltype VALUES (10, 'S (Sokak Köpeği)', NULL);
INSERT INTO animaltype VALUES (11, 'İ (İstenmeyen Kedi)', NULL);
INSERT INTO animaltype VALUES (12, 'C (Sokak Kedisi)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Muhtelif)', NULL);
INSERT INTO animaltype VALUES (40, 'B (Barınak Hayvanı Değil)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'Siyah', NULL);
INSERT INTO basecolour VALUES (2, 'Beyaz', NULL);
INSERT INTO basecolour VALUES (3, 'Siyah ve Beyaz', NULL);
INSERT INTO basecolour VALUES (4, 'Kızıl', NULL);
INSERT INTO basecolour VALUES (5, 'Beyaz ve Siyah', NULL);
INSERT INTO basecolour VALUES (6, 'Alacalı', NULL);
INSERT INTO basecolour VALUES (7, 'Tekir', NULL);
INSERT INTO basecolour VALUES (8, 'Kızıl Kahverengi', NULL);
INSERT INTO basecolour VALUES (9, 'Siyah ve Kızıl Kahverengi', NULL);
INSERT INTO basecolour VALUES (10, 'Kızıl kahverengi ve Siyah', NULL);
INSERT INTO basecolour VALUES (11, 'Kahverengi', NULL);
INSERT INTO basecolour VALUES (12, 'Kahverengi ve Siyah', NULL);
INSERT INTO basecolour VALUES (13, 'Siyah ve Kahverengi', NULL);
INSERT INTO basecolour VALUES (14, 'Benekli Gri', NULL);
INSERT INTO basecolour VALUES (15, 'Benekli Gri ve Siyah', NULL);
INSERT INTO basecolour VALUES (16, 'Benekli Gri ve Beyaz', NULL);
INSERT INTO basecolour VALUES (17, 'Siyah ve Benekli Gri', NULL);
INSERT INTO basecolour VALUES (18, 'Beyaz ve Benekli Gri', NULL);
INSERT INTO basecolour VALUES (19, 'Üçrenkli', NULL);
INSERT INTO basecolour VALUES (20, 'Koyu Kızıl', NULL);
INSERT INTO basecolour VALUES (21, 'Koyu Kızıl ve Beyaz', NULL);
INSERT INTO basecolour VALUES (22, 'Beyaz ve Koyu Kızıl', NULL);
INSERT INTO basecolour VALUES (23, 'Krem', NULL);
INSERT INTO basecolour VALUES (24, 'Kızıl Kahverengi ve Beyaz', NULL);
INSERT INTO basecolour VALUES (26, 'Beyaz ve Kızıl Kahverengi', NULL);
INSERT INTO basecolour VALUES (27, 'Alacalı Beyaz', NULL);
INSERT INTO basecolour VALUES (28, 'Tekir Beyaz', NULL);
INSERT INTO basecolour VALUES (29, 'Kızıl Beyaz', NULL);
INSERT INTO basecolour VALUES (30, 'Gri', NULL);
INSERT INTO basecolour VALUES (31, 'Gri ve Beyaz', NULL);
INSERT INTO basecolour VALUES (32, 'Beyaz ve Gri', NULL);
INSERT INTO basecolour VALUES (33, 'Beyaz ve Alacalı', NULL);
INSERT INTO basecolour VALUES (35, 'Kahverengi ve Beyaz', NULL);
INSERT INTO basecolour VALUES (36, 'Mavi', NULL);
INSERT INTO basecolour VALUES (37, 'Beyaz ve Tekir', NULL);
INSERT INTO basecolour VALUES (38, 'Sari ve Gri', NULL);
INSERT INTO basecolour VALUES (39, 'Karışık', NULL);
INSERT INTO basecolour VALUES (40, 'Beyaz ve Kahverengi', NULL);
INSERT INTO basecolour VALUES (41, 'Yeşil', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Afgan Tazısı', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Alaskan Malamute', '', '', 1);
INSERT INTO breed VALUES (7, 'American Bulldog', '', '', 1);
INSERT INTO breed VALUES (8, 'American Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (9, 'American Staffordshire Terrier', '', '', 1);
INSERT INTO breed VALUES (10, 'American Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (11, 'Anadolu Kangal', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzell Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (13, 'Australian Cattle Dog/Blue Heeler', '', '', 1);
INSERT INTO breed VALUES (14, 'Australian Kelpie', '', '', 1);
INSERT INTO breed VALUES (15, 'Australian Shepherd', '', '', 1);
INSERT INTO breed VALUES (16, 'Australian Terrier', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgian Shepherd Dog Sheepdog', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgian Shepherd Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgian Shepherd Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgian Shepherd Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Bernese Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon Frise', '', '', 1);
INSERT INTO breed VALUES (29, 'Black and Tan Coonhound', '', '', 1);
INSERT INTO breed VALUES (30, 'Black Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Bloodhound', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Borzoi', '', '', 1);
INSERT INTO breed VALUES (37, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (38, 'Bouvier des Flanders', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Brittany Spaniel', '', '', 1);
INSERT INTO breed VALUES (43, 'Brussels Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Canaan Dog', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso Mastiff', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina Dog', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Cattle Dog', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bay Retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chinese Crested Dog', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinese Foo Dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Chocolate Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Dachshund', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmaçyalı', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Doberman Pinscher', '', '', 1);
INSERT INTO breed VALUES (70, 'Dogo Argentino', '', '', 1);
INSERT INTO breed VALUES (71, 'Dogue de Bordeaux', '', '', 1);
INSERT INTO breed VALUES (72, 'Dutch Shepherd', '', '', 1);
INSERT INTO breed VALUES (73, 'English Bulldog', '', '', 1);
INSERT INTO breed VALUES (74, 'English Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (75, 'English Coonhound', '', '', 1);
INSERT INTO breed VALUES (76, 'English Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'English Setter', '', '', 1);
INSERT INTO breed VALUES (78, 'English Shepherd', '', '', 1);
INSERT INTO breed VALUES (79, 'English Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (80, 'English Toy Spaniel', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila Brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Finnish Lapphund', '', '', 1);
INSERT INTO breed VALUES (86, 'Finnish Spitz', '', '', 1);
INSERT INTO breed VALUES (87, 'Flat-coated Retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'French Bulldog', '', '', 1);
INSERT INTO breed VALUES (91, 'German Pinscher', '', '', 1);
INSERT INTO breed VALUES (92, 'German Shepherd Dog', '', '', 1);
INSERT INTO breed VALUES (93, 'German Shorthaired Pointer', '', '', 1);
INSERT INTO breed VALUES (94, 'German Wirehaired Pointer', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Great Dane', '', '', 1);
INSERT INTO breed VALUES (99, 'Great Pyrenees', '', '', 1);
INSERT INTO breed VALUES (100, 'Greater Swiss Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Havanese', '', '', 1);
INSERT INTO breed VALUES (103, 'Tazı', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibizan Hound', '', '', 1);
INSERT INTO breed VALUES (107, 'Illyrian Sheepdog', '', '', 1);
INSERT INTO breed VALUES (108, 'Irish Setter', '', '', 1);
INSERT INTO breed VALUES (109, 'Irish Terrier', '', '', 1);
INSERT INTO breed VALUES (110, 'Irish Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (111, 'Irish Wolfhound', '', '', 1);
INSERT INTO breed VALUES (112, 'Italian Greyhound', '', '', 1);
INSERT INTO breed VALUES (113, 'Italian Spinone', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Japanese Chin', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Dog', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelian Bear Dog', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue Terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Löwchen', '', '', 1);
INSERT INTO breed VALUES (131, 'Maltese', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremma Sheepdog', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Miniature Pinscher', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (140, 'Neapolitan Mastiff', '', '', 1);
INSERT INTO breed VALUES (141, 'New Guinea Singing Dog', '', '', 1);
INSERT INTO breed VALUES (142, 'Newfoundland Dog', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich Terrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Norwegian Buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Norwegian Elkhound', '', '', 1);
INSERT INTO breed VALUES (147, 'Norwegian Lundehund', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia Duck-Tolling Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Old English Sheepdog', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhound', '', '', 1);
INSERT INTO breed VALUES (151, 'Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier (Fell Terrier)', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekingese', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruvian Inca Orchid', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit Basset Griffon Vendeen', '', '', 1);
INSERT INTO breed VALUES (156, 'Pharaoh Hound', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Portugese Podengo', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polish Lowland Sheepdog', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Poodle', '', '', 1);
INSERT INTO breed VALUES (164, 'Portuguese Water Dog', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Pug', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesian Ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'Saint Bernard St. Bernard', '', '', 1);
INSERT INTO breed VALUES (176, 'Samoyed', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Scottish Deerhound', '', '', 1);
INSERT INTO breed VALUES (180, 'Scottish Terrier Scottie', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Sheep Dog', '', '', 1);
INSERT INTO breed VALUES (185, 'Shepherd', '', '', 1);
INSERT INTO breed VALUES (186, 'Shetland Sheepdog Sheltie', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Siberian Husky', '', '', 1);
INSERT INTO breed VALUES (190, 'Silky Terrier', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Smooth Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'South Russian Ovcharka', '', '', 1);
INSERT INTO breed VALUES (198, 'Swedish Vallhund', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Tibetan Mastiff', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibetan Spaniel', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibetan Terrier', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimaraner', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier Westie', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'White German Shepherd', '', '', 1);
INSERT INTO breed VALUES (216, 'Wire-haired Pointing Griffon', '', '', 1);
INSERT INTO breed VALUES (217, 'Wirehaired Terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'Yellow Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier Yorkie', '', '', 1);
INSERT INTO breed VALUES (220, 'Xoloitzcuintle/Mexican Hairless', '', '', 1);
INSERT INTO breed VALUES (221, 'Abyssinian', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'American Shorthair', '', '', 2);
INSERT INTO breed VALUES (224, 'American Wirehair', '', '', 2);
INSERT INTO breed VALUES (225, 'Applehead Siamese', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinese', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengal', '', '', 2);
INSERT INTO breed VALUES (228, 'Birman', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'British Shorthair', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmese', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Calico', '', '', 2);
INSERT INTO breed VALUES (235, 'Canadian Hairless', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Dilute Calico', '', '', 2);
INSERT INTO breed VALUES (242, 'Dilute Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (243, 'Domestic Long Hair', '', '', 2);
INSERT INTO breed VALUES (252, 'Domestic Medium Hair', '', '', 2);
INSERT INTO breed VALUES (261, 'Domestic Short Hair', '', '', 2);
INSERT INTO breed VALUES (271, 'Egyptian Mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Exotic Shorthair', '', '', 2);
INSERT INTO breed VALUES (273, 'Extra-Toes Cat (Hemingway Polydactyl)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Japanese Bobtail', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Norwegian Forest Cat', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Oriental Long Hair', '', '', 2);
INSERT INTO breed VALUES (285, 'Oriental Short Hair', '', '', 2);
INSERT INTO breed VALUES (286, 'Oriental Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'İran', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Russian Blue', '', '', 2);
INSERT INTO breed VALUES (292, 'Scottish Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siyam', '', '', 2);
INSERT INTO breed VALUES (295, 'Sibirya', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somali', '', '', 2);
INSERT INTO breed VALUES (299, 'Sfenks (tüysüz kedi)', '', '', 2);
INSERT INTO breed VALUES (300, 'Tekir', '', '', 2);
INSERT INTO breed VALUES (307, 'Tiger', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkinese', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (311, 'Ankara Kedisi', '', '', 2);
INSERT INTO breed VALUES (312, 'Van Kedisi', '', '', 2);
INSERT INTO breed VALUES (313, 'Tuxedo', '', '', 2);
INSERT INTO breed VALUES (314, 'American', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Ankara Tavşanı', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Tavşan', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Dutch', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polish', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silver', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Kızıl Kahverengi', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabian', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Eşek', '', '', 26);
INSERT INTO breed VALUES (361, 'Draft', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Midilli', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Ferret', '', '', 3);
INSERT INTO breed VALUES (381, 'Gerbil', '', '', 18);
INSERT INTO breed VALUES (382, 'Guinea Pig', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Hedgehog', '', '', 6);
INSERT INTO breed VALUES (385, 'Fare', '', '', 4);
INSERT INTO breed VALUES (386, 'Prairie Dog', '', '', 5);
INSERT INTO breed VALUES (387, 'Rat', '', '', 5);
INSERT INTO breed VALUES (388, 'Skunk', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (391, 'Vietnamese Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (392, 'Gecko', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Kertenkele', '', '', 13);
INSERT INTO breed VALUES (395, 'Yılan', '', '', 13);
INSERT INTO breed VALUES (396, 'Kaplumbağa', '', '', 13);
INSERT INTO breed VALUES (397, 'Balık', '', '', 21);
INSERT INTO breed VALUES (398, 'African Grey', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Budgie/Budgerigar', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Canary', '', '', 3);
INSERT INTO breed VALUES (404, 'Chicken', '', '', 3);
INSERT INTO breed VALUES (405, 'Cockatiel', '', '', 3);
INSERT INTO breed VALUES (406, 'Cockatoo', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Dove', '', '', 3);
INSERT INTO breed VALUES (409, 'Duck', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'Emu', '', '', 3);
INSERT INTO breed VALUES (412, 'Finch', '', '', 3);
INSERT INTO breed VALUES (413, 'Goose', '', '', 3);
INSERT INTO breed VALUES (414, 'Guinea fowl', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lory/Lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Ostrich', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakeet (Other)', '', '', 3);
INSERT INTO breed VALUES (422, 'Parrot (Other)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Peacock/Pea fowl', '', '', 3);
INSERT INTO breed VALUES (425, 'Pheasant', '', '', 3);
INSERT INTO breed VALUES (426, 'Pigeon', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Swan', '', '', 3);
INSERT INTO breed VALUES (435, 'Toucan', '', '', 3);
INSERT INTO breed VALUES (436, 'Turkey', '', '', 3);
INSERT INTO breed VALUES (437, 'Cow', '', '', 16);
INSERT INTO breed VALUES (438, 'Goat', '', '', 16);
INSERT INTO breed VALUES (439, 'Sheep', '', '', 16);
INSERT INTO breed VALUES (440, 'Llama', '', '', 16);
INSERT INTO breed VALUES (441, 'Pig (Farm)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%';
INSERT INTO configuration VALUES ('Organisation', 'Organizasyon');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Bebek');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Genç Yetişkin');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Yetişkin');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Yaşlı');
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Mikroçip Takılmamış Hayvan', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Denetim');
INSERT INTO customreport VALUES (37, 'Fotoğrafsız Hayvanlar', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Denetim');
INSERT INTO customreport VALUES (38, 'Hiç Aşılanmamış Hayvanlar', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Denetim');
INSERT INTO customreport VALUES (39, 'Non-Neutered/Spayed Animals Aged Over 6 Months', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Denetim');
INSERT INTO customreport VALUES (40, 'Cats Not Combi-Tested', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Denetim');
INSERT INTO customreport VALUES (41, 'Aylık Hayvan Rakamları', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Rakamlar');
INSERT INTO customreport VALUES (42, 'Uzun DönemliHayvanlar', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Rakamlar');
INSERT INTO customreport VALUES (43, 'Barınak Envanteri', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (44, 'Detailed Shelter Inventory', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (45, 'Animals Not Part Of A Litter', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Litters');
INSERT INTO customreport VALUES (46, 'In/Out', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Hareketler');
INSERT INTO customreport VALUES (47, 'Giriş/Çıkış Özetleri', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Hareketler');
INSERT INTO customreport VALUES (48, 'Transfer Raporu', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Hareketler');
INSERT INTO customreport VALUES (49, 'Satıcı başına Evlat Edinme Hacmi', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Satıcılar');
INSERT INTO customreport VALUES (50, 'Evlat Edinmeden Önce Satıcıda Geçen Ortalama Süre', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Satıcılar');
INSERT INTO customreport VALUES (51, 'Satıcı Envanteri', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Satıcılar');
INSERT INTO customreport VALUES (52, 'İadeEDilenHayvanlar Raporu', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'İadeler');
INSERT INTO customreport VALUES (53, '6 Ay İçinde Geri Dönen Hayvanlar', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'İadeler');
INSERT INTO customreport VALUES (54, '6 Aydan Sonra Geri Dönen Hayvanlar', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'İadeler');
INSERT INTO customreport VALUES (55, 'En Sık kullanılan İsim', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'İstatistikler');
INSERT INTO customreport VALUES (56, 'Hayvan Ölüm    Sebepleri', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'İstatistikler');
INSERT INTO customreport VALUES (57, 'En Sık Hayvan Giriş Alanları', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'İstatistikler');
INSERT INTO customreport VALUES (58, 'En Sık Evlat EDinme Alanları', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'İstatistikler');
INSERT INTO customreport VALUES (59, 'Bekleme Listesinde Geçen Ortalam Zaman', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'İstatistikler');
INSERT INTO customreport VALUES (60, 'Aylık Bağışlar', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Fİnansal Grafikler');
INSERT INTO customreport VALUES (61, 'Türlere Göre Aylık Bağışlar', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Fİnansal Grafikler');
INSERT INTO customreport VALUES (62, 'Türlere Göre Aylık Evlat Edinmeler', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Hareket Grafikleri');
INSERT INTO customreport VALUES (63, 'Alana Göre Aylık Evlat Edinmeler', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Hareket Grafikleri');
INSERT INTO customreport VALUES (64, 'Hayvan Kayıt Nedenleri', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Hareket Grafikleri');
INSERT INTO customreport VALUES (65, 'Hayvan Geri Dönüş Nedenleri', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Hareket Grafikleri');
INSERT INTO customreport VALUES (66, 'Sahip Kriter Eşleşmesi', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Ölü Olarak Varmış', '');
INSERT INTO deathreason VALUES (2, 'Öldü', '');
INSERT INTO deathreason VALUES (3, 'Sağlıklı', '');
INSERT INTO deathreason VALUES (4, 'Hasta/Yaralı', '');
INSERT INTO deathreason VALUES (5, 'TalepEdilen', '');
INSERT INTO deathreason VALUES (6, 'Dışlanmış', '');
INSERT INTO deathreason VALUES (7, 'Yabani', '');
INSERT INTO deathreason VALUES (8, 'Isırma', '');
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'Bağış', '');
INSERT INTO donationtype VALUES (2, 'Adoption Fee', '');
INSERT INTO donationtype VALUES (3, 'Bekleme Listesi Bağışı', '');
INSERT INTO donationtype VALUES (4, 'Giriş Bağışı', '');
INSERT INTO donationtype VALUES (5, 'Animal Sponsorship', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Evlilik/İlişki Bölünmesi', '');
INSERT INTO entryreason VALUES (2, 'Alerjiler', '');
INSERT INTO entryreason VALUES (3, 'Isırma', '');
INSERT INTO entryreason VALUES (4, 'Başedilememiş', '');
INSERT INTO entryreason VALUES (5, 'Uygunsuz Yerleşim Yeri', '');
INSERT INTO entryreason VALUES (6, 'Öldü', '');
INSERT INTO entryreason VALUES (7, 'Kaçak', '');
INSERT INTO entryreason VALUES (8, 'Hasta/Yaralı', '');
INSERT INTO entryreason VALUES (9, 'Mali Zorluklar', '');
INSERT INTO entryreason VALUES (10, 'İstismar', '');
INSERT INTO entryreason VALUES (11, 'Terkedilmiş', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'Bölge Yok', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'Dişi');
INSERT INTO lksex VALUES (1, 'Erkek');
INSERT INTO lksex VALUES (2, 'Bilinmeyen');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'Çok Büyük');
INSERT INTO lksize VALUES (1, 'Büyük');
INSERT INTO lksize VALUES (2, 'Orta');
INSERT INTO lksize VALUES (3, 'Küçük');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'Kısa');
INSERT INTO lkcoattype VALUES (1, 'Uzun');
INSERT INTO lkcoattype VALUES (2, 'Sert');
INSERT INTO lkcoattype VALUES (3, 'Kıvırcık');
INSERT INTO lkcoattype VALUES (4, 'Çizgili');
INSERT INTO lkcoattype VALUES (5, 'Tüysüz');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'Hiçbiri');
INSERT INTO lksmovementtype VALUES (1, 'Evlat Edinme');
INSERT INTO lksmovementtype VALUES (2, 'Koruyucu Aile');
INSERT INTO lksmovementtype VALUES (3, 'Transfer');
INSERT INTO lksmovementtype VALUES (4, 'Kaçak');
INSERT INTO lksmovementtype VALUES (5, 'Geri İsteme');
INSERT INTO lksmovementtype VALUES (6, 'Çalıntı');
INSERT INTO lksmovementtype VALUES (7, 'Doğaya Salınmış');
INSERT INTO lksmovementtype VALUES (8, 'Satıcı');
INSERT INTO lksmovementtype VALUES (9, 'Rezervasyon');
INSERT INTO lksmovementtype VALUES (10, 'İptal Rezervasyon');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'Hayvan');
INSERT INTO lksmedialink VALUES (1, 'Kayıp Hayvan');
INSERT INTO lksmedialink VALUES (2, 'Bulunmuş Hayvan');
INSERT INTO lksmedialink VALUES (3, 'Sahip');
INSERT INTO lksmedialink VALUES (4, 'Hareket');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'Hiçbiri');
INSERT INTO lksdiarylink VALUES (1, 'Hayvan');
INSERT INTO lksdiarylink VALUES (2, 'Sahip');
INSERT INTO lksdiarylink VALUES (3, 'Kayıp Hayvan');
INSERT INTO lksdiarylink VALUES (4, 'Bulunmuş Hayvan');
INSERT INTO lksdiarylink VALUES (5, 'Bekleme Listesi');
INSERT INTO lksdiarylink VALUES (6, 'Hareket');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'One-Off');
INSERT INTO lksdonationfreq VALUES (1, 'Weekly');
INSERT INTO lksdonationfreq VALUES (2, 'Monthly');
INSERT INTO lksdonationfreq VALUES (3, 'Quarterly');
INSERT INTO lksdonationfreq VALUES (4, 'Half-Yearly');
INSERT INTO lksdonationfreq VALUES (5, 'Annually');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'Hayvan');
INSERT INTO lksfieldlink VALUES (1, 'Sahip');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'Evet/Hayır');
INSERT INTO lksfieldtype VALUES (1, 'Metin');
INSERT INTO lksfieldtype VALUES (2, 'Notlar');
INSERT INTO lksfieldtype VALUES (3, 'Sayı');
INSERT INTO lksfieldtype VALUES (4, 'Tarih');
INSERT INTO lksfieldtype VALUES (5, 'Para');
INSERT INTO lksfieldtype VALUES (6, 'Arama');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'Hayvan');
INSERT INTO lksloglink VALUES (1, 'Sahip');
INSERT INTO lksloglink VALUES (2, 'Kayıp Hayvan');
INSERT INTO lksloglink VALUES (3, 'Bulunmuş Hayvan');
INSERT INTO lksloglink VALUES (4, 'Bekleme Listesi');
INSERT INTO lksloglink VALUES (5, 'Hareket');
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Acil');
INSERT INTO lkurgency VALUES (2, 'Yüksek');
INSERT INTO lkurgency VALUES (3, 'Orta');
INSERT INTO lkurgency VALUES (4, 'Düşük');
INSERT INTO lkurgency VALUES (5, 'En düşük');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Isırık', '');
INSERT INTO logtype VALUES (2, 'Şİkayet', '');
INSERT INTO logtype VALUES (3, 'Geçmiş', '');
INSERT INTO logtype VALUES (4, 'Ağırlık', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'Köpek', '', '');
INSERT INTO species VALUES (2, 'Kedi', '', '');
INSERT INTO species VALUES (3, 'Kuş', '', '');
INSERT INTO species VALUES (4, 'Fare', '', '');
INSERT INTO species VALUES (5, 'Rat', '', '');
INSERT INTO species VALUES (6, 'Hedgehog', '', '');
INSERT INTO species VALUES (7, 'Tavşan', '', '');
INSERT INTO species VALUES (8, 'Dove', '', '');
INSERT INTO species VALUES (9, 'Ferret', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'Yılan', '', '');
INSERT INTO species VALUES (12, 'Kaplumbağa', '', '');
INSERT INTO species VALUES (13, 'Su Kaplumbağası', '', '');
INSERT INTO species VALUES (14, 'Chicken', '', '');
INSERT INTO species VALUES (15, 'Baykuş', '', '');
INSERT INTO species VALUES (16, 'Goat', '', '');
INSERT INTO species VALUES (17, 'Goose', '', '');
INSERT INTO species VALUES (18, 'Gerbil', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'Guinea Pig', '', '');
INSERT INTO species VALUES (21, 'Japon Balığı', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Deve', '', '');
INSERT INTO species VALUES (24, 'At', '', '');
INSERT INTO species VALUES (25, 'Midilli', '', '');
INSERT INTO species VALUES (26, 'Eşek', '', '');
INSERT INTO species VALUES (27, 'Llama', '', '');
INSERT INTO species VALUES (28, 'Domuz', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Kısırlaştırmak', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Geçici Aşı', '');
INSERT INTO vaccinationtype VALUES (2, 'İlk Aşı', '');
INSERT INTO vaccinationtype VALUES (3, 'İkinci Aşı', '');
INSERT INTO vaccinationtype VALUES (4, 'Ek Aşı', '');
INSERT INTO vaccinationtype VALUES (5, 'Lösemi', '');
INSERT INTO vaccinationtype VALUES (6, 'Öksürük', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirus', '');
