DELETE FROM accounts;
INSERT INTO accounts VALUES (1, 'Income::Donation', 'Incoming donations (misc)', 5, 1, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (2, 'Income::Adoption', 'Adoption fee donations', 5, 2, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (3, 'Income::WaitingList', 'Waiting list donations', 5, 3, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (4, 'Income::EntryDonation', 'Donations for animals entering the shelter', 5, 4, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (5, 'Income::Sponsorship', 'Sponsorship donations', 5, 5, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (6, 'Income::Shop', 'Income from an on-site shop', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (7, 'Income::Interest', 'Bank account interest', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (8, 'Income::OpeningBalances', 'Opening balances', 5, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (9, 'Bank::Current', 'Bank current account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (10, 'Bank::Deposit', 'Bank deposit account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (11, 'Bank::Savings', 'Bank savings account', 1, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (12, 'Asset::Premises', 'Premises', 8, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (13, 'Expenses::Phone', 'Telephone Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (14, 'Expenses::Electricity', 'Electricity Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (15, 'Expenses::Water', 'Water Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (16, 'Expenses::Gas', 'Gas Bills', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (17, 'Expenses::Postage', 'Postage costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (18, 'Expenses::Stationary', 'Stationary costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
INSERT INTO accounts VALUES (19, 'Expenses::Food', 'Animal food costs', 4, 0, 0, 'translate', '2010-06-14 11:51:00', 'translate', '2010-06-14 11:51:00');
DELETE FROM animaltype;
INSERT INTO animaltype VALUES (2, 'D (Dog)', NULL);
INSERT INTO animaltype VALUES (10, 'F (Stray Dog)', NULL);
INSERT INTO animaltype VALUES (11, 'U (Unwanted Cat)', NULL);
INSERT INTO animaltype VALUES (12, 'S (Stray Cat)', NULL);
INSERT INTO animaltype VALUES (13, 'M (Miscellaneous)', NULL);
INSERT INTO animaltype VALUES (40, 'N (Non Shelter Animal)', NULL);
DELETE FROM basecolour;
INSERT INTO basecolour VALUES (1, 'ดำ', NULL);
INSERT INTO basecolour VALUES (2, 'ขาว', NULL);
INSERT INTO basecolour VALUES (3, 'ดำและขาว', NULL);
INSERT INTO basecolour VALUES (4, 'Ginger', NULL);
INSERT INTO basecolour VALUES (5, 'ขาวและดำ', NULL);
INSERT INTO basecolour VALUES (6, 'Torti', NULL);
INSERT INTO basecolour VALUES (7, 'Tabby', NULL);
INSERT INTO basecolour VALUES (8, 'Tan', NULL);
INSERT INTO basecolour VALUES (9, 'Black and Tan', NULL);
INSERT INTO basecolour VALUES (10, 'Tan and Black', NULL);
INSERT INTO basecolour VALUES (11, 'น้ำตาล', NULL);
INSERT INTO basecolour VALUES (12, 'น้ำตาลและดำ', NULL);
INSERT INTO basecolour VALUES (13, 'ดำและน้ำตาล', NULL);
INSERT INTO basecolour VALUES (14, 'Brindle', NULL);
INSERT INTO basecolour VALUES (15, 'Brindle and Black', NULL);
INSERT INTO basecolour VALUES (16, 'Brindle and White', NULL);
INSERT INTO basecolour VALUES (17, 'Black and Brindle', NULL);
INSERT INTO basecolour VALUES (18, 'White and Brindle', NULL);
INSERT INTO basecolour VALUES (19, 'Tricolour', NULL);
INSERT INTO basecolour VALUES (20, 'Liver', NULL);
INSERT INTO basecolour VALUES (21, 'Liver and White', NULL);
INSERT INTO basecolour VALUES (22, 'White and Liver', NULL);
INSERT INTO basecolour VALUES (23, 'ครีม', NULL);
INSERT INTO basecolour VALUES (24, 'Tan and White', NULL);
INSERT INTO basecolour VALUES (26, 'White and Tan', NULL);
INSERT INTO basecolour VALUES (27, 'Torti and White', NULL);
INSERT INTO basecolour VALUES (28, 'Tabby and White', NULL);
INSERT INTO basecolour VALUES (29, 'Ginger and White', NULL);
INSERT INTO basecolour VALUES (30, 'เทา', NULL);
INSERT INTO basecolour VALUES (31, 'เทาและขาว', NULL);
INSERT INTO basecolour VALUES (32, 'ขาวและเทา', NULL);
INSERT INTO basecolour VALUES (33, 'White and Torti', NULL);
INSERT INTO basecolour VALUES (35, 'น้ำตาลและขาว', NULL);
INSERT INTO basecolour VALUES (36, 'น้ำเงิน', NULL);
INSERT INTO basecolour VALUES (37, 'White and Tabby', NULL);
INSERT INTO basecolour VALUES (38, 'เหลืองและเทา', NULL);
INSERT INTO basecolour VALUES (39, 'Various', NULL);
INSERT INTO basecolour VALUES (40, 'ขาวและน้ำตาล', NULL);
INSERT INTO basecolour VALUES (41, 'เขียว', NULL);
DELETE FROM breed;
INSERT INTO breed VALUES (1, 'Affenpinscher', '', '', 1);
INSERT INTO breed VALUES (2, 'Afghan Hound', '', '', 1);
INSERT INTO breed VALUES (3, 'Airedale Terrier', '', '', 1);
INSERT INTO breed VALUES (4, 'Akbash', '', '', 1);
INSERT INTO breed VALUES (5, 'Akita', '', '', 1);
INSERT INTO breed VALUES (6, 'Alaskan Malamute', '', '', 1);
INSERT INTO breed VALUES (7, 'American Bulldog', '', '', 1);
INSERT INTO breed VALUES (8, 'American Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (9, 'American Staffordshire Terrier', '', '', 1);
INSERT INTO breed VALUES (10, 'American Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (11, 'Anatolian Shepherd', '', '', 1);
INSERT INTO breed VALUES (12, 'Appenzell Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (13, 'Australian Cattle Dog/Blue Heeler', '', '', 1);
INSERT INTO breed VALUES (14, 'Australian Kelpie', '', '', 1);
INSERT INTO breed VALUES (15, 'Australian Shepherd', '', '', 1);
INSERT INTO breed VALUES (16, 'Australian Terrier', '', '', 1);
INSERT INTO breed VALUES (17, 'Basenji', '', '', 1);
INSERT INTO breed VALUES (18, 'Basset Hound', '', '', 1);
INSERT INTO breed VALUES (19, 'Beagle', '', '', 1);
INSERT INTO breed VALUES (20, 'Bearded Collie', '', '', 1);
INSERT INTO breed VALUES (21, 'Beauceron', '', '', 1);
INSERT INTO breed VALUES (22, 'Bedlington Terrier', '', '', 1);
INSERT INTO breed VALUES (23, 'Belgian Shepherd Dog Sheepdog', '', '', 1);
INSERT INTO breed VALUES (24, 'Belgian Shepherd Laekenois', '', '', 1);
INSERT INTO breed VALUES (25, 'Belgian Shepherd Malinois', '', '', 1);
INSERT INTO breed VALUES (26, 'Belgian Shepherd Tervuren', '', '', 1);
INSERT INTO breed VALUES (27, 'Bernese Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (28, 'Bichon Frise', '', '', 1);
INSERT INTO breed VALUES (29, 'Black and Tan Coonhound', '', '', 1);
INSERT INTO breed VALUES (30, 'Black Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (31, 'Black Mouth Cur', '', '', 1);
INSERT INTO breed VALUES (32, 'Bloodhound', '', '', 1);
INSERT INTO breed VALUES (33, 'Bluetick Coonhound', '', '', 1);
INSERT INTO breed VALUES (34, 'Border Collie', '', '', 1);
INSERT INTO breed VALUES (35, 'Border Terrier', '', '', 1);
INSERT INTO breed VALUES (36, 'Borzoi', '', '', 1);
INSERT INTO breed VALUES (37, 'Boston Terrier', '', '', 1);
INSERT INTO breed VALUES (38, 'Bouvier des Flanders', '', '', 1);
INSERT INTO breed VALUES (39, 'Boykin Spaniel', '', '', 1);
INSERT INTO breed VALUES (40, 'Boxer', '', '', 1);
INSERT INTO breed VALUES (41, 'Briard', '', '', 1);
INSERT INTO breed VALUES (42, 'Brittany Spaniel', '', '', 1);
INSERT INTO breed VALUES (43, 'Brussels Griffon', '', '', 1);
INSERT INTO breed VALUES (44, 'Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (45, 'Bullmastiff', '', '', 1);
INSERT INTO breed VALUES (46, 'Cairn Terrier', '', '', 1);
INSERT INTO breed VALUES (47, 'Canaan Dog', '', '', 1);
INSERT INTO breed VALUES (48, 'Cane Corso Mastiff', '', '', 1);
INSERT INTO breed VALUES (49, 'Carolina Dog', '', '', 1);
INSERT INTO breed VALUES (50, 'Catahoula Leopard Dog', '', '', 1);
INSERT INTO breed VALUES (51, 'Cattle Dog', '', '', 1);
INSERT INTO breed VALUES (52, 'Cavalier King Charles Spaniel', '', '', 1);
INSERT INTO breed VALUES (53, 'Chesapeake Bay Retriever', '', '', 1);
INSERT INTO breed VALUES (54, 'Chihuahua', '', '', 1);
INSERT INTO breed VALUES (55, 'Chinese Crested Dog', '', '', 1);
INSERT INTO breed VALUES (56, 'Chinese Foo Dog', '', '', 1);
INSERT INTO breed VALUES (57, 'Chocolate Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (58, 'Chow Chow', '', '', 1);
INSERT INTO breed VALUES (59, 'Clumber Spaniel', '', '', 1);
INSERT INTO breed VALUES (60, 'Cockapoo', '', '', 1);
INSERT INTO breed VALUES (61, 'Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (62, 'Collie', '', '', 1);
INSERT INTO breed VALUES (63, 'Coonhound', '', '', 1);
INSERT INTO breed VALUES (64, 'Corgi', '', '', 1);
INSERT INTO breed VALUES (65, 'Coton de Tulear', '', '', 1);
INSERT INTO breed VALUES (66, 'Dachshund', '', '', 1);
INSERT INTO breed VALUES (67, 'Dalmatian', '', '', 1);
INSERT INTO breed VALUES (68, 'Dandi Dinmont Terrier', '', '', 1);
INSERT INTO breed VALUES (69, 'Doberman Pinscher', '', '', 1);
INSERT INTO breed VALUES (70, 'Dogo Argentino', '', '', 1);
INSERT INTO breed VALUES (71, 'Dogue de Bordeaux', '', '', 1);
INSERT INTO breed VALUES (72, 'Dutch Shepherd', '', '', 1);
INSERT INTO breed VALUES (73, 'English Bulldog', '', '', 1);
INSERT INTO breed VALUES (74, 'English Cocker Spaniel', '', '', 1);
INSERT INTO breed VALUES (75, 'English Coonhound', '', '', 1);
INSERT INTO breed VALUES (76, 'English Pointer', '', '', 1);
INSERT INTO breed VALUES (77, 'English Setter', '', '', 1);
INSERT INTO breed VALUES (78, 'English Shepherd', '', '', 1);
INSERT INTO breed VALUES (79, 'English Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (80, 'English Toy Spaniel', '', '', 1);
INSERT INTO breed VALUES (81, 'Entlebucher', '', '', 1);
INSERT INTO breed VALUES (82, 'Eskimo Dog', '', '', 1);
INSERT INTO breed VALUES (83, 'Field Spaniel', '', '', 1);
INSERT INTO breed VALUES (84, 'Fila Brasileiro', '', '', 1);
INSERT INTO breed VALUES (85, 'Finnish Lapphund', '', '', 1);
INSERT INTO breed VALUES (86, 'Finnish Spitz', '', '', 1);
INSERT INTO breed VALUES (87, 'Flat-coated Retriever', '', '', 1);
INSERT INTO breed VALUES (88, 'Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (89, 'Foxhound', '', '', 1);
INSERT INTO breed VALUES (90, 'French Bulldog', '', '', 1);
INSERT INTO breed VALUES (91, 'German Pinscher', '', '', 1);
INSERT INTO breed VALUES (92, 'German Shepherd Dog', '', '', 1);
INSERT INTO breed VALUES (93, 'German Shorthaired Pointer', '', '', 1);
INSERT INTO breed VALUES (94, 'German Wirehaired Pointer', '', '', 1);
INSERT INTO breed VALUES (95, 'Glen of Imaal Terrier', '', '', 1);
INSERT INTO breed VALUES (96, 'Golden Retriever', '', '', 1);
INSERT INTO breed VALUES (97, 'Gordon Setter', '', '', 1);
INSERT INTO breed VALUES (98, 'Great Dane', '', '', 1);
INSERT INTO breed VALUES (99, 'Great Pyrenees', '', '', 1);
INSERT INTO breed VALUES (100, 'Greater Swiss Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (101, 'Greyhound', '', '', 1);
INSERT INTO breed VALUES (102, 'Havanese', '', '', 1);
INSERT INTO breed VALUES (103, 'Hound', '', '', 1);
INSERT INTO breed VALUES (104, 'Hovawart', '', '', 1);
INSERT INTO breed VALUES (105, 'Husky', '', '', 1);
INSERT INTO breed VALUES (106, 'Ibizan Hound', '', '', 1);
INSERT INTO breed VALUES (107, 'Illyrian Sheepdog', '', '', 1);
INSERT INTO breed VALUES (108, 'Irish Setter', '', '', 1);
INSERT INTO breed VALUES (109, 'Irish Terrier', '', '', 1);
INSERT INTO breed VALUES (110, 'Irish Water Spaniel', '', '', 1);
INSERT INTO breed VALUES (111, 'Irish Wolfhound', '', '', 1);
INSERT INTO breed VALUES (112, 'Italian Greyhound', '', '', 1);
INSERT INTO breed VALUES (113, 'Italian Spinone', '', '', 1);
INSERT INTO breed VALUES (114, 'Jack Russell Terrier', '', '', 1);
INSERT INTO breed VALUES (115, 'Japanese Chin', '', '', 1);
INSERT INTO breed VALUES (116, 'Jindo', '', '', 1);
INSERT INTO breed VALUES (117, 'Kai Dog', '', '', 1);
INSERT INTO breed VALUES (118, 'Karelian Bear Dog', '', '', 1);
INSERT INTO breed VALUES (119, 'Keeshond', '', '', 1);
INSERT INTO breed VALUES (120, 'Kerry Blue Terrier', '', '', 1);
INSERT INTO breed VALUES (121, 'Kishu', '', '', 1);
INSERT INTO breed VALUES (122, 'Komondor', '', '', 1);
INSERT INTO breed VALUES (123, 'Kuvasz', '', '', 1);
INSERT INTO breed VALUES (124, 'Kyi Leo', '', '', 1);
INSERT INTO breed VALUES (125, 'Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (126, 'Lakeland Terrier', '', '', 1);
INSERT INTO breed VALUES (127, 'Lancashire Heeler', '', '', 1);
INSERT INTO breed VALUES (128, 'Lhasa Apso', '', '', 1);
INSERT INTO breed VALUES (129, 'Leonberger', '', '', 1);
INSERT INTO breed VALUES (130, 'Löwchen', '', '', 1);
INSERT INTO breed VALUES (131, 'Maltese', '', '', 1);
INSERT INTO breed VALUES (132, 'Manchester Terrier', '', '', 1);
INSERT INTO breed VALUES (133, 'Maremma Sheepdog', '', '', 1);
INSERT INTO breed VALUES (134, 'Mastiff', '', '', 1);
INSERT INTO breed VALUES (135, 'McNab', '', '', 1);
INSERT INTO breed VALUES (136, 'Miniature Pinscher', '', '', 1);
INSERT INTO breed VALUES (137, 'Mountain Cur', '', '', 1);
INSERT INTO breed VALUES (138, 'Mountain Dog', '', '', 1);
INSERT INTO breed VALUES (139, 'Munsterlander', '', '', 1);
INSERT INTO breed VALUES (140, 'Neapolitan Mastiff', '', '', 1);
INSERT INTO breed VALUES (141, 'New Guinea Singing Dog', '', '', 1);
INSERT INTO breed VALUES (142, 'Newfoundland Dog', '', '', 1);
INSERT INTO breed VALUES (143, 'Norfolk Terrier', '', '', 1);
INSERT INTO breed VALUES (144, 'Norwich Terrier', '', '', 1);
INSERT INTO breed VALUES (145, 'Norwegian Buhund', '', '', 1);
INSERT INTO breed VALUES (146, 'Norwegian Elkhound', '', '', 1);
INSERT INTO breed VALUES (147, 'Norwegian Lundehund', '', '', 1);
INSERT INTO breed VALUES (148, 'Nova Scotia Duck-Tolling Retriever', '', '', 1);
INSERT INTO breed VALUES (149, 'Old English Sheepdog', '', '', 1);
INSERT INTO breed VALUES (150, 'Otterhound', '', '', 1);
INSERT INTO breed VALUES (151, 'Papillon', '', '', 1);
INSERT INTO breed VALUES (152, 'Patterdale Terrier (Fell Terrier)', '', '', 1);
INSERT INTO breed VALUES (153, 'Pekingese', '', '', 1);
INSERT INTO breed VALUES (154, 'Peruvian Inca Orchid', '', '', 1);
INSERT INTO breed VALUES (155, 'Petit Basset Griffon Vendeen', '', '', 1);
INSERT INTO breed VALUES (156, 'Pharaoh Hound', '', '', 1);
INSERT INTO breed VALUES (157, 'Pit Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (158, 'Plott Hound', '', '', 1);
INSERT INTO breed VALUES (159, 'Portugese Podengo', '', '', 1);
INSERT INTO breed VALUES (160, 'Pointer', '', '', 1);
INSERT INTO breed VALUES (161, 'Polish Lowland Sheepdog', '', '', 1);
INSERT INTO breed VALUES (162, 'Pomeranian', '', '', 1);
INSERT INTO breed VALUES (163, 'Poodle', '', '', 1);
INSERT INTO breed VALUES (164, 'Portuguese Water Dog', '', '', 1);
INSERT INTO breed VALUES (165, 'Presa Canario', '', '', 1);
INSERT INTO breed VALUES (166, 'Pug', '', '', 1);
INSERT INTO breed VALUES (167, 'Puli', '', '', 1);
INSERT INTO breed VALUES (168, 'Pumi', '', '', 1);
INSERT INTO breed VALUES (169, 'Rat Terrier', '', '', 1);
INSERT INTO breed VALUES (170, 'Redbone Coonhound', '', '', 1);
INSERT INTO breed VALUES (171, 'Retriever', '', '', 1);
INSERT INTO breed VALUES (172, 'Rhodesian Ridgeback', '', '', 1);
INSERT INTO breed VALUES (173, 'Rottweiler', '', '', 1);
INSERT INTO breed VALUES (174, 'Saluki', '', '', 1);
INSERT INTO breed VALUES (175, 'Saint Bernard St. Bernard', '', '', 1);
INSERT INTO breed VALUES (176, 'Samoyed', '', '', 1);
INSERT INTO breed VALUES (177, 'Schipperke', '', '', 1);
INSERT INTO breed VALUES (178, 'Schnauzer', '', '', 1);
INSERT INTO breed VALUES (179, 'Scottish Deerhound', '', '', 1);
INSERT INTO breed VALUES (180, 'Scottish Terrier Scottie', '', '', 1);
INSERT INTO breed VALUES (181, 'Sealyham Terrier', '', '', 1);
INSERT INTO breed VALUES (182, 'Setter', '', '', 1);
INSERT INTO breed VALUES (183, 'Shar Pei', '', '', 1);
INSERT INTO breed VALUES (184, 'Sheep Dog', '', '', 1);
INSERT INTO breed VALUES (185, 'Shepherd', '', '', 1);
INSERT INTO breed VALUES (186, 'Shetland Sheepdog Sheltie', '', '', 1);
INSERT INTO breed VALUES (187, 'Shiba Inu', '', '', 1);
INSERT INTO breed VALUES (188, 'Shih Tzu', '', '', 1);
INSERT INTO breed VALUES (189, 'Siberian Husky', '', '', 1);
INSERT INTO breed VALUES (190, 'Silky Terrier', '', '', 1);
INSERT INTO breed VALUES (191, 'Skye Terrier', '', '', 1);
INSERT INTO breed VALUES (192, 'Sloughi', '', '', 1);
INSERT INTO breed VALUES (193, 'Smooth Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (194, 'Spaniel', '', '', 1);
INSERT INTO breed VALUES (195, 'Spitz', '', '', 1);
INSERT INTO breed VALUES (196, 'Staffordshire Bull Terrier', '', '', 1);
INSERT INTO breed VALUES (197, 'South Russian Ovcharka', '', '', 1);
INSERT INTO breed VALUES (198, 'Swedish Vallhund', '', '', 1);
INSERT INTO breed VALUES (199, 'Terrier', '', '', 1);
INSERT INTO breed VALUES (200, 'Thai Ridgeback', '', '', 1);
INSERT INTO breed VALUES (201, 'Tibetan Mastiff', '', '', 1);
INSERT INTO breed VALUES (202, 'Tibetan Spaniel', '', '', 1);
INSERT INTO breed VALUES (203, 'Tibetan Terrier', '', '', 1);
INSERT INTO breed VALUES (204, 'Tosa Inu', '', '', 1);
INSERT INTO breed VALUES (205, 'Toy Fox Terrier', '', '', 1);
INSERT INTO breed VALUES (206, 'Treeing Walker Coonhound', '', '', 1);
INSERT INTO breed VALUES (207, 'Vizsla', '', '', 1);
INSERT INTO breed VALUES (208, 'Weimaraner', '', '', 1);
INSERT INTO breed VALUES (209, 'Welsh Corgi', '', '', 1);
INSERT INTO breed VALUES (210, 'Welsh Terrier', '', '', 1);
INSERT INTO breed VALUES (211, 'Welsh Springer Spaniel', '', '', 1);
INSERT INTO breed VALUES (212, 'West Highland White Terrier Westie', '', '', 1);
INSERT INTO breed VALUES (213, 'Wheaten Terrier', '', '', 1);
INSERT INTO breed VALUES (214, 'Whippet', '', '', 1);
INSERT INTO breed VALUES (215, 'White German Shepherd', '', '', 1);
INSERT INTO breed VALUES (216, 'Wire-haired Pointing Griffon', '', '', 1);
INSERT INTO breed VALUES (217, 'Wirehaired Terrier', '', '', 1);
INSERT INTO breed VALUES (218, 'Yellow Labrador Retriever', '', '', 1);
INSERT INTO breed VALUES (219, 'Yorkshire Terrier Yorkie', '', '', 1);
INSERT INTO breed VALUES (220, 'Xoloitzcuintle/Mexican Hairless', '', '', 1);
INSERT INTO breed VALUES (221, 'Abyssinian', '', '', 2);
INSERT INTO breed VALUES (222, 'American Curl', '', '', 2);
INSERT INTO breed VALUES (223, 'American Shorthair', '', '', 2);
INSERT INTO breed VALUES (224, 'American Wirehair', '', '', 2);
INSERT INTO breed VALUES (225, 'Applehead Siamese', '', '', 2);
INSERT INTO breed VALUES (226, 'Balinese', '', '', 2);
INSERT INTO breed VALUES (227, 'Bengal', '', '', 2);
INSERT INTO breed VALUES (228, 'Birman', '', '', 2);
INSERT INTO breed VALUES (229, 'Bobtail', '', '', 2);
INSERT INTO breed VALUES (230, 'Bombay', '', '', 2);
INSERT INTO breed VALUES (231, 'British Shorthair', '', '', 2);
INSERT INTO breed VALUES (232, 'Burmese', '', '', 2);
INSERT INTO breed VALUES (233, 'Burmilla', '', '', 2);
INSERT INTO breed VALUES (234, 'Calico', '', '', 2);
INSERT INTO breed VALUES (235, 'Canadian Hairless', '', '', 2);
INSERT INTO breed VALUES (236, 'Chartreux', '', '', 2);
INSERT INTO breed VALUES (237, 'Chinchilla', '', '', 2);
INSERT INTO breed VALUES (238, 'Cornish Rex', '', '', 2);
INSERT INTO breed VALUES (239, 'Cymric', '', '', 2);
INSERT INTO breed VALUES (240, 'Devon Rex', '', '', 2);
INSERT INTO breed VALUES (241, 'Dilute Calico', '', '', 2);
INSERT INTO breed VALUES (242, 'Dilute Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (243, 'Domestic Long Hair', '', '', 2);
INSERT INTO breed VALUES (252, 'Domestic Medium Hair', '', '', 2);
INSERT INTO breed VALUES (261, 'Domestic Short Hair', '', '', 2);
INSERT INTO breed VALUES (271, 'Egyptian Mau', '', '', 2);
INSERT INTO breed VALUES (272, 'Exotic Shorthair', '', '', 2);
INSERT INTO breed VALUES (273, 'Extra-Toes Cat (Hemingway Polydactyl)', '', '', 2);
INSERT INTO breed VALUES (274, 'Havana', '', '', 2);
INSERT INTO breed VALUES (275, 'Himalayan', '', '', 2);
INSERT INTO breed VALUES (276, 'Japanese Bobtail', '', '', 2);
INSERT INTO breed VALUES (277, 'Javanese', '', '', 2);
INSERT INTO breed VALUES (278, 'Korat', '', '', 2);
INSERT INTO breed VALUES (279, 'Maine Coon', '', '', 2);
INSERT INTO breed VALUES (280, 'Manx', '', '', 2);
INSERT INTO breed VALUES (281, 'Munchkin', '', '', 2);
INSERT INTO breed VALUES (282, 'Norwegian Forest Cat', '', '', 2);
INSERT INTO breed VALUES (283, 'Ocicat', '', '', 2);
INSERT INTO breed VALUES (284, 'Oriental Long Hair', '', '', 2);
INSERT INTO breed VALUES (285, 'Oriental Short Hair', '', '', 2);
INSERT INTO breed VALUES (286, 'Oriental Tabby', '', '', 2);
INSERT INTO breed VALUES (287, 'Persian', '', '', 2);
INSERT INTO breed VALUES (288, 'Pixie-Bob', '', '', 2);
INSERT INTO breed VALUES (289, 'Ragamuffin', '', '', 2);
INSERT INTO breed VALUES (290, 'Ragdoll', '', '', 2);
INSERT INTO breed VALUES (291, 'Russian Blue', '', '', 2);
INSERT INTO breed VALUES (292, 'Scottish Fold', '', '', 2);
INSERT INTO breed VALUES (293, 'Selkirk Rex', '', '', 2);
INSERT INTO breed VALUES (294, 'Siamese', '', '', 2);
INSERT INTO breed VALUES (295, 'Siberian', '', '', 2);
INSERT INTO breed VALUES (296, 'Singapura', '', '', 2);
INSERT INTO breed VALUES (297, 'Snowshoe', '', '', 2);
INSERT INTO breed VALUES (298, 'Somali', '', '', 2);
INSERT INTO breed VALUES (299, 'Sphynx (hairless cat)', '', '', 2);
INSERT INTO breed VALUES (300, 'Tabby', '', '', 2);
INSERT INTO breed VALUES (307, 'เสือ', '', '', 2);
INSERT INTO breed VALUES (308, 'Tonkinese', '', '', 2);
INSERT INTO breed VALUES (309, 'Torbie', '', '', 2);
INSERT INTO breed VALUES (310, 'Tortoiseshell', '', '', 2);
INSERT INTO breed VALUES (311, 'Turkish Angora', '', '', 2);
INSERT INTO breed VALUES (312, 'Turkish Van', '', '', 2);
INSERT INTO breed VALUES (313, 'Tuxedo', '', '', 2);
INSERT INTO breed VALUES (314, 'อเมริกัน', '', '', 7);
INSERT INTO breed VALUES (315, 'American Fuzzy Lop', '', '', 7);
INSERT INTO breed VALUES (316, 'American Sable', '', '', 7);
INSERT INTO breed VALUES (317, 'Angora Rabbit', '', '', 7);
INSERT INTO breed VALUES (318, 'Belgian Hare', '', '', 7);
INSERT INTO breed VALUES (319, 'Beveren', '', '', 7);
INSERT INTO breed VALUES (320, 'Britannia Petite', '', '', 7);
INSERT INTO breed VALUES (321, 'Bunny Rabbit', '', '', 7);
INSERT INTO breed VALUES (322, 'Californian', '', '', 7);
INSERT INTO breed VALUES (323, 'Champagne DArgent', '', '', 7);
INSERT INTO breed VALUES (324, 'Checkered Giant', '', '', 7);
INSERT INTO breed VALUES (325, 'Chinchilla', '', '', 7);
INSERT INTO breed VALUES (326, 'Cinnamon', '', '', 7);
INSERT INTO breed VALUES (327, 'Crème DArgent', '', '', 7);
INSERT INTO breed VALUES (328, 'Dutch', '', '', 7);
INSERT INTO breed VALUES (329, 'Dwarf', '', '', 7);
INSERT INTO breed VALUES (330, 'Dwarf Eared', '', '', 7);
INSERT INTO breed VALUES (331, 'English Lop', '', '', 7);
INSERT INTO breed VALUES (332, 'English Spot', '', '', 7);
INSERT INTO breed VALUES (333, 'Flemish Giant', '', '', 7);
INSERT INTO breed VALUES (334, 'Florida White', '', '', 7);
INSERT INTO breed VALUES (335, 'French-Lop', '', '', 7);
INSERT INTO breed VALUES (336, 'Harlequin', '', '', 7);
INSERT INTO breed VALUES (337, 'Havana', '', '', 7);
INSERT INTO breed VALUES (338, 'Himalayan', '', '', 7);
INSERT INTO breed VALUES (339, 'Holland Lop', '', '', 7);
INSERT INTO breed VALUES (340, 'Hotot', '', '', 7);
INSERT INTO breed VALUES (341, 'Jersey Wooly', '', '', 7);
INSERT INTO breed VALUES (342, 'Lilac', '', '', 7);
INSERT INTO breed VALUES (343, 'Lop Eared', '', '', 7);
INSERT INTO breed VALUES (344, 'Mini-Lop', '', '', 7);
INSERT INTO breed VALUES (345, 'Mini Rex', '', '', 7);
INSERT INTO breed VALUES (346, 'Netherland Dwarf', '', '', 7);
INSERT INTO breed VALUES (347, 'New Zealand', '', '', 7);
INSERT INTO breed VALUES (348, 'Palomino', '', '', 7);
INSERT INTO breed VALUES (349, 'Polish', '', '', 7);
INSERT INTO breed VALUES (350, 'Rex', '', '', 7);
INSERT INTO breed VALUES (351, 'Rhinelander', '', '', 7);
INSERT INTO breed VALUES (352, 'Satin', '', '', 7);
INSERT INTO breed VALUES (353, 'Silver', '', '', 7);
INSERT INTO breed VALUES (354, 'Silver Fox', '', '', 7);
INSERT INTO breed VALUES (355, 'Silver Marten', '', '', 7);
INSERT INTO breed VALUES (356, 'Tan', '', '', 7);
INSERT INTO breed VALUES (357, 'Appaloosa', '', '', 24);
INSERT INTO breed VALUES (358, 'Arabian', '', '', 24);
INSERT INTO breed VALUES (359, 'Clydesdale', '', '', 24);
INSERT INTO breed VALUES (360, 'Donkey/Mule', '', '', 26);
INSERT INTO breed VALUES (361, 'Draft', '', '', 24);
INSERT INTO breed VALUES (362, 'Gaited', '', '', 24);
INSERT INTO breed VALUES (363, 'Grade', '', '', 24);
INSERT INTO breed VALUES (364, 'Missouri Foxtrotter', '', '', 24);
INSERT INTO breed VALUES (365, 'Morgan', '', '', 24);
INSERT INTO breed VALUES (366, 'Mustang', '', '', 24);
INSERT INTO breed VALUES (367, 'Paint/Pinto', '', '', 24);
INSERT INTO breed VALUES (368, 'Palomino', '', '', 24);
INSERT INTO breed VALUES (369, 'Paso Fino', '', '', 24);
INSERT INTO breed VALUES (370, 'Percheron', '', '', 24);
INSERT INTO breed VALUES (371, 'Peruvian Paso', '', '', 24);
INSERT INTO breed VALUES (372, 'Pony', '', '', 25);
INSERT INTO breed VALUES (373, 'Quarterhorse', '', '', 25);
INSERT INTO breed VALUES (374, 'Saddlebred', '', '', 24);
INSERT INTO breed VALUES (375, 'Standardbred', '', '', 24);
INSERT INTO breed VALUES (376, 'Thoroughbred', '', '', 24);
INSERT INTO breed VALUES (377, 'Tennessee Walker', '', '', 24);
INSERT INTO breed VALUES (378, 'Warmblood', '', '', 24);
INSERT INTO breed VALUES (379, 'Chinchilla', '', '', 10);
INSERT INTO breed VALUES (380, 'Ferret', '', '', 3);
INSERT INTO breed VALUES (381, 'Gerbil', '', '', 18);
INSERT INTO breed VALUES (382, 'Guinea Pig', '', '', 20);
INSERT INTO breed VALUES (383, 'Hamster', '', '', 22);
INSERT INTO breed VALUES (384, 'Hedgehog', '', '', 6);
INSERT INTO breed VALUES (385, 'Mouse', '', '', 4);
INSERT INTO breed VALUES (386, 'Prairie Dog', '', '', 5);
INSERT INTO breed VALUES (387, 'Rat', '', '', 5);
INSERT INTO breed VALUES (388, 'Skunk', '', '', 5);
INSERT INTO breed VALUES (389, 'Sugar Glider', '', '', 5);
INSERT INTO breed VALUES (390, 'Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (391, 'Vietnamese Pot Bellied', '', '', 28);
INSERT INTO breed VALUES (392, 'Gecko', '', '', 13);
INSERT INTO breed VALUES (393, 'Iguana', '', '', 13);
INSERT INTO breed VALUES (394, 'Lizard', '', '', 13);
INSERT INTO breed VALUES (395, 'งู', '', '', 13);
INSERT INTO breed VALUES (396, 'เต่า', '', '', 13);
INSERT INTO breed VALUES (397, 'ปลา', '', '', 21);
INSERT INTO breed VALUES (398, 'African Grey', '', '', 3);
INSERT INTO breed VALUES (399, 'Amazon', '', '', 3);
INSERT INTO breed VALUES (400, 'Brotogeris', '', '', 3);
INSERT INTO breed VALUES (401, 'Budgie/Budgerigar', '', '', 3);
INSERT INTO breed VALUES (402, 'Caique', '', '', 3);
INSERT INTO breed VALUES (403, 'Canary', '', '', 3);
INSERT INTO breed VALUES (404, 'Chicken', '', '', 3);
INSERT INTO breed VALUES (405, 'Cockatiel', '', '', 3);
INSERT INTO breed VALUES (406, 'Cockatoo', '', '', 3);
INSERT INTO breed VALUES (407, 'Conure', '', '', 3);
INSERT INTO breed VALUES (408, 'Dove', '', '', 3);
INSERT INTO breed VALUES (409, 'เป็ด', '', '', 3);
INSERT INTO breed VALUES (410, 'Eclectus', '', '', 3);
INSERT INTO breed VALUES (411, 'อีมู', '', '', 3);
INSERT INTO breed VALUES (412, 'Finch', '', '', 3);
INSERT INTO breed VALUES (413, 'Goose', '', '', 3);
INSERT INTO breed VALUES (414, 'Guinea fowl', '', '', 3);
INSERT INTO breed VALUES (415, 'Kakariki', '', '', 3);
INSERT INTO breed VALUES (416, 'Lory/Lorikeet', '', '', 3);
INSERT INTO breed VALUES (417, 'Lovebird', '', '', 3);
INSERT INTO breed VALUES (418, 'Macaw', '', '', 3);
INSERT INTO breed VALUES (419, 'Mynah', '', '', 3);
INSERT INTO breed VALUES (420, 'Ostrich', '', '', 3);
INSERT INTO breed VALUES (421, 'Parakeet (Other)', '', '', 3);
INSERT INTO breed VALUES (422, 'Parrot (Other)', '', '', 3);
INSERT INTO breed VALUES (423, 'Parrotlet', '', '', 3);
INSERT INTO breed VALUES (424, 'Peacock/Pea fowl', '', '', 3);
INSERT INTO breed VALUES (425, 'Pheasant', '', '', 3);
INSERT INTO breed VALUES (426, 'นกพิราบ', '', '', 3);
INSERT INTO breed VALUES (427, 'Pionus', '', '', 3);
INSERT INTO breed VALUES (428, 'Poicephalus/Senegal', '', '', 3);
INSERT INTO breed VALUES (429, 'Quaker Parakeet', '', '', 3);
INSERT INTO breed VALUES (430, 'Rhea', '', '', 3);
INSERT INTO breed VALUES (431, 'Ringneck/Psittacula', '', '', 3);
INSERT INTO breed VALUES (432, 'Rosella', '', '', 3);
INSERT INTO breed VALUES (433, 'Softbill (Other)', '', '', 3);
INSERT INTO breed VALUES (434, 'Swan', '', '', 3);
INSERT INTO breed VALUES (435, 'Toucan', '', '', 3);
INSERT INTO breed VALUES (436, 'Turkey', '', '', 3);
INSERT INTO breed VALUES (437, 'Cow', '', '', 16);
INSERT INTO breed VALUES (438, 'แพะ', '', '', 16);
INSERT INTO breed VALUES (439, 'แกะ', '', '', 16);
INSERT INTO breed VALUES (440, 'ลามะ', '', '', 16);
INSERT INTO breed VALUES (441, 'หมู (ฟาร์ม)', '', '', 28);
DELETE FROM configuration WHERE ItemName Like 'Organisation' OR ItemName Like 'AgeGroup%Name';
INSERT INTO configuration VALUES ('Organisation', 'Organisation');
INSERT INTO configuration VALUES ('AgeGroup1Name', 'Baby');
INSERT INTO configuration VALUES ('AgeGroup2Name', 'Young Adult');
INSERT INTO configuration VALUES ('AgeGroup3Name', 'Adult');
INSERT INTO configuration VALUES ('AgeGroup4Name', 'Senior');
DELETE FROM costtype;
DELETE FROM customreport;
INSERT INTO customreport VALUES (36, 'Non-Microchipped Animals', '001', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (37, 'สัตว์ที่ยังไม่มีสื่อรูปถ่าย', '002', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (38, 'สัตว์ที่ยังไม่ได้ให้วัคซีน', '003', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (39, 'Non-Neutered/Spayed Animals Aged Over 6 Months', '004', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (40, 'Cats Not Combi-Tested', '005', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Auditing');
INSERT INTO customreport VALUES (41, 'Monthly Animal Figures', '006', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (42, 'Long Term Animals', '007', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Figures');
INSERT INTO customreport VALUES (43, 'Shelter Inventory', '008', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (44, 'Detailed Shelter Inventory', '009', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
INSERT INTO customreport VALUES (45, 'Animals Not Part Of A Litter', '010', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Litters');
INSERT INTO customreport VALUES (46, 'เข้า/ออก', '011', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (47, 'เข้า/ออก สรุป', '012', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (48, 'Transfer In Report', '013', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movements');
INSERT INTO customreport VALUES (49, 'Volume Of Adoptions Per Retailer', '014', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (50, 'Average Time At Retailer Before Adoption', '015', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (51, 'Retailer Inventory', '016', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Retailers');
INSERT INTO customreport VALUES (52, 'Returned Animals Report', '017', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (53, 'Animals Returned Within 6 Months', '018', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (54, 'Animals Returned After 6 Months', '019', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Returns');
INSERT INTO customreport VALUES (55, 'Most Common Name', '020', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'สถิติ');
INSERT INTO customreport VALUES (56, 'เหตุผลที่สัตว์เสียชีวิต', '021', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'สถิติ');
INSERT INTO customreport VALUES (57, 'Most Common Animal Entry Areas', '022', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'สถิติ');
INSERT INTO customreport VALUES (58, 'Most Common Animal Adoption Areas', '023', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'สถิติ');
INSERT INTO customreport VALUES (59, 'Average Time On Waiting List', '024', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'สถิติ');
INSERT INTO customreport VALUES (60, 'บริจาครายเดือน', '025', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'กราฟทางการเงิน');
INSERT INTO customreport VALUES (61, 'Monthly Donations By Species', '026', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'กราฟทางการเงิน');
INSERT INTO customreport VALUES (62, 'Monthly Adoptions By Species', '027', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (63, 'Monthly Adoptions By Location', '028', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (64, 'Animal Entry Reasons', '029', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (65, 'Animal Return Reasons', '030', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Movement Graphs');
INSERT INTO customreport VALUES (66, 'Owner Criteria Matching', '031', '', '', 0, 0, 'translate', '2003-07-02 11:51:00', 'translate', '2003-07-02 11:51:00', 'Inventories');
DELETE FROM deathreason;
INSERT INTO deathreason VALUES (1, 'Dead On Arrival', '');
INSERT INTO deathreason VALUES (2, 'Died', '');
INSERT INTO deathreason VALUES (3, 'สมบูรณ์', '');
INSERT INTO deathreason VALUES (4, 'ป่วย/บาดเจ็บ', '');
INSERT INTO deathreason VALUES (5, 'Requested', '');
INSERT INTO deathreason VALUES (6, 'Culling', '');
INSERT INTO deathreason VALUES (7, 'Feral', '');
INSERT INTO deathreason VALUES (8, 'Biting', '');
DELETE FROM diet;
DELETE FROM donationtype;
INSERT INTO donationtype VALUES (1, 'บริจาค', '');
INSERT INTO donationtype VALUES (2, 'Adoption Fee', '');
INSERT INTO donationtype VALUES (3, 'Waiting List Donation', '');
INSERT INTO donationtype VALUES (4, 'Entry Donation', '');
INSERT INTO donationtype VALUES (5, 'Animal Sponsorship', '');
DELETE FROM entryreason;
INSERT INTO entryreason VALUES (1, 'Marriage/Relationship split', '');
INSERT INTO entryreason VALUES (2, 'Allergies', '');
INSERT INTO entryreason VALUES (3, 'Biting', '');
INSERT INTO entryreason VALUES (4, 'Unable to Cope', '');
INSERT INTO entryreason VALUES (5, 'Unsuitable Accomodation', '');
INSERT INTO entryreason VALUES (6, 'Died', '');
INSERT INTO entryreason VALUES (7, 'Stray', '');
INSERT INTO entryreason VALUES (8, 'ป่วย/บาดเจ็บ', '');
INSERT INTO entryreason VALUES (9, 'Unable to Afford', '');
INSERT INTO entryreason VALUES (10, 'Abuse', '');
INSERT INTO entryreason VALUES (11, 'Abandoned', '');
DELETE FROM internallocation;
INSERT INTO internallocation VALUES (1, 'ไม่มีที่ตั้ง', '');
DELETE FROM lksex;
INSERT INTO lksex VALUES (0, 'เพศเมีย');
INSERT INTO lksex VALUES (1, 'เพศผู้');
INSERT INTO lksex VALUES (2, 'ไม่ทราบ');
DELETE FROM lksize;
INSERT INTO lksize VALUES (0, 'ใหญ่มาก');
INSERT INTO lksize VALUES (1, 'ใหญ่');
INSERT INTO lksize VALUES (2, 'กลาง');
INSERT INTO lksize VALUES (3, 'เล็ก');
DELETE FROM lkcoattype;
INSERT INTO lkcoattype VALUES (0, 'สั้น');
INSERT INTO lkcoattype VALUES (1, 'ยาว');
INSERT INTO lkcoattype VALUES (2, 'Rough');
INSERT INTO lkcoattype VALUES (3, 'Curly');
INSERT INTO lkcoattype VALUES (4, 'Corded');
INSERT INTO lkcoattype VALUES (5, 'Hairless');
DELETE FROM lksaccounttype;
DELETE FROM lksmovementtype;
INSERT INTO lksmovementtype VALUES (0, 'ไม่มี');
INSERT INTO lksmovementtype VALUES (1, 'Adoption');
INSERT INTO lksmovementtype VALUES (2, 'Foster');
INSERT INTO lksmovementtype VALUES (3, 'Transfer');
INSERT INTO lksmovementtype VALUES (4, 'Escaped');
INSERT INTO lksmovementtype VALUES (5, 'Reclaimed');
INSERT INTO lksmovementtype VALUES (6, 'Stolen');
INSERT INTO lksmovementtype VALUES (7, 'Released To Wild');
INSERT INTO lksmovementtype VALUES (8, 'Retailer');
INSERT INTO lksmovementtype VALUES (9, 'Reservation');
INSERT INTO lksmovementtype VALUES (10, 'Cancelled Reservation');
DELETE FROM lksmedialink;
INSERT INTO lksmedialink VALUES (0, 'สัตว์');
INSERT INTO lksmedialink VALUES (1, 'สัตว์ที่สูญหาย');
INSERT INTO lksmedialink VALUES (2, 'สัตว์ที่พบเจอ');
INSERT INTO lksmedialink VALUES (3, 'เจ้าของ');
INSERT INTO lksmedialink VALUES (4, 'Movement');
DELETE FROM lksdiarylink;
INSERT INTO lksdiarylink VALUES (0, 'ไม่มี');
INSERT INTO lksdiarylink VALUES (1, 'สัตว์');
INSERT INTO lksdiarylink VALUES (2, 'เจ้าของ');
INSERT INTO lksdiarylink VALUES (3, 'สัตว์ที่สูญหาย');
INSERT INTO lksdiarylink VALUES (4, 'สัตว์ที่พบเจอ');
INSERT INTO lksdiarylink VALUES (5, 'รายชื่อที่กำลังคอย');
INSERT INTO lksdiarylink VALUES (6, 'Movement');
DELETE FROM lksdonationfreq;
INSERT INTO lksdonationfreq VALUES (0, 'One-Off');
INSERT INTO lksdonationfreq VALUES (1, 'รายสัปดาห์');
INSERT INTO lksdonationfreq VALUES (2, 'รายเดือน');
INSERT INTO lksdonationfreq VALUES (3, 'รายไตรมาสต์');
INSERT INTO lksdonationfreq VALUES (4, 'รายครึ่งปี');
INSERT INTO lksdonationfreq VALUES (5, 'รายปี');
DELETE FROM lksfieldlink;
INSERT INTO lksfieldlink VALUES (0, 'สัตว์');
INSERT INTO lksfieldlink VALUES (1, 'เจ้าของ');
DELETE FROM lksfieldtype;
INSERT INTO lksfieldtype VALUES (0, 'ใช่/ไม่');
INSERT INTO lksfieldtype VALUES (1, 'ข้อความ');
INSERT INTO lksfieldtype VALUES (2, 'Notes');
INSERT INTO lksfieldtype VALUES (3, 'Number');
INSERT INTO lksfieldtype VALUES (4, 'วันที่');
INSERT INTO lksfieldtype VALUES (5, 'เงิน');
INSERT INTO lksfieldtype VALUES (6, 'Lookup');
DELETE FROM lksloglink;
INSERT INTO lksloglink VALUES (0, 'สัตว์');
INSERT INTO lksloglink VALUES (1, 'เจ้าของ');
INSERT INTO lksloglink VALUES (2, 'สัตว์ที่สูญหาย');
INSERT INTO lksloglink VALUES (3, 'สัตว์ที่พบเจอ');
INSERT INTO lksloglink VALUES (4, 'รายชื่อที่กำลังคอย');
INSERT INTO lksloglink VALUES (5, 'Movement');
DELETE FROM lksyesno;
DELETE FROM lksynun;
DELETE FROM lksposneg;
DELETE FROM lkurgency;
INSERT INTO lkurgency VALUES (1, 'Urgent');
INSERT INTO lkurgency VALUES (2, 'High');
INSERT INTO lkurgency VALUES (3, 'กลาง');
INSERT INTO lkurgency VALUES (4, 'Low');
INSERT INTO lkurgency VALUES (5, 'Lowest');
DELETE FROM logtype;
INSERT INTO logtype VALUES (1, 'Bite', '');
INSERT INTO logtype VALUES (2, 'Complaint', '');
INSERT INTO logtype VALUES (3, 'ประวัติ', '');
INSERT INTO logtype VALUES (4, 'น้ำหนัก', '');
DELETE FROM species;
INSERT INTO species VALUES (1, 'สุนัข', '', '');
INSERT INTO species VALUES (2, 'แมว', '', '');
INSERT INTO species VALUES (3, 'นก', '', '');
INSERT INTO species VALUES (4, 'Mouse', '', '');
INSERT INTO species VALUES (5, 'Rat', '', '');
INSERT INTO species VALUES (6, 'Hedgehog', '', '');
INSERT INTO species VALUES (7, 'กระต่าย', '', '');
INSERT INTO species VALUES (8, 'Dove', '', '');
INSERT INTO species VALUES (9, 'Ferret', '', '');
INSERT INTO species VALUES (10, 'Chinchilla', '', '');
INSERT INTO species VALUES (11, 'งู', '', '');
INSERT INTO species VALUES (12, 'Tortoise', '', '');
INSERT INTO species VALUES (13, 'Terrapin', '', '');
INSERT INTO species VALUES (14, 'Chicken', '', '');
INSERT INTO species VALUES (15, 'Owl', '', '');
INSERT INTO species VALUES (16, 'แพะ', '', '');
INSERT INTO species VALUES (17, 'Goose', '', '');
INSERT INTO species VALUES (18, 'Gerbil', '', '');
INSERT INTO species VALUES (19, 'Cockatiel', '', '');
INSERT INTO species VALUES (20, 'Guinea Pig', '', '');
INSERT INTO species VALUES (21, 'ปลาทอง', '', '');
INSERT INTO species VALUES (22, 'Hamster', '', '');
INSERT INTO species VALUES (23, 'Camel', '', '');
INSERT INTO species VALUES (24, 'ม้า', '', '');
INSERT INTO species VALUES (25, 'Pony', '', '');
INSERT INTO species VALUES (26, 'Donkey', '', '');
INSERT INTO species VALUES (27, 'ลามะ', '', '');
INSERT INTO species VALUES (28, 'หมู', '', '');
DELETE FROM voucher;
INSERT INTO voucher VALUES (1, 'Neuter/Spay', '');
DELETE FROM vaccinationtype;
INSERT INTO vaccinationtype VALUES (1, 'Temporary Vaccination', '');
INSERT INTO vaccinationtype VALUES (2, 'First Vaccination', '');
INSERT INTO vaccinationtype VALUES (3, 'Second Vaccination', '');
INSERT INTO vaccinationtype VALUES (4, 'Booster', '');
INSERT INTO vaccinationtype VALUES (5, 'Leukaemia', '');
INSERT INTO vaccinationtype VALUES (6, 'Kennel Cough', '');
INSERT INTO vaccinationtype VALUES (7, 'Parvovirus', '');
